### ISSUE TITLE
How to pass screen sharing permission to Jitsi iframe inside iframe?

### ISSUE THREAD

**Issue by MurzNN** [jitsi/jitsi-meet-electron#111]
Riot Electron app use Jitsi Meet as third-party component for implement conferencing. And it have problem with giving screen share permissions to Jitsi widget, here is issue about this: https://github.com/vector-im/riot-web/issues/4880#issuecomment-412052311

Can you provide any ways to solve or bypass permission problem in Electron app, when using Jitsi widget in iframe?

**Comment by MurzNN** [comment]
From developers of Riot:
> that is already fitted but it doesn't work due to it being an iframe inside an iframe and it not getting passed through because of this

Does any other solutions exists?

**Comment by saghul** [comment]
@MurzNN I don't know if there is a solution for this. The utils package provides a function which must be available at the global scope for Jitsi Meet to detect and use, then screen sharing will work. If you can make that happen in an iframe within an iframe, I don't really know.

We did not design any of the features in https://github.com/jitsi/jitsi-meet-electron-utils with that scenario in mind, so if you run into problems I'm afraid we won't be of much help.

Wouldn't it be possible for Riot to embed Jitsi Meet without wrapping it in an iframe first? We already create an iframe.

**Comment by saghul** [comment]
I'm going to close this since a) it belongs in https://github.com/jitsi/jitsi-meet-electron-utils and (more importantly) b) We cannot do anything about it AFAIK.

**Comment by saghul** [comment]
This will, however, be solved when Chrome implements `getDisplayMedia` which is scheduled to happen soon.

**Comment by MurzNN** [comment]
@saghul thanks for info, this is excellent news! Can you post links to Chrome schedule with this feature?

**Comment by saghul** [comment]
@MurzNN it's already available in Chrome 70 beta, behind a flag: https://groups.google.com/forum/#!msg/discuss-webrtc/Uf0SrR4uxzk/uO8sLrWuEAAJ
