### ISSUE TITLE
Window dragging during remote control screenshare

### ISSUE THREAD

**Issue by daytonturner** [jitsi/jitsi-meet-electron#116]
The new screen share remote control feature is fantastic!  I found one bug however.

It seems as though there is a windowhandler for the electron app, where the intention is to be able to click in non-titlebar locations of the electron app, so you might drag the electron app around the screen.  Normally of course, this is limited to clicking on a window's title bar (I should mention all of this testing was on MacOS).  Ive noticed you can click and drag on the bottom jitsi toolbar where the hangup/screenshare/raise hand icons are.  That would be cool - except it also seems to impact a remote screen sharing session.  If i try to click and drag something within remote control session, it actually moves my LOCAL electron jitsi meet app window around, the same way it would if i was dragging by own jitsi meet window titlebar around.

If there's a way I can capture relevant data, please let me know, happy to share but wanted to report it nonetheless.

**Comment by saghul** [comment]
@daytonturner Interesting. The dragging thing is intentional: https://github.com/jitsi/jitsi-meet-electron/commit/1d3cfbb5692e6d97ee60e9ff04f9fab663f930e2

Otherwise we'd have to add a titlebar on macOS, which doesn't look as nice.

I'm not sure how to solve this, TBH, but any suggestions are more than welcome!

**Comment by daytonturner** [comment]
I think the dragging thing is a great idea, and I know of other electron apps (Slack) that employ this same strategy in an effort to eliminate the need for a status bar.

In the example of Slack, they have an area along the top of the window which usually represents the name of the chat you're in, the search bar, some settings icons, etc..  That part is draggable.  The chat area itself is not considered click-draggable.

I wonder if there's a way to make it such that the content-area of the screen share is not draggable, but there are overlay areas that adhere to the draggable concept (like the icon control strip along the bottom of the window, where mute/hangup/etc is).  The tough part is if you consider excluding the screenshare area, allow the bottom icon overlay to be draggable - but what do you do around the top of the window?

A couple ideas:
- Add a padded title above the screenshare itself, preventing the remote users screen from filling right to the top of the app window, providing an area to become draggable.  It could just be a dark strip with centered white text that says "Remote Screen share: username" or something.
- allow the screenshare to extend all the way to the top of the screen, but just make an invisible strip thats approximately the height of where a statusbar would be that becomes draggable.  Of course this can lead to confusion if you're trying to drag a window around on the users desktop which is top-aligned on their screen. You wont be able to move it.
- Add a toggle button to the UI that enables/disables this behavior while screenshare mode is active

Thoughts?

**Comment by saghul** [comment]
We have added the statusbar...
