### ISSUE TITLE
error switching server

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-meet-electron#118]
Hi,
I'm trying to switch the server from https://meet.jit.si to another internal server.
The problem is that a message "invalid server URL" is shown.
do you have idea to understand why I have this error?
thank you

Angelo

**Comment by patrick-othmer** [comment]
Check out issues: #109 & #98

**Comment by manang** [comment]
Hi,
I'm debugging the application and I don't see issues like yours.
My different thing is that the jitsi server certificate is self signed.
could it be the problem?
I've imported the public key in the OS x keychain access.
Thank you very much
Angelo
