### ISSUE TITLE
error before call starts

### ISSUE THREAD

**Issue by manang** [jitsi/jitsi-meet-electron#120]
Hi,
I'm trying to use jitsi electron with my internal server.
I have the following error:

external_api.js:1 Uncaught SyntaxError: Unexpected identifier
Conference.js:187 Uncaught TypeError: JitsiMeetExternalAPI is not a constructor
    at Conference._onScriptLoad (Conference.js:187)
    at HTMLScriptElement.script.onload (Conference.js:88)

do you have ideas about it?
Thank you
Angelo

**Comment by saghul** [comment]
Your external_api.js file seems to not be correct. Please that https://your_server.com/external_api.js returns a valid JS file.

That said, we should have caught this error so I'll make a fix for it, but it won't fix your problem.

**Comment by saghul** [comment]
Can you share the config you used in your server? You must allow iframes, of course.

**Comment by manang** [comment]
server_names_hash_bucket_size 64;

 

server {

    listen 443 ssl;

    include snippets/self-signed.conf;

    include snippets/ssl-params.conf;

    server_name jitsitest.mydomain.com;

    # set the root

    root /srv/jitsitest.mydomain.com;

    index index.html;

    location ~ ^/([a-zA-Z0-9=\?]+)$ {

        rewrite ^/(.*)$ / break;

    }

    location / {

        ssi on;

    }

    # BOSH

    location /http-bind {

        proxy_pass      http://localhost:5280/http-bind;

        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_set_header Host $http_host;    }

}

**Comment by saghul** [comment]
I can't see anything wrong there :-/ Can you share the URL privately so I can take a look? (saghul @ jitsi . org)

**Comment by manang** [comment]
Sorry, it is an internal site. You can’t access to it.

I solved, I had add_header X-Frame-Options DENY; in snippets/ssl-params.conf

 

Thanks for your support.

 

Angelo
