### ISSUE TITLE
[FR] Clear chat history or at lest remove the old chat rooms

### ISSUE THREAD

**Issue by Ark74** [jitsi/jitsi-meet-electron#127]
This feature request is in the sense that the app saves the complete history of chats.
So it would be nice to be able to clear it or remove old chat rooms from the list in order to keep a slim list.

![ft-clear-list](https://user-images.githubusercontent.com/7444518/46251238-0c9f7680-c413-11e8-9dd1-55bd74fe7a2c.png)

Cheers!

**Comment by saghul** [comment]
Makes sense, thanks for the feedback!

**Comment by demlak** [comment]
Is it possible to clear cache or something like this to archive deleting rooms?

**Comment by janwels89** [comment]
this seems to be stored on the client-side in your browser cookies. Try loading the page with an incognito tap to confirm.

Just delete your local browser cookies and the list should be empty again.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/392
