### ISSUE TITLE
Error after run:npm install 

### ISSUE THREAD

**Issue by TangXT** [jitsi/jitsi-meet-electron#130]
Error after run:npm install as below:
react-lorem-component@0.12.2 requires a peer of react@15.x but none was installed.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Darwin 18.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! robotjs@0.4.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the robotjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs robotjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls robotjs
npm ERR! There is likely additional logging output above.

**Comment by saghul** [comment]
What platform are you running on and what version of Node are you using?

**Comment by saghul** [comment]
Doh, I see them now. Update to Node 8 and give it another try please.

**Comment by TangXT** [comment]
@saghul Which version of node you using on macOS? I use v8.0.0,but alse error as below:
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/TangXT/jitsi-meet-electron/node_modules/jitsi-meet-electron-utils/node_modules/robotjs
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by saghul** [comment]
I'm using Node 8.11.3 and npm 6.4.1.

**Comment by TangXT** [comment]
@saghul Now I run npm install npm@6.4.1 -g
update npm to 6.4.1 and It's OK! Thank you!

**Comment by saghul** [comment]
Cool! I'm going to go ahead and close this then!

**Comment by TangXT** [comment]
@saghul  I using Node 8.11.3 and npm 6.4.1 run jitsi-meet-electron succeed. But while run jitsi-meet shows error, but I using Node 7.9.0 succeed as before. That's Why?

/Users/XXXXXX/jitsi-meet/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/XXXXXX/jitsi-meet/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/XXXXXX/jitsi-meet/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/XXXXX/jitsi-meet/node_modules/node-sass/bin/node-sass:11:10)
rm: css/all.bundle.css: No such file or directory
make: *** [deploy-css] Error 1
DouglastekiMacBook-Pro:jitsi-meet XXXXXX$

**Comment by TangXT** [comment]
@saghul Do you mean that？run as below： 
rm -rf node_modules
npm install
make

**Comment by saghul** [comment]
Yes.

**Comment by TangXT** [comment]
@saghul jitsi-meet  npm install, and show error as below:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/github/url-polyfill.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

**Comment by saghul** [comment]
You have an old checkout. Update to latest master.

**Comment by TangXT** [comment]
@saghul Oh! but I do some change for the code, How to update and NOT break my code?

**Comment by saghul** [comment]
There is no answer for that. There is a risk with every update. As it stands, you are using a pretty old version, which depended on a package which no longer exists. You have no other choice but to move forward.

So I suggest you take the time to update to our latest stable release: https://github.com/jitsi/jitsi-meet/releases/latest and apply your changes on top.

**Comment by TangXT** [comment]
@saghul You mean that url-polyfill  no longer exists?

**Comment by saghul** [comment]
Correct.

**Comment by TangXT** [comment]
@saghul I think I could delete it in package.json/package.lock.json and copy a backup into node_models

**Comment by saghul** [comment]
That’s up to you, but I wouldn’t recommend doing it.

**Comment by TangXT** [comment]
@saghul By the way，Which IDE you are using for coding jitsi-meet and jitsi-meet-electron??WebStorm?Eclipse??

**Comment by saghul** [comment]
Visual Studio Code, but I've used vim and also WebStorm in the past.

**Comment by saraswatyash** [comment]
> git-validate@2.2.4 install /home/yash/jitsi-meet-electron/node_modules/git-validate
> node bin/install


> robotjs@0.6.0 install /home/yash/jitsi-meet-electron/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.18.1 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/yash/jitsi-meet-electron/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6,
                 from ../src/robotjs.cc:7:
../src/keycode.h:112:10: fatal error: X11/Xutil.h: No such file or directory
  112 | #include <X11/Xutil.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [robotjs.target.mk:130: Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '/home/yash/jitsi-meet-electron/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-37-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/yash/jitsi-meet-electron/node_modules/robotjs
gyp ERR! node -v v12.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Please Resolve
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yash/.npm/_logs/2020-06-23T06_36_47_626Z-debug.log

**Comment by jrie** [comment]
From what is given:

> ../src/keycode.h:112:10: fatal error: X11/Xutil.h: No such file or directory
112 | #include <X11/Xutil.h>

You must install the development packages, in Debian this is [libx11-dev](https://packages.debian.org/buster/libx11-dev).

This includes the "Xutil.h" header files and you should be good to go. The name may vary so.
