### ISSUE TITLE
Problem connecting with private jitsi-meet server - external_api.js ?

### ISSUE THREAD

**Issue by JFMALBI** [jitsi/jitsi-meet-electron#133]
It is not possible to connect with our own jitsi-meet server (it works with https://meet.jit.si/)

In /var/log/nginx/error I have : 
2018/10/08 18:17:39 [error] 27096#27096: *7762 open() "/usr/share/jitsi-meet/[object Object]" failed (2: No such file or directory), client: 10.x.x.x, server: jitsi.mydomain.fr, request: "GET /[object%20Object] HTTP/1.1", host: "jitsi.mydomain.fr"

I thought it was the external_api.js file. But the file can be open using a web browser : jitsi.mydomain.fr/external_api.js

I do create the external_api.js file in /usr/share/jitsi-meet/ as described in release note

Any ideas ?

**Comment by saghul** [comment]
Can you share the URL here or privately?

**Comment by JFMALBI** [comment]
https://webconf.mairie-albi.fr I use a Ldap/active directory authentification but even if I turn off this authentification the issue is the same Regards JF MARTEL
 IT Directory
 Albi city Le 8 oct. 2018 6:32 PM, Saúl Ibarra Corretgé <notifications@github.com> a écrit :
Can you share the URL here or privately?

**Comment by saghul** [comment]
If I access https://webconf.mairie-albi.fr/external_api.js (what the Electron app needs) I get a 404 error. Have you double checked your web server configuration?

**Comment by JFMALBI** [comment]
Envoyé depuis mon Motorola Smartphone Le 8 oct. 2018 9:31 PM, Saúl Ibarra Corretgé <notifications@github.com> a écrit :
If I access https://webconf.mairie-albi.fr/external_api.js (what the Electron app needs) I get a 404 error. Have you double checked your web server configuration?

**Comment by JFMALBI** [comment]
You're right. I get also a 404 error.
 I will check tomorrow morning my configuration because I have tested this before posting issue ... external_api.js is stored in /usr/share/jitsi-meet
 Is it right ? Le 8 oct. 2018 9:31 PM, Saúl Ibarra Corretgé <notifications@github.com> a écrit :
If I access https://webconf.mairie-albi.fr/external_api.js (what the Electron app needs) I get a 404 error. Have you double checked your web server configuration?

**Comment by saghul** [comment]
Yes, but it’s called “exrernal_api.min.js”. You need to alias it to external_api.js

**Comment by JFMALBI** [comment]
OK I found the error. In the conf file of the server, there was an alias for all external.* files (for backwrads compatibility ...)
So now  https://webconf.mairie-albi.fr/external_api.js do display external_api.min.js
But I get the same error in /var/log/nginx/error 
2018/10/09 10:43:19 [error] 4707#4707: *7931 open() "/usr/share/jitsi-meet/[object Object]" failed (2: No such file or directory), client: 10.x.x.x, server: webconf.mairie-albi.fr, request: "GET /[object%20Object] HTTP/1.1", host: "webconf.mairie-albi.fr"

**Comment by saghul** [comment]
I just tested it and it works fine here. You should see me testing the "saghul" room in your logs.

**Comment by JFMALBI** [comment]
Yes I see you in the jitsi log file ! Did you use jitsi-meet-electron ?
I use the v1.1.0 version on a Windows7 desktop (binary verseion jitsi-meet.exe)
Is there a log somewhere on the desktop ?

**Comment by JFMALBI** [comment]
Yes I see you in the jitsi log file ! Did you use jitsi-meet-electron ?
I use the v1.1.0 version on a Windows7 desktop (binary verseion jitsi-meet.exe)
Is there a log somewhere on the desktop ?

**Comment by saghul** [comment]
Yes, I used the latest jitsi-meet-electron version. I used a debug build where I can check the console. I wonder if the problem is the 10 seconds join timeout not being enough for you? Can you run a Debug build? There?

**Comment by JFMALBI** [comment]
Where can I find a debug build ?

**Comment by saghul** [comment]
You need to do it yourself. Clone the repo, `npm install` then `npm start`.

**Comment by Ark74** [comment]
After the latest update/release I also find issues on a working env.
I'm opening #135 to debug the issue.

Cheers!

**Comment by JFMALBI** [comment]
ubuntu@boulimix:~/jitsi-meet-electron$ npm install

> robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd install /home/ubuntu/jitsi-meet-electron/node_modules/jitsi-meet-electron-utils/node_modules/robotjs
> node-gyp rebuild

make : on entre dans le répertoire « /home/ubuntu/jitsi-meet-electron/node_modules/jitsi-meet-electron-utils/node_modules/robotjs/build »
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:103:23: fatal error: X11/Xutil.h: Aucun fichier ou dossier de ce type
compilation terminated.
robotjs.target.mk:120 : la recette pour la cible « Release/obj.target/robotjs/src/robotjs.o » a échouée
make: *** [Release/obj.target/robotjs/src/robotjs.o] Erreur 1
make : on quitte le répertoire « /home/ubuntu/jitsi-meet-electron/node_modules/jitsi-meet-electron-utils/node_modules/robotjs/build »
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-63-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/jitsi-meet-electron/node_modules/jitsi-meet-electron-utils/node_modules/robotjs
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-lorem-component@0.12.2 requires a peer of react@15.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@github:jitsi/robotjs#5cc469f655669e728b61271c2c57ce97d62976fd install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Ark74** [comment]
Maybe using a more appropiate place like #135 since this is no longer related to connecting issues directly.

**Comment by JFMALBI** [comment]
You're right
