### ISSUE TITLE
Not Found external_api.js in Jetty

### ISSUE THREAD

**Issue by TangXT** [jitsi/jitsi-meet-electron#136]
@saghul  New version of jitsi using Jetty instead of Nginx,but I found that it couldn't found libs/external_api.js in Jetty

HTTP ERROR: 404
Problem accessing /external_api.js. Reason:

    Not Found
Powered by Jetty://

**Comment by saghul** [comment]
You'll need to edit the Jetty configuration in `/etc/jitsi/videobridge/sip-communicator.properties` and add the following line:

```
org.jitsi.videobridge.rest.jetty.ResourceHandler.alias./external_api.js=/usr/share/jitsi-meet/libs/external_api.min.js
```

Note that Jitsi Meet will use nginx if you have it installed prior to installing Jitsi Meet itself.

**Comment by TangXT** [comment]
@saghul Thanks
