### ISSUE TITLE
Not being able to use organization links

### ISSUE THREAD

**Issue by baco** [jitsi/jitsi-meet-electron#138]
On the company I work we use Slack for communicating, using the Slack-Jitsi plugin, the bot generates room links of the form meet.jit.si/the-slack-team/RandomlyNamedConferenceRoom

Those links are rejected by the Electron App when I try to use them there.

**Comment by saghul** [comment]
Ah damn. This is a bug indeed. Thanks for the heads up.

**Comment by saghul** [comment]
@baco This should be fixed now! Please give it a test and holler if you run into any problems. Thanks for the report!
