### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by roy2651** [jitsi/jitsi-meet-electron#140]
Hi this's great app.
about npm start in development mode:
when I run npm start in cmd, it does not work 
so I open anther cmd and run electron ./build/main.js.
and the Electron window is show.
please help me see what's problem?
Node: 8.11.2
npm: 6.4.1
Electron: 3.0.2
OS: Windows7

**Comment by saghul** [comment]
Please paste some output, we cannot just guess what's wrong. When you say "it does not work", what happens exactly?

**Comment by roy2651** [comment]
![image](https://user-images.githubusercontent.com/14157170/46988307-a1e87d80-d12a-11e8-9b43-1755a16d0170.png)
so like this。
npm start and the electron window is not show。
and may I ask anther question？
is remote control is default close

**Comment by saghul** [comment]
Please show more of the output, the error might be before or after.

The remote control feature requires user consent (they'll get a dialog asking for permission).
