### ISSUE TITLE
Screen sharing does not follow Jitsi server settings

### ISSUE THREAD

**Issue by halpro** [jitsi/jitsi-meet-electron#141]
Its seems like screen/application sharing does not respect Jitsi Meet config.js ([site].js) screen sharing settings. In my own environment I can set frame rate for screen sharing in Jitsi Meet config.js ([site].js) file and Web browsers (Firefox namely) accepts and follows the settings. But Jitsi Meet Electron doesn't.

Could someone explain why it is so? And what source files can I amend to make Jitsi Meet Electron read Jitsi Meet config.js  settings?

**Comment by saghul** [comment]
Hi!

The Electron app will load the web app on an iframe by using the external API, but screen sharing follows a slightly different code path. What settings are being ignored for you? JUst the frame rate?

**Comment by halpro** [comment]
Hi!
Thanks for quick reply. Frame rate (to show smooth video) and output resolution (to manage bandwidth).
Cheers!

**Comment by halpro** [comment]
saghul, can you tell where is the code to manage screen sharing settings?

**Comment by halpro** [comment]
@saghul what is screen sharing code path? Please let me know the place in the code base.

**Comment by saghul** [comment]
@halpro Sorry for the delay, I missed the reply. Here it is: https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/RTC/ScreenObtainer.js

**Comment by halpro** [comment]
@saghul I'm not JS guy, could you share the ideas on how to read the settings from the server?

**Comment by TiagoDapper** [comment]
Hello, how are you? 
Want to know how you can enable or control the remote inside jitsi? 
I would be grateful if you could explain it to me.
