### ISSUE TITLE
Using Electron to launch with settings

### ISSUE THREAD

**Issue by erm3nda** [jitsi/jitsi-meet-electron#142]
It would be cool if this remote control app can be launched as default, in background, with some settings. So i can reboot computer and be available to control it.

If i have to be present to drive things becomes not that much usefull, at least for me: (I know i can automate Electron stuff vía Selenium but is not the question at all)

Regards.

**Comment by saghul** [comment]
I’m afraid this is out of the scope of what we want to accomplish with the app at this stage.

Sorry but I don’t see this happening as a built in option.
