### ISSUE TITLE
Disable Keyboard mirror on chat box

### ISSUE THREAD

**Issue by Ark74** [jitsi/jitsi-meet-electron#143]
I've only tested this with a two user setup.

But if you take remote control and send a message through the integrated chat, then not only you as the controller type de message but you also type the message on the controlled environment, giving duplicated messages on the chat, since the chat box needs to be open to read the sent text.

Maybe disabling keyboard mirror when writing on the jitsi integrated chatbox could be a future feature for this use case.

Cheers!

**Comment by Echolon** [comment]
@Ark74 what were you operating systems? Do you have screenshots?

**Comment by saghul** [comment]
The effort required to fix this is too high for little gain. Closing as wontfix, sorry.

**Comment by Ark74** [comment]
np, thanks for letting know.
