### ISSUE TITLE
black windows in screen sharing on win10

### ISSUE THREAD

**Issue by rhwu** [jitsi/jitsi-meet-electron#145]
Steps to reproduce:
1) Install latest jitsi-meet-electron v1.1.1 on win10.
2) Join a meeting and launch the windows picker.
3) All the chromium based apps (chrome, vs code, jitsi-meet-electron etc) shown as a black window.

Works fine on Mac. Not sure about the other win versions.

**Comment by saghul** [comment]
Do other application windows look ok?

**Comment by saghul** [comment]
What graphics card do you have? I think you might be running into this Electron issue: https://github.com/electron/electron/issues/10863

**Comment by steven09200808** [comment]
I also got the same issue. I tested screen sharing on Win10 Chrome for both GPU and no-GPU laptops. It always gives me a black screen. I tested Opera browser, also black screen. Firefox works well. PowerPoint and Word also good. if I want to share a Microsoft Edge browser, I can not select it , cause the application can not find it at all.

**Comment by steven09200808** [comment]
I just disabled the hardware acceleration in my Chrome browser and Opera browser, it works. So I think this feature of chrome is not perfect. GPU is not the issue. Hardware acceleration feature of chrome would cause the issue.

**Comment by rhwu** [comment]
> What graphics card do you have? I think you might be running into this Electron issue: [electron/electron#10863](https://github.com/electron/electron/issues/10863)

intel graphics 630

**Comment by rhwu** [comment]
> I just disabled the hardware acceleration in my Chrome browser and Opera browser, it works. So I think this feature of chrome is not perfect. GPU is not the issue. Hardware acceleration feature of latest version chrome(Windows) would cause the issue. Hardware acceleration feature of chrome(Mac) wouldn't cause the issue.

How do you disable hw acceleration? I tried with below code but it doesn't seem to make a different.

app.commandLine.appendSwitch('disable-gpu');

**Comment by steven09200808** [comment]
Open Google Chrome.
Click Customize and Control Google Chrome > Settings.
Click on Show advanced settings and scroll to the System section.
Uncheck Use hardware acceleration when available and restart Google Chrome.

**Comment by rhwu** [comment]
I see, so you changed chrome setting so that jitsi-meet-electron's screen sharing can see chrome.

Might be too much to ask the end user to do this, but thanks for the information and workable workaround. 

It will be great if jitsi-meet-electron can handle this.

**Comment by saghul** [comment]
@rhwu It's impossible for us to do that. Chrome / Opera are other applications runnin in your system, we cannot just change their settings.

**Comment by akshitkrnagpal** [comment]
> How do you disable hw acceleration? I tried with below code but it doesn't seem to make a different.

https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration

**Comment by saghul** [comment]
Closing since there is nothing we can do other than update Electron, which we are going to do frequently anyway.
