### ISSUE TITLE
Screen sharing can not work well in Win Office 365

### ISSUE THREAD

**Issue by steven09200808** [jitsi/jitsi-meet-electron#147]
I just tested Screen sharing in Win10. For Office 2010, like Word 2010, PowerPoint 2010 and etc. Screen sharing works well. But when I switch to Office 365(Word 365,PowerPoint 365 and etc.), screen sharing can not work well. Every time I modify my word, the sharing screen can not show my modification simultaneously. After I minimize the word window and maximize the window again. the sharing screen can be updated.

**Comment by steven09200808** [comment]
I tested other screen sharing samples based on electron API. They all have same issue for Office 365. I guess this issue is caused by electron API "electron.desktopCapturer".

**Comment by saghul** [comment]
Do you also experience some black screen as in #145 ?

**Comment by steven09200808** [comment]
No black screen.

**Comment by steven09200808** [comment]
https://github.com/electron/electron/issues/13536
I think this is the issue caused from.

**Comment by saghul** [comment]
Good find. Looks like we'll need to wait until they release a fix in Electron.

**Comment by saghul** [comment]
Closing since there is nothing we can do other than update Electron, which we are going to do frequently anyway.
