### ISSUE TITLE
Error when Trying to Use Remote Control in a Custom Deployment

### ISSUE THREAD

**Issue by buddhikajay** [jitsi/jitsi-meet-electron#155]
Environment
---

Node Version : `8.12.0`
Npm Version : `6.41`
Operating System : `Ubuntu 18.04`
jitsi-meet-electrom version: `031205ef4fdd15c27f279ca8d74a2edd4402ef0d`
jitsi-meet version: `f89f3f144f1bf1c3f1f3269db12c3e4b4431aa95`

Use-Case
---
User `A` uses the `jitsi-meet-electron` app which is pointed to a custom jitsi deployment.
User `B` uses the web interface of `jitsi-meet` custom deployment
Both user `A` and user `B` are connected to the same room of the custom deployment.

When the user `B` clicks on `Remote Control` button to control user `A`s desktop, he receives the following error.

`An error occurred while trying to request remote control permission from test_user.` 

<img width="400" alt="screen shot 2018-12-20 at 5 24 00 pm" src="https://user-images.githubusercontent.com/6940024/50286995-263ae200-0487-11e9-9307-10ca4563eb8e.png">

Any clue on this ?

**Comment by ckurrat** [comment]
Got the same issue here on windows using jitsi-meet-electron with a custom installation .
Any idea?

**Comment by hristoterezov** [comment]
Any errors in the console for user A or user B?

**Comment by ckurrat** [comment]
where can i find the error log using jitsi-meet-electron on windows ?

**Comment by ckurrat** [comment]
seems the electron user does not accept the remote-request from the web session

**Comment by hristoterezov** [comment]
@ckurrat Should we close this issue?

**Comment by TiagoDapper** [comment]
Hello, how are you? Want to know how you can enable or control the remote inside jitsi? I would be grateful if you could explain it to me.
