### ISSUE TITLE
Square image

### ISSUE THREAD

**Issue by tiotrom** [jitsi/jitsi-meet-electron#156]
I simply cannot make my Logitech c920 display in wide-screen mode with Jitsi. Any other video conference application shows my webcam in wide mode. I use Manjaro Linux.

**Comment by saghul** [comment]
Does the same happen when you use Jitsi from meet.jit.si ?

**Comment by tiotrom** [comment]
> Does the same happen when you use Jitsi from meet.jit.si ?

Yes. And regardless of the browser

**Comment by saghul** [comment]
You seem to have enabled tile view. Disable it by pressing the 4 squares button in the lower right corner and the video should fill the entire screen.

**Comment by tiotrom** [comment]
@saghul I understand that pressing it will stretch the image to become wide, but why is the image square in the first place? It is nit square in any video-conference app nor is my laptop webcam square when it tile view. We use Jitsi with OBS Studio and we need to live stream in tile view so all participants are in focus at all time.

**Comment by saghul** [comment]
@tiotrom I see. If you hover over the "signal bars" icon you should see the local video resolution. What does it say?

**Comment by saghul** [comment]
But also, @virtuacoplenny, why is `object-fit` set to `contain` in tile view? Is it for portrait mobile participants? Otherwise, why not use `cover` like in the regular view?

**Comment by tiotrom** [comment]
This is what I see:
![2018-12-27_11-44](https://user-images.githubusercontent.com/34804533/50477619-62150080-09cd-11e9-9347-1e0acc567f65.png)

**Comment by saghul** [comment]
Uh. Can you connect another participant? I think stats are not initialized while you are alone.

**Comment by tiotrom** [comment]
oh ok here it is
![2018-12-27_11-59](https://user-images.githubusercontent.com/34804533/50477993-32ff8e80-09cf-11e9-90c1-0ea6afc41b28.png)

**Comment by saghul** [comment]
The resolution your camera is providing is 960x720, which is 4:3 aspect ratio, hence the black bars (unless we change the object-fit as I inquired above).

Can you try to use `qv4l2` to ssee what resolution is displayed there? I believe it's part of the `v4l2-utils` package.

**Comment by virtuacoplenny** [comment]
@saghul, we stuck with "contain" because that's what what the verbal spec called for. I stuck with it because it was the easiest to use to get tile view pushed out quickly without worrying about portrait videos and having those portrait videos look too zoomed.

**Comment by tiotrom** [comment]
> Can you try to use `qv4l2` to see what resolution is displayed there? I believe it's part of the `v4l2-utils` package.

Ok tried. It showcases 960x720 which is indeed 4:3 however I can change the resolution there even though it does not remember the change. I somehow defaults to  960x720.

**Comment by virtuacoplenny** [comment]
Yes, I could do that. That wasn't implemented for the sake of time and the bars being per desired design.

**Comment by tiotrom** [comment]
@virtuacoplenny Would be useful if you can implement this :)
