### ISSUE TITLE
Can I customize it?

### ISSUE THREAD

**Issue by tiotrom** [jitsi/jitsi-meet-electron#158]
I am using the appimage version on Linux and of course in Linux it creates some config files. Is there anywhere I can configure the way it looks in the config? Like to force changes? Would love to make some custom changes. We use it in combination with OBS Studio for our podcast :)  -  Cheers!

**Comment by saghul** [comment]
What kind of changes would you like to make? It depends on what you are after.

**Comment by saghul** [comment]
What toggle mode?

**Comment by tiotrom** [comment]
Toggle tile view, where you see all the participants. Like I reported here https://github.com/jitsi/jitsi-meet-electron/issues/156 that the image is not in cover mode but it is square

**Comment by saghul** [comment]
Right. So, those 2 changes are not pat of the electron app *per se* they are part of Jitsi Meet itself, which the electron app loads using the iframe API.

By default it loads meet.jit.si, but if you have your own server will whatever configurations you like, you can change the server in the settings and it will load your changes too.

**Comment by tiotrom** [comment]
Yup I understand but I was wondering in much the same way that you can inject CSS into a webpage from your browser, couldn't Jitsi use external CSS from settings to re-write it's own CSS?

**Comment by saghul** [comment]
While technically possible, that's not something that we are willing to support in this app.

**Comment by tiotrom** [comment]
I understand. In this case I might suggest to change the background for toggle view to black (pretty much all video conferences have that background, I think it highlights the participants) + make the video cover format else it looks weird in square format :) - thanks for the work, amazing application!
