### ISSUE TITLE
Persist conference room credentials

### ISSUE THREAD

**Issue by jk** [jitsi/jitsi-meet-electron#159]
We use our own deployment of the jitsi-server and have the API/json auth in place, so every conference room needs a username/password which is shared across all conference rooms.

Looks like when I'm using a web browser, the browsers saves the credentials and prefills the auth dialog upon joining a conference room.

So the feature request is that the Electron apps does something similar. Or provides a conference-room-level dialog to persist credentials so that one doesn't need to provide them on every room join.

**Comment by saghul** [comment]
I believe those are saved in localStorage. I wonder why this is not working in Electron, maybe because we are loading meet in a iframe...

**Comment by larslue** [comment]
I believe to have the same issue. We are on a private jitsi instance that requires credentials to host a meeting. These credentials always need to be re-entered after closing the App. They are persisted within an app session, though.

**Comment by GitRon** [comment]
Same here. The password is remembered about one day, after this, you have to put it in again.

**Comment by saghul** [comment]
Your deployment must have session caching configured on Jicofo, 1 day is the default.

**Comment by saghul** [comment]
Sorry folks, but I have to close this. We have no plans to implement credentials caching in the Electron app. That said, a PR implementing the functionality would be welcome.
