### ISSUE TITLE
'npm install' taking so much time to execute .

### ISSUE THREAD

**Issue by vinay72** [jitsi/jitsi-meet-electron#160]
Whenever I try to execute `npm install` in my terminal . It takes a lot more time than the usual. Here is the screenshot : 
![screenshot from 2019-02-03 22-11-12](https://user-images.githubusercontent.com/28500944/52179442-ba2af800-2800-11e9-95fa-fd257697da20.png)

**Comment by saghul** [comment]
Well, there are many things to install, Electron is not particularly small. There is nothing we can do about that.
