### ISSUE TITLE
Error in executing 'npm start ' in my terminal. 

### ISSUE THREAD

**Issue by vinay72** [jitsi/jitsi-meet-electron#161]
When I try to install `jitsi/jitsi-meet-electron` in my terminal after doing `npm install` , when I try to do npm start in my Terminal , it is showing me following error : 
![screenshot from 2019-02-08 16-17-15](https://user-images.githubusercontent.com/28500944/52473961-29b43500-2bbd-11e9-8f20-e8baef6f27bb.png)
![screenshot from 2019-02-08 16-17-22](https://user-images.githubusercontent.com/28500944/52473970-2de05280-2bbd-11e9-9d4c-a3226f8183d5.png)

**Comment by saghul** [comment]
Why are you running commands in the build directory? You need to run the commands in the root directory.

**Comment by vinay72** [comment]
Okay, thanks for replying.
