### ISSUE TITLE
CPU very high and crash

### ISSUE THREAD

**Issue by tiotrom** [jitsi/jitsi-meet-electron#163]
Basically the appimage, on my Manjaro Gnome, is eating alive my CPU :D - I have a  core i7 7700HQ and 32GB of Ram and it still manages to crash system. It is true, only after like 1h of video talk. Let me know if you are aware of these and/or if I can debug it in a way that I can help you guys track down the issue. Cheers!

**Comment by saghul** [comment]
How does it crash your system? Also, how many participants are in the conference?

**Comment by tiotrom** [comment]
The CPU goes to 100% but not all the time. Usually it goes at 80% and if I do something else in the meantime like browse on firefox it can freeze the system. There are about 5-6 people maximum in the stream.

**Comment by saghul** [comment]
It's not uncommon to see this. The default codec is VP8, which won't be hardware acelerated so everything needs to be done in software. Using this app is no different that using the Chrome browser, so there is not much we can do.

There is a "manage call quality" option in the "..." menu while in a conference, but then you are traidng CPU usage for call quality.

**Comment by tiotrom** [comment]
I see. So the more people are joining the more software (thus hardware) intensive the task is?

**Comment by saghul** [comment]
Sort of. We have ways to mitigate that (participant's video will be suspended for instance) but this is a resource intensive task, yeah.

**Comment by tiotrom** [comment]
I want to say that I tested it for the past 3-4 days with just one single participant (so 2 in total) and I see the same issue. CPU is crazy high for me on Linux but not for my friend on Windows. Any way to debug this?

**Comment by saghul** [comment]
IIRC it comes down to graphics drivers, so there is nothing you can do from this apps perspective.

**Comment by tiotrom** [comment]
I am using the proprietary Nvidia drives on Linux.

**Comment by tiotrom** [comment]
I have to update you on this. So, tonight we had one of our weekly podcasts and Jitsi destroyed my computer. I was only able to stream 20 minutes. This is the stream in case https://www.youtube.com/watch?v=UNF4O7PFYX0 and my core i7 with Nvidia and 32GB of ram become unusable. I had to give the task to one of my friends with Windows to handle all that. Thing is, on other Linux distros and other computers with linux this app makes the CPU go so high it makes it very difficult to handle. It is such a shame because we love Jitsi and we use it for our live cast. But I simply cannot use it to stream, or anyone I know with a Linux distro. It makes the GPU go crazy high....Any way this can be debugged? Tell me how to help with the process please

**Comment by saghul** [comment]
It is not impossible an Electron update will fix it, but hard to tell since I have no means to reproduce it.

Does using Chrome (since Electron is based on it) yield similar results?

**Comment by tiotrom** [comment]
I don't know about using Chrome. I don't use it on Linux. But maybe I can try if this helps with this very annoying issue :D. Would it be ok to test with Ungoogled Chromium?

**Comment by saghul** [comment]
Yeah, for the purposes of this test it should yield the same results.

**Comment by tiotrom** [comment]
We tested today on an AMD processor and worked perfectly fine (same operating system - Manjaro)....I am starting to think is an issue with certain drivers. If I get the chance to test on my system with Chromium I'll post there. On my system as soon as I open Jitsi it takes about 30% of my CPU from the get-go.

**Comment by saghul** [comment]
We have updated the Electron version in the laatest release. Please give it a try. There is not much else we can do...

**Comment by tiotrom** [comment]
Seems to be working fine now!  Thank you for the appimage!
