### ISSUE TITLE
Always On Top Video Not Working in Session

### ISSUE THREAD

**Issue by nsudds** [jitsi/jitsi-meet-electron#165]
I tried a test session earlier today and when minimizing the app the Always on Top video worked well.  But now I have a partner in a session and it's not working.   Is there a way to toggle this on and off? Or should it just work when minimizing?

**Comment by saghul** [comment]
It should work when the main window goes out of focus.

**Comment by nsudds** [comment]
I may try again -- in a test session it worked to pop up my own video but then in an actual session with another person it didn't end up working.  Could as easily be an issue with my computer not sure. 

I switched to the Picture in Picture extension from Google to get the same effect now and it's working within Chrome. 
https://chrome.google.com/webstore/detail/picture-in-picture-extens/hkgfoiooedgoejojocmhlaklaeopbecg/related
