### ISSUE TITLE
Can't connect to local jitsi server. Invalid Server URL.

### ISSUE THREAD

**Issue by skrmn** [jitsi/jitsi-meet-electron#167]
#98 & #109 are checked.
I'm able to get access to external_api.js
But still get this error.
Could the problem be in self-signed certificate for the server?

Thanks.

**Comment by saghul** [comment]
Can you paste some JS console output?

**Comment by skrmn** [comment]
> Can you paste some JS console output?
I'm using release version of Jitsi-Meet for Windows, not sure if it has any console output....

**Comment by skrmn** [comment]
I've built it locally to be able to check output, but it doesn't start, just waiting for something.
Please see attached:
npm install log & npm start log

Thanks.



[install.log](https://github.com/jitsi/jitsi-meet-electron/files/3162895/install.log)
[start.log](https://github.com/jitsi/jitsi-meet-electron/files/3162896/start.log)

**Comment by skrmn** [comment]
Still on the same stage. Can't use local server. external_api is working,
Can build on a Windows machine, but the app doesn't show a windows and waiting for something in console. All outputs are attached to previous comment. Some help will be appreciated.
Thanks.

**Comment by saghul** [comment]
We don't support developing on Windows. Starting Electron seems to fail for some reason:

```
[1] 'electro' is not recognized as an internal or external command,
[1] operable program or batch file.
[2] '.' is not recognized as an internal or external command,
[2] operable program or batch file.
[1] electro exited with code 1
[2] ./build/main.js' exited with code 1
```

I suspect it's not liking this: https://github.com/jitsi/jitsi-meet-electron/blob/master/package.json#L8

Try this instead. Open 2 terminals. On the first one, run:

```
webpack --config ./webpack.main.js --mode development
npm:watch
```

And on the second one:

```
electron ./build/main.js
```

**Comment by skrmn** [comment]
@saghul  Thank you for reply.

I was able to start webpack in one terminal window and electron build in second.
Can't manage to run npm:watch.

However app started and result is the same, URL is invalid and no extra information in console.
Please check screenshots attached.

I don't want really to develop on Windows, I just want to understand why it's not working with local server. 

Thanks.

![Screenshot_1](https://user-images.githubusercontent.com/20071630/57695040-8bb58800-764d-11e9-98f3-e9ff4152293f.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/20071630/57695041-8bb58800-764d-11e9-8d1b-d1628d0373d1.jpg)

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet/commit/2180d33e3d1a7f2176007b6e63c4abbf54549b2c
Maybe your deployment is missing the external_api.js location, can you check?

**Comment by skrmn** [comment]
@damencho It's in place, and I did setup nginx to work with it as well.
You can check few comments earlier my output from the browser.
Thanks.

**Comment by saghul** [comment]
Can you share the URL privately ? GH username at jitsi dot org

**Comment by skrmn** [comment]
I'm on Ubuntu 18.04.2, 
jitsi-meet from apt, version 1.0.3734-1 if it's matter.

**Comment by skrmn** [comment]
@saghul message sent. Thanks.

**Comment by saghul** [comment]
Got it. So, the problem is the self-signed certificate. The default behavior is to reject them, which is what happens.

With this small patch you can make it to work, but I don't recommend you release it to production:

```
diff --git a/main.js b/main.js
index 38f455c..8442556 100644
--- a/main.js
+++ b/main.js
@@ -183,7 +183,7 @@ app.on('activate', () => {
 app.on('certificate-error',
     // eslint-disable-next-line max-params
     (event, webContents, url, error, certificate, callback) => {
-        if (url.startsWith('https://localhost')) {
+        if (true || url.startsWith('https://localhost')) {
             event.preventDefault();
             callback(true);
         } else {
```
