### ISSUE TITLE
feat: launch from URL with custom protocol like `jitsi://ROOM_ID`

### ISSUE THREAD

**Issue by tonytonyjan** [jitsi/jitsi-meet-electron#168]
This would be a wonderful feature if it is possible.

I wonder if it is being planed in the future or it can not be done by Electron.

**Comment by saghul** [comment]
Sure, why not! :-) We don't currently have much time to improve the Electron app, but if you send a PR I'll b e happy to review it.

**Comment by ctramnitz** [comment]
why should the url be jitsi:// ? and why jitsi://test/<some_server_uri> (room & server reversed)?

The redirect to an installed app already uses org.jitsi.meet://server/room

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet-electron/pull/263
