### ISSUE TITLE
Please add a way to remember the user and the password.

### ISSUE THREAD

**Issue by gerroon** [jitsi/jitsi-meet-electron#170]
Hi

I have the same issue with this app that I haev with the Android app. It does not remember the last used user/pass. 

Here is the full details of the issue, so I wont repeat it here

https://github.com/jitsi/jitsi-meet/issues/4359

**Comment by saghul** [comment]
Closing since this needs to be fixed in jitsi-meet. This electron app acts just as a "shell".
