### ISSUE TITLE
Remote control: no keyboard input even after closing Jitsi Meet, had to log out of the Windows session

### ISSUE THREAD

**Issue by tuxayo** [jitsi/jitsi-meet-electron#173]
- the controller only had mouse control
- we canceled the call
- the controlled didn't recover keyboard control on it's own machine
- ctrl shift escape (open task manager) didn't work
- ctrl alt del didn't work
- had to log out of the windows session by using the mouse
  - (which implies closing all application, luckily not work in progress was lost)
- log in
- keyboard input worked again

Controlled:
OS: Windows 10
Jitsi Meet: jitsi-meet.exe v1.1.1

Controller:
OS: Antergos Linux (Arch Linux)
Jitsi Meet: jitsi-meet-x86_64.AppImage v1.1.1

**Comment by tuxayo** [comment]
Redid a call and remote control session: keyboard input worked. So not clear about how to reproduce.

**Comment by hristoterezov** [comment]
Hmm.. I've never seen this. Let us know if it happens again and if you have steps to reproduce.
