### ISSUE TITLE
Jitsi Meet Electron app is now in AUR for Arch-based Linux

### ISSUE THREAD

**Issue by mr-eshua** [jitsi/jitsi-meet-electron#179]
Hello,

I submitted a package build procedure for jitsi-meet-electron app in AUR yesterday. Now, it can be installed in Arch-based Linux using `pacman -Syu jitsi-meet-electron` or any other package manager you prefer.

AUR page: https://aur.archlinux.org/packages/jitsi-meet-electron/

Any comments/suggestions/enhancements are welcomed, just let me know if you have something :wink:

**Comment by saghul** [comment]
Thank you!

**Comment by hristoterezov** [comment]
Awesome!

**Comment by PolynomialDivision** [comment]
And it is gone?

**Comment by mr-eshua** [comment]
> And it is gone?

It was replaced with:
https://aur.archlinux.org/packages/jitsi-meet-desktop-bin/

And updated to 2.0.0.
