### ISSUE TITLE
MODULE_VERSION 48

### ISSUE THREAD

**Issue by freeeflyer** [jitsi/jitsi-meet-electron#182]
Hi,

building the app needs a node 6 ??

Isn't it a bit obsolete ?

Regards

**Comment by saghul** [comment]
It should work with Node 12. Are you running into any problems?

**Comment by freeeflyer** [comment]
Yes.. 
I downloaded node 10 for windows..  (stable?)
"npm run dist " was ok (except 2 security warnings), but when i tried to execute the resulting build, I got a message about needed version of NODE_MODULE_VERSION to 48.
I then tried to build with node 6 it was not working either..

I'm trying node 12 as I type this message.. 

hold on..

**Comment by saghul** [comment]
Note that we don't test building on Windows much so hopefully it's still good :-)

**Comment by freeeflyer** [comment]
Node 12 builds ok, like node 10..
But it gives the same message :

![image](https://user-images.githubusercontent.com/12149490/66760583-b5940480-eea2-11e9-8eda-921637fc11f1.png)

**Comment by saghul** [comment]
@hristoterezov Any idea?

**Comment by hristoterezov** [comment]
How are you building the app?

Have you run `npm install` before building the app?

**Comment by freeeflyer** [comment]
I just did.. same message.

**Comment by hristoterezov** [comment]
Could you please provide what are you executing the build and start the app?

Are you doing ` npm install; npm start` or `npm run pack`?

**Comment by freeeflyer** [comment]
npm install && npm run dist

**Comment by freeeflyer** [comment]
This is what I get from  "npm start"
`[watch]
[watch] > jitsi-meet-electron@1.1.1 watch C:\Users\zagulajew\Documents\Projets\jitsi\jitsi-meet-electron
[watch] > webpack --config ./webpack.renderer.js --mode development --watch --watch-poll
[watch]
[1]
[1] App threw an error during load
[1] Error: The module '\\?\C:\Users\zagulajew\Documents\Projets\jitsi\jitsi-meet-electron\node_modules\jitsi-meet-electron-utils\build\Release\sourceId2Coordinates.node'
[1] was compiled against a different Node.js version using
[1] NODE_MODULE_VERSION 48. This version of Node.js requires
[1] NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
[1] the module (for instance, using `npm rebuild` or `npm install`).
[1]     at process.func (electron/js2c/asar.js:155:31)
[1]     at process.func [as dlopen] (electron/js2c/asar.js:155:31)
[1]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
[1]     at Object.func (electron/js2c/asar.js:155:31)
[1]     at Object.func [as .node] (electron/js2c/asar.js:155:31)
[1]     at Module.load (internal/modules/cjs/loader.js:645:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
[1]     at Module.require (internal/modules/cjs/loader.js:685:19)
[1]     at require (internal/modules/cjs/helpers.js:16:16)
[1]     at Object.<anonymous> (C:\Users\zagulajew\Documents\Projets\jitsi\jitsi-meet-electron\node_modules\jitsi-meet-electron-utils\node_addons\sourceId2Coordinates\index.js:2:7)
[watch]
[watch] webpack is watching the files...
[watch]
[watch] Hash: cd00b3db58540df45ee2
[watch] Version: webpack 4.27.1
[watch] Time: 14111ms
[watch] Built at: 2019-10-14 18:00:48
[watch]                                Asset       Size  Chunks             Chunk Names
[watch] 6d44496ff4d9cadbdad46a2921a754ff.png    5.8 KiB          [emitted]
[watch]                               app.js   4.53 MiB     app  [emitted]  app
[watch]                           index.html  238 bytes          [emitted]
[watch] Entrypoint app = app.js
[watch] [./app/features/app/index.js] 29 bytes {app} [built]
[watch] [./app/features/conference/index.js] 113 bytes {app} [built]
[watch] [./app/features/config/index.js] 642 bytes {app} [built]
[watch] [./app/features/navbar/index.js] 161 bytes {app} [built]
[watch] [./app/features/onboarding/index.js] 218 bytes {app} [built]
[watch] [./app/features/recent-list/index.js] 103 bytes {app} [built]
[watch] [./app/features/redux/index.js] 95 bytes {app} [built]
[watch] [./app/features/redux/middleware.js] 385 bytes {app} [built]
[watch] [./app/features/redux/persistor.js] 110 bytes {app} [built]
[watch] [./app/features/redux/reducers.js] 512 bytes {app} [built]
[watch] [./app/features/redux/store.js] 482 bytes {app} [built]
[watch] [./app/features/router/index.js] 149 bytes {app} [built]
[watch] [./app/features/settings/index.js] 215 bytes {app} [built]
[watch] [./app/features/welcome/index.js] 55 bytes {app} [built]
[watch] [./app/index.js] 1.04 KiB {app} [built]
[watch]     + 869 hidden modules
[watch] Child html-webpack-plugin for "index.html":
[watch]      1 asset
[watch]     Entrypoint undefined = index.html
[watch]     [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] 405 bytes {0} [built]
[watch]     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[watch]         + 1 hidden module`

**Comment by hristoterezov** [comment]
Do you have any errors on `npm install`?

It seems that `node-gyp rebuild` from jitsi-meet-electron-utils haven't been executed or failed.

**Comment by hristoterezov** [comment]
Also deleting node_modules and running again `npm install` could help.

**Comment by hristoterezov** [comment]
I've just reproduced the issue. Will try to come up with a fix soon. In meantime I guess you can use older version. The last 2 commits are just updating electron and there isn't any new functionalities introduced.

**Comment by freeeflyer** [comment]
Hello 
> Also deleting node_modules and running again `npm install` could help.
I started from a fresh install

> I've just reproduced the issue. Will try to come up with a fix soon. In meantime I guess you can use older version. The last 2 commits are just updating electron and there isn't any new functionalities introduced.

Thanks a lot for the bugfix, I will try the older version..

Nicolas

**Comment by hristoterezov** [comment]
@freeeflyer We've just merged a fix into master. Could you please try again and confirm it works?

**Comment by freeeflyer** [comment]
> @freeeflyer We've just merged a fix into master. Could you please try again and confirm it works?

It's working. Thanks a lot

**Comment by saghul** [comment]
Excellent, thanks for confirming!
