### ISSUE TITLE
entering my url gives error: "invalid server URL or external API not found"

### ISSUE THREAD

**Issue by mikycomputers** [jitsi/jitsi-meet-electron#189]
I'm trying to make electron works, I've installed jitsi-meet on ubuntu virtual server - and it works using chrome. 
 when trying to sign in using your app, it works only with the default: https://meet.jit.si it works
but when try to enter my domain it says: "invalid server URL or external API not found"

Do you have any suggestions?

Thanks alot,

**Comment by saghul** [comment]
Does your server have a proper TLS certificate and the external API enabled?

**Comment by mikycomputers** [comment]
Hey Saghul, 
yes it does have TLS Cert. 
I've installed jitsi using the fast-install on ubunto server. and it works on Chrome.
I've read yours: "In order to use this application with your own Jitsi Meet installation it's necessary to enable the External API. Your server must serve a external_api.js file at the root of the installation. "

I'd be grateful if you can be more detailed about this, like step-by-step explaination.
Also can you tell me how do I check the external API enabled? 

Thanks ALOT

**Comment by damencho** [comment]
If you are using nginx do you have this in your config: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L30 ?

**Comment by saghul** [comment]
I forgot to mention a TLS cert alone is not enough. It must not be self-signed because Electron will reject it by default otherwise.

**Comment by Haertie** [comment]
> Wenn Sie nginx verwenden, haben Sie dies in Ihrer Konfiguration: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet/jitsi-meet.example#L30 ?
----------
location = /external_api.js {
        alias /usr/share/jitsi-meet/libs/external_api.min.js;
    }
------------
Thx that was the solution

**Comment by trainingcity** [comment]
What is the equivalent config in Apache2?
