### ISSUE TITLE
external_api.js

### ISSUE THREAD

**Issue by enlicayomer** [jitsi/jitsi-meet-electron#19]
Hello there,
windows / jitsi-meet / render.js
The external_api.js file specified in the file does not exist in my jitsi-meet installation. I installed the latest version.
modules / API / external / external_api.js does not work. He is not throwing an error.
What can I do about it?

Thanks,

**Comment by abdurrahmanekr** [comment]
Hi @enlicayomer, you need to add the following setting to nginx: https://github.com/jitsi/jitsi-meet/blob/dc2bae4ae13f3b06ac12eb35f3b08358100bac3d/doc/debian/jitsi-meet/jitsi-meet.example#L38

**Comment by hsahmed** [comment]
The external_api.js (installed at /usr/share/jits-meet/libs in debian/ubuntu) is outdated (Sep 2016) causing iframe rendering issues with the electron client that appear only with self-hosted jitsi-meet not with meet.jit.si, the new external_api.js in jitsi-meet installation is installed as external_api.min.js. Either the jitsi-meet package should install the correct external_api.js or render.js should point to external_api.min.js

**Comment by saghul** [comment]
ping @damencho

**Comment by AkshitKrNagpal** [comment]
@saghul 
Since `external_api.js` is minified now and is exactly same as `external_api.min.js`, this issue should be closed right?
