### ISSUE TITLE
can not build with mac pro, 

### ISSUE THREAD

**Issue by zsinba** [jitsi/jitsi-meet-electron#190]
![image](https://user-images.githubusercontent.com/890157/71721741-37bc1580-2e61-11ea-8bda-2804ad3daf48.png)

node -v 
v13.5.0

electron -v 
v7.1.7

                                          ^
7 errors generated.
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sbin/Documents/jitsi-meet-electron/node_modules/robotjs
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@github:jitsi/robotjs#f0fc08c8d96231ebba223a41304a6b82524e24fb install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@github:jitsi/robotjs#f0fc08c8d96231ebba223a41304a6b82524e24fb install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sbin/.npm/_logs/2020-01-03T11_41_51_897Z-debug.log

**Comment by saghul** [comment]
@hristoterezov Do you know of any incompatibilities with robotjs and the reporter's node / electron versions?

**Comment by saghul** [comment]
We updated robotjs and this should now build without problems.
