### ISSUE TITLE
Floating window resizing itself when dragging it

### ISSUE THREAD

**Issue by lrq3000** [jitsi/jitsi-meet-electron#192]
I tested the 1.1.1 build on Windows 10 64-bits, and the when I try to drag around the floating window, there's a very weird phenomenon that happens, which makes the floating window constantly resizes itself into being bigger and bigger and bigger indefinitely. And it seems there is no way to scale it down manually, so then I'm stuck with a huge window taking my entire screen.

**Comment by damencho** [comment]
This had been fixed, it is just that there was no release since it was fixed.

**Comment by lrq3000** [comment]
Damn! I would love to use the latest release then, because that's the one biggest complaint I have currently to keep using it. Is there a way I can build it? I have read there is a problem with the SSL certificate or something, will this prevent a custom build to work?

**Comment by lrq3000** [comment]
Sorry I mean "certificate" errors as mentioned in #178, will this affect custom builds if I try to connect to the common main server?

**Comment by lrq3000** [comment]
PS: as a workaround for those with the same issue as me, it's possible to reset the floating window size by opening and reducing again Jitsi Meet main window. It will however also position back the floating window back to its default position. But still better than having it cover the whole screen.

**Comment by lrq3000** [comment]
Correction: when minimizing jitsi meet main window, the floating window will be positined back where you left it, not the default position, so actually that's a very workable solution until there is a new release :-)

**Comment by saghul** [comment]
> Is there a way I can build it? I have read there is a problem with the SSL certificate or something, will this prevent a custom build to work?

Sure, you can build it by following the instructions on the README. The certificate problem doesn't affecct you because it's related to signing.

**Comment by lrq3000** [comment]
Ok great! I'll try that, thanks a lot! :D

**Comment by lrq3000** [comment]
Ok thanks, it works great! I have compiled a build for Windows here if someone else would like to use the latest release (don't worry there is no malware, that would be quite bad for my reputation :-) ): https://drive.google.com/file/d/1ikPE24KUsLDckkFBYfQbvtis2FutkVjF/view?usp=sharing
