### ISSUE TITLE
When I execute `npm install` on windows 10, I get the following error.

### ISSUE THREAD

**Issue by lixuguang** [jitsi/jitsi-meet-electron#194]
![image](https://user-images.githubusercontent.com/4262121/74298007-7eb3f980-4d83-11ea-86a8-97232b6c8487.png)

**Comment by saghul** [comment]
Did you pull latest master?

**Comment by lixuguang** [comment]
> Did you pull latest master?

yes, I did. I tried many times, but I never succeeded. I thought it may be caused by the bad network, but I still can't install it properly after I open the agent and I don't know what else I can do now.

**Comment by saghul** [comment]
What command did you use to clone the repo?
