### ISSUE TITLE
No Loading Screen

### ISSUE THREAD

**Issue by AkshitKrNagpal** [jitsi/jitsi-meet-electron#20]
**Current Behavior**
It shows blank white screen while `external_api.js` is being loaded.

**Desired Behaviour**
It should at least show a loading screen. 

I would like to work on this.

**Comment by hristoterezov** [comment]
This sounds like a nice feature. 

We haven't decided yet how exactly do we want to solve this issue. There are some ongoing discussion in the team on this topic. I'll keep you posted once there is a final decision.

**Comment by AkshitKrNagpal** [comment]
@hristoterezov 
Okay. Thanks.
Is the discussion going on somewhere I can join? Just asking.
