### ISSUE TITLE
Cannot share entire screen in Wayland

### ISSUE THREAD

**Issue by probonopd** [jitsi/jitsi-meet-electron#200]
Cannot share entire screen in Linux distributions such as Fedora that use Wayland as their display server. Just getting a black screen with a cursor in it.

Works well on Xorg based distributions.

Reference:
https://gitlab.freedesktop.org/wayland/wayland/issues/150

**Comment by saghul** [comment]
I think this is a problem in Chromium, which Electron uses. Do you get the same behavior when using a Chromium based browser vs the Electron app?

**Comment by probonopd** [comment]
Yes.

**Comment by saghul** [comment]
Yeah, this is a Chromium thing, not much we can do here, other than updating the Electron version when it's fixed in Chromium and  Eletron picks it up.

**Comment by probonopd** [comment]
Electron says Chromium needs to fix it, Chromium says Wayland has to fix it, and Wayland says they won't fix it...

A developer from the TeamViewer team neatly summarized the situation years ago:

https://community.teamviewer.com/t5/Linux/State-of-Wayland-amp-TeamViewer/td-p/26340

> By design, Wayland does not provide an interface to do remote control (screen capturing, mouse and keyboard emulation). This is to keep the Wayland core lean. The idea is that the compositor provides these interfaces, which could mean that TeamViewer would have to implement different interfaces for every desktop environment we want to support. This is unfortunate, but it's even more unsatisfying that these interfaces are not available yet.

**Comment by saghul** [comment]
Alas, that is how things are and we have no control over it.

**Comment by olberger** [comment]
FWIW, it's no better with Firefox ;-)

**Comment by genodeftest** [comment]
Actually, screen sharing *is* supported by Wayland through pipewire. New (unmerged?) changes in Electron include support for this: electron/electron#10915

In other words: This is being worked on and electron 8.2.2+ or 9+ should support this feature. As long as you keep electron updated, it should work out of the box some time in the near future.

**Comment by probonopd** [comment]
That's great to hear @genodeftest. i hope it will also work on non-GNOME systems, such as Xfce and MATE?

**Comment by genodeftest** [comment]
Do Xfce and MATE have support for pipewire? (I was surprised to learn that they have / will have wayland support…)

**Comment by blaggacao** [comment]
I played around with pipewire some time ago, pleased to see it's getting donwstreamed already into electron. It's really fresh bread.

**Comment by probonopd** [comment]
Does Pipewire work on Xfce and MATE or is it GNOME-focused only?

**Comment by genodeftest** [comment]
> Does Pipewire work on Xfce and MATE or is it GNOME-focused only?

You'll have to ask that question in their upstream. If they are investing in "*new*" technology such as wayland, they will have to go with pipewire or build their own alternative. If they are not interested in 21st century technology and security, they can keep using X. Pipewire seems to be part of the Wayland ecosystem just as stuff like xinput was part of the X ecosystem.

**Comment by rzr** [comment]
As a workaround, can RDP backend for wayland compositor ? 

This reminds me previous experiences I had with @Tarnyko ?

https://wiki.tizen.org/Weston_RDP_access

**Comment by faern** [comment]
Does anyone know if this should now work with the new releases based on Electron 12 (2.7.0 and 2.7.1)? This comment seems to indicate whole screen sharing should be possible now: https://github.com/wireapp/wire-desktop/issues/1630#issuecomment-788993291

I can get the new jitsi-meet-desktop release to run as a native Wayland application under flatpak in the following way:
```
flatpak run --socket=wayland org.jitsi.jitsi-meet --enable-features=UseOzonePlatform --ozone-platform=wayland
```
But when I try to share the screens the entire screen options are still just black.

Some part of this still seems to use X11. Because I can see the mouse pointer move around on the otherwise black shared screen view. But the position of the mouse pointer is only updated when it hovers an XWayland (X11) window, not when it hovers a native Wayland window.

I'm on Fedora 33 with sway 1.5.

**Comment by genodeftest** [comment]
Do you have pipewire installed and running? I thought I have read a while ago that screen sharing on wayland will only be enabled through pipewire.

**Comment by faern** [comment]
Yes. As far as I can tell I have pipewire installed and running. I also have `xdg-desktop-portal-wlr` installed and `XDG_CURRENT_DESKTOP=sway` set.

I found this as a reference also: https://github.com/flathub/org.jitsi.jitsi-meet/issues/7

Update to the previous post. It's not only whole screens that can't be shared. I noticed later that individual Wayland windows can't be shared either. The only windows that show up are the ones running under XWayland.

**Comment by dasJ** [comment]
Can confirm this is a jitsi-meet-electron bug. Screensharing works with Firefox (so pipewire and the desktop portal are working), and running with `jitsi-meet-electron --enable-features=UseOzonePlatform --ozone-platform=wayland` does the same black-window-with-cursors-only-updating-on-xwayland-windows-thing you explained above.

**Comment by saghul** [comment]
> Can confirm this is a jitsi-meet-electron bug. Screensharing works with Firefox (so pipewire and the desktop portal are working), and running with `jitsi-meet-electron --enable-features=UseOzonePlatform --ozone-platform=wayland` does the same black-window-with-cursors-only-updating-on-xwayland-windows-thing you explained above.

Can you get it to work on Chrome? Comparing it to Firefox is pointless because Electron uses the Chrome engine.

**Comment by alanorth** [comment]
As I understand it Chrome uses their own WebRTC implementation that does not use Pipewire. On Wayland it is currently better to use Firefox + Pipewire for screen sharing via the browser than the Jitsi Meet "desktop" (Electron) application.
