### ISSUE TITLE
Remote control fails on computer with external display

### ISSUE THREAD

**Issue by zestyjackets** [jitsi/jitsi-meet-electron#201]
Assume we have two users: User A and User B. User B has an external display connected. When User A sends a request to remote control User B's computer, User B receives an error:

```
2020-03-10T06:57:41.477Z [modules/remotecontrol/Receiver.js] Error: Can't detect the display that is currently shared
```

Using my application, I have tested various Electron versions and have found that 5.0.13 (current 5.x release) is the last build with working remote control on a user with an external display.

Does this have something to do with nodeIntegrationInSubframes changes in 6.0.0? https://www.electronjs.org/releases/stable?version=6&page=5

**Comment by Echolon** [comment]
@zestyjackets what is you operating system?

**Comment by csett86** [comment]
As remote control is unfortunately no longer supported (see https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md), closing this.
