### ISSUE TITLE
Support for HTTP authentication

### ISSUE THREAD

**Issue by outis151** [jitsi/jitsi-meet-electron#203]
In addition to the "secure domain" feature of jitsi-meet, I use http authentication with apache2 (which I have setup as a reverse proxy for jitsi meet).

jitsi-meet-electron however doesn't ask for credential input and just an unauthorized page is displayed

**Comment by saghul** [comment]
Sorry, we don't support that.

**Comment by Echolon** [comment]
@saghul should this be closed there fore as a `invalid` or `won't fix`?

**Comment by saghul** [comment]
Yep
