### ISSUE TITLE
Can only share the Jitsi Meet window when using AppImage on Gnome

### ISSUE THREAD

**Issue by JLTastet** [jitsi/jitsi-meet-electron#205]
When using the Jitsi Meet AppImage (`jitsi-meet-x86_64.AppImage`) on Fedora 31 with Gnome 3.34.4 (Wayland), I can only share the Jitsi Meet window. Other windows do not show up, and when selecting the entire screen, the screen share is black, with only the cursor being visible.

Sharing the entire screen works fine when using the WebRTC interface with Firefox 73.0.1, although it is still not possible to share individual windows.

When sharing the screen through the web interface, the Gnome "Screen casting" dialog box appears and prompts me to choose which screen to share, while for the electron app it never shows up.

Let me know if there is something I can do to help debug this issue.

**Comment by saghul** [comment]
HI there!

Alas this is a problem in Chromium, which is what Electron uses and what the app is built atop.

**Comment by C0rn3j** [comment]
Using [AUR/jitsi-meet-electron](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jitsi-meet-electron) on Arch, which extracts the AppImage, I don't even get to share the window.

![image](https://user-images.githubusercontent.com/1641362/76962881-50947d00-6920-11ea-99cb-df2ba6781f76.png)

Is there a Chromium issue/bug report I can follow about this? 

I've been working around this by using JM in Chromium where screen sharing works great (apart from not being able to recognize my screens separately, which I guess is an another problem entirely)

**Comment by JLTastet** [comment]
@saghul This seems to be an issue with Chromium indeed. I observe the exact same behaviour in Chromium and in the Electron app (as expected).

@C0rn3j With Jitsi Meet on Firefox 73, running on Fedora 31 with Gnome 3.34 (Wayland), I can choose which screen to share, but I cannot select an individual window.

**Comment by saghul** [comment]
I'm closing this as there is nothing we can do other than wait for Chromium to implement it (and then Electron).

**Comment by C0rn3j** [comment]
![image](https://user-images.githubusercontent.com/1641362/78546462-bd06eb80-77fd-11ea-945e-02066c30321b.png)

After updating to the latest jitsi-meet and jicofo git versions (NOT JM-electron) I am now able to share individual app windows on Linux (Xorg) using the electron app and also on Windows 10 using the electron app, so I guess the electron client itself wasn't the issue
