### ISSUE TITLE
UI to share screen is broken on X in the appimage

### ISSUE THREAD

**Issue by C0rn3j** [jitsi/jitsi-meet-electron#206]
![image](https://user-images.githubusercontent.com/1641362/77230472-c012a280-6b94-11ea-9d3b-db11ee46e526.png)

I am on Arch Linux, running the 1.1.1 AppImage.

As you can see, trying to share the screen does not show anything. 
However, if I use the Remote Control feature (which should seriously be more advertised, I found it by complete accident), the screen is actually shared (despite the remote control itself being broken), so the UI just isn't able to display that I can share my screen for some reason.

**Comment by saghul** [comment]
Can you please test the just released 2.0.0?

**Comment by C0rn3j** [comment]
https://github.com/jitsi/jitsi-meet-electron/issues/205#issuecomment-609702077
I forgot to close this here
