### ISSUE TITLE
Proxy Support?

### ISSUE THREAD

**Issue by knobhead** [jitsi/jitsi-meet-electron#208]
Hi,
is there any chance can I get jitsi-meet-electron to work behind a corporate proxy? It doesn't seem to adhere to system-wide proxy seetings nor `http[s]_proxy` ENV variables...

Win 10 b1903
Jitsi Meet Electron v1.1.1 github release

**Comment by knobhead** [comment]
ok, found it myself: 

start Jitsi Meet.exe with `--proxy-server=<ip>:<port>` (parameter. omit protocol)

thanks!

**Comment by saghul** [comment]
Thanks for leaving the solution!
