### ISSUE TITLE
Push-to-talk

### ISSUE THREAD

**Issue by mykolarudenko** [jitsi/jitsi-meet-electron#210]
Hi! I'd like to add a push-to-talk global shortcut. I see how to set a global shortcut in Electron but where do I find the "Toggle Mute" action to bind? Thanks!

**Comment by saghul** [comment]
There is already such a shortcut, the space bar. Does it not work in the Electron app?

**Comment by mykolarudenko** [comment]
I'm talking about a system-wide shortcut that works when the app is not focused. Currently, you need to switch back to the app.

**Comment by stefandesu** [comment]
I would really like to have this feature, but unfortunately, I don't think it is trivial to implement. I tried adding a [global shortcut](https://www.electronjs.org/docs/tutorial/keyboard-shortcuts#global-shortcuts) to the application which works in general, but according to [this issue](https://github.com/electron/electron/issues/7802), Electron uses one of Chrome's APIs to implement global shortcut listeners and that API does not support keyDown/keyUp events. And without keyDown/keyUp events, this is not possible to implement.

I don't have enough knowledge to hook into the OS's keyboard APIs to implement this, and I can imagine that this goes beyond the scope of this repository. I also couldn't find anyone else implementing this as a ready-to-use module.

Maybe a nice first step would be to add a global keyboard shortcut to mute/unmute oneself. That's better than nothing I guess.

**Comment by mykolarudenko** [comment]
Found a few working examples of doing it via ioHook lib. https://wilix-team.github.io/iohook/usage.html

**Comment by stefandesu** [comment]
I just found [this PR](https://github.com/vector-im/riot-web/pull/7709/files) which could be interesting for implementing it here as well.

**Comment by saghul** [comment]
I saw that PR and it is quite involved, including a native dependency.

This project gets little maintenancce and we just want to keep it simple. Muting / unmuting is already relatively straightforward with the always-on-top window.

Thus, I'm clossing this.

We might revisit this, who knows, but right now we can't have this, sorry.

**Comment by ThomasAH** [comment]
As the issue is already closed, just a quick "+1 ... push-to-talk would be very helpful for me" here.

**Comment by luixxiul** [comment]
FYI you could do +1 simply by clicking +1 icon on the first post.
