### ISSUE TITLE
Empty Screen from the App

### ISSUE THREAD

**Issue by Test4564** [jitsi/jitsi-meet-electron#212]
Hello together,
yesterday I installed the jitsi-meet-electron app from the Aur (Manjaro)
The install was successfully.
At the first start the app works fine, there was all icons, buttons and textfields...

But at the second start/all further starts the background from the app is empty (darkblue background without any icons, buttons,...).
I tried to reinstall the jitsi-meet-electron package, but now there is alwas the empty background.

Do you have an idea where the problem could be?

Thank you!
Best wishes

Alex

**Comment by netcoding** [comment]
the same at me.

**Comment by knobhead** [comment]
AUR package _works for me™_ on Arch Linux.
Can you start `jitsi-meet` from a terminal/shell and post debug output here?

**Comment by saghul** [comment]
Also, are you tagrettting your own deployment or meet.jit.si ?

**Comment by Test4564** [comment]
I solved the problem with this method:

1. I uninstalled the  jitsi-meet-electron package
2. searched for any left files from jitsi-meet in my filesystem
    => delete this files
3. reinstalled the jitsi-meet-electron package
4. and until now the app is working fine!

At my first install, I did not complete the start tutorial, and close the app.
At the next start, there was the problem, which I described in my first post.
Maybe there was the problem?

**Comment by Echolon** [comment]
@Test4564 I cannot answer to your question, but is this issue resolved?

**Comment by saghul** [comment]
@Test4564 Interrsting! Did you skip the tutorial or cancelled mid way?

**Comment by Test4564** [comment]
@Echolon 
For me the problem is solved but only through my workaround, and not through a official way.
Should I close the issue anyway?

**Comment by Test4564** [comment]
@saghul 
I cancelled it mid way. (I closed the program while the tutorial was running)

**Comment by Echolon** [comment]
I leave it open for the moment

**Comment by saghul** [comment]
No clear repro case, closing.
