### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by igygi** [jitsi/jitsi-meet-electron#213]
How do i uninstall this app?

**Comment by demlak** [comment]
depends on your operating system

**Comment by knobhead** [comment]
as a side note: 
Windows Version 1.1.1 installs fine _without_ Admin rights (Win 10 1903), but to uninstall Admin privileges are required.

**Comment by saghul** [comment]
On Windows: Just like any other app, it shows up in the add / remove software menu
On macOS: drag the iccon from the Applications folder to the trash
On Linux: delete the AppImage file.

**Comment by KhanhsBaor** [comment]
> On Windows: Just like any other app, it shows up in the add / remove software menu On macOS: drag the iccon from the Applications folder to the trash On Linux: delete the AppImage file.

@saghul  How can I clean or initial persist state after uninstall app ??
