### ISSUE TITLE
Is it possible to have an option to play system sounds?

### ISSUE THREAD

**Issue by PeeJVee** [jitsi/jitsi-meet-electron#215]
It would be an awesome feature to be able to play system sounds when doing an presentation with sounds or play simple games for example with your kid with assistance of remote desktop connection.

**Comment by damencho** [comment]
This will be available in latest jitsi-meet, you can share tabs with playing youtube videos with sound and on windows you will be able to share Apps with their sound. And all this from the webrowser, you will not need electron app. Probably those will be available for use and in the electron app. This version is still not deployed on meet.jit.si, but soon will be.

Please when you have questions use the community forum before opening new issues.
