### ISSUE TITLE
Win 10: Microphone permission problems

### ISSUE THREAD

**Issue by knobhead** [jitsi/jitsi-meet-electron#217]
Hi, 

thanks for Jitsi Meet and Jitsi Meet Desktop. Very helpful to have FLOSS solutions at hand in times of #covid-19.

Unfortunately we have trouble using JMD v1.1.1 running on Windows 10 1903. When trying to select the systems default (array) microphone, JMD gives a yellow warning toast popup "Error accessing the microphone" stating that the reason is unknown.
There's no console log output regarding this error:

```
[12:57:31.651] [info] Checking for update
[12:57:33.891] [info] Update for version 1.1.1 is not available (latest version: 1.1.1, downgrade is disallowed).
[12:57:33.892] [debug] checkForUpdatesAndNotify called, downloadPromise is null
```

Jitsi is not listed in Win 10 microphone privacy settings dialogue / list of allowed apps. Microphone Access is granted to all apps. Webcam permission works fine.

Our IT department suggests a driver problem with HP Elitebook 840 G6 notebooks' audio equipment (something Bang&Olufsen branded using an Intel Array .

Using an external audio input, e.g. USB microphone or bluetooth headset seems to work fine.

Any ideas where to poke next? Can I increase the debug log verbosity?

**Comment by saghul** [comment]
Can you try the latest beta releases? You will need to manually update due to a change in the signing key though.

**Comment by knobhead** [comment]
> Can you try the latest beta releases? You will need to manually update due to a change in the signing key though.

Yes, works for me! Thanks for your efforts!

**Comment by lzuhuo** [comment]
Hello. I installed 2.0.2 version and I had the same problem.
