### ISSUE TITLE
macOS: Camera and microphone permission error

### ISSUE THREAD

**Issue by rubendibattista** [jitsi/jitsi-meet-electron#218]
The app doesn't ask for permissions on macOS and in **System Preferences > Privacy** the app is not available to give the permissions to access camera and mic. 

<img width="781" alt="image" src="https://user-images.githubusercontent.com/8077364/77945891-b807e080-72c1-11ea-8323-568c4f348aba.png">

**Comment by saghul** [comment]
Can you test our latest beta releases? This is solved on those.

**Comment by rubendibattista** [comment]
I updated the App with the last beta and I have exactly the same problem, with the additional problem of getting this error when I close the app:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/8077364/78786639-60483400-79a9-11ea-8ab0-c7032ddbcc73.png">

**Comment by rubendibattista** [comment]
Sorry, 
I needed to remove all the things related to Jits in `Application Support` to make it work. Starting from scratch made the App asking for the right permissions. Thanks!

**Comment by kaxline** [comment]
I'm getting this with the 2.0.0 release.

I have a 2019 16" MacBook Pro running macOS 10.15.4, and I'm not being prompted to access my camera. Therefore the app says that it cannot access my camera. 

If I go into **System Preferences -> Privacy & Security -> Privacy -> Camera**, then I don't see Jitsi Meet as an option to give access.

Let me know if you need any more info to diagnose, or if I've missed something obvious.

**Comment by rubendibattista** [comment]
@kaxline 

Ehi, try to delete the `"/Library/Application Support/Jitsi Meet" ` folder.

**Comment by kaxline** [comment]
@rubendibattista Yep, that did it, thanks!

**Comment by rubendibattista** [comment]
Actually this is not completelfy fixed: if you change the server, the permission gets somehow forgotten, and it this not prompted again.

**Comment by caseyryan** [comment]
It still doesn't work. I don't have that folder at all. An no permission is ever asked

**Comment by aneesijaz** [comment]
same thing here ... Microphone list is being showed but it does not seems to work.

**Comment by dubf** [comment]
May 2022 and I'm having the same issue. Tried updating to the the latest version (2022.4.1) last night, but that didn't help. I forgot to note which version I was running before this update.

Running macOS Mojave 10.14.6 on a Mac Book Pro (Late 2017). Have been running this device and OS version for a long time and didn't use to have this problem with Jitsi half a year ago.

It doesn't seem to be an OS-side issue, since resetting Camera permissions by running the command `tccutil reset Camera` didn't help either.

**Comment by saghul** [comment]
Unlikely it's the same issue, please open a new one. We now allow opening devtools also on release builds, same shrotcut as son Chrome. Please share your console logs too.
