### ISSUE TITLE
No App Structure

### ISSUE THREAD

**Issue by AkshitKrNagpal** [jitsi/jitsi-meet-electron#22]
Currently, the app does not have a structure. It would become difficult to understand and contribute to this project for others.
There should be separate folders for main processes, renderer processes and assets.

**Comment by hristoterezov** [comment]
I think splitting the project into directories by functionality is better and more organized than splitting them into 2 folders - main and render. For example if we need to add some menus we can than create folder /menus, put the code related to the menus there and than use it in main.js or any other place that we need it.

I don't see what will be the benefit to have folders main and render.

Also the main process will always be 1, right? Am I missing something here?

**Comment by AkshitKrNagpal** [comment]
@hristoterezov 
> Also the main process will always be 1, right? Am I missing something here?

The main process includes a lot of functions like creating and managing BrowserWindow instances, registering global shortcuts, dialogs, menus, system trays, notifications, etc. Auto updater and crash reporter are also a part of the main process. ( I am not saying we will be needing all right now or in future but definitely some)
Also, when dealing with multiple windows splitting current `main.js` into multiple files will make the code more organised.
It would be nice if we have a main folder where all this code can be placed. 


> I don't see what will be the benefit to have folders main and render.
Besides what I said above
* It will prevent new contributors to mix up main and renderer process code.
* It will also enable uniformity in code.


> I think splitting the project into directories by functionality is better and more organized than splitting them into 2 folders - main and render.

I don't disagree with you. But the benefits are good and the code inside these folders will be organised too.

**Comment by saghul** [comment]
Let's close this and decide on every structure change as they are needed. As new features are implemented, we'll need changes, but it will become clearer once we get there.
