### ISSUE TITLE
Blank screen after entering conference name on private instance with ldap enabled

### ISSUE THREAD

**Issue by ynsta** [jitsi/jitsi-meet-electron#220]
Hello,

I can't use jitsi-meet-eltectron from AUR with private instance that require ldap authentication.

I get a blank screen (color #1b2638) instead of the authentication form after entering conference name.

My private instance is based on the docker compose from [here](https://github.com/jitsi/docker-jitsi-meet) and works well with firefox, chrome and android app.

I checked that the external_api.js is well served in by web server.

```
[...] "GET /external_api.js HTTP/2.0" 200 27486 "-" "-" 41917 [...]
```

edit: the issue is also present with windows release.

Kind Regards,

**Comment by mdavids** [comment]
Same thing here. Not sure if it is related to our authentication = "internal_plain" setting. Do you have that enabled?

**Comment by ynsta** [comment]
Authentication ldap for me, it's like the authentication modal is missing.

I tested with the windows client in release and it is not working.

**Comment by mdavids** [comment]
> Authentication ldap for me, it's like the authentication modal is missing.

I found another issue, causing the blank screen; Jitsi-Meet-Electron doesn't like the X-Frame-Options header. Do you have such a header configured, by any change?

**Comment by ynsta** [comment]
Yes thank you @mdavids it works if I remove the x-frame-options.

**Comment by mdavids** [comment]
> Yes thank you @mdavids it works if I remove the x-frame-options.

Nice! I read here and there that folks have programmed workaround (like here: https://github.com/electron/electron/issues/5036) maybe this something to be considered for jitsi-meet-electron as well?

**Comment by saghul** [comment]
The external API, which this client relies upon, requires opening up for iframe integration... I don't think we should workaround this on the Electron side.
