### ISSUE TITLE
Audio Transfer during remote control not possible

### ISSUE THREAD

**Issue by rogerknop** [jitsi/jitsi-meet-electron#222]
Hello,
I need to send the audio from the controlled PC which is running Jitsi Meet Electron App.
But the flag to activate that is not visible when starting sharing.
When I share from the Web App, I have this flag, but then I can't use remote control.
Regards, Roger

**Comment by saghul** [comment]
It's coming soon, with the next update.

**Comment by rogerknop** [comment]
With 2.0.0 it works now. 
But the problem is, that the voice is then doubled, so that I hear me twice.
Thanks, Roger
