### ISSUE TITLE
Wrong mouse position during remote control

### ISSUE THREAD

**Issue by rogerknop** [jitsi/jitsi-meet-electron#223]
Hello,
it happens very often that the mouse position of the remote PC is different to the controlling mouse.
Then you see both mouse pointers moving in sync but on different positions.
Regards, Roger

**Comment by saghul** [comment]
Can you please test version 2.0.0 ? We just released it.

**Comment by rogerknop** [comment]
Cannot be installed. Chrome blames download as virus and win 10 defender is doing the same.

**Comment by saghul** [comment]
Can you try beta 3? It should be solved on that one.

**Comment by rogerknop** [comment]
Still virus warnings in crhome and win 10.

**Comment by saghul** [comment]
@awlx Any idea?

**Comment by awlx** [comment]
@saghul that is very interesting ... because none of my users reported that.

**Comment by awlx** [comment]
Also asked some of our users to download it and none has a mention of a specific virus. It's just the normal "You downloaded a potential dangerous file" like with every unsigned .exe.

**Comment by rogerknop** [comment]
I get the message after downloading in Chrome: Unusual download. Potentially dangerous.
If I ignore this warning and keep the exe file, I cannot start it, because Defender is blocking this.

3 days ago, the previous version was 30 MB smaller! And I did not get any warnings from Chrome or Win 10.

**Comment by saghul** [comment]
I can asssure you we didn't add 30MB worth of virii to our app!

**Comment by rogerknop** [comment]
Now 2.0.0 I could download with the mentioned certificate warning. The virus warning does not appear anymore. Also installation worked fine again.
AND the issue does not appear anymore :-)
Thanks, Roger
