### ISSUE TITLE
this app is old

### ISSUE THREAD

**Issue by heylix** [jitsi/jitsi-meet-electron#224]
Hi Jitsi people,

Since this is the "official" app and it didn't have a release for years, wouldn't it be beneficial to just merge the changes from https://github.com/freifunkMUC/jitsi-meet-electron/ which is maintained by a community in Munich and has current, updated releases?

@awlx

**Comment by saghul** [comment]
We will be releasing a new version this week. As for the changes, they haven't submitted them to us AFAICT.

**Comment by awlx** [comment]
@heylix @saghul I opened a merge request, gonna work on the debrandings this evening if the PR otherwise suits your stuff :).
