### ISSUE TITLE
Downloads very slow

### ISSUE THREAD

**Issue by Razzeee** [jitsi/jitsi-meet-electron#230]
Hey, 

this might not be the correct place, so if this is wrong, please refer me to a better repo :)

Downloading the stable desktop build of jitsi are projected to take about 45 minutes for me via https://desktop.jitsi.org/Main/Download#latestnightly
That's not due to my connection. It also decided to get more bandwidth now and was done instantly now. Feel free to close this, but I think it's good for you to know, as people that just want to try the client might be annoyed by this.

https://download.jitsi.org/jitsi/windows/jitsi-latest-x64.exe

**Comment by saghul** [comment]
What did you want to dowmload, the legaccy Jitsi Desktop client or the Jitsi Meet electron client?

**Comment by Razzeee** [comment]
I guess it might still be my connection, downloading the jitsi meet beta from github is stuck at about 200-300kb/s
Sorry for the noise

**Comment by Razzeee** [comment]
I'm only interested in the new electron client due to the FF problems and jitsi being evaluated for our company (but unfortunately seeming to loose against Teams)

**Comment by saghul** [comment]
You are right. We are in the process of revamping our website, and we'll hopefully maake that clear soon. Here is the one you are looking for: https://github.com/jitsi/jitsi-meet-electron/releases
