### ISSUE TITLE
AutoUpdate

### ISSUE THREAD

**Issue by ebal** [jitsi/jitsi-meet-electron#232]
I've noticed that the AppImage is automatically download the latest version of jitsi-meet-electron.

This is a nice feature, but perhaps it's best NOT to automatically download ~80M in the background but ask the user (via a popup?) if they want to download the latest app. This behavior takes a little bandwidth when you need it for the meeting, and it is always polite to ask & inform users that the app is downloading files in the background when using it.

```bash
20:12:59.444 › Checking for update
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
20:13:03.011 › Found version 2.0.0-beta3 (url: jitsi-meet-x86_64.AppImage)
20:13:03.013 › Downloading update from jitsi-meet-x86_64.AppImage
20:13:03.015 › updater cache dir: /home/ebal/.cache/jitsi-meet-electron-updater
```

**Comment by saghul** [comment]
I hear you, but realistically speaking you are going to burn 80MB very quickly while having a video conference, so I don't think the impact is that high. Web browsers have been doing this for ages now and wether some like it or not it has become standard practice. I know it may reate a bit of trouble for some, but the vast majority will benefit from transparent upates so things like security updates are not missed.

**Comment by ebal** [comment]
fair enough,
I would counter propose at least a short notify for transparency reasons.

**Comment by chamerling** [comment]
Hello,

Coming back to this subject, we agree that this is a common practice in personal deployments BUT this is not common in some professional deployments: There are some companies which does not want to have auto updates and want to manage updates 'by hand' in some cases.

Are you against a compilation flag to disable auto update?

**Comment by saghul** [comment]
> Are you against a compilation flag to disable auto update?

Not at all, that is a very reasonable way to do it, assuming it will default to the current value. A command line arg disabling updates for a given run so testing can be done is also fine, since it's very explicit.
