### ISSUE TITLE
Remote Control button not visible

### ISSUE THREAD

**Issue by simformsolutions** [jitsi/jitsi-meet-electron#236]
I have installed latest beta 3 version on windows 10. After doing npm install started the app. I did started in browser too for screen share but from Electron app not able to find any remote control access button. Please guide. @saghul

**Comment by saghul** [comment]
<img width="386" alt="Screen Shot 2020-04-08 at 11 49 46" src="https://user-images.githubusercontent.com/317464/78770604-13576400-798f-11ea-9db7-b5c086bcabdf.png">

Only Elecctron app participants can be controlled. You can access the menu in the 3 dots button for that participant's tile.

**Comment by simformsolutions** [comment]
@saghul  so that means, if I have one web view participants and 1 is from electron participant then `Remote Control` button will not come..right ?  Both the side Electron app is compulsory ?

**Comment by saghul** [comment]
Only the controllED side needs to be on Electron. The controlING side can be anywhere.
