### ISSUE TITLE
Screen sharing issue

### ISSUE THREAD

**Issue by PeeJVee** [jitsi/jitsi-meet-electron#238]
Hi!

Happened now few times: Cannot share my screen from jitsi-meet-electron for mac (happened from 1.1.1 and also beta3) I get this warning with changing numbers:

2020-04-08 13:49:52.346 WARNING: [51] [confId=d29eae95278a7f6c epId=33f9deb9 gid=ff588e stats_id=Lesley-Yoz conf_name=testaillaan] VideoParser.transform#58: Unable to find encoding matching packet! packet=RtpPacket: PT=100, Ssrc=2819984434, SeqNum=29999, M=false, X=true, Ts=2898691116, encodings=

Any ideas?

**Comment by PeeJVee** [comment]
Gets back to working, dont know how.

**Comment by saghul** [comment]
Does it also happen with the latest release (2.4) ?

**Comment by d3hof** [comment]
Not working on iOS 14.2 with jitsi app version 20.5 either.

**Comment by saghul** [comment]
@d3hof The question is about the Electron app. It's not yet implemented on iOS.

**Comment by d3hof** [comment]
@saghul would you be so kind and tell me where to find issues regarding the app for iOS and Android?

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet

**Comment by d3hof** [comment]
@saghul thank you!
