### ISSUE TITLE
2.0.0.Beta3 on mac keeps on popping accept incoming network connections

### ISSUE THREAD

**Issue by PeeJVee** [jitsi/jitsi-meet-electron#240]
Do you want the "jitsi meet.app" to accept incoming network connections? It keeps popping up all the time even though i have accepted them in firewall also. I havent had the problem with 1.1.1. version so i was wondering if there is something to do about it.

**Comment by saghul** [comment]
You should only need to accpt that once. The change is due to Electron using more modern maOS APIs.

**Comment by saghul** [comment]
Cannot reproduce this. It askss only once for me.
