### ISSUE TITLE
Unable to access camera start up, down 5-10 sec.

### ISSUE THREAD

**Issue by edgiru** [jitsi/jitsi-meet-electron#241]
Hello!
My camera turns off after a while.
![Annotation 2020-04-08 165720](https://user-images.githubusercontent.com/4624056/78793675-66dfa700-79bb-11ea-8bb8-64f333cc1d89.jpg)

I use a desktop application. I create a conference room at the entrance, everything works. After about 5-10 seconds, the camera turns off with the message that it can’t access the camera that the camera is supposedly using another application, but the microphone built into the camera continues to work. In google chrome there is no such thing, everything works fine and the camera does not crash. Firewall is disabled in Windows 10.

When viewing the "settings" of the camera, it turns on
 and shows.
![Annotation 2020-04-08 170050](https://user-images.githubusercontent.com/4624056/78793701-70690f00-79bb-11ea-9d51-7a7ca8d1f312.jpg)

When you preview the camera in the center from the bottom, the camera also turns on and shows.
![Annotation 2020-04-08 165937](https://user-images.githubusercontent.com/4624056/78793719-76f78680-79bb-11ea-8ad5-f3cdf2068061.jpg)

OS: Windows 10 1909 (build 18363.720)
cam: A4 Tech HD PC Camera (ID: USB \ VID_0AC8 & PID_3500 & REV_1007 & MI_00) Driver: Microsoft
soft: jitsi-meet-electron v2.0.0-beta4

**Comment by iarani1975** [comment]
Facing the same issue after build on macOS Mojave after build. Similar to #299

**Comment by saghul** [comment]
We have made many changes to handle these in Jitsi Meet. Please test the latest version, using meet.jit.si as the server.
