### ISSUE TITLE
Auto-Update

### ISSUE THREAD

**Issue by demlak** [jitsi/jitsi-meet-electron#243]
Hi,
where to disable auto-update? and why the hell is this not a user-choice or any warning?
It's a horror time now for us. we build our own version with our own server as default one and translation into our own language. we deployed this to our friends who are absolutly not into computers. and now they were auto-updated.

**Comment by saghul** [comment]
Interesting attitude. You created your own project using ours, made a mistake, YOUR mistake, and somehow we are to blame.

Your users were auto-updated because you didn't change the repository in package.json: https://github.com/jitsi/jitsi-meet-electron/blob/6ce4e51071b886ea804fa3ff182c3d89eca874f9/package.json#L66

**Comment by demlak** [comment]
i'm sorry if i offended you, that's not my attitude. i understand, that in a developer-world it is kind of my own mistake to not check and understand the complete code, before i deploy my own build.. but well.. really?

my complainment is not only about the own build. to present a warning is respectfull to the user and is typical in software-updates for decades. sorry.. but implementing an auto-update without a warning is kind of disrespectful and a take-over. minimum it should be announced that there will be no warning. better would be a warning.
you made a very helping onboarding for users. but why not a little warning?
There are many reasons why a warning should be placed in.

- 100mb download automaticaly on a per data-package-payed line could cost much (not every jitsi-meet instance out there is on the internet. There are also local server instances typicaly for those you have to pay much on internet-data)
- letting users decide if and when an update could happen, is respectfull
- an auto-update to a software that is not wideley tested could lead to a non working software. it should be choice of user which version gets installed.
- MITM-Scenarios are not user-controllable on auto-updates.

and so on.. and on. 

thx for showing the option to change the repo for auto-update. but the question was about how to disable auto-update at all. is this possible in an easy way?

thx
