### ISSUE TITLE
AppImage 2.0.0. does not start due to SUID sandboxing not found, old working AppImage rendered unusable due to forced automatic update

### ISSUE THREAD

**Issue by musger** [jitsi/jitsi-meet-electron#244]
The latest jitsi-meet-2.0.0-x86_64.AppImage on my 64bit Debian/GNU Linux box fails to start throwing
`[12197:0409/033907.851569:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_jitsi-UzQxwu/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap`
The old and previosly working AppImage was just rendered useless as I am writing this by being automatically and forcibly updated to 2.0.0 now crashing with the same (above) error.

**Comment by cni-md** [comment]
Yes, a big pain. You have to delete the app image an download a fresh 1.1 verison. It will auto update again, so you have only one try to start the app.

**Comment by saghul** [comment]
Dupliocatte of https://github.com/jitsi/jitsi-meet-electron/issues/231?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDgxMTk3OTYwOTozMTc0NjQ%3D&notifications_query=repo%3Ajitsi%2Fjitsi-meet-electron#issuecomment-610907172

**Comment by olberger** [comment]
./jitsi-meet-x86_64.AppImage --no-sandbox worked for me, in case it helps.

**Comment by musger** [comment]
Thanks Oliver, this indeed works around the error! 

I don't understand what sandboxing means in the context of
jitsi-meet-electron but perhaps this flag could be made the default
for 64bit Linux application images unless it poses a security risk(?).
