### ISSUE TITLE
Provide Docker-based way to run locally

### ISSUE THREAD

**Issue by olberger** [jitsi/jitsi-meet-electron#245]
It would be interesting to have a way to (rebuild and) run jitsi-meet-electron inside a docker container, to "sandbox" it, much like what is done for Zoom in this repo : https://github.com/mdouchement/docker-zoom-us

Thanks in advance.

**Comment by saghul** [comment]
I don't think there is a good reason to do that here. This app is open source, you can inspect what it does and also build it yourself.
