### ISSUE TITLE
AppImage 2.0.0 does not wirk with auth. setup

### ISSUE THREAD

**Issue by miwie** [jitsi/jitsi-meet-electron#246]
I have a jitsi setup with enabled authentication so that only moderators are able to start a new conference. This works w/o any problmes in brwoser and Android app.
If I try the same with the AppImage I only get a black screen after typing a room name and "Go". There should popup a message saying that the conference not yet started and the user should wait for the moderator to start it or start the conference by submitting authentication details.

**Comment by saghul** [comment]
Do you get any logs? Any chance youi can run the dev version to check?

**Comment by miwie** [comment]
All I get in the terminal is:

`$:~$ Downloads/jitsi-meet-x86_64.AppImage
15:27:30.096 › Checking for update
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
15:27:31.349 › Update for version 2.0.0 is not available (latest version: 2.0.0, downgrade is disallowed).
15:27:31.350 › checkForUpdatesAndNotify called, downloadPromise is null
`
How would I run the dev version? If not to many hassles I could try that.

**Comment by saghul** [comment]
Here you go: https://github.com/jitsi/jitsi-meet-electron#development

**Comment by ulab** [comment]
Not sure if this helps zero in on the problem, but I have (LDAP) authentication for hosts and guests activated in my setup. The app version 2.0.0 is running on OSX 10.14.6 and was installed with brew.

Authentication works as expected (German internationalization): 

<img width="912" alt="Screenshot 2020-04-10 at 21 58 33" src="https://user-images.githubusercontent.com/504616/79019383-83740e80-7b76-11ea-8e32-27c075c138ae.png">
<img width="912" alt="Screenshot 2020-04-10 at 21 58 20" src="https://user-images.githubusercontent.com/504616/79019390-88d15900-7b76-11ea-9b6b-9f38e31c83c5.png">

**Comment by miwie** [comment]
Running app version 2.0.0 on MacOS using my jitsi setup (with moderator auth.) does not work either. Same effect as with the Appimage on Linux: black screen only.
If using web access and Android App would not work I'd suspect a wrong setup on my side, but both work flawlessly.

Up to now I was not able to build the dev version (and I don't want to spend much time on trying it).

**Comment by ulab** [comment]
Not sure if this will cause issues like thata, but the `README.md` mentions it requires `external_api.js`. (I'm just poking things with an engineering stick, not really knowing what might be the issue 😄)

Can you try calling `https://meet.example.com/external_api.js` (with your hostname) in a browser and see if it returns javascript code?

Do you run https with self-signed certificates or Let's Encrypt?

**Comment by miwie** [comment]
external_api.js is enabled/served from nginx. 
Cert from Letsencrypt.

**Comment by ulab** [comment]
Sorry, out of things to poke the stick at. I hope @saghul can help you out with this.

**Comment by saghul** [comment]
I just tested it by pointing it to my test erver with internal auth and it works ok:

<img width="912" alt="Screen Shot 2020-04-14 at 09 49 43" src="https://user-images.githubusercontent.com/317464/79199505-65880180-7e35-11ea-859d-3e44ac674e58.png">

If you can run the dev version, you could see the console by opening the developer tools with Cmd + option + i, like in Chrome.

**Comment by nobbs** [comment]
> external_api.js is enabled/served from nginx.
> Cert from Letsencrypt.

Have you by any chance a reverse-proxy in front of Jitsi that is setting the `X-Frame-Options` header to `DENY` or `SAMEORIGIN`? Had the issues you described -- in the end, this header was the culprit, see also the issues #233 and #220. Removing it solved the issues.

**Comment by miwie** [comment]
Great!
I configured nginx with some additional headers (to get a better rating from https://observatory.mozilla.org/ ). Two of them are responsible that the Electron App does not work:
``` 
 add_header Content-Security-Policy "frame-ancestors 'none'";
 add_header X-Frame-Options "DENY";
```
After removing these everything looks fine now!
Thanks for pointing me to the other issues!

**Comment by saghul** [comment]
If either of you could update the README pointing those out, it would be great :-)

**Comment by miwie** [comment]
Just submitted a pull request.

**Comment by saghul** [comment]
Landed, thank you!
