### ISSUE TITLE
Can't remote control Linux from Windows.

### ISSUE THREAD

**Issue by FrenchHope** [jitsi/jitsi-meet-electron#248]
I can remote control Windows from my Fedora but not the other way.

**Comment by PeeJVee** [comment]
I have also noticed that i cant remote control windows on my mac but vice versa works fine.

**Comment by guerby** [comment]
Remote control Windows from debian 10 ok, but the reverse doesn't work (no mouse/keyboard control)

**Comment by saghul** [comment]
Ping @hristoterezov @andrei-gavrilescu

**Comment by andrei-gavrilescu** [comment]
I'll check it out.
