### ISSUE TITLE
Can't connect to own instance - configuration question

### ISSUE THREAD

**Issue by mMuck** [jitsi/jitsi-meet-electron#250]
Hi,
with the electron app I can't connect to a individually hosted jitsi instance. It responds with this after some seconds of the loading spinner but without any further information:
![grafik](https://user-images.githubusercontent.com/8143240/78925643-61d53300-7a61-11ea-8104-cdf205844cfe.png)

The server instance has room create auth enabled.

Perhaps this is connected to this, because "/external_api.js" serves the min.js file
_Originally posted by @saghul in https://github.com/jitsi/jitsi-meet-electron/issues/133#issuecomment-428064589_

Is the difference in the "external_api.js" served version a limitation of the electron app or is this documented somewhere and there is an error in the installation of the jitsi server.

Thanks.

**Comment by derwok** [comment]
> is this documented somewhere 

see here: 
https://github.com/jitsi/jitsi-meet-electron#using-it-with-your-own-jitsi-meet-installation

**Comment by mMuck** [comment]
Thanks 👍 
I will check the HTTP headers and will compare both /external_api.js responses from official meet.jit.si and the own installation.
