### ISSUE TITLE
Controlling Jitsi with javascript in my electron app

### ISSUE THREAD

**Issue by cfry** [jitsi/jitsi-meet-electron#251]
I've got a large electron app that is a development environment for software.
From it, I'd love to programmatically:
- connect to jitsi server
- set up a conference room
- send a text message to it
- set up a callback to get messages posted by other people.
I've carefully searched the source for jitsi-meet-electron,
https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/example/example.js
and everything else I can find on the web. Tried lots of code but 
can't get it to work.
What I need is a concise, complete JS example.
Please help! This is an open source project for robotics.
Any pointers to such examples greatly appreciated!

**Comment by akshitkrnagpal** [comment]
Hi @cfry 

You can accomplish these using Jitsi Meet API. Have you tried the following link?
https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md

**Comment by cfry** [comment]
thanks so much akshitkrnagpal, I didn't know about that doc.
I can now, within my electron app, programmatically create a jitsi session, and do
api.dispose()
api.executeCommand('toggleChat') 
api.getNumberOfParticipants()
The UI works great including sending and receiving chat messages.
What I can't do is programmatically send or receive chat messages.
Note doc on the doc page leaves out the event name, it should be:
api.executeCommand('sendEndpointTextMessage', 'Fry', 'programmatic text'); //does nothing
api.executeCommand('sendEndpointTextMessage', 'fry_dde', 'pt1') //can't even send text to myself.
For receive
function text_listener(data){
  console.log("got text data: " + JSON.stringify(data))
}
api.addEventListener('endpointTextMessageReceived', text_listener); //text_listener not called even though gui shows message sent from other jitsi client in my electron jitsi window.
Am I missing something?

**Comment by akshitkrnagpal** [comment]
Are you using https://meet.jit.si server? Can you try https://beta.meet.jit.si?

After taking a quick look, I can see`sendEndpointTextMessage`, `endpointTextMessageReceived` were added just last month in https://github.com/jitsi/jitsi-meet/pull/5137. https://meet.jit.si does not always have the latest changes but only stable changes. 

I don't manage servers though so can't comment on that.

**Comment by cfry** [comment]
Yes  I was using ttps://meet.jit.si server.Clever idea, to use the beta server, but I get the same behavior. 
When calling, from my electron app:api.executeCommand('sendEndpointTextMessage', 'Fry', 'programmatic text'); //does nothing 
No errors. Also a text message sent programmatically from my electron app does not even show up in the Jitsi GUI on my electron app (let alone the Jitsi GUI when I run it directly from a chrome browser.The two can obviously communicate because via the gui, I can send messages.
How do you send a text message to all participants instead of just a particular one? 
There's no doc on this in sendEndpointTextMessage. 
If the problem had to do with selecting a particularparticipant, then sending to "all participants" might isolate that bug.

One more thing: I am using Electron 4, which doesn't have the latest chrome. (chrome version 69, with Node version 10.11) Might it be that sendEndpointTextMessage requires a later version of chrome or node? I am not getting errors, as I suspect I would be if I had the wrong version of chrome, but still.

**Comment by akshitkrnagpal** [comment]
> Clever idea, to use the beta server, but I get the same behavior.

I can confirm it is available and working in beta server. The problem might be of participantId.

> api.executeCommand('sendEndpointTextMessage', 'Fry', 'programmatic text');

I am not sure you are using correct participantId. It should look something like `a71262ea`.
Try `console.log(api._participants)`, the keys of the object should be the id. You can also get when when `participantJoined` event is called.

> I am using Electron 4

Electron version should not be a problem.

And I don't think `sendEndpointTextMessage` and `endpointTextMessageReceived` are the same as what you see in Jitsi Chat GUI. For GUI, there are two more events `incomingMessage` and `outgoingMessage`, they are events you can use to set up callback actions. Sending a message isn't available in the API. So it will be a feature request in https://github.com/jitsi/jitsi-meet.

Depending on the use case, you can use `sendEndpointTextMessage` and `endpointTextMessageReceived` and implement custom UI, if you need it.

**Comment by cfry** [comment]
The concept of a participantID being both undocumented and different from the displayed ID certainly would screw up any developer.
The concept of there being an undocumented  secrete text message channel that's
different than the GUI chat certainly would screw up any developer.
I  am taking careful notes and will make a coherent doc for your review when I
make it through this process so that your valuable knowledge can be used
by others. Thank you!

Now after following your latest directions, I at least am up to the point of getting an error
message when sending an email (major advance!) 
Here's what I've got:
`var domain = 'beta.meet.jit.si' //'meet.jit.si'
var options = {
    roomName: 'fry_room',
    width:  490,
    height: 470,
    parentNode: jitsi_id // document.querySelector('#meet')
    //openBridgeChannel: true //https://github.com/jitsi/jitsi-meet/blob/master/config.js, maybe helps text messaging
                      //but this does not fix the error when sending: Failed sending endpoint text message Error: Channel support
}
var api = new JitsiMeetExternalAPI(domain, options)
function text_listener(data){
  console.log("got text data: " + JSON.stringify(data))
}
api.addEventListener('endpointTextMessageReceived', text_listener); //not GUI chat messages, just secrete data channel messages

                                  //'receiverParticipantId', ;the message
api.executeCommand('sendEndpointTextMessage', api._myUserID, 'programmatic text'); 
//beware: such sent messages don't display in the UI of Jitsi`
And when making that last call I get:
`Logger.js:154 2020-04-11T17:53:23.026Z [modules/API/API.js] <Object.send-endpoint-text-message>:  Failed sending endpoint text message Error: Channel support is disabled!
    at t.value (VM1479 lib-jitsi-meet.min.js:1)
    at oe.sendEndpointMessage (VM1479 lib-jitsi-meet.min.js:10)
    at Object.sendEndpointMessage (VM1480 app.bundle.min.js:126)
    at Object.send-endpoint-text-message (VM1480 app.bundle.min.js:126)
    at b.on (VM1480 app.bundle.min.js:126)
    at n.size.n.forEach.e (VM1480 app.bundle.min.js:29)
    at Set.forEach (<anonymous>)
    at p.emit (VM1480 app.bundle.min.js:29)
    at p._onMessageReceived (VM1480 app.bundle.min.js:29)
    at postis.listen.e (VM1480 app.bundle.min.js:29)
    at u (VM1480 app.bundle.min.js:152)`
Note that I attempted to enable Channel support by
going though config.js and finding the only related option:
openBridgeChannel: true
But that didn't change this error.
If you've got it working in the beta server, perhaps the easiest thing
is for me to just see your code, but I can appreciate if its 
proprietary or nested very deep, so fixing my simple example above
might still be easier.
THANKS!!!
PS: note that `api._myUserID`  is the same as one of the keys in
api._participants.

**Comment by akshitkrnagpal** [comment]
> The concept of a participantID being both undocumented and different from the displayed ID certainly would screw up any developer.
The concept of there being an undocumented secrete text message channel that's
different than the GUI chat certainly would screw up any developer.

Can you please create an issue in https://github.com/jitsi/jitsi-meet regarding the same? Also, I am not sure for what use cases `sendEndpointTextMessage and `endpointTextMessageReceived` were introduced. Might be better to ask there and close this issue as it is not directly related to electron app.

> Failed sending endpoint text message Error: Channel support 

Now I am also getting the same error message. So I am pretty sure you are doing exactly what I was doing.

**Comment by saghul** [comment]
Yep, this belongs on jitsi/jitsi-meet Thanks for helpiong out @akshitkrnagpal !

**Comment by cfry** [comment]
Thanks, I've submitted the issue to jitsi-meet.

**Comment by MuhammadFaizanHaidar** [comment]
Hi @cfry did you find out the solution. For this one?
api.executeCommand('sendEndpointTextMessage', api._myUserID, 'programmatic text');
//beware: such sent messages don't display in the UI of JitsiAnd when making that last call I get:Logger.js:154 2020-04-11T17:53:23.026Z [modules/API/API.js] <Object.send-endpoint-text-message>: Failed sending endpoint text message Error: Channel support is disabled!
