### ISSUE TITLE
Please build Debian package

### ISSUE THREAD

**Issue by olberger** [jitsi/jitsi-meet-electron#252]
Would you please also build/release a .deb package, which requires the following patch: 49feea2a21c66ecec49a510aaadae57a8fbc8582

It think it would help in the context of
https://github.com/jitsi/jitsi-meet-electron/issues/231

**Comment by saghul** [comment]
Sorry, but we have to draw the line somewhere. Our attention has to be divided amongst many projects, and adding yet another thing we maintain is not something we can afford.

As for #231 that wouldd only help Debian, Ubuntu for example seems to be configured to allow it out of the box, so this wouldn't be a silver bullet anyway.

**Comment by 532910** [comment]
It will be nive to have deb packages available via https://download.jitsi.org/
