### ISSUE TITLE
Need help with signing / notarization?

### ISSUE THREAD

**Issue by jakubzitny** [jitsi/jitsi-meet-electron#253]

**Comment by Echolon** [comment]
@jakubzitny what exactly do you mean?

**Comment by jakubzitny** [comment]
Mac apps on Catalina need to be "notarized by apple" in order to get rid of the message that they might contain malware. Last time I checked Jitsi in Electron was not properly notarized and I had the warning.

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by luixxiul** [comment]
Closing as duplicate of https://github.com/jitsi/jitsi-meet-electron/issues/234

**Comment by jakubzitny** [comment]
Careful though, this is a macOS-specific thing. Windows is a separate thing (you need a EV certificate with a hardware signing key). But it's one issue of signing the builds.

**Comment by luixxiul** [comment]
Please let me know if they are essentially the different issue. I would like to reopen the issue then, thanks!

**Comment by jakubzitny** [comment]
It is essentially just one problem, but has to be solved differently for Windows and macOS. So, you decide.

**Comment by luixxiul** [comment]
I see. Would you please replace the title, so that it would indicate the difference between this issue and #234?
