### ISSUE TITLE
AltGr from french keyboard doesn't seem to work while remote control

### ISSUE THREAD

**Issue by guerby** [jitsi/jitsi-meet-electron#254]
Tried Linux (debian 10) to control linux (debian 9) and Linux (debian 10) to control windows 10 and in both case AltGr-6 didn't produce a pipe character (keyboard FR).

**Comment by saghul** [comment]
@hristoterezov any idea? that would be a robotjs issue or ours?

**Comment by csett86** [comment]
As remote control is unfortunately no longer supported (see https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md), closing this.
