### ISSUE TITLE
[Linux] System audio sharing

### ISSUE THREAD

**Issue by snevas** [jitsi/jitsi-meet-electron#255]
Release: 2.0.0 AppImage

According to changelog system audio sharing should work, no mention of Linux being excluded:
"Updated jitsi-meet-electron utils, bringing in new features such as system audio sharing (if the Jitsi Meet deployment has support for it)."

There is no checkbox to share the system audio when trying to share your screen.

**Comment by saghul** [comment]
> if the Jitsi Meet deployment has support for it

It hasn't been released to meet.jit.si yet (the Electron integration part) nor it has been to our Debian stable packages.

**Comment by joe733** [comment]
It's `2.3.1` now. Is this feature released? still no option seen in the app..

**Comment by saghul** [comment]
That feature is only supported on Windows. Chrome does not support system audio sharing elsewhere. In the browser, it's only supported when sharing a tab on macOS and Linux, and there is no such thing as sharing a tab here.

**Comment by joe733** [comment]
Is there any known workaround (except rerouting sound via mic) for this?

**Comment by saghul** [comment]
Alas, no, sorry.
