### ISSUE TITLE
Add repo URL to help

### ISSUE THREAD

**Issue by svoop** [jitsi/jitsi-meet-electron#256]
On MacOS, the automatic update from 1.1.1 to 2.0.0 does not work. Shouldn't be a problem, just download and install it manually.

Unfortunately, in the help menu on the welcome screen, "About" links to "https://jitsi.org/what-is-jitsi" which neither mentions nor contains any download link for Jitsi Meet Electron:

<img width="195" alt="Screen Shot 2020-04-10 at 14 44 26" src="https://user-images.githubusercontent.com/7255/78991768-fe6b0400-7b39-11ea-99ef-72ebb13f7097.png">

It would be very helpful to have the URL to this repo (https://github.com/jitsi/jitsi-meet-electron
) added to the help menu.

Thanks for considering this small addition.

**Comment by saghul** [comment]
Good point. Would you like to open a PR with a fix?

**Comment by svoop** [comment]
@saghul Sure thing, here you go: #257
