### ISSUE TITLE
Room name handling not the same as meet.jit.si

### ISSUE THREAD

**Issue by sj14** [jitsi/jitsi-meet-electron#262]
When I enter a room on meet.jit.si, all spaces in the room name get removed and `Room With Spaces` automatically becomes `RoomWithSpaces`. When I enter `Room With Spaces` in jitsi-meet-electron, the room becomes `Room%20With%20Spaces`.
Thus, entering the same name leads to different rooms.

**Comment by aerogus** [comment]
maybe related to https://github.com/jitsi/jitsi-meet-electron/issues/326 and so fixed in the next release ?

**Comment by saghul** [comment]
Tentatively closing.

**Comment by sj14** [comment]
Doesn't seem to be solved for me with version 2.1.0.
