### ISSUE TITLE
Option for accepting self signed certs

### ISSUE THREAD

**Issue by jpds** [jitsi/jitsi-meet-electron#268]
I have a testing Jitsi server that's behind a VPN connection, so it currently has a self-signed cert.

Currently users are using it with a web browser, but some of them would like to use this app - but I cannot get the app to accept the internal domain name for the server.

While the app says that the URL is invalid, I can see it making an HTTP request in the server logs:

```
"HEAD //external_api.js HTTP/1.1" 301 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) JitsiMeet/2.0.0 Chrome/80.0.3987.163 Electron/8.2.1 Safari/537.36"
```

**Comment by saghul** [comment]
Sorry, this is not a scenario we will support. You are welcome to make a ccustom build that forgoes the check here: https://github.com/jitsi/jitsi-meet-electron/blob/bbe835d23a52019ad4554c234b5737f0ebaa7821/main.js#L196 but it's just not safe to do in the public build.
