### ISSUE TITLE
Remote control not working with external monitor

### ISSUE THREAD

**Issue by dpauwels** [jitsi/jitsi-meet-electron#275]
Version: 2.0.2
OS: mac OS 10.13.6

Remote screen control works fine with one screen but not with an external screen connected. Other user is connected via browser.

**Comment by nemozar** [comment]
Same problem at Ubuntu 19.10. If disable second monitor connect successfull. And if after connect add second monitor in Ubuntu work fine for all monitors.

**Comment by individual-it** [comment]
duplicate of #201 ?

**Comment by seanm** [comment]
Issue https://github.com/jitsi/jitsi-meet-electron/issues/530 also mentions occurring only with multiple monitors.

**Comment by csett86** [comment]
As remote control is unfortunately no longer supported (see https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md), closing this.
