### ISSUE TITLE
Internationalization / i18n support

### ISSUE THREAD

**Issue by ctr49** [jitsi/jitsi-meet-electron#278]
It would be great if the app had support for other languages than English.
i18next looks very promising.

**Comment by pioneer** [comment]
I vote for i18n, should be relatively fast to translate once there is a facility for that.

**Comment by luixxiul** [comment]
I would expect some progress would be made after translate.jitsi.org would eventually be back.

https://github.com/jitsi/jitsi-meet/pull/6551#pullrequestreview-404638316

> We are working to put back translate.jitsi.org back in place ... Just more priority tasks moves that back in the list. Will see how it goes with the weekly plan and can merge of we cannot finish the move in the following few weeks.

**Comment by saghul** [comment]
> I would expect some progress would be made after translate.jitsi.org would eventually be back.

Not really because the few strings the app uses don't use i18n. If someone wants to get that effort started, I'll happily review, but I cannot commit to making it happen.

**Comment by luixxiul** [comment]
Yeah, please tackle stuff on priorities @saghul 👍

**Comment by chamerling** [comment]
Hello,

Is there someone working on this right now? If not I will propably open a PR.

Thx

**Comment by saghul** [comment]
Not that I know of, thanks for volunteering!

**Comment by freddytuxworth** [comment]
> Hello,
> 
> Is there someone working on this right now? If not I will propably open a PR.
> 
> Thx

@chamerling I had started a bit of work on adding i18n - have you made significant progress already?

**Comment by chamerling** [comment]
@freddytuxworth I did not have time to do anything so please do.
