### ISSUE TITLE
URL Handler Support

### ISSUE THREAD

**Issue by paynecodes** [jitsi/jitsi-meet-electron#280]
It would be great if Jitsi Meet could register itself as a handler for https://meet.jit.si and custom URLs. Anyone with electron experience know how this is done?

**Comment by paynecodes** [comment]
It appears that this would require more than I initially thought. Perhaps, if this application registered as a protocol handler, a browser extension could intercept requests for https://meet.jit.si or other urls then open the meeting in the electron app.

**Comment by kempu** [comment]
The protocol handler is already in works :)  (previous issue: #168, and pull request: #263)

**Comment by epsen** [comment]
This would be a very nice feature! I'm using jitsi-meet-electron on Windows.

**Comment by Yajo** [comment]
Maybe a simple fix would be a button in the web version of jitsi that says "open in app" and opens the jitsi-meet:// URL, which is already handled by the app AFAICS.

Also the jitsi-meet:// URL could appear in the copied message when inviting others.

**Comment by weeman1337** [comment]
> which is already handled by the app AFAICS.

That does not work for the Linux AppImage. Something is missing there..

**Comment by saghul** [comment]
The custom protocol was implemented and fixed up a few releases past.

We currently have no plans to extend the work here to things like "open in app" on the web.
