### ISSUE TITLE
[UX] jitsi-meet does not respect userʼs locale

### ISSUE THREAD

**Issue by d-g** [jitsi/jitsi-meet-electron#281]
Steps to reproduce:

	$ LANG=ru_RU.UTF-8 jitsi-meet

Actual result:

jitsi-meet presents me an English interface.  To switch language I have to open some conference first and and then follow a path of ‘More actions’ / ‘Settings’ / ‘More’ / ‘Language’ / ‘Russian’.

Expected result:

jitsi-meet presents me a Russian interface wherever itʼs already possible.

Related bugs:

- https://github.com/jitsi/jitsi-meet/issues/5865
- https://github.com/jitsi/jitsi-meet/issues/3888

**Comment by l3d00m** [comment]
No need to reopen the issue here, it's tracked in the jitsi-meet repository already. I'd close this but I don't have the permissions for that here. I reopened #3888 though as it has gone stale.

**Comment by d-g** [comment]
Thomas <notifications@github.com> wrote:
> No need to [report] the issue [again] here

Sorry, I believed, that it I had been reporting it for the first time.  In fact, I still cannot find where it was mentioned before.

> it's tracked in the jitsi-meet repository already.

Where?  And why, when itʼs obviously specific to the Electron port?

> I reopened #3888 though as it has gone stale.

Thanks.
