### ISSUE TITLE
Logitech Capture not supported

### ISSUE THREAD

**Issue by Keepps** [jitsi/jitsi-meet-electron#282]
Running Logitech Capture with Zoom or Discord allows it to be assigned as the video source.  Running it with Jitsi gives a "Failed to access your camera" warning and it doesn't appear in the camera list.

**Comment by Clodo76** [comment]
Same issue here

**Comment by saghul** [comment]
Does it work in Chrome using Jitsi?

**Comment by Keepps** [comment]
> Does it work in Chrome using Jitsi?

No, same problem.

**Comment by Erik-Per** [comment]
This is solved for me.
I can now select 'Logi Capture' as a webcam in Jitsi.

**Comment by Keepps** [comment]
Yes, me too.  At first, it didn't work, even with Jitsi 2.20.  Then I uninstalled and reinstalled it and it worked fine.

**Comment by da5nsy** [comment]
This is not working for me (Firefox and Chrome).
'Video error: Could not start video source'.

Was trying to use Logi Capture to flip (see #3774 and #7022) and also rotate the video.

**Comment by saghul** [comment]
If it doesn't work in Chrome then there is nothing we can do in the app to make it work, as it runs on the same engine. Closing.
