### ISSUE TITLE
Suggestion: Remove items from "recent list"

### ISSUE THREAD

**Issue by asmaloney** [jitsi/jitsi-meet-electron#283]
(Just saw #127 which asks for a way to clear the list - this suggestion is similar but gives more control to the user.)

It would be useful to be able to remove items from the recent list OR provide a way to save a list of favourite rooms and show them at the top (this would be preferred of course, but sounds like more work).

For those of us that only use this with a few people (not using it for hundreds of different chats), it would be nice to be able to remove rooms we won't use in the future. (e.g. I have a few "test" rooms and one-offs listed.)

It could be a close "x" in the upper-right of each room box, or a right-click context menu to remove it.

(I would tackle this myself, but I'm a C++ developer and have not been initiated into the ways of the electron 😀.)

**Comment by Echolon** [comment]
@asmaloney Isn't this a duplicate? or would make more sense to add you suggestions to the previous issue?

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/392
