### ISSUE TITLE
can't share youTube to Android Jitsi meet app

### ISSUE THREAD

**Issue by kloro2006** [jitsi/jitsi-meet-electron#284]
when I share a youTube video, I can see it on the app display, but when i go to the meeting room with my Android, the video doesn't appear on it.  I'm running the app on Debian. I'm using the Jitsi Meet app on the Android.

**Comment by saghul** [comment]
This issue belongs in jitssi-meet, not here, this is the Electron client.

At any rate, good news, work is underway to support this feature!
