### ISSUE TITLE
Support X-Frame-Options DENY or ORIGIN

### ISSUE THREAD

**Issue by isnuryusuf** [jitsi/jitsi-meet-electron#285]
Hi, 

is there any way to make jitsi-meet-electron support from X-Frame-Options Header Deny / sameorigin?
something like on this page:
https://github.com/electron/electron/pull/573 and https://github.com/electron/electron/issues/5036

really appreciate it your response

**Comment by saghul** [comment]
Looks like this should work: https://github.com/electron/electron/pull/573#issuecomment-642216738

**Comment by TheAssassin** [comment]
This issue has been open for a long time now. Some servers I want to use do set `X-Frame-Options` and thus break the electron app: it does not react any more, just shows the blue background (there is just an error message on the CLI which regular users won't see).

I'd like to see a workaround be implemented, but the one you suggested apparently strips the header completely, removing an important security feature. Perhaps it just needs to be replaced by `allow-from <local server>`?

**Comment by saghul** [comment]
The Electron app's origin would be blank I think, so I'm not sure what we should be setting there TBH. If you resolve the problem a PR would be welcome.
