### ISSUE TITLE
Always On Top Window in Tiling Window Managers

### ISSUE THREAD

**Issue by rpls** [jitsi/jitsi-meet-electron#287]
I'm using the i3 window manager and have some problems with the always on top window. The window manager does not detect it as a "floating" window, hence the window will be displayed as a tile. As the main window and the always on top window don't have any different X11 window properties, I can't configure i3 to automatically set the always on top window to floating mode, without also setting the main window into floating mode.

Many tiling window managers use [X11 window manager hints](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html) to determine whether to display a window in tiling or floating mode. Skype for Linux has a similar functionality, so I checked which X11 window properties differ from the always on top window in Jitsi. In this case, Skype hints a maximum size to the window manager, which will cause i3 to classify the window as floating. The (IMO) nicer option would be to specify a window type with the `_NET_WM_WINDOW_TYPE` property. AFAIK, electron exposes this property, so you could set it, e.g., to a a dialog or splash type.

Bonus point: in addition to properly classifying the window with a type or size hint, you could also make the window "sticky", which would cause it to be shown on all virtual desktops, but that's not that important.

**Comment by rpls** [comment]
I guess the easiest fix would be to set the `maxWidth`/`maxHeight` options for the `BrowserWindow` object of the Always on Top Window to the same value as the `minWidth`/`minHeight`.

**Comment by saghul** [comment]
I'm not sure why, but we seem to want it to be resizeable. If there is any extra property we can seet on it, feel free to send a PR. This is the relevant file: https://github.com/jitsi/jitsi-meet-electron-utils/blob/master/alwaysontop/main.js
