### ISSUE TITLE
Application translation

### ISSUE THREAD

**Issue by susobaco** [jitsi/jitsi-meet-electron#288]
Hi, I'd like to translate the application into Spanish. Which files need translation?
Salud!

**Comment by KovalevArtem** [comment]
https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by KovalevArtem** [comment]
#https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by KovalevArtem** [comment]
Duplicate of #jitsi/jitsi-meet#5056

**Comment by KovalevArtem** [comment]
Duplicate of #https://github.com/jitsi/jitsi-meet/issues/5056

**Comment by susobaco** [comment]
thanks

**Comment by KovalevArtem** [comment]
@saghul But the application itself also has a minimal interface, which would be nice to translate!
![image](https://user-images.githubusercontent.com/36500228/79997923-c01efe80-84c2-11ea-8934-4c34bb50c55e.png)

**Comment by susobaco** [comment]
I was referring to this interface, the jitsi-meet-electron

**Comment by susobaco** [comment]
Sorry, but I can't find the project to translate

**Comment by ctr49** [comment]
The app does not use internationalization yet, so there is no place to translate things unfortunately. See #278

**Comment by susobaco** [comment]
But, you're scheduled to have it, right? I'm leaving the issue open and waiting.

**Comment by freddytuxworth** [comment]
@susobaco Internationalisation is now added so you could make a PR to add Spanish. See [this PR](https://github.com/jitsi/jitsi-meet-electron/pull/399/files) for an example/template.
