### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by ItchyBugReporter** [jitsi/jitsi-meet-electron#292]
![error](https://user-images.githubusercontent.com/20482407/80041699-1728d180-84cb-11ea-9151-da3e8643a0bd.png)

When trying to launch version 2.0.2 on Debian Stretch, I see an error message regarding JavaScript. Since I cannot select the text to copy it, I have posted a screenshot instead.

**Comment by saghul** [comment]
Please test it again with the latest (2.6.0) release.
