### ISSUE TITLE
config storage

### ISSUE THREAD

**Issue by Triskele69** [jitsi/jitsi-meet-electron#294]
Hello, where are config stored? Username, e-mail and Server URL.

And is it possible to install application with preconfigured server url, maybe there are any options in installer?

**Comment by saghul** [comment]
They are stordd in the appData directory: https://www.electronjs.org/docs/api/app#appgetpathname



> And is it possible to install application with preconfigured server url, maybe there are any options in installer?

Not really, sorry.
