### ISSUE TITLE
Config flag to disable auto-update

### ISSUE THREAD

**Issue by knobhead** [jitsi/jitsi-meet-electron#295]
Hi, 

as #243 has been closed but the question remained open:

Could you add support a configuration option to disable automatic updating?
This does not have to be a switch in the settings dialog, a (documented) flag in the `config.json` would suffice.

Use Case: We plan to roll-out JMD and updates to our users centrally via software deployment. Hence we'd prefer the clients not auto-updating themselves and requiring user interaction. 

Thanks!

**Comment by C3dom** [comment]
main.js comment line 113:

`autoUpdater.checkForUpdatesAndNotify();`

**Comment by saghul** [comment]
I assume you are forming this project and changing at least the default server, right? If so you could make the change @C3dom suggests. Or do you have a different use case in mind?

I don’t like the idea of letting users choose here, because they will forget and then be subject to security vulnerabilities, should any arise.

**Comment by knobhead** [comment]
Hi! Thanks for your replies!

> main.js comment line 113:
> `autoUpdater.checkForUpdatesAndNotify();`

But that would require us to build Jitsi Meet Electron by ourselves, right? Never tried that, might be too much for me. 🤔 

> I assume you are forming this project and changing at least the default server, right? If so you could make the change @C3dom suggests. Or do you have a different use case in mind?

What exactly do you mean by 'forming'? So far we're rolling out the Windows x64 Binaries and passing along a customized `config.json` including our own server url and the users Windows `%USERNAME%`. But as for customizing/'forming': that's about it.

> I don’t like the idea of letting users choose here, because they will forget and then be subject to security vulnerabilities, should any arise.

👍

**Comment by saghul** [comment]
Sorry, I meant forking (damn autocorrect).

Looks like you are already doing that aren’t you?

**Comment by cvandesande** [comment]
> I don’t like the idea of letting users choose here, because they will forget and then be subject to security vulnerabilities, should any arise.

With all due respect, it is the spirit of free software to allow users to choose unsafe defaults.  The security vulnerability could be coming from GitHub, malware infected packaged downloaded via auto-update.  In such a case, you could inform users via Twitter or something to disable auto-updates. The ultimate choice is yours of course, but worth looking at this from the users' point of view.

That, and remote control was just "quietly" removed from 2.3.0. So without notice a feature was removed. No doubt there was a good reason, but that also means I need to find a new remote support solution from some other less preferred solution

**Comment by saghul** [comment]
You can re-enable the feature if you build it yourself.

This was not done without much regret mind you, we’ll post about the reasoning shortly.

**Comment by krikk** [comment]
would also like to see an opion in config.json to configure auto-updating, and even nice it would be if we could enable/disable "remote control" via this file...

**Comment by saghul** [comment]
I'll be honest the auto-update option is not something I plan to work on, so unless someone contributes it as a PR it's unlikely to happen.

Regarding remote-control, it was disabled for security reasons: https://github.com/jitsi/jitsi-meet-electron/security/advisories/GHSA-x4h8-fhrp-pm3p There will be no option to enable it, you can just comment out the code and build it at your own risk. Once the feature has been reworked we shall re-enable it. No ETA for that though, sorry.

**Comment by saghul** [comment]
Back on topic. If someone wants to add a command line / config option to disable auto updates, a PR is welcome, as longs as the current behavior is the default one.

**Comment by arlt** [comment]
@saghul We are interested in this and possibly other improvements to Jitsi Meet Eelctron. We would therefore be willing to make a donation. Is there interest on your side?

**Comment by saghul** [comment]
We don't take donations, but if you'd like to submit a pull request, you're more than welcome to do so!
