### ISSUE TITLE
Raspberry pi 4 support ?

### ISSUE THREAD

**Issue by nyok92** [jitsi/jitsi-meet-electron#297]
Hi, is there a way to make the electron app working on a raspberry pi 4 ? maybe on raspbian ?

**Comment by branigan** [comment]
You could try build appimage for armv7l cpu.
More info:
https://stackoverflow.com/questions/57813389/how-do-i-build-and-install-an-electron-app-for-raspbian-using-appimage

**Comment by nyok92** [comment]
thanks, i will try it !

**Comment by frizman21** [comment]
@nyok92 , any luck?

**Comment by nyok92** [comment]
Didn t try it yet 😅

**Comment by kiai72** [comment]
i just noticed this. don't even know about electron. before i dig deeper into this: did someone test it in the meanwhile ?
