### ISSUE TITLE
Error While Building the Application on Windows 10

### ISSUE THREAD

**Issue by ajaysingh452** [jitsi/jitsi-meet-electron#298]
Hi Folks,
Greetings, I am getting below error while trying to build the JItsi meet Electron with npm build.
![picturemessage_jiydsmqb fpx](https://user-images.githubusercontent.com/8072971/80175023-185a1b80-85fd-11ea-8ec0-56487f9edad6.png)

Early support will be appreciated. 

Thank you in Advance.

**Comment by dom-k** [comment]
Have you installed all required dependencies (`npm install`) before building the app?

**Comment by akalana** [comment]
Before doing ```npm install``` Please try this ```npm install --global --production windows-build-tools```
