### ISSUE TITLE
Camera access issue

### ISSUE THREAD

**Issue by Triskele69** [jitsi/jitsi-meet-electron#299]
I have an error Failed to access your camera for an unknown reason. Sometimes error about no permissions.
Checked in ProcessManager that no other programs are using my camera.
Sharing desktop is working.
And everything is working in browser.
Connection to server is https with valid cert.

Cameras not working on every computer. Win7 and Win10.

What could it be?

**Comment by iarani** [comment]
Facing the same issue on macOS Mojave version 10.14.6. Can access it during development but not after creating a distribution file. Tried manually editing info.plist to update <key>Privacy - Camera Usage Description</key> to a more "proper" description. Camera turns on for a second and then shows the error "Your camera is in use by another application"

**Comment by iarani** [comment]
Resolved it by adding askForMediaAccess("camera") explicitly on Mac 

`const { systemPreferences } = require('electron');`
`if(systemPreferences.askForMediaAccess("camera")) { createJitsiMeetWindow(); } `

**Comment by awlx** [comment]
Where did you patch this @iarani and does it also work for other OS?

**Comment by saghul** [comment]
Any chance you were using an old version of the code?

**Comment by awlx** [comment]
The issue seems to persists with the new version :/.

**Comment by saghul** [comment]
I’m running Mojave and haven’t run into this whole testing the release. Any specific steps I should follow to try to repro?

**Comment by awlx** [comment]
I am still trying to repro this in a good way ... It seems to only fail for some users which makes it hard to track down -.-.

**Comment by Echolon** [comment]
Hi,
If you have an issue with your camera, please see the pinned issue #5425, which has more information on how to help the Jitsi team to resolve the issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by saghul** [comment]
We have made many changes to handle these in Jitsi Meet. Please test the latest version, using meet.jit.si as the server.
