### ISSUE TITLE
Sharing entire screen also shares the Jitsi Meet window

### ISSUE THREAD

**Issue by wigging** [jitsi/jitsi-meet-electron#302]
I'm using the Jitsi Meet Electron app on macOS 10.15.4. When I share my entire screen, the app also shares the Jitsi Meet window which causes an "inception" effect (see image below). To fix this, I have to minimize the Jitsi Meet window to properly share my entire screen. Can you update the Electron app to not share the Jitsi Meet window when sharing the full screen?

<img width="1536" alt="screenshot" src="https://user-images.githubusercontent.com/6828967/80280311-4741c180-86d1-11ea-8b6d-dcb8ff343ada.png">

**Comment by saghul** [comment]
That’s not possible. When you share the screen you literally share everything that’s on the screen. This is the API provided by the browser / Electron.

**Comment by wigging** [comment]
@saghul What browser/Electron API are you referring to?
