### ISSUE TITLE
No way to go back to main screen from ad

### ISSUE THREAD

**Issue by asmaloney** [jitsi/jitsi-meet-electron#304]
After a call I received an ad for "8x8 Video Meetings Pro" covering the main window.

There doesn't seem to be a way to go back to the main screen other than quitting and starting the app again.

**Comment by saghul** [comment]
Are you using your own server or the default? Can you reproduce it reliably?

**Comment by asmaloney** [comment]
(I apologize - that's a terrible bug report. I didn't even include the version. It would have been the most recent version at the time -  2.0.2.)

I am using the default server.

I'm not sure what triggered the ad to begin with - I don't normally see that. Do you what triggers it?

**Comment by saghul** [comment]
This has been fixed since the report.
