### ISSUE TITLE
app.allowRendererProcessReuse is deprecated in Electron 9 Trisquel_etiona/Ubuntu_18.04

### ISSUE THREAD

**Issue by susobaco** [jitsi/jitsi-meet-electron#305]
Hi, every time I run the app, I get this error. Is it a problem with the program or the distribution? It also refers to this issue.
Sorry, but I don't have enough knowledge.

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false". It will change to be "true" in Electron 9. For more information please check https://github.com/electron/electron/issues/18397

electron/electron#18397

**Comment by saghul** [comment]
I explicitly set it to false now, because robotjs needs to be updated to be context aware.
