### ISSUE TITLE
Shared document (Etherpad) closes automatically.

### ISSUE THREAD

**Issue by stonerl** [jitsi/jitsi-meet-electron#306]
## Description
When one opens the shared document (Etherpad) it gets closed as soon as another person speaks and that person's video gets focused. The only way to circumvent this at the moment, is to focus on the own video before opening etherpad.

## Current behavior
Dominant speaker gets focus and the shared document is closed.

## Expected Behavior
Shared document stays open even if other people speak.

## Possible Solution
Disable dominant speaker gets focus while shared document is open. Enable it when the shared document gets closed. 

## Steps to reproduce
- Open a meeting with 3 or more people. 
- Open shared document.
- Let the dominant speaker change
- Shared document gets closed.

This issue is already resolved in https://github.com/jitsi/jitsi-meet/issues/5785. But still present here.

**Comment by saghul** [comment]
Closing since this is a Jitsi Meet issue, already being tracked in https://github.com/jitsi/jitsi-meet/issues/5785
