### ISSUE TITLE
I'm unable to join any room? i tried to connect to my own server but same issue

### ISSUE THREAD

**Issue by noFAYZ** [jitsi/jitsi-meet-electron#307]
![Capture](https://user-images.githubusercontent.com/57537470/80311755-ef06de80-87fa-11ea-8c7f-a83a7d065828.PNG)

**Comment by mxvin** [comment]
Experiencing same issue.

**Comment by noFAYZ** [comment]
My firewall is turned off. I can't able to join or make a room.

**Comment by noFAYZ** [comment]
Tried v2.0.1 also Windows 10 x64 same problem

**Comment by rboccadoro** [comment]
Same issue here. No firewall active on my PC. Can't join any room

**Comment by noFAYZ** [comment]
Any help?

**Comment by szimszon** [comment]
Same here... ;(

**Comment by noFAYZ** [comment]
Also tried on my own build. Anyone found any solution?

![Cdsfapture](https://user-images.githubusercontent.com/57537470/81505614-028d6b80-930a-11ea-954e-962af86df9d1.PNG)

**Comment by saghul** [comment]
Wait, I wonder if... have you tried just with the room name, instead of the full URL? The latter should also work but maybe we broke it inadvertently...

**Comment by cduduc** [comment]
Getting the same result. Cannot join any rooms with my own Jitsi meet server. Trying from Ubuntu 18.04

**Comment by Sunny090628** [comment]
Tried with only name and works.
Win 10 x64

**Comment by fangwei57** [comment]
Same problem on  windows10 and  macos

**Comment by fangwei57** [comment]
When i try entry any room ,the request canceled immediately.
![image](https://user-images.githubusercontent.com/20739640/89977831-b18d6a80-dc9e-11ea-82d9-17100392b18a.png)

**Comment by pgenderson** [comment]
@bloom-repo doesn't a Jitsi server only work if it's using SSL/TLS?

**Comment by saghul** [comment]
The specified server must have a valid TLS certificate. That said, I loosened the checks in the latest version (2.4) so please try that out.
