### ISSUE TITLE
Add an exit conference button

### ISSUE THREAD

**Issue by magicvince** [jitsi/jitsi-meet-electron#312]
Is there a way to quit a conference in jitsi-meet-electron without closing the app? a button to exit could be an easy way.
Thanks

**Comment by xoan** [comment]
Just click on «Hang Up button».

![image](https://user-images.githubusercontent.com/288246/80713777-8746e100-8ae3-11ea-8679-8c81c03534df.png)

**Comment by magicvince** [comment]
Thanks, it was logic!
