### ISSUE TITLE
Deleting or bookmarking old session

### ISSUE THREAD

**Issue by magicvince** [jitsi/jitsi-meet-electron#313]
When we launch jitsi-meet-electron, we can see our last "conference room". 
Is there a way to remove some or all of them?  Is there a way to create favorite ones?

**Comment by UweKeim** [comment]
Yes, this would be helpful for me, too.

The iPhone app allows the removal of old sessions.

**Comment by tiiiecherle** [comment]
Thanks for the suggestion, would be really helpful for us, too.

**Comment by saghul** [comment]
A PR would be welcome, but we have no time to invest in this right now, sorry.
