### ISSUE TITLE
Take screenshot and print

### ISSUE THREAD

**Issue by didlawowo** [jitsi/jitsi-meet-electron#316]
Hi, 
i would like if it was complicated to have a little option to take screenshot during video conversation and print it to default printer ?
cause i have found serious way to does this, but there is always icon on picture and it's necessary to crop / clean before print, and it's not easy for someone who don't use computer every like my grandma :)

the idea is to permit to my family to take screenshot during conversation and print for the old papy :)

i'll very happy to help this project if needed.

**Comment by saghul** [comment]
Sorry, no , we don’t have this feature. As for implementing it, I don’t see it happening, I’ll be honest.

Feel free to discuss it in our community forum, since this would need to be implemented on jitsi meet itself I think.
