### ISSUE TITLE
SHA512 hash for Linux (AppImage) version 2.0.2 not match what dictated in "latest-linux.yml" file !

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#318]
Hi dears.
I downloaded AppImage version 2.0.2 & used GtkHash (version 1.2 from my official Fedora repositories) for hashing the file. It gave me the following output:

SHA512:
4b4be2b6e04e01d39db9391835e587b0477bd8a127681e9fae217a991ce1f0502ee56421a70378b331a786a93d16156e9d3e65644e832002c7bd14dfc008124d

But what dictated in "latest-linux.yml" file is other value ! It is:
sha512: S0vituBOAdOduTkYNeWHsEd72KEnaB6friF6mRzh8FAu5WQhpwN4szGnhqk9FhVunT5lZE6DIALHvRTfwAgSTQ==

Kindly, your look for this .....

**Comment by saghul** [comment]
Apparently that's not the hash sum of the fille per se, but that, taken as a binary and base64 encoded. I have no idea why. Here is how you can verify it: `sha512sum jitsi-meet-x86_64.AppImage | awk '{ print $1 }' | xxd -r -p | base64`

Found it here: https://discourse.joplinapp.org/t/checksum-failure/3014/5

**Comment by Nokia808** [comment]
@saghul 
Thank you very much ! I will ask GtkHash to add feature to support this (base64).

Also, I searched further & I found this site:
http://tomeko.net/online_tools/hex_to_base64.php

But as you see, it is http:// (not https://) & being Java !! You can not trust it unless it yield you positive compatible result.

Thank you again for command line you gave me !

Best.

By the way, I opened issue about flatpak in "Jitsi Meet" repository:
https://github.com/jitsi/jitsi-meet/issues/6503
Is it correct to post it in "Jitsi Meet" repository as I did already, or it should be posted here in this repository "jitsi-meet-electron" ?

**Comment by saghul** [comment]
I think that belongs here

**Comment by Nokia808** [comment]
@saghul 
So, close it there & open it here ?

**Comment by Nokia808** [comment]
@saghul 
Last questions: I'm currently installed your AppImage file:
1) does it will show me message when new version releases & I can update to it automatically after that? I did not see "Update" or "Search for new version" option .....
2) does the AppImage also using WebRTC as web version ?
3) which is more secure: web application or AppImage version ? In my mind the AppImage version, is this correct or they are equally secure ?

No further questions.

Thank you.
