### ISSUE TITLE
[Questions] About AppImage package of Jitsi.

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#319]
Hi.

I'm currently installed your AppImage file & have the following questions about this package:

1) does it will show me message when new version releases & I can update to it automatically after that? I did not see "Update" or "Search for new version" option .....
2) does the AppImage also using WebRTC as web version ?
3) does AppImage version, more secure than web version, or they are equally secure ?

Thank you.

**Comment by saghul** [comment]
1. No, it auto-updates in the background.

2. Yes, it’s built with Electron, which uses the Chromium engine.

3. They should be equally secure.

**Comment by Nokia808** [comment]
@saghul 
Many thanks! Every thing now clear. Jitsi not suitable with VPN because it is always use WebRTC which undermine VPN by yielding real IP of user .....

The AppImage of Jitsi Meet is the best AppImage that I see till now ! It update itself with itself & not need other tool to achieve it's update & user need just to download & verify it for only one time no more ..... !
