### ISSUE TITLE
[Packaging] Make "Jitsi Meet Electron" available as official flatpak package on FlatHub.

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#320]
Hellow.

I would like to suggest on you to make "Jitsi Meet" officially available by you as official flatpak package on FlatHub.

Flatpak is a universal Linux package that compatible with almost all Linux distros ...... By making Jitsi Meet available as flatpak on FlatHub, it will be available for almost all Linux distros & users.

Flatpak is secure package system with default sandbox. It offer users automatic updates, & being independent from system version.

FlatHub home page is:
https://www.flathub.org/home
FlatHub repositories are here:
https://github.com/flathub
To post your flatpak on FlatHub, you have to make PR on:
https://github.com/flathub/flathub/pulls

Flatpak documentation here:
https://docs.flatpak.org/en/latest/

I forgot to say that flatpak is easier to be packaged than AppImage & flatpaks on FlatHub all are signed & the administrations of FlatHub prefer for open source packages to be deterministic (fully reproducible).

Unfortunately, you have no enough resource to achieve this at current time. So, please keep this issue open in the hope that you will get enough resources in future to achieve it .....

Best.

**Comment by saghul** [comment]
Sorry, we can't sspend more resources on making yet anothher package.

**Comment by Nokia808** [comment]
@saghul 
Never mind. It is not a big problem as long as built-in update feature of your AppImage is working regularly. This way, user need for only one time verification of heir/his download & the remaining will be automatic .....
I had very bad experience with built-in automatic update of Rambox. But, I feel your AppImage is perfectly implement this feature .....

**Comment by digitalethics** [comment]
@Nokia808 Since when is there an update feature in AppImages? Can you point me to this in their repo?

**Comment by digitalethics** [comment]
> Sorry, we can't sspend more resources on making yet anothher package.

Would you mind re-opening this issue and add a "need help" label so someone can pick this up? I think this is also a matter of outreach and it should be fairly trivial to package this for someone experienced.
