### ISSUE TITLE
I can not copy/past to chat !

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#325]
Hi dears. I noticed that I can not copy/past to chat in "jitsi-meet-electron" !

Please, kindly, investigate this issue.

**Comment by beatstick** [comment]
Yeah, I think I ran into this bug on Windows 7. It seems sometimes copy and paste stops working on the whole operating system some time after the electron client was started. It is highly annoying.

**Comment by saghul** [comment]
If it's an Electron problem, then there is not much we can do about it, other than keeping up with updates.
