### ISSUE TITLE
room url is not trimmed in the input form

### ISSUE THREAD

**Issue by aerogus** [jitsi/jitsi-meet-electron#326]
Tested on app electron, v 2.0.2, MacOS

I copy/paste a room url from somewhere and I notice that the url of the input is not trimmed.

and https://meet.example.com/roomName is different from https://meet.example.com/roomName%20 !

Could you trim the input form ?

**Comment by saghul** [comment]
Are you up for sending a PR?

**Comment by aerogus** [comment]
nope but I could try :)

**Comment by aerogus** [comment]
I can't reproduce the bug with the master branch. I think it has been resolved by https://github.com/jitsi/jitsi-meet-electron/commit/cf7f2dabfb0762f5294c4cadb40c329c70987ff2 ?

**Comment by saghul** [comment]
Ah, I think yeah, this line probably removes the trailing spaces: https://github.com/jitsi/jitsi-meet-electron/commit/cf7f2dabfb0762f5294c4cadb40c329c70987ff2#diff-935b7681656235270d8f6e4015ff3d2eR244

**Comment by aerogus** [comment]
exact ! I let you close this issue, it will be fixed in the next release. Thx for checking
