### ISSUE TITLE
Offer diceware room names

### ISSUE THREAD

**Issue by hoxia** [jitsi/jitsi-meet-electron#329]
Unlike the other Jitsi Meet frontends, the desktop app does not offer suggestions for room names. Diceware is one of the best way of generating a conveyable secret (aside from its memorability!) and is very useful to offer for default room names.

**Comment by saghul** [comment]
We have this functionality in an auxiliary library (js-utils) it should be was to add it here too now.

What is Diceware?

**Comment by hoxia** [comment]
https://en.wikipedia.org/wiki/Diceware
In the most generic sense, it just refers to generating a memorable passphrase via randomly selecting multiple words from a wordlist. Or here, a hard-to-guess but easy-to-read room name!

(Your implementation is pretty atypical for these. Instead of one wordlist, yours is separated into syntactic categories so that the phrase it generates more closely resembles speech. It probably has less entropy as a result, though I would guess probably still plenty enough for ephemeral rooms. ...While I'm offtopic, you might indeed want to offer diceware for room passwords too.)

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/342

**Comment by bgrozev** [comment]
> (Your implementation is pretty atypical for these. Instead of one wordlist, yours is separated into syntactic categories so that the phrase it generates more closely resembles speech. It probably has less entropy as a result, though I would guess probably still plenty enough for ephemeral rooms.

Yep, we played a lot with this to make it more readable. It has ~40 bitts of entropy, which we judge enough for room names. :)
