### ISSUE TITLE
High CPU usage on Linux

### ISSUE THREAD

**Issue by ekianjo** [jitsi/jitsi-meet-electron#330]
Hi, just wondering if it's normal when using the electron client that all CPUs are maxed out when handling a video conversation with 3 other parties? is there a way to enable gpu decoding in order to save CPU usage?

**Comment by Theseday** [comment]
Its not only on Linux, my macbook also have unnormal high cpu usage and goes up to 90 - 100 °C. In normal use (3 - 6 person, only audio) the jitsi meet renderer take 30 % cpu usage, when only one person shared his screen it goes up to 60% and when i share my screen the cpu ist maxed. 

Sorry for my english

**Comment by maik-s** [comment]
Can confirm it on windows, too: Screen sharing really consumes high cpu usage and hence heat it up

**Comment by Echolon** [comment]
Hi @ekianjo,
thank you for your report. However, I think this is a duplicate and I will close this with reference to:
**High CPU load (Linux)** #259 

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
