### ISSUE TITLE
https://desktop.jitsi.org/Main/Download links to outdated clients

### ISSUE THREAD

**Issue by mhoye** [jitsi/jitsi-meet-electron#331]
After going to  to https://desktop.jitsi.org/Main/Download and pulling the Windows clients, it looks like the client linked there is out of date. (I certainly haven't been asked for my AIM or ICQ accounts in quite some time.)

The Windows download links should probably point to the Electron client instead, which works a treat: https://github.com/jitsi/jitsi-meet-electron

Thank you.

**Comment by saghul** [comment]
That's a different project altogether, I'll see so the website gets updated.

**Comment by Echolon** [comment]
@saghul is this an invalid issue?

**Comment by hutson** [comment]
I went through this as well, landing on the Download page, clicking on _Latest Stable Build_, only to see a version released 3 years ago, which does not seem quite right, before eventually discovering this repository and the Jitsi Electron application.

**Comment by saghul** [comment]
We have added a banner indicating that the web page is deprecated and just contains information about the legacy desktop client.
