### ISSUE TITLE
Calender

### ISSUE THREAD

**Issue by Pleximar** [jitsi/jitsi-meet-electron#332]
Is there a way to see and configure a calender in the desktop app? 
And by the way, is there a way to bind a caldav calendar?

**Comment by Pleximar** [comment]
I have found a way to configure the calendar but it isnt displayed on the startpage. Theres also no way to configure it from the startmenu

**Comment by saghul** [comment]
It'ss currently not possible.

**Comment by Pleximar** [comment]
Mhhh...  And what is with the utils? Is there a way to display the next conversation times?

**Comment by saghul** [comment]
What utils? No, there iss no way to dissplay the next converssation time.

**Comment by Pleximar** [comment]
The jisi-meet-electron-utils repo

**Comment by saghul** [comment]
I don't understand what you are asking.

**Comment by Pleximar** [comment]
For what is the repository "utils". Are there any extra features? And it would be possible to program the whole thing yourself, so the calendar

**Comment by saghul** [comment]
Those are usseed to implement some extra Electron-sspecific features. The calendar is visible on the welcome page, but we don't display that in the Electron app, that's why you don't see it.

There is really nothing you can do at the moment to make it work.

**Comment by Pleximar** [comment]
Well, okay... I've been looking for a desktop app for 30 minutes and haven't found one. And one I programmed myself that just displays the website. The problem with me is that the screen sharing doesn't work and there is just a loading icon all the time. After that I found you. Also the Google and Microsoft login did not work for me.

**Comment by saghul** [comment]
I'm really confused. Your message mixes 3 different things.



> I've been looking for a desktop app for 30 minutes and haven't found one.

Well, you're posting in the bugtracker for our app, so there is that.



> And one I programmed myself that just displays the website. The problem with me is that the screen sharing doesn't work and there is just a loading icon all the time.

That's what the utils repo is for, it allows for screen-sharing for example, which doesn't work out of the box.



> Also the Google and Microsoft login did not work for me.

Where? On meet.jit.si, on your own app?

**Comment by Pleximar** [comment]
>  Also the Google and Microsoft login did not work for me.
In my app

>Well, you're posting in the bugtracker for our app, so there is that.
Before i found this app :D
