### ISSUE TITLE
[Feature request] Add option to delete program catch.

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#334]
Hi. Currently it is not possible to delete program catch unless manually by delete:
home/myusername/.config/Jitsi Meet

It will be better if you add an option to "Delete program catch" in the "setting" to achieve this.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/392

**Comment by Nokia808** [comment]
@saghul 
Hi dear. Thank you very much for your very hard efforts to make this application better & better !
But, only one thing: does removal of conference(s) is equal to removal of cache ? No, it is not equal ! In fact, it is a removal of part of cache not all cache ... !
What about other element, like custom instance setting ? I asked about an option to remove ALL directories that created by run the AppImage ... This what I meant by removal the cache.

Kindly, if you review the state of this issue ...
