### ISSUE TITLE
[Question] does view type has impact on performance with bad Internet connection ?

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#335]
Hi. I would like to ask: does the view type has impact on performance in bad Internet connection cases? If yes, then which is better in this situation: default view or tile view ? Which of them associated with better performance & less disconnectedness chance ?

Thank you.

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by Nokia808** [comment]
@Echolon 
Okay.
