### ISSUE TITLE
Is localization possible or available for Jitsi Meet Electron ?

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jitsi-meet-electron#336]
Hi, I recently found out about this desktop version of Jitsi Meet.
I can't seem to find how to change the language, is this possible ?
If not (yet), can it be localized ?

**Comment by ctr49** [comment]
It is not possible yet, the components around internationalization support are missing, see #278

**Comment by saghul** [comment]
Closing in favor of #278.
