### ISSUE TITLE
Enable the Wiki

### ISSUE THREAD

**Issue by cmorty** [jitsi/jitsi-meet-electron#338]
Enabling the wiki would allow to, for example, add some notes about installing jitisi-meet-electron in an enterprise environment. I spent quite some time figuring out how to do so for windows. Might also allow to collect data on using it in a linux environment.

**Comment by saghul** [comment]
We haven’t announced it just yet, but all documentation is being moved here: https://github.com/jitsi/handbook

Feel free to make PRs there.
