### ISSUE TITLE
Default server URL not changing

### ISSUE THREAD

**Issue by noFAYZ** [jitsi/jitsi-meet-electron#339]
I've changed the default server url in the default settings but whenever i start a room its using meet.jit.si as server. How can i change this?

![sasas](https://user-images.githubusercontent.com/57537470/82150163-78955380-9871-11ea-8cbf-576515ba6968.PNG)

**Comment by coach1988** [comment]
Your screenshot shows a wrong URL; You are pointing it to the official server (https://meet.jit.si/), but with some more added to it (/sadas), which is very likely not a jitsi server instance.

1. Replace "https://meet.jit.si/" with "https://your.server.fqdn/" (trailing slash is required i think)
2. Leave out the rest (/sadas), unless you have some redirection in place (IDK if that would work at all, maybe someone else can answer that); This part is the meeting ID and has nothing to do with the actual server URL.

**Comment by noFAYZ** [comment]
@coach1988  It's fixed now. Just rebuild the app and it changed the default server url.
