### ISSUE TITLE
Electron app Referring to Server homepage after call ends

### ISSUE THREAD

**Issue by noFAYZ** [jitsi/jitsi-meet-electron#344]
After successful call ends the page is referring to the server's homepage.

![Captsadsdure](https://user-images.githubusercontent.com/57537470/82461675-22741a80-9ad4-11ea-856d-ffe5877dfbc7.PNG)

**Comment by saghul** [comment]
Are you using your own server?

**Comment by noFAYZ** [comment]
Yes, i'm using my own

**Comment by saghul** [comment]
Can you share your config.js? Or better yet, your server URL so we can test it.

**Comment by noFAYZ** [comment]
webrtc.dotfines.com/config.js

**Comment by noFAYZ** [comment]
Any help?

**Comment by saghul** [comment]
Sorry I haven’t gotten a chance to look into it yet.

**Comment by saghul** [comment]
I believe this was fixed with the latest stable release. Tentatively closing.
