### ISSUE TITLE
Unable to scroll during remote control

### ISSUE THREAD

**Issue by mallt** [jitsi/jitsi-meet-electron#345]
Srolling is not working during remote control with version 2.0.2. Is there a specific setting to enable scrolling during remote control? Thanks!

**Comment by Echolon** [comment]
@mallt what is you operating system?

**Comment by mallt** [comment]
@Echolon I'm running linux on the controlling pc, and windows on the controlled pc. Thanks!

**Comment by Echolon** [comment]
Thank you!

**Comment by amir-mine-data** [comment]
Hi, In the latest release (4.2.1), remote desktop is disabled. 
Any plans to re-enable it?
Is there anyway to enable it manually?
Thanks!

**Comment by jonnytest1** [comment]
https://github.com/jitsi/jitsi-meet-electron/issues/483 this thread seems more active

**Comment by csett86** [comment]
As remote control is unfortunately no longer supported (see https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md), closing this.
