### ISSUE TITLE
Video off

### ISSUE THREAD

**Issue by SlalomJohn** [jitsi/jitsi-meet-electron#348]
Need the option to "Turn off the video" to the user by the moderator.

**Comment by Nokia808** [comment]
@SlalomJohn 
But all participants in video conference over https://meet.jit.si are moderator by default ! So, how this could be done ? I see this feature is suitable only on certain servers which configured to make creator of room as the only moderator .....

**Comment by SlalomJohn** [comment]
Yes. I have personal server with auth for moderator.

**Comment by saghul** [comment]
Please post on jitsi-meet, this repository is just the Electron wrapper.
