### ISSUE TITLE
Improve design of disabling E2EE feature

### ISSUE THREAD

**Issue by Nokia808** [jitsi/jitsi-meet-electron#349]
Hi. I tested the new feature of e2ee & it working fine. Thank you for adding it.
However, it need to tweak in regard to how disable it after it was enabled to be in same design of "Blur my background" option as following:

Currently, if user enable "Blur my background" option, then "Blur my background" in menu will changed into "Disable blur my background" so that user need just to click "Disable blur my background" to disable it.
But, currently, if user click "End-to-end encryption" in menu & enter password then click "okay" then "End-to-end encryption" in the menu will remain "End-to-end encryption" & user need to click it then delete password then click "okay" so as to disable e2ee. This not brilliant. It should be so that when user click "End-to-end encryption" then set password & click "okay", the "End-to-end encryption" in menu should changed into "Disable end-to-end encryption" so that user need just to click "Disable end-to-end encryption" to disable it by single click .....

**Comment by saghul** [comment]
Thanks for the feedback!

This is our first implementation (hence the BETA tag) and it will be completely overhauled. We are already working on the firt iteration.

I'm going to close this since we are already working on the next iteration.

**Comment by Nokia808** [comment]
@saghul 
This is very good. 
I would bring your attention to other point: as long as using e2ee make server dependent options (like recording, live streaming, share a YouTube video ...) impossible, then these options should become inactive within menu while e2ee is enabled & return active when user stop e2ee

A question: is chat service covered by e2ee new feature like audio & video or not ?
