### ISSUE TITLE
[PROPOSAL] Auto-updates integration

### ISSUE THREAD

**Issue by UtkarshGupta-CS** [jitsi/jitsi-meet-electron#35]
Following are steps to build an auto-updates feature:

#### Deploying an Update Server
As mentioned in the official documentation of electron (https://electronjs.org/docs/tutorial/updates),  to update the application using electron auto-updater module we need to deploy a server that the autoUpdater module will download new updates from. 
I suggest [Hazel](https://github.com/zeit/hazel)  for deploying the update server as it is widely used and can be deployed for free on Now. It pulls from GitHub Releases and leverages the power of GitHub's CDN.

```
const hazel = require('hazel-server')

http.createServer((req, res) => {
  hazel(req, res)
})
```

#### Auto Update Feature for Mac and Windows application

This feature will be implemented in [jitsi-meet-electron-utils](https://github.com/jitsi/jitsi-meet-electron-utils) and then integrated with [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron.) 

Currently, only macOS and Windows are supported. There is no built-in support for auto-updater on Linux, so it is recommended to use the distribution's package manager to update your app.

Auto-updating for OSX is handled by Squirrel.Mac, which is built-in Electron. The way Squirrel.Mac works are by checking a given API endpoint to see if there is a new version of the app. If there is no new version, the endpoint should return HTTP 204. If there is a new version, however, it will expect a HTTP 200 JSON-formatted response, containing an URL to a .zip file:

```
{
  "url": "http://example.com/path/to/app.zip"
}
```

Squirrel will make an application/zip request using that URL, download the file, and fire up the final event to let you know that the update is ready to install.

On Windows, you have to install your app into a user's machine before you can use the autoUpdater, so it is recommended that you use the electron-winstaller, electron-forge or the grunt-electron-installer package to generate a Windows installer.

`const { app, autoUpdater, dialog } = require('electron')`

Next, construct the URL of the update server and tell autoUpdater about it:

```
const server = 'https://deployment-url.com'
const feed = `${server}/update/${process.platform}/${app.getVersion()}`
  
autoUpdater.setFeedURL(feed)
```

As the final step, check for updates. The example below will check every minute:

```
setInterval(() => {
    autoUpdater.checkForUpdates()
  }, 60000)
```
Once your application is packaged, it will receive an update for each new GitHub Release that you publish.

####  Applying Updates
Now that you've configured the basic update mechanism for your application, you need to ensure that the user will get notified when there's an update. This can be achieved using the autoUpdater API events:

```
autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
    const dialogOpts = {
      type: 'info',
      buttons: ['Restart', 'Later'],
      title: 'Application Update',
      message: process.platform === 'darwin' ? releaseNotes : releaseName,
      detail: 'A new version has been downloaded. Restart the application to apply the updates.'
    }
  
    dialog.showMessageBox(dialogOpts, (response) => {
      if (response === 0) autoUpdater.quitAndInstall()
    })
  })
```

Also make sure that errors are being handled. Here's an example for logging them to stderr:

```
autoUpdater.on('error', message => {
    console.error('There was a problem updating the application')
    console.error(message)
  })
```

### Note: If possible, I like to work on this.

**Comment by saghul** [comment]
Hi @UtkarshGupta-CS! This is a great proposal, thanks for making it!

We do want to have this in the project. However, we currently have @AkshitKrNagpal as a GSoC student making several improvements to the project and this may fail under his scope if time allows.

So let's do this: I'll discuss it with @AkshitKrNagpal and once we have a first jitsi-meet-electron release we'll revisit this and let you know.

Thanks again for the detailed proposal, I'm glad you did it before starting the implementation, so we just avoided a potential conflict!

**Comment by saghul** [comment]
This is done now!
