### ISSUE TITLE
No more meeting connections at all after update to version 2.1.0 on macOS

### ISSUE THREAD

**Issue by tiiiecherle** [jitsi/jitsi-meet-electron#350]
Hey, 

thanks for the update which solves having the window shortcuts back on macOS. But unfortunately after allowing camera and microphone access I can not connect to any meeting on macOS 10.15.4. There is no message or error displayed, just the jitsi meet screen with no camera picture and no sound unable to join meetings.

Downgrading to version 2.0.2 solves it. Thanks for looking into it in advance.

**Comment by saghul** [comment]
Are you using your own server or meet.jit.si?

**Comment by tiiiecherle** [comment]
Hey, thanks for the fast feedback. I'm using my own server and I remembered that there were a few Content-Security-Policys that were causing trouble when using the electron app.

I just found out trying that when completely deleting
```
frame-ancestors
default-src
script-src
```
then the new app starts working again. But I guess that is not a very safe setup. The current one working is this one:

```
add_header Content-Security-Policy "img-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none';";

add_header Feature-Policy "geolocation 'none'; camera 'self'; microphone 'self'; autoplay 'none'; accelerometer 'none'; autoplay 'none'; payment 'none';";
```

I tried a few combinations, even
`default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'`
did not work.

I don't know about all Content-Security-Policys and their values that have to be added to work without removing all of the above.

It would be nice if you could help out finding the safest working setup for this and afterwards the documentation could be updated to help others out. 

Thanks a lot

**Comment by saghul** [comment]
I’ll admit I don’t know the answer to that myself.

Happy to update the docs once we know what a reasonable value for those headers is.

**Comment by tiiiecherle** [comment]
Thanks for the feedback. Would be nice if this issue could be updated as soon as someone can come up with the "best" solution as a combination of usability and security.

Thanks

**Comment by Bapf** [comment]
Same problem here, even _with_ the proposed header changes.

**Comment by saghul** [comment]
The only thing I can think of is tougher default policies on Electron 9.

**Comment by seanm** [comment]
Not sure If I'm seeing this or https://github.com/jitsi/jitsi-meet-electron/issues/352

But 2.1 is way worse for me, downgrading to 2.0.2 and all is well again.

**Comment by Bapf** [comment]
> But 2.1 is way worse for me, downgrading to 2.0.2 and all is well again.
Which isn't really a vaiable workaround since it constantly auto-updates itself again. :-/

**Comment by seanm** [comment]
>Which isn't really a vaiable workaround since it constantly auto-updates itself again. :-/

It does? Because the download page says: "the Windows and macOS releases are unsigned, so auto-update won't work."

**Comment by saghul** [comment]
That was between the signed / unsigned transition. They should auto-update now.

**Comment by chref** [comment]
And is there a way to prevent auto-update for the time being?

**Comment by tiiiecherle** [comment]
I have to correct my post above. Setting the Content-Security-Policys as stated above joining and opening a room as first participant works. But as soon as a second person joins the room (both using jitsi-meet-electron 2.1.0 on macOS) one gets kicked out and gets a white screen.

Even disabling all Content-Security-Policys does not help.

Downgrading to 2.0.2 solves the problem.

**Comment by saghul** [comment]
This is a Chrome bug: https://github.com/jitsi/jitsi-meet-electron/issues/352#issuecomment-633890883 Closing in favor of #352.

We'll see what we can do here.
