### ISSUE TITLE
How do I build for windows?

### ISSUE THREAD

**Issue by maddie-wang** [jitsi/jitsi-meet-electron#353]
i'm on a mac, what's the command to build for windows?

 npm run dist currently only builds mac files.

**Comment by maddie-wang** [comment]
@saghul

**Comment by maddie-wang** [comment]
when i do electron-builder -wm i get....
`• building        target=macOS zip arch=x64 file=dist/sesame.zip
  • building        target=DMG arch=x64 file=dist/sesame.dmg
  • rebuilding native dependencies  dependencies=iconv@3.0.0, jitsi-meet-electron-utils@2.0.6, robotjs@0.6.0 platform=win32 arch=ia32
  • install prebuilt binary  name=robotjs version=0.6.0 platform=win32 arch=ia32
  • install prebuilt binary  name=jitsi-meet-electron-utils version=2.0.6 platform=win32 arch=ia32
  ⨯ cannot find prebuild-install  
  ⨯ cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /Users/mac/.npm/_prebuilds/14e8e4-robotjs-v0.6.0-electron-v76-win32-ia32.tar.gz
    prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.6.0/robotjs-v0.6.0-electron-v76-win32-ia32.tar.gz
    prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.6.0/robotjs-v0.6.0-electron-v76-win32-ia32.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=8.2.1 runtime=electron arch=ia32 libc= platform=win32)
    
                                    command=/usr/local/Cellar/node/12.11.1/bin/node /Users/mac/Documents/yeetings/node_modules/jitsi-meet-electron-utils/node_modules/prebuild-install/bin.js --platform=win32 --arch=ia32 --target=8.2.1 --runtime=electron --verbose --force
                                    workingDir=/Users/mac/Documents/yeetings/node_modules/jitsi-meet-electron-utils/node_modules/robotjs
  • building embedded block map  file=dist/sesame.zip`

**Comment by saghul** [comment]
Not all native dependencies provide prebuilt binaries, so you need to build it on a Windows machine.

We use AppVeyor for our builds for example.
