### ISSUE TITLE
End-Call button breaks when pressing it while it fades in during beginning of call

### ISSUE THREAD

**Issue by luclu** [jitsi/jitsi-meet-electron#354]
If the End-Call button is pressed right after the beginning of a call (while it fades in from below; and microphon and camera buttons are still not white (activated)) it will break its functionality. 

Apparently the only way to end the call after this is to close the application.

**Comment by saghul** [comment]
I tried to reproduce this, but couldn't. Are you using your own server or targeting meet.jit.si ?

**Comment by luclu** [comment]
Hi @saghul, this happens using my own server as well as using ```meet.jit.si```

#### System info:
macOS ```10.15.4```
jitsi-meet-electron ```2.1.1```

**Comment by luclu** [comment]
Apparently this issue is not reproducable on `Windows 10` using ```2.1.1```.

**Comment by saghul** [comment]
I don't think it's platform dependent. I have tried to reproduce it on macOS FWIW, to no avail.

**Comment by luclu** [comment]
Thanks for looking into this. Here is a small gif with two tries to reproduce it.
The first time I failed, too. But the second time later in the clip I was able to reproduce it.

![end-call-button mov](https://user-images.githubusercontent.com/10135872/83572864-9c6fbf00-a52a-11ea-891a-b8e420adc2d5.gif)

**Comment by Echolon** [comment]
Thank you very much

**Comment by saghul** [comment]
I believe we have solved this in jitsi-meet recently. Tentatively closing, please holler if you manage to reproduce it again.
