### ISSUE TITLE
macOS screen-sharing second screen actually shares primary screen

### ISSUE THREAD

**Issue by luclu** [jitsi/jitsi-meet-electron#355]
While the local preview displays the second screen, pariticipants are shown the primary screen.

This is highly problematic from a security stand-point.

**Comment by saghul** [comment]
Thanks for the report, which check ASAP. What version are you using? Do earlier versions exhibit the same problem?

**Comment by saghul** [comment]
I just tested this on macOS and couldn't reproduce the problem. What operating system and version are you using?

**Comment by luclu** [comment]
Trying to reproduce it I stumbled into several anomalies - I will get back to you with a more coherent understanding of those.

**Comment by luclu** [comment]
First anomaly is descripted in #366.

**Comment by saghul** [comment]
Should I close this since it cannot be reproduced then?

**Comment by luclu** [comment]
@saghul the bug still exists, but only applies to macOS.
At lieast I cannot reproduce it on Windows - can't speak for linux.

Although it might be an electron bug and - if true - should be reported upstream I would like to keep the issue open as long as it still occurs.

**Comment by saghul** [comment]
Well, I haven’t been able to reproduce it myself.

Please provide as many details as possible and the exact steps you follow.

**Comment by saghul** [comment]
Ping, have you find a reliable way to reproduce this?
