### ISSUE TITLE
Mint: Jitsi-Meet standalone application will not allow text entry into ID fields and indeed locks up the computer

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [jitsi/jitsi-meet-electron#356]
## Description

The Jitsi-Meet standalone application will not allow text entry into ID field. Whenever I try to type into the field, a little box opens on my desktop and the text appears there. (That box is some sort of method Mint Cinnamon has for searching the desktop.) Worse, the rest of the computer's UI becomes inaccessible. I had to enter a tty and reboot the system.

Or at least I _presume_ that the field into which I am trying to type is for the meeting ID; the field is not actually labelled. Also, the window seems not to be Hi-DPI aware and so it is hard to see because it is tiny.

The inability to type into the Jitsi field and even perhaps the lock-up may be a Mint / Cinnamon problem. If it is, I will close this issue, and open some other one(s) for the Hi-DPI problem and the lack of any labelling of the box.

## Current behavior
See above. 

## Expected Behavior

One needs to be able to enter text into the field (not to mention be able to see the field properly and know what the field is for). And one needs one's computer not to lock up.

## Possible Solution
Entering text and locking-up: I don't know.
The visibility problem: fix the Hi-DPI support.
The labelling problem: add a label.

## Steps to reproduce

Download and install the software on Mint Cinnamon. Use the PPA version - for the .deb version (another problem) would not install.

# Environment details

OS: Linux Mint 19.3 Tricia x86_64
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th
Kernel: 5.6.7-050607-generic
Resolution: 2560x1440 @ 60.01Hz
DE: Cinnamon
WM: Mutter (Muffin)
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: Intel UHD Graphics 620

**Comment by saghul** [comment]
Can you share a screenshot of what you see?

**Comment by saghul** [comment]
No follow-up, closing.
