### ISSUE TITLE
Doesn't work on debian buster

### ISSUE THREAD

**Issue by susobaco** [jitsi/jitsi-meet-electron#357]
Hi, if I try to run the last meet-jitsi-electron appimage it doesn't work, and throw this error in debian buster.

_Cannot open /proc/self/exe: Permission denied
Failed to get fs offset for /proc/self/exe_

**ls -la /proc/self/exe**
_lrwxrwxrwx 1 ****** ********* 0 may 26 13:10 /proc/self/exe -> /usr/bin/ls_

Salud!

**Comment by saghul** [comment]
Are you running a 32 bit system by any chance?

**Comment by susobaco** [comment]
**uname -m**
_x86_64_

**Comment by susobaco** [comment]
I upgraded to the latest version, and the error message was different:

_The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that_

By adding this line to the end of the /etc/sysctl.conf file:
_kernel.unprivileged_userns_clone=1_

Everything works perfectly. Thank you
