### ISSUE TITLE
jitsi-meet-electron doesn't work with self-hosted jitsi

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet-electron#358]
I have a self-hosted jitsi instance. It works fine from browser, ios and android applications. It doesn't require a password to start a conference.

I've installed the latest [jitsi-meet-electron](https://github.com/jitsi/jitsi-meet-electron/releases/download/v2.1.0/jitsi-meet.exe) on w10. It works fine with https://meet.jit.si.
But it just hangs trying to connect to my instance.

While I typing the address in `Server URL` it shows a warning: `Invalid Server URL or external API not enabled`, but when I finis this warning disappears. The same time I see
```
INFO: [19] Videobridge.createConference#320: create_conf, id=7f1fbffde388435a gid=null logging=false
INFO: [19] AbstractHealthCheckService.run#171: Performed a successful health check in PT0.010016S. Sticky failure: false
```
in the `jvb.log`.

But pressing the `GO` button I see nothing in the server logs.

![Peek 2020-05-26 16-16](https://user-images.githubusercontent.com/14617699/82906620-343f3d00-9f6e-11ea-9512-40515b575140.gif)

**Comment by C0rn3j** [comment]
You might want to try testing with 2.0.2 (check version after installing since it autoupdates), as 2.1.0 introduced a few issues.

**Comment by 532910** [comment]
Forgot to say, one of the previous versions also has the same issue. Not sure, but suppose it was 2.0.2.

**Comment by saghul** [comment]
Can you share the server URL so we can test it out?

**Comment by coach1988** [comment]
@532910 I've noticed that the app is quite picky regarding the format of the URL in the settings, e.g. a trailing slash.
In our case, we're using **https://**jitsi.fqdn.com**:<ourPort>****/**

**Comment by 532910** [comment]
@coach1988,

1. It works with https://meet.jit.si the same as with https://meet.jit.si/
2. It can create new and join existent room on meet.jit.si


I've tried 2.0.0, 2.0.2 and 2.1.0 on linux debian sid and windows 10 in virtualbox and intel stick with the same result.

I believe it's my server side issue, but it should not behave so (as shown on the screenrecord above).

@saghul, I sent you a letter.

**Comment by TimmiORG** [comment]
@532910 
Just to double check. You have added this right?
https://github.com/jitsi/jitsi-meet-electron#using-it-with-your-own-jitsi-meet-installation
Best regards
Christoph

**Comment by 532910** [comment]
Saúl pointed me to CSP, and the solution was to remove `frame-ancestors=self` policy that was mistakenly added.

Electron app works fine with `default-src=none` and no `frame-ancestors` specified. As I understand this is completely contrary the [note in README.md]( https://github.com/jitsi/jitsi-meet-electron#using-it-with-your-own-jitsi-meet-installation).

**Comment by 532910** [comment]
The question is: should it behave so (as shown on the screenrecord above) or this is a correct behaviour?

**Comment by saghul** [comment]
The README says that those headers are known NOT to work, so I’d say it’s correct?

**Comment by saghul** [comment]
I’d say it’s correct. Electron doesn’t have a valid origin that would pass the ancestor check, so you have to configure the server so iframe can be embedded anywhere, if you want the electron app to work.

If there is a better way to handle this, I’d be happy to add it to the README.

**Comment by 532910** [comment]
Under **known NOT to work** I understand it doesn't affect Electron App, but in fact setting `frame-ancestors=self` breaks it!

**Comment by saghul** [comment]
On the contrary, if affects the Electron app directly as it embed Jitsi using the iframe. If you feel like the wording could be improved feel free to send a PR, that would be much appreciated.

**Comment by luixxiul** [comment]
@532910 do you set exactly `frame-ancestors=self`, not `frame-ancestors 'self'`?

**Comment by 532910** [comment]
frame-ancestors 'self' of course

**Comment by 532910** [comment]
CSP header that works for me:

```nginx
set $CSP "";
set $CSP "${CSP}default-src 'none';";
set $CSP "${CSP}style-src 'self' 'unsafe-inline';";
set $CSP "${CSP}font-src 'self';";
set $CSP "${CSP}media-src 'self';";
set $CSP "${CSP}img-src 'self' https://www.gravatar.com https://ui-avatars.com/api/ https://matrix-client.matrix.org";
set $CSP "${CSP}script-src 'self' 'unsafe-inline';";
set $CSP "${CSP}worker-src blob:;";
set $CSP "${CSP}connect-src 'self';";
add_header Content-Security-Policy $CSP;
```

**Comment by saghul** [comment]
Why the matrix url?

**Comment by 532910** [comment]
If you type something like @username:homeserver.tld in the e-mail field it will request avatar from homeserver.tld.

But this works only for jitsi-meet. jitsi-meet-electron doesn't recognize matrix IDs.

I have not found where matrix ID is parsed/used, is this a gravatar magick? 

I found where gravatar and ui-avatars are used:
https://github.com/jitsi/jitsi-meet-electron/blob/d2f49288f13bfd9590d7968909b096353e87231b/app/features/settings/functions.js 
https://github.com/jitsi/jitsi-meet/blob/0598e7369b2dfac9c11637c3c356cf634466430f/react/features/base/participants/functions.js

Looks like jitsi-meet and jitsi-meet-electron has quite different (or possibly unsynced) codebase, isn't it? I I thought they are similar (same as riot desktop and electron app).

Moreover, taking userpics directly from the remote services you will never be able to set img-src policy as you can never specify all matrix homeservers.

**Comment by saghul** [comment]
> If you type something like @username:homeserver.tld in the e-mail field it will request avatar from homeserver.tld.

Humm, no.



> But this works only for jitsi-meet. jitsi-meet-electron doesn't recognize matrix IDs.
> 
> I have not found where matrix ID is parsed/used, is this a gravatar magick?

I have never seen this. Might be some gravatar stuff, but I doubt it, since we use the email field and not the user id.

> Looks like jitsi-meet and jitsi-meet-electron has quite different (or possibly unsynced) codebase, isn't it? I I thought they are similar (same as riot desktop and electron app).

The Electron app uses the iframe API to embed Jitsi Meet. We are setting the avatar for historical reasons at this point. I'm think about just removing it completely from the Electron app since Jitsi Meet itself knows what avatar to display based on the email or initials.

**Comment by saghul** [comment]
I'm closing this since we have clarified why it didn't work.

**Comment by 532910** [comment]
> Might be some gravatar stuff

Not sure, but it smells like some kind of black magic:
While it works pretty stable in my default firefox profile, I can't reproduce this on a clean ff profile or in chromium. Typing my matrix id in the e-mail fied it requests `https://www.gravatar.com/avatar/<Matrix ID>?d=404&size=200` and receives 404. I tried to open riot and loing in the previous tab but it changes nothing.

**Comment by 532910** [comment]
But it'd be interesting to figure out how it works.

**Comment by 532910** [comment]
It's due to my ff's `webappsstore.sqlite`:

```SQL
INSERT INTO webappsstore2
VALUES(
        '',
        'ten.ecafretuo.istij.:https:443',
        'ten.ecafretuo.istij.:https:443',
        'features/base/settings', '{
                "avatarID":"<ID>",
                "displayName":"sergio",
                "email":"@my_matrix_id",
                "avatarURL":"https://matrix.homeserver.tld/_matrix/media/r0/download/outerface.net/<ID>"}'
);
```
I believe it was created by riot web app, that integrates jitsi.

**Comment by faxotherapy** [comment]
Same issue here, but on MacOS. No problem when using the browser. Once, I input my URL (to my own server) to the Electron app, I got the message “Invalid Server URL”. So, is my Firefox browser more clever than the app?

**Comment by Reavus3** [comment]
> Saúl pointed me to CSP, and the solution was to remove `frame-ancestors=self` policy that was mistakenly added.
> 
> Electron app works fine with `default-src=none` and no `frame-ancestors` specified. As I understand this is completely contrary the [note in README.md](https://github.com/jitsi/jitsi-meet-electron#using-it-with-your-own-jitsi-meet-installation).



Where are you changing this setting? I have just come across this problem and can't seem to find it.

Thanks in advance.

**Comment by 532910** [comment]
In nginx settings.
