### ISSUE TITLE
Mirroring window on Wayland

### ISSUE THREAD

**Issue by varac** [jitsi/jitsi-meet-electron#364]
I am running wayland (sway 1.4, ubuntu 20.04) and have a strange, annoying issue with jitsi-meet-electron, which I don't experience with any other app.

Steps to reproduce:

* start a conference using jitsi-meet-electron on display A
* hover over with the mouse to display B
* conference window will get mirrored to the display B

Anyone else having this ?

**Comment by saghul** [comment]
Maybe it's the always on top window? You can disable it in the settings menu.

**Comment by varac** [comment]
> Maybe it's the always on top window?

Thx for the hint, I tried with enabled and disabled always-on-top window, without any difference.

**Comment by saghul** [comment]
When you disable it is shouldn't show up, does it show up regardless?

**Comment by varac** [comment]
> does it show up regardless?

Yes it does. It was disabled (seems like the default behaviour) at the time I created this issue.

**Comment by saghul** [comment]
Hum, the default is to have it enabled. Can you paste a screenshot of your settings panel?

**Comment by varac** [comment]
Sorry for the lag, here you go:

![screenshot-2020-06-28T22:41:58Z](https://user-images.githubusercontent.com/488213/85957789-adc4b380-b990-11ea-8d61-09f58d12c7bb.png)

**Comment by saghul** [comment]
I believe this to be fixed in the latest release.
