### ISSUE TITLE
Black window after stopping remote-control client–side

### ISSUE THREAD

**Issue by luclu** [jitsi/jitsi-meet-electron#365]
When stoping a remote-control session via the overlay "Jitsi-Meet is sharing your screen - stop sharing" button (client-side), Jitsi-Meet (remote-control host) will show an unusable black window.

There seems to be some requirements for this to happen:
1. jitsi-meet (host-side) must be covered by another application window
2. that application window must be in maximized

---
#### Host
Windows 10, `2.1.1`
#### Client
macos 10.15.4, `2.1.1`

**Comment by saghul** [comment]
I've heard of this being a Chrome issue. Since we updated it in 2.2.0 this might have been fixed with the update. Can you test the latest version?

**Comment by luclu** [comment]
Perfect - I cannot reproduce it anymore.
Closed as fixed.
