### ISSUE TITLE
Some eslint rules are not applied

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#37]
Note this:

```
                        <Button
                            appearance = 'primary'
                            type = 'button'
                            onClick = { this._onJoin }>
                            GO
                        </Button>
```

This should trigger react/jsx-sort-props, but somehow it doesn't seem to be working.

**Comment by saghul** [comment]
@hristoterezov You may know this. I have no idea how the jitsi-meet project gets that rule applied...

**Comment by AkshitKrNagpal** [comment]
@saghul
`jitsi-meet` has some eslint rules for `react` folder only.
`react/jsx-sort-props` seems to be part of that. 

https://github.com/jitsi/jitsi-meet/blob/master/react/.eslintrc.js

Maybe we should do something like that for `app` folder.

**Comment by saghul** [comment]
Dammit, I'm blind! Yes please, let's do that for the app/ folder too, here.

**Comment by AkshitKrNagpal** [comment]
@saghul
Just a suggestion. 
Should we maybe make a shareable config for react too? 
Maybe in same repo or different repo.?

Maybe something like `eslint:recommended` and `eslint:all`

IDK. If its possible. 

I think it will be good. Otherwise using a partial shared config is of no point if we are defining react rules again. 

Maybe we can do something like if its normal project extend `eslint-config-jitsi` .
For react extend `eslint-config-jitsi/react' also.

WDYT?

**Comment by saghul** [comment]
> Maybe we can do something like if its normal project extend eslint-config-jitsi .
> For react extend eslint-config-jitsi/react also.

This makes sense! @hristoterezov any thoughts?

**Comment by AkshitKrNagpal** [comment]
@saghul @hristoterezov 
I tested this. This is possible.

The `.eslintrc.js` will look like this.
```
module.exports = {
    'extends': [
        'eslint-config-jitsi',
        'eslint-config-jitsi/react'
    ]
};
```
You can see the changes I made in `eslint-config-jitsi` here - [Link](https://github.com/AkshitKrNagpal/eslint-config-jitsi/tree/react)

Ofcourse we'll need to have a better structure for `eslint-config-jitsi`. I just placed to check if this will work.

**Comment by saghul** [comment]
@AkshitKrNagpal This is great. I want it! Can you please make PRs for this?

**Comment by AkshitKrNagpal** [comment]
@saghul 
Sure. Let me structure it a little bit.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/42, thanks @AkshitKrNagpal !
