### ISSUE TITLE
Web Developer Tools

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet-electron#371]
Please add a way to open Web Developer Tools.
For example [riot-desktop](https://github.com/vector-im/riot-desktop) allows it via `Alt (opens menu) -> View -> Toggle Developer tools`.

**Comment by saghul** [comment]
We only allow that in debug builds. I can see how this can be useful to help diagnose issues. Enabling it should be removing a condition I think.

I’ll to that shortly, but if you want to take a stab at it and send a PR, feel free to do so!

**Comment by 532910** [comment]
> We only allow that in debug builds.

What's wrong to have some key like `--web-developer-dools` for all builds?

**Comment by saghul** [comment]
Nothing really. We could enable them always. Care to send a PR?

**Comment by 532910** [comment]
Not sure :confused:

**Comment by saghul** [comment]
No worries, I’ll squeeze it in next time I work on the electron client.

**Comment by 532910** [comment]
1. `(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.`
2. Right-click shows `Inspect element`

**Comment by saghul** [comment]
Yeah we need to update some dependency for 1) to go.

2) is intentional.

**Comment by 532910** [comment]
> is intentional

![image](https://user-images.githubusercontent.com/14617699/84219514-62c62780-aad9-11ea-8ff4-c4ce52624c75.png)

I believe it shouldn't be in release builds and see no reason for debug ones.
