### ISSUE TITLE
Allow users to start meetings, find their contacts, just like with zoom

### ISSUE THREAD

**Issue by Joe23232** [jitsi/jitsi-meet-electron#372]
Just a suggestion, it is not as feature rich as Zoom is. It would be nice if the electron Windows application allows users to start meetings, find their contacts, just like with zoom.

![image](https://user-images.githubusercontent.com/34926497/83343335-4a694680-a33c-11ea-9a0e-5f93666874b5.png)

Also another thing I was I can disable floating calls when I minimise it.

**Comment by saghul** [comment]
Finding contacts and inviting them requires a backend service integration which is not deployed on meet.jit.si. You can deploy it on your own instance, for example to search on your company directory.

We just made inviting via email easier, should be part of the next release (of meet.jit.si, this app won’t need an update for that).

You can toggle the “always on top window” toggle in the settings (cogwheel on the left) to disable the floating window.

**Comment by Joe23232** [comment]
Oh ok thanks man.
