### ISSUE TITLE
Electron app screen share appears broken with latest release

### ISSUE THREAD

**Issue by r-eason** [jitsi/jitsi-meet-electron#375]
Hi, after the 2.1.1 release I have users on different OS platforms reporting that screenshare does not work from the app.

I can reproduce on my CentOS 7 workstation by downloading the Appimage and sharing to a room. As another user in the conference in a browser (e.g. Chrome Version 83.0.4103.61) I do not see anything shared from my app.

I can provide logs or obfuscated jitsi configs if needed.

Jitsi docker version: https://hub.docker.com/layers/jitsi/jibri/stable-4548-1/images/sha256-81ad9e5a24be52faa792d1022ea2b6199678d83e59a8ef5ad0de72177cd53771?context=explore

Thanks for your help!

**Comment by saghul** [comment]
You need to update to 4627.
