### ISSUE TITLE
Outdated AppImage built

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [jitsi/jitsi-meet-electron#376]
Hi,

it seems the AppImage built is outdated. 
I am downloading and running the latest one from https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2.1.1
When I run it, after the app starts, I get a pop-up saying that there is a new version downloaded and will install after restarting the app. If I restart the app, nothing new happens, the above is repeated.

In the help->Version menu of Jitsi Electron Frontend, 2.0.2 is displayed. 

I have tried manually removing my local AppImage from /home/user/Applications and the relevant config files and downloading again from scratch, with no difference in the outcome.

System info: ubuntu 18.04 LTS, KDE.

**Comment by saghul** [comment]
How are you running the app? Directly from the downloaded file or are you launching it from some menu?

**Comment by nikolas-digitalBabylon** [comment]
Hi,

I was executing with both the appimage file and the .desktop entry. Today I run the desktop entry via command line, hoping to get some printouts. That is what I got:

```
20:28:49.866 › Checking for update
20:28:51.867 › Found version 2.2.0 (url: jitsi-meet-x86_64.AppImage)
20:28:51.869 › Downloading update from jitsi-meet-x86_64.AppImage
20:28:51.873 › updater cache dir: /home/USER/.cache/jitsi-meet-electron-updater
20:28:52.180 › Update has already been downloaded to /home/USER/.cache/jitsi-meet-electron-updater/pending/jitsi-meet-x86_64.AppImage).
20:28:55.533 › Auto install update on quit
20:28:55.536 › Install: isSilent: true, isForceRunAfter: false
20:28:55.555 › Error: Error: ENOSYS: function not implemented, unlink '/run/user/1000/appimagelauncherfs/0000.AppImage'
    at unlinkSync (fs.js:1035:3)
    at p.doInstall (/tmp/.mount_jitsi-Y2F3Tu/resources/app.asar/build/main.js:1:76935)
    at p.install (/tmp/.mount_jitsi-Y2F3Tu/resources/app.asar/build/main.js:1:78444)
    at /tmp/.mount_jitsi-Y2F3Tu/resources/app.asar/build/main.js:1:78879
    at App.<anonymous> (/tmp/.mount_jitsi-Y2F3Tu/resources/app.asar/build/main.js:2:217722)
    at Object.onceWrapper (events.js:313:26)
    at App.emit (events.js:228:7)
    at App.<anonymous> (/tmp/.mount_jitsi-Y2F3Tu/resources/app.asar/build/main.js:1:101400)
    at App.emit (events.js:228:7)
```

Then I tried running `appimagelauncherfs` , which gave me the following:

```
FUSE version: 2.9
Registered new AppImage: "/home/USER/Applications/jitsi-meet-x86_64_00000000000000000000000000000000.AppImage" (ID: 0000)
mountpoint: /run/user/1000/appimagelauncherfs/
Starting FUSE filesystem
Shutting down FUSE filesystem

```

After that, latest version 2.2.0 - which I just downloaded, is running. Can it be some caching issue with appimage itself? I hope it helps.

currently appimagelauncher installed version: 1.2.2+dfsg-1+18.04+bionic+build6 from official repos.

**Comment by saghul** [comment]
I have no idea, but there is nothing I can do here. AppImage has removed the desktop entry thing a while ago from Electron apps, no idea about the cause.

**Comment by Linux-joy** [comment]
Hi,

please could someone post the content of the further desktop entry file, so I can create a desktop entry file myself with a little risk?

Thanks in advance.
