### ISSUE TITLE
POLL: Should the avatar go?

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#379]
Since this repo has a small (but enthusiastic) group of individuals, let's try this.

There is a disconnect between the avatar displayed in the app and what the web would use, should you use a browser. Since we are already asking for a username and email, the embedded jitsi meet will already know to use gravatar or the locally generated avatar, or whatever is configured.

There is no good way to embed the avatar logic in Jitsi Meet here.

So I'm thinking of getting rid of it from the UI here. Thoughts? Please vote with 👍  or 👎  and leave a comment if you need to elaborate.

**Comment by dchmelik** [comment]
Just allow people to open their own: don't force gravatar.
