### ISSUE TITLE
Right click not working in conference name field

### ISSUE THREAD

**Issue by Bapf** [jitsi/jitsi-meet-electron#380]
In the "Enter a name for your conference or a Jitsi URL"-Field right click isn't working.

This is quite a big issue here, because a lot of our users only do copy&paste with the context menu and some of them don't even know that it's possible with keyboard shortcuts.
And since the context menu isn't working in the electron client (at least on windows and mac os) they can't attend meetings other then inputting the whole URL by hand which is another source of error.

**Comment by saghul** [comment]
Looks like https://github.com/sindresorhus/electron-context-menu can do exactly what we need here.

If anyone wants to take this one, feel free to do so, otherwise I'll get to it when I get some spare cycles.
