### ISSUE TITLE
Make sound devices configurable

### ISSUE THREAD

**Issue by Razzeee** [jitsi/jitsi-meet-electron#382]
Here's my scenario right now:

- Listening to music via speakers
- Want to do a quick jitsi meet
- Start the app
- Change windows sound controls to my headset
- Start chatting

I would like the app to always use my headset and never my speakers (or just if I disconnected my headphone).
I think the best way to achieve this is have an option in the settings.

**Comment by saghul** [comment]
The in-conference settings already provide this functionality. Soon there will be a pre-join screen where you'll be able to choose your devices before actually joining.

**Comment by Razzeee** [comment]
That's good news, are there any docs on that, searching for it doesn't seem to help? Will that still mean I might have to change it each time?

Basically changes this from above:
- Change windows sound controls to my headset

To:
- Change sound controls in jitsi to use my headset

**Comment by saghul** [comment]
> That's good news, are there any docs on that

The pre-join screen hasn't been released yet.



> Will that still mean I might have to change it each time?

No, even now, if you change your device once in a conference it should be remembered and used next time. If not, that's a bug.

**Comment by Razzeee** [comment]
![image](https://user-images.githubusercontent.com/5943908/83884723-9d306d00-a745-11ea-9dfb-5027f16331a2.png)

Hrm, seems like changing it via the quick icon doesn't persist it. I needed to go into the settings and change it there.

It also feels weird to have to join a call to do such configurations, but I guess that's hard to prevent with the way jitsi is structured at the moment.

**Comment by Razzeee** [comment]
Feel free to close this.
