### ISSUE TITLE
Cannot build the app due to robotjs error

### ISSUE THREAD

**Issue by cduduc** [jitsi/jitsi-meet-electron#387]
Robotjs won't install at npm install
I have tried this on nodejs 8. 11. 12. 13. 14. Getting the same.
I am on Ubuntu 18.04 LTS

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: prebuild-install || node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Is there anything I do wrong in building the app?

**Comment by haviduck** [comment]
have you installed the mitigation tools from Vs?

**Comment by saghul** [comment]
Do you have more output? Some X libraries are needed.

**Comment by cduduc** [comment]
@haviduck  I think I did not installed nothing related to Vs. I tried directly in ubuntu, and preinstalled nodejs and npm.
@saghul here is the whole output:
cosmin@electron-test:~/jitsi-meet-electron$ npm install

> robotjs@0.6.0 install /home/cosmin/jitsi-meet-electron/node_modules/robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.20.1 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/cosmin/jitsi-meet-electron/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6:0,
                 from ../src/robotjs.cc:7:
../src/keycode.h:112:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
robotjs.target.mk:122: recipe for target 'Release/obj.target/robotjs/src/robotjs.o' failed
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory '/home/cosmin/jitsi-meet-electron/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.3.0-28-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cosmin/jitsi-meet-electron/node_modules/robotjs
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN @atlaskit/panel@0.3.5 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/analytics-next@6.3.6 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/button@13.3.12 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/icon@20.1.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/spinner@12.1.7 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @atlaskit/theme@9.5.3 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-memo-one@1.1.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cosmin/.npm/_logs/2020-06-06T05_26_44_751Z-debug.log

**Comment by saghul** [comment]
You need the robot js build dependencies, check here: https://github.com/octalmage/robotjs
