### ISSUE TITLE
Unable to run due to incorrect NODE_MODULE_VERSION

### ISSUE THREAD

**Issue by jrie** [jitsi/jitsi-meet-electron#388]
I am trying to build jitsi using `NodeJs` v13.14.0 which results into the below error, after updating and rebuilding the app using `npm rebuild` and `npm start`.

Note `NODE_MODULE_VERSION`.

![error](https://user-images.githubusercontent.com/5701785/83937144-8849ed00-a7ca-11ea-8e2f-fdb8bb33b6dc.png)

When using nvm, installing `NodeJs v14.0.0`, - the Node_Module_Version turns to 83 which also does not seem to fit - so I can build but not start Jitsi.

**Comment by saghul** [comment]
I think you need Node 12, the version Eelctron ships with.

**Comment by jrie** [comment]
Hi, unfortunately changing the NodeJs Version to v12 -  does not fix the issue, instead I receive the following error.

![error_2](https://user-images.githubusercontent.com/5701785/83939413-2181ff00-a7dd-11ea-828b-578add9b9620.png)

This time I used `nvm install v12` which installed `v12.18.0` (latest version is downloaded by npm I assume), then `npm update`, and `npm rebuild`. After runing `npm start` the error persists.

**Comment by saghul** [comment]
Hum that’s weird, I’m developing with Node 12 no problem (in macOS but I don’t think it matters in this case).

Did you run npm install after changing the node version?

**Comment by jrie** [comment]
@saghul : I only used `npm start` but `npm install` does nothing while complaining about non existing (pre-)build binaries.

If it helps, I develop using Debian Sid

**Comment by saghul** [comment]
Well, npm install should have installed the required dependencies matching the electron version we depend on.

So, you get the same error after running npm install, then npm start?! How weird!

**Comment by jrie** [comment]
It seems the issue is gone. I used `npm install` and then `npm start` that time I directly landed in the application.

About the NodeJs version, `nvm current` is telling me that I use v14.4.0 currently.

So I am not sure what exactly fixed it, but this time `npm install` did the correct thing and build the application and I could start it using `npm start`. So I guess the issue can be closed.
