### ISSUE TITLE
Jitsi App Camera not detected (permission not granted)

### ISSUE THREAD

**Issue by jbahillo** [jitsi/jitsi-meet-electron#394]
JItsi App does not detect camera.
mett.jitsi work on Firefox and any other browser, but Chrome This looks to happen as Jitsi App uses chrome api, and chrome looks to fail to detect a number of cameras unless "RunVideoCaptureServiceInBrowserProcess" is enabled. When running meet.jitsi from a Google Chrome browser with this flags enabled, allows camera to be detected and allowed. Disabling it makes Chrome not to detect camera and not even request for permission to acces it.

Is there any way to launch Jitsi-meet App with this chrome flag enabled?

**Comment by jbahillo** [comment]
Found. Adding switch --enable-features=RunVideoCaptureServiceInBrowserProcess does the trick

**Comment by neehalsaal** [comment]
Hi, I face a similar issue when trying to run the app in development environment(npm install/npm start) on macOS catalina 10.15.6.
Could you please detail where you have added this switch to `--enable-features`? @jbahillo

**Comment by jbahillo** [comment]
HI:

I experienced this under Windows 10. My other computers, using Linux did not experience this issue. The fix for me was to add the mentioned parameter in the shortcut through which I launch the Jitsi App (not sure if you will need to create a custom one, or if you can customize launcher parameters in macOS:
![imagen](https://user-images.githubusercontent.com/2781605/97274790-6c0c2280-1835-11eb-995d-fd43dac4085c.png)

**Comment by neehalsaal** [comment]
> HI:
> 
> I experienced this under Windows 10. My other computers, using Linux did not experience this issue. The fix for me was to add the mentioned parameter in the shortcut through which I launch the Jitsi App (not sure if you will need to create a custom one, or if you can customize launcher parameters in macOS:
> ![imagen](https://user-images.githubusercontent.com/2781605/97274790-6c0c2280-1835-11eb-995d-fd43dac4085c.png)

Thank you so much, I shall try to figure out where I can provide this switch in my dev environment and keep you posted
