### ISSUE TITLE
problem sharing windows in the desktop application

### ISSUE THREAD

**Issue by cisasmendi** [jitsi/jitsi-meet-electron#396]
I am using my own jitsi and jibri server, when I start to share a window in win10 the receivers cannot receive the transmission, this does not happen in the browser version

**Comment by amesser** [comment]
I can confirm the issue. Using the electron app on windows 10 neither screen sharing nor remote control works. When enabling screen sharing in electron app on windows 10, on the remote peer browser the avatar/image changes to a "computer symbol" but no image is shown. When stopping screen sharing, the avatar/image changes back to the name shortcut.
The other direction of screensharing (browser -> desktop app) works as expected.

We're also using an own jitsi server. I have skimmed through the javascript console logs in the desktop app but did bot found any useful information.

**Comment by C0rn3j** [comment]
Same problem after updating Jitsi to the new stable versions (4857) that just got tagged yesterday.

**Comment by saghul** [comment]
meet.jit.si is running the same version as the current stable. What are these problems you mention?
