### ISSUE TITLE
in windows npm install is showing error please resolve asap

### ISSUE THREAD

**Issue by saraswatyash** [jitsi/jitsi-meet-electron#397]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jitsi-meet-electron@2.2.0~prestart: jitsi-meet-electron@2.2.0
6 info lifecycle jitsi-meet-electron@2.2.0~start: jitsi-meet-electron@2.2.0
7 verbose lifecycle jitsi-meet-electron@2.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle jitsi-meet-electron@2.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\jitsi-meet-electron\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\saras\AppData\Local\Microsoft\WindowsApps;;C:\Users\saras\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\saras\AppData\Roaming\npm
9 verbose lifecycle jitsi-meet-electron@2.2.0~start: CWD: F:\jitsi-meet-electron
10 silly lifecycle jitsi-meet-electron@2.2.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'webpack --config ./webpack.main.js --mode development && concurrently "npm:watch" "electron ./build/main.js"'
10 silly lifecycle ]
11 silly lifecycle jitsi-meet-electron@2.2.0~start: Returned: code: 1  signal: null
12 info lifecycle jitsi-meet-electron@2.2.0~start: Failed to exec start script
13 verbose stack Error: jitsi-meet-electron@2.2.0 start: `webpack --config ./webpack.main.js --mode development && concurrently "npm:watch" "electron ./build/main.js"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jitsi-meet-electron@2.2.0
15 verbose cwd F:\jitsi-meet-electron
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error jitsi-meet-electron@2.2.0 start: `webpack --config ./webpack.main.js --mode development && concurrently "npm:watch" "electron ./build/main.js"`
22 error Exit status 1
23 error Failed at the jitsi-meet-electron@2.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by VPetar** [comment]
Had no issue, works from the first try. :/

**Comment by saraswatyash** [comment]
Can you please tell how to install

**Comment by VPetar** [comment]
> Can you please tell how to install

![image](https://user-images.githubusercontent.com/24390795/85745553-14826c80-b706-11ea-8413-e529290ffabc.png)

These are the Node and NPM versions I have installed, please install them on your windows machine and try with `npm install` again.

**Comment by VPetar** [comment]
> Can you please tell how to install

Did you resolve your problems with the new npm/node versions like I recommended?

**Comment by saraswatyash** [comment]
It's still not working can you tell me about the packages you've installed before installing

**Comment by VPetar** [comment]
Hey saras, sry to hear about that,

Nothing fancy. My procedure was as follows:
```
git clone git@github.com:jitsi/jitsi-meet-electron.git
cd jitsi-meet-electron
npm install
```

Would you be so kind to download [Git bash](https://git-scm.com/downloads) and try running your `npm install` from it?

**Comment by saraswatyash** [comment]
it worked thanks
