### ISSUE TITLE
Black window after entering room name

### ISSUE THREAD

**Issue by faxotherapy** [jitsi/jitsi-meet-electron#406]
Hello,
I enter the room name, press _GO_, then I'm welcomed by a black window. I can connect to the room via a regular browser.
System: MacOS Mojave 10.14.6

I have this issue from the console:
```
Refused to display 'https://vc.belgavox.nl//ebfadeee-49d0-4e09-9350-535aa9a4adab#jitsi_meet_external_api_id=0&config.startWithAudioMuted=false&config.startWithVideoMuted=false' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

A bit too bad I can't use`DENY` or `SAMEORIGIN` as using `X-Frame-Options` is quite a requirement nowadays…

Thanks for your help.

**Comment by saghul** [comment]
You are not in a website but on a an app, so the origin check won't work. I don't think there is a way around it.
