### ISSUE TITLE
Auto-Update not working ?

### ISSUE THREAD

**Issue by Ribero** [jitsi/jitsi-meet-electron#410]
## Description
Auto-Updater does not seems to update the application to it's latest version

## Current behavior
Using version 2.2.0, 2.3.0 is out but no update seems to be launched. No popup message or any type of user information/choice for update

## Expected Behavior
As I never see it in action, I have no idea on how the auto-update process is supposed to work: 

- Maybe notify user that an update is available
- Allow the user to choose to update or not

## Possible Solution
Workaround: download latest version from https://github.com/jitsi/jitsi-meet-electron/releases/latest/download/

Maybe add a user setting to enable/disable auto-update, force check or display new version available...

## Steps to reproduce

1. Launch Jitsi Meet Electron 2.2.0 (or earlier)
2. Check version in menu (2.2.0)
3. Wait a few minutes or even start a video meeting
4. Quit
5. Relaunch
6. Check version -> still 2.2.0

 -> no indication of new version available, no update done

# Environment details

- Jitsi Meet Electron v 2.2.0 installed in ~/Applications/ (same test done with installation in /Applications but no change)
- macOS 10.14.6 (18G5033)

**Comment by saghul** [comment]
This is expected on macOS since our build is unsigned.

**Comment by Ribero** [comment]
@saghul Ok, thanks, it make sens. Maybe it could be usefull to add this information to https://github.com/jitsi/jitsi-meet-electron#macos ?

**Comment by saghul** [comment]
Absolutely. Care to send a PR?

**Comment by Ribero** [comment]
done ! (My first PR 😄) Hope everything is OK.

**Comment by saghul** [comment]
Almost :-) You need to send the PR to this repo.
