### ISSUE TITLE
join via protocol link not fully working on Linux

### ISSUE THREAD

**Issue by chref** [jitsi/jitsi-meet-electron#411]
Jitsi Meet Electron release: 2.3.0
Platform: Linux (CentOS 8/GNOME/Xorg)

We just tried the new "join conference via protocol link" (#389) feature. We noticed that on Windows 10 it works perfectly out-of-the-box, but unfortunately not on Linux.

(Let's ignore for the moment the problem of the actual registration of a scheme handler in the desktop environment, which we had to do manually in order to get the client launched when clicking on jitsi-meet: URIs.)

The problem we observed is that if JME is not currently running, the invocation of "~/jitsi-meet-x86_64.AppImage jitsi-meet://meetingname" only results in the client being started, but then remaining on the welcome page where I can enter the meeting name manually.

If, however, the JME client is already running in this state, executing  "~/jitsi-meet-x86_64.AppImage jitsi-meet://meetingname" results in the already-running instance to immediately join the meeting.

We would have expected that the client join the meeting on the first invocation, just like it happens with the Windows client.

**Comment by saghul** [comment]
Thanks for the report! If anyone has ideas, patches are very welcome.

**Comment by chamerling** [comment]
Have to check what happens on Linux here https://github.com/jitsi/jitsi-meet-electron/blob/master/main.js#L230
