### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by jrie** [jitsi/jitsi-meet-electron#414]
The string "Invalid Timeout" is not by default translated.

Please see here:
https://github.com/jitsi/jitsi-meet-electron/blob/e4742dbc995a10b5a1eef84ca65ced725cbd95a7/app/features/settings/components/ServerTimeoutField.js#L80

**Comment by saghul** [comment]
Nice catch! Any chance you can provide a fix?

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/415
