### ISSUE TITLE
Where in the code is the background color set?

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet-electron#416]
Hi,

I just compiled the app for linux and osx and so far so good (except E2EE which leads to connection loss once it's set).

I'll look into the E2EE bug and will open a ticket about that once I have some more interesting info to share.

My question is where in the code can I change the background color of the app from Jitsi blue to something else?
I've looked around through the source and I can't find anything related to color.

Thanks

**Comment by akshitkrnagpal** [comment]
Hi, You can find background colour in this file.

https://github.com/jitsi/jitsi-meet-electron/blob/master/app/features/welcome/styled/Wrapper.js

**Comment by pdarcos** [comment]
Thanks @akshitkrnagpal!
That's exactly what I was looking for.

**Comment by pdarcos** [comment]
Sorry to be a pain but now I'm looking for the colors in the onboarding (ugly purple) view and also the blue color inside the GO button.

I'm probably blind but I can't seem to find those set anywhere in the code.

**Comment by saghul** [comment]
They are probably in the “styled” file for that component.

**Comment by pdarcos** [comment]
Thanks @saghul 

That's the first place I looked. I checked [here](https://github.com/jitsi/jitsi-meet-electron/tree/master/app/features/onboarding/components) but I don't see any styled file for onboarding at all.
I also looked at the Wrapper.js file [here](https://github.com/jitsi/jitsi-meet-electron/tree/master/app/features/conference/styled)   for the background in the GO button but there's no color settings there either.

Either I'm blind or its pulling those properties from somewhere else.

**Comment by pdarcos** [comment]
@saghul Any other ideas as to where it could be pulling the colors from?

I've gone through the code thoroughly but my eyes are starting to hurt and I can't find it anywhere.

Do you know the hex colors used for the purple and blue that's used so I can try to search using those string?

Thanks

**Comment by saghul** [comment]
Ah, then they might come from AtlasKit, in which case it's harder to override...

**Comment by pdarcos** [comment]
Yeah, that's where it is. 
That really sucks, specially considering Atlassian seems to be going back on their "open source forever" pledge as can be read [here](https://community.developer.atlassian.com/t/atlaskit-mirror-not-a-mirror-changes-to-open-source-licensing/36229/20) where a bunch of disappointed devs have been complaining.

**Comment by saghul** [comment]
That is very unfortunate indeed.

Going forward we will move away from AtlasKit, but there is no ETA for that.

**Comment by pdarcos** [comment]
I understand. Too many other priorities at the moment.

I'll go ahead and close this issue for now. No sense in leaving it open indefinitely.

Thanks
