### ISSUE TITLE
building for windows on linux machine?

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet-electron#418]
Hi,

I've built the app for OSX and linux and was going to build for windows when I noticed there doesn't seem to be any instructions for compiling for windows. At least I can't seem to find any info on building the windows installer.

Can it be compiled on a linux machine or do I need to find a windows PC to compile the app?

Thanks

**Comment by akshitkrnagpal** [comment]
@pdarcos
You can't build windows installer in Linux or Mac. You should consider using https://www.appveyor.com which we use for building windows builds.

**Comment by pdarcos** [comment]
Thanks @akshitkrnagpal 
That's what I suspected but was hoping there was an easier way.

Cheers
