### ISSUE TITLE
Don't work remote control 

### ISSUE THREAD

**Issue by denyk443245235** [jitsi/jitsi-meet-electron#419]

**Comment by denyk443245235** [comment]
When I try to do something actions, nothing happens

**Comment by saghul** [comment]
I has been disabled as of version 2.3.0

**Comment by lsowen** [comment]
@saghul any background on why it was disabled?  I see the commit (https://github.com/jitsi/jitsi-meet-electron/commit/0b88a783f3f7658d7e04e8a868ffbb4b56b77c7b), but it doesn't provide any additional info
