### ISSUE TITLE
Half of the UI on the Mac version is showing Korean despite English is set as primary language

### ISSUE THREAD

**Issue by lucky13820** [jitsi/jitsi-meet-electron#423]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
I just downloaded the newest version for Mac. Many texts for the UI is showing Korean for me. My Mac's language is set to English as Primary language. I do have Korean in my preferred language list, but it's at the bottom of list, below the Chinese. 
![CleanShot 2020-07-26 at 10 10 46](https://user-images.githubusercontent.com/7293811/88485484-e83b5500-cf2a-11ea-9050-bd5f26667b58.jpg)

## Current behavior
Half of the UI is in Korean. 

## Expected Behavior
All UI should be English as that's the primary language in my system. 

## Possible Solution
After delete Korean in my preferred language list and reinstall Jitsi Meet, it solved the problem. 

## Steps to reproduce
I tried to reproduce this problem by adding Korean to the list again and reinstall Jitsi Meet, but it doesn't show Korean anymore. 

# Environment details
macOS 10.15.6 Jitsi Meet 2.3.0

**Comment by saghul** [comment]
Do you happen to be in Korea?

**Comment by lucky13820** [comment]
No, I’m not. I’m in Canada.

**Comment by saghul** [comment]
Can you open the JS console (Cmd, Opt, i) and type `jitsiNodeAPI.getLocale()` ? What do you get?

**Comment by lucky13820** [comment]
Right now it says en-US, but that's probably because the UI is fine. I actually couldn't reproduce the bug now. Maybe could be some random bug.

**Comment by saghul** [comment]
We pass that value on to the iframe, so if you saw it in Korean, chances are that returned Korean, which is extremely weird!

**Comment by lucky13820** [comment]
![CleanShot 2020-07-29 at 00 34 53](https://user-images.githubusercontent.com/7293811/88770996-71bd7380-d133-11ea-9126-61fd056ea892.jpg)
So I actually reproduced it. All I did is to switch Korean in the language setting, then half of the UI is in Korean again, the value returns en-US still. Was it just because some of the strings don't have translations?

**Comment by saghul** [comment]
Yep, strings without translations will show the fallback language, English.

**Comment by lucky13820** [comment]
Oh, yeah, I guess that's what happened. But not sure why it happened when I first installed Jitsi. I don't know what language was it in, but I didn't change the language setting after installed, everything was the default.

**Comment by saghul** [comment]
We pick the default language as reported by Electron.

**Comment by Echolon** [comment]
Is this solved?

**Comment by lucky13820** [comment]
Yeah, it's solved

**Comment by gauravgg** [comment]
i can also see text in korean or in chinese language in a webview. Please let me know how to resolve it
