### ISSUE TITLE
How to rename the deskotp application name "electron" to our website name

### ISSUE THREAD

**Issue by Ramyapriya24** [jitsi/jitsi-meet-electron#424]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by saghul** [comment]
That will automatically be done when you package the app for release.
