### ISSUE TITLE
Select the language/locale

### ISSUE THREAD

**Issue by ovari** [jitsi/jitsi-meet-electron#429]
Can an option please be added to select the GUI language/locale?

![image](https://user-images.githubusercontent.com/17465872/89165291-b0cc4880-d5bb-11ea-86a8-823324ae6f7d.png)

This would be similar to https://meet.jit.si/ which allows the `Language` to be selected.

![image](https://user-images.githubusercontent.com/17465872/89165654-364ff880-d5bc-11ea-96ff-b6a1222008d7.png)

What do you think?

Thank you

**Comment by saghul** [comment]
Yes, a pull request adding this would be most welcome.
