### ISSUE TITLE
Remote Control Issue is missing

### ISSUE THREAD

**Issue by deepkesh26** [jitsi/jitsi-meet-electron#431]
I have tested the latest 2.3.1 build but found that there is no option for the remote control but it was present in the 2.0.0 version so I downloaded the 2.0.0 version and found remote control option is there.

**Comment by indiebrain** [comment]
Looks like Remote Control was disabled in [this commit](https://github.com/jitsi/jitsi-meet-electron/commit/0b88a783f3f7658d7e04e8a868ffbb4b56b77c7b), but no context, nor breadcrumbs were given in this commit explaining the "WHY". @saghul , any chance you could add some color or point us in a direction to understand what lead to this feature being disabled? Is there a technical issue the community might help resolve?

**Comment by tmartincpp** [comment]
Hello,

It has been disabled because of security issues AFAIK :+1: https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md

**Comment by saghul** [comment]
Security: https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md

**Comment by indiebrain** [comment]
Many thanks for the context @saghul !

**Comment by ronnystandtke** [comment]
Is there any chance that the remote control feature is coming back?

We just recently replaced other proprietary remote control software with jitsi-meet-electron and were very, very happy with it. Now we are stuck with an older version of jitsi-meet-electron.
Because the commit message said "**Temporarily** disable remote control", I thought I might ask if or when the remote control feature is coming back?

Thanks for this wonderful piece of open source video conferencing and remote support software!

**Comment by saghul** [comment]
Not in the horizon I'm afraid. You can reenable it and build the application yourself. If you lock it down to your own deployment there is not much to worry about.

**Comment by mtkunkel** [comment]
@ronnystandtke Would you point you to [Remotely](https://remotely.one)/ as a completely FOSS teamviewer alternative. 

Came here to find Jitsi remote control for other (video conference) type reasons. It seems only proprietary meeting services provide this feature, currently.

**Comment by hex-m** [comment]
> Not in the horizon I'm afraid.

Even if it's not a priority and won't be solved "soon" it would imho still make sense to have an open issue (feature request) about this topic. I suggest to reopen this issue so people can `+1` it.

**Comment by STPKITT** [comment]
Yes, re-open this please!

**Comment by bensonkb** [comment]
Yes, Please re-open this feature !

**Comment by ypid-geberit** [comment]
Reopening does not get the feature any more ready, actual contribution does.

@bensonkb @STPKITT A simple thumbs up on the comment of @hex-m would have been sufficient in my eyes. Your comment does not contribute anything to the discussion. Maybe the issues need to be moderated? Would be sad.

**Comment by bensonkb** [comment]
@ypid-geberit : Please create a sponsor button so that we can contribute financially which we guys can do. [**opencollective**](https://opencollective.com/)
