### ISSUE TITLE
302 redirect = permissions not granted

### ISSUE THREAD

**Issue by tmartincpp** [jitsi/jitsi-meet-electron#432]
Hello,

I have configured two Jitsi servers on two different servers :
- 1 for internal/confidential use
- 1 for public use

They are both working well.

In Jitsi Meet Electron's configuration, the default server is the internal one, to access to the external I need to use the full url (https://external/room).

But here is the tricky part, I would like to “automatize” as much as I can for my users.
My idea is to do an HTTP 302 redirect for rooms names starting with “external_”.
For example, a request to https://internal/external_room1 is redirected to https://external/room1.

It’s working fine with chromium but not Jitsi Meet Electron, the connection is OK but audio or video permissions are not granted.

I guess this is because Electron grant the permission for https://internal before being redirected to https://external.

Do you think this behavior could be implement in Jitsi Meet Electron ?

Thanks!

Original post: https://community.jitsi.org/t/jitsi-meet-electron-302-redirect-permissions-not-granted/72633

**Comment by saghul** [comment]
Electron should behave just like the browser, in principle. What do you see on the JS console? You can bring it up with the same key combination as in Chrome.

**Comment by tmartincpp** [comment]
Hi @saghul,

In Electron's webpage I can see the yellow message "Error obtaining microphone permissions", here is what I see in the console when I want to unmute the mic :
`Logger.js:154 2020-08-11T11:16:28.420Z [modules/RTC/RTCUtils.js] Failed to get access to local media.  NotAllowedError: Permission denied [object Object] `
`Logger.js:154 2020-08-11T11:16:28.421Z [features/base/tracks] Failed to create local tracks 
["audio"]
s {gum: {…}, name: "gum.permission_denied", message: "User denied permission to use device(s): audio", stack: "Error↵    at new s (https://_external_/**li…nce.com**/libs/lib-jitsi-meet.min.js?v=4289:1:92547"}`

**li…nce.com** might actually be part of my internal domain.

My guess is that Chromium ask the permission to use MIC after the 302, while Electron is allowing mic and cam access before following the 302. I might be wrong of course, you know way better.

For the record I'm using the linux AppImage (version 2.3.1).

**Comment by saghul** [comment]
Hum. What will happen is that the generated iframe URL will be the internal one indeed, and the iframe probably doesn't allow the redirected URL to get the permissions because the allow directive would only apply to the internal one.

I think overall your approach is kinda brittle, as this bug shows.

Have you considered proxying the traffic to either server instead of using the redirect? This would mean the URL remains the same.

**Comment by tmartincpp** [comment]
I liked the idea to have different URLs but I didn't really considered to reverse proxy it.

I agree that my goal/approach is quite special, should I close this bug ?

Thanks a lot for your time and help in any case :+1:

**Comment by saghul** [comment]
No worries, now we know. I'll go ahead and close this then.
