### ISSUE TITLE
Remote control  

### ISSUE THREAD

**Issue by clemoan** [jitsi/jitsi-meet-electron#434]
Remote control seems disabled (no start/stop button) since version 2.3.1. I test it with 2.2.0, it is ok.
Is it a bug ? Do I need to authorize or set a flag somewhere to enable the feature ?

Many thanks

**Comment by tmartincpp** [comment]
It has been answered a few times already, remote control is currently disabled for security reasons:
https://github.com/jitsi/security-advisories/blob/master/advisories/JSA-2020-0001.md

It might be a good idea to modify the readme page and remove, or append, the remote control mention.
