### ISSUE TITLE
Screen sharing shares all screens when share audio is selected

### ISSUE THREAD

**Issue by jamesatjaminit** [jitsi/jitsi-meet-electron#435]
## Description
The screen sharing option shares all the screens, in a tiled like view when the share audio box is ticked. This can only happen if you have multiple monitors, single monitor setups are fine.
## Current behavior
When you share your screen and select "share audio" it shares all of your screens instead of just the one you select.

## Expected Behavior
Only shares the screen that you've selected

## Possible Solution
N/A

## Steps to reproduce
1) Start a call
2) Share a screen
3) Tick the "share audio" checkbox

# Environment details
Jitsi-Meet version: 2.3.1
OS: Windows
OS Build: 19041.450

**Comment by saghul** [comment]
@andrei-gavrilescu Can you PTAL?

**Comment by andrei-gavrilescu** [comment]
Hello,

The issue has been addressed by https://github.com/jitsi/lib-jitsi-meet/pull/1313 . It was a limitation of the electron getUserMedia API, however it seems to be working with individual screens despite the documentation.

**Comment by saghul** [comment]
Cool! Just reviewed and landed it. @jamesatjaminit it will be part of the next Jitsi Meet release. No app update will be necessary.

**Comment by jamesatjaminit** [comment]
Ah, that's great. Thanks for clarification! 😀
