### ISSUE TITLE
When trying to connect jitsi meet getting : window.JitsiMeetExternalAPI is not a constructor

### ISSUE THREAD

**Issue by creadigol** [jitsi/jitsi-meet-electron#437]
Have connected Jitsee meet with firebase authentication that work fine, however when try to call Jitsi-Meet for video call getting this error.
" window.JitsiMeetExternalAPI is not a constructor " 

Below is error log mention and also attache screenshot to error.

2020/08/30 23:13:14 [error] 18090#18090: *184 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 5.188.206.50, server: 0.0.0.0:443, upstream: "127.0.0.1:5349", bytes from/to client:0/0, bytes from/to upstream:0/47
2020/08/30 23:20:05 [error] 18090#18090: *245 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 194.61.55.81, server: 0.0.0.0:443, upstream: "127.0.0.1:5349", bytes from/to client:0/0, bytes from/to upstream:0/47
2020/08/30 23:20:05 [error] 18090#18090: *247 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 194.61.55.81, server: 0.0.0.0:443, upstream: "127.0.0.1:5349", bytes from/to client:0/0, bytes from/to upstream:0/47

![Screenshot 2020-08-31 at 7 15 47 AM](https://user-images.githubusercontent.com/10026007/91678605-9a39f280-eb63-11ea-93b9-c7ffc69452f6.png)

**Comment by saghul** [comment]
Please open an issue on the jitsi-meet repo, this is the Electron wrapper, and AFAICT your problem is not related to Electron.
