### ISSUE TITLE
AppImage does not create desktop file

### ISSUE THREAD

**Issue by chref** [jitsi/jitsi-meet-electron#438]
## Description
When starting JME > 1.1.1 for the first time on Linux (tested on Fedora 32 and CentOS 8), it does not offer to integrate Jitsi Meet by installing a desktop file.

---

## Current behavior
`chmod +x jitsi-meet-x86_64.AppImage`
`./jitsi-meet-x86_64.AppImage`
JME main window opens

---

## Expected Behavior
`chmod +x jitsi-meet-x86_64.AppImage`
`./jitsi-meet-x86_64.AppImage`

![Screenshot from 2020-08-31 23-34-21](https://user-images.githubusercontent.com/33349974/91771643-9a79d280-ebe3-11ea-97ca-bf47d8e84c5f.png)

JME asks whether to install integration before opening main window

---

## Possible Solution
I manually unpacked the AppImages of JME versions 1.1.1 and 2.3.1. Looking at the AppRun script contained within, I noticed that the script in version 1.1.1 contains instructions for installing the desktop file, in particular a call to `desktop-file-install`. The AppRun script of later versions does not have this. 
I do not know the internal workings of AppImage etc., but to me it seems like there is something missing here.

---

## Steps to reproduce

1. start with a newly-created temporary Linux user account
2. download JME 1.1.1 or 2.3.1 AppImage, respectively
3. run the downloaded AppImage

---

**Comment by saghul** [comment]
AppImage no longer does that, this is not something we consciously turned off.
