### ISSUE TITLE
etherpad, open shared document err.

### ISSUE THREAD

**Issue by atuctuc** [jitsi/jitsi-meet-electron#439]
the "open shared document" does not work in jitsi-meet-electron app for me.

in firefox and chromium it works fine.

i get this error when i try to open shared document opton:

ErrorId: M51H52DU4oIIhe5YviUG
URL: https://mydomin/etherpad/p/b768fc9e9ef14ddba32a632d51322b76?showControls=true&showChat=false&showLineNumbers=true&useMonospaceFont=false&userName=anan
UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) JitsiMeet/2.3.1 Chrome/83.0.4103.122 Electron/9.1.2 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://mydomain/etherpad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define&v=680f501f at line 237

**Comment by zoernert** [comment]
If you have a look into your browsers javascript console you might something like "cross domain iframe" blabla... if you are on two different domains. Reason is that etherpad is typically installed on a different domain and jitsi opens it via a iframe. Now the historic solution would have been adding a  [X-Frame-Option](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) `ALLOW-FROM` however this is deprecated.

**Comment by tsia** [comment]
that's weird. both etherpad and jitsi are coming from the same domain in my case. in the browser it works fine but in Jitsi Meet Electron i get cross origin errors.

**Comment by DarksoulMachine** [comment]
Same problem but for me work on mobile!

**Comment by DarksoulMachine** [comment]
Hi guys, i just updated etherpad-lite to version 1.8.7 and now everything works!!!

**Comment by texperiri** [comment]
I can confirm that - the current jitsi docker-image (checkin: 12823cb) uses etherpad version 1.8.6. Switching to 1.8.7 in the etherpad.yml fixes the problem
