### ISSUE TITLE
PGP signed commits and builds

### ISSUE THREAD

**Issue by sunknudsen** [jitsi/jitsi-meet-electron#440]
Hi,

Very excited about the end-to-end encryption feature.

Feels like it’s a good time to implement mandatory signed commits and builds and establish a web-of-trust around Jitsi’s pub key.

![Screen Shot 2020-09-02 at 8 21 52 AM](https://user-images.githubusercontent.com/2117655/91980518-ec6f4500-ed16-11ea-919d-e1d84819891d.png)

As a privacy and security researcher, I feel uneasy when I see messages like this one without being able to confirm who is behind a build.

Thanks for Jitsi!

**Comment by saghul** [comment]
Alas we don't have many resources to devote to this application. It's be hard to prove that a given (even signed) build was built from the code in this repository. So, if trust is an issue you can always build the app yourself, it's pretty much 2 commands which are documented in the readme.

**Comment by awlx** [comment]
This happens because the Build is not signed for MacOS. @saghul maybe we can find a way to sign it :).

**Comment by sunknudsen** [comment]
I value what you guys (and girls) are developing and I’m worried a warning like that one will drive people away from Jitsi.

As a privacy advocate, I stay away from Chrome and end-to-end support in Firefox is broken I believe... hence why I am considering the Electron app.

@saghul Thanks for the follow-up and I agree PGP signing isn’t a silver bullet... depends who is behind the keys... that being said, it does add a layer of trust... especially if the pub key is signed by other trusted parties (web of trust).

@awlx That would be amazing! I guess the build was done without a valid Apple developer account (haven’t touched native stuff in a while).

**Comment by saghul** [comment]
> I’m worried a warning like that one will drive people away from Jitsi.

The main avenue for Jitsi users is the browser.

> As a privacy advocate, I stay away from Chrome

Ironically Chrome/ium is better here because it's the only browser which allows for end-to-end encryption to happen. 

> end-to-end support in Firefox is broken I believe...

Not sure what "end-to-end" is supposed to mean here. Firefox support has been on par with Chrome for a while now.

**Comment by sunknudsen** [comment]
Thanks for the follow up @saghul.

> Ironically Chrome/ium is better here because it's the only browser which allows for end-to-end encryption to happen.

Chromium-based browsers are being praised more and more for their security in general.

> Not sure what "end-to-end" is supposed to mean here. Firefox support has been on par with Chrome for a while now.

Referring to above point where Chrome/ium browsers are the only browsers that support Jitsi end-to-end encryption.

Btw, tried installing the Jitsi Meet Electron app this week and end-to-end encryption was not available (the option in the hamburger menu was not present).

Am I missing something?

**Comment by saghul** [comment]
It's now in the security dialog, press the shield button.

**Comment by csett86** [comment]
macOS releases are signed and notarized since v2021.11.2, so the scary screen that triggered this report is gone and fixed.
