### ISSUE TITLE
Kaspersky flagged this as malware

### ISSUE THREAD

**Issue by e-t-l** [jitsi/jitsi-meet-electron#442]
When I installed this, I got a notification from Kaspersky Security Cloud AV: "Application performing suspicious activity characteristic of malware. Detected: PDM:Trojan.Win32.Generic" and it listed this executable as the source.

Can anyone explain why this might be getting flagged?

**Comment by saghul** [comment]
@awlx Is this the flagging we saw in the past?

**Comment by awlx** [comment]
The last time it was flagged from Windows Defender so I suspect this is different. But I have a look as our users are affected too.

**Comment by saghul** [comment]
Thank you!

**Comment by awlx** [comment]
@e-t-l when did you see this and which version did you install? Was there an auto-update happening and then the warning occured?

**Comment by awlx** [comment]
So I build our version with Electron 10.1.1 and the issue seems gone:
https://www.virustotal.com/gui/file/21bdea2c447cc92fc67bd9de444ce4c9739827a8468219cc0ae604e98eb4e0c8/detection

**Comment by e-t-l** [comment]
@awlx I have no idea if it was trying to auto-update. I just downloaded the most up-to-date installer from here (2.3.1.361), installed it, then Kaspersky Security Cloud detected "suspicious activity." Unfortunately I couldn't find any more detailed logs about what specific activity was detected.

**Comment by awlx** [comment]
@e-t-l could you try out of curiosity if this version:
https://github.com/freifunkMUC/jitsi-meet-electron/releases/tag/v2.0.27

Fixes the issue? If so then @saghul can just release a new version of JitsiMeet with Electron 10.1.1 and we are set :).

**Comment by saghul** [comment]
JUst updated the Electron version yesterday, I can push an update soon indeed.

**Comment by e-t-l** [comment]
> @e-t-l could you try out of curiosity if this version:
> https://github.com/freifunkMUC/jitsi-meet-electron/releases/tag/v2.0.27 (no fear it's 100% upstream apart from the logos, defaultserver and color)

@awlx @saghul I just tried FreifunkMeet and it works fine, no antivirus warnings.

**Comment by awlx** [comment]
@saghul so I think you can/should release

**Comment by ovari** [comment]
@saghul can you please advise when the release is expected? Thank you

**Comment by saghul** [comment]
Sorry folks, dropped the ball. Making a new release now.

**Comment by saghul** [comment]
2.4.0 is out: https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2.4.0
