### ISSUE TITLE
Not working with other instances

### ISSUE THREAD

**Issue by tiotrom** [jitsi/jitsi-meet-electron#443]
Since the default meet.jitsi.si started to inject ads and trackers into their instance, I thought to use this app with a trade-free instance (one that doesn't ask me anything in return for the service. no trade).

Anyways, I tried with:
https://calls.disroot.org/
https://meet.libreops.cc/
https://meet.calyx.net/
https://talk.snopyta.org/

None works. Indeed, for https://calls.disroot.org/ it says API not active. But not for the rest. I get a blank screen...no error or anything.

Cheers!

**Comment by saghul** [comment]
The server needs to allow iframe embedding, check the readme.
