### ISSUE TITLE
User's name sometimes won't change

### ISSUE THREAD

**Issue by danmanrana** [jitsi/jitsi-meet-electron#445]
On the Windows Electron app, when I try to change my name (on the settings pane where below appear the advanced options) and then hit the back arrow, that change doesn't get saved.

Update: I just tried it again and it worked fine. Not sure what the reason could be. Not sure if I should submit this or not because it could still be a bug.

**Comment by saghul** [comment]
You did catch a bug: we currently save the name to settings on blur, but that seems to not fire when you close the drawer.

**Comment by saghul** [comment]
Reopening as the bug is not fixed :-)

**Comment by fremzy** [comment]
Watching....  🤗

**Comment by csett86** [comment]
Usernames are no longer set in the settings, but instead the pre-meeting screen is forced (where the username can be set). Thus closing this as no longer reproducible.
