### ISSUE TITLE
Floating window cannot be marked as always on top or always on current desktop

### ISSUE THREAD

**Issue by Yajo** [jitsi/jitsi-meet-electron#449]
## Description

Floating video window cannot be pinned on top of other windows or to the desktop. Thus, it's not much useful.

## Current behavior

Floating video window cannot be pinned on top of other windows or to the desktop. Thus, it's not much useful. This is the only thing you see in its contextual menu:

![imagen](https://user-images.githubusercontent.com/973709/94547661-dd18e400-024f-11eb-8861-f73619e15544.png)

## Expected Behavior

It should be able to get pinned.

## Possible Solution

It should behave just like any other normal window. See for example what you can do with Firefox's floating video window:

![ezgif com-optimize](https://user-images.githubusercontent.com/973709/94547552-ae9b0900-024f-11eb-851b-525538ed04ac.gif)

## Steps to reproduce

1. Open a jitsi call.
1. Click on other window.
1. Try to pin the minicall widget on top. Impossible.
1. Try to pin it to the current desktop always. Impossible.

# Environment details

OS: Fedora 32 silverblue.
Desktop: GNOME.

**Comment by saghul** [comment]
The window should already be pinned to be always on top. This looks like an Electron bug.

**Comment by dlalinsp** [comment]
I have had the same issue for a while now. It would be nice to see this fixed.

**Comment by saghul** [comment]
Can you test 2.5.1?

**Comment by saghul** [comment]
Make that 2.6.0. Should have been fixed by https://github.com/jitsi/jitsi-meet-electron-utils/commit/080fa332773f586620a5cf2ec2610d2383506d04

**Comment by saghul** [comment]
What behavior are you observing exactly?

**Comment by saghul** [comment]
What window manager are you using?

**Comment by axelsimon** [comment]
Fedora 35's default, GNOME 41.5.

**Comment by axelsimon** [comment]
Oh sorry, misread. Yes, Wayland it is.

**Comment by saghul** [comment]
This must be an Electron / Chromium, there is nothing we can do on the app side AFAIK.

**Comment by Yajo** [comment]
As you can see, with Firefox is possible to do it. Actually, you can do it
on almost any app by right-clicking on its title bar. So it doesn't seem to
be a Wayland limitation.

**Comment by saghul** [comment]
I'm not saying it is I'm saying there might be a bug in how Electron / Chromium handle it.

We are just using the Electron API to set the window to be always on top here.
