### ISSUE TITLE
Allow to select camera in application settings

### ISSUE THREAD

**Issue by thet** [jitsi/jitsi-meet-electron#450]
## Description

On my Thinkpad T480s I have an IR and a normal camera. The application uses the IR camera by default and I have to change it to the normal camera on every call via the call's settings.

## Possible Solution

It would be good if I could set the default camera in the application settings.

## Environment details

Version 2.4.0
Ubuntu 20.04

**Comment by saghul** [comment]
Doesn't Jitsi remember the camera you previously chose in the prejoin screen?

**Comment by thet** [comment]
It does - I don't have any issues since quite a while. Closing and sorry for the noise.
