### ISSUE TITLE
Jitsi Electron forcefully installing alongside Customized desktop app

### ISSUE THREAD

**Issue by fremzy** [jitsi/jitsi-meet-electron#452]
### Description:

When customized Jitsi electron app ("xyz") is installed (on Windows), it auto-installs the original Jitsi electron app as well

### Steps to reproduce:

1. Double click generated xyz.exe file
2. xyz app installs
3. But Jitsi ALSO installs...

### Expected behavior:

Only the customized app should install 

### Actual behavior:

I cloned the Jitsi Electron repo, did some basic customizations in the look (colors) and generated an exe file on a Windows 10 machine. I was able to install on the same machine without any issues, but I sent the generated exe file to a friend to try it out. She reported back that although it installed successfully for her as well, **_it also auto-installed Jitsi Meet_**. Note that this friend knew nothing about Jitsi prior to this. 

### Server information:

- Jitsi Meet version: 2.4.0
- Operating System: Ubuntu Server 20.04

### Client information:

- Browser / app version: Electron
- Operating System: Windows 10

**Comment by awlx** [comment]
Sounds like you missed to change the autoupdater URL? So it downloaded the original App as well.

**Comment by fremzy** [comment]
Thanks @awlx. Yes, found out through research later that was likely the cause. I've since made the change. I should've closed this. Thanks for responding though.

**Comment by jagad89** [comment]
@fremzy I am trying to build with custom name but no luck so far. I am new to electron. 

Can you help with steps/changes you followed to build custom build?

**Comment by fremzy** [comment]
@jagad89 the steps outlined in the guide are actually pretty straightforward. To be honest, I've found working with this Electron app to be the easiest of all the builds I've done (Jitsi Meet install, building the Android app, building the ios app). You literally need just 2 steps (maybe 3, to debug) once you've created the environment (install node js)

1. npm install
2. npm run dist

That's it! Now if you want to check your changes before you do the final build, use "npm start" to check changes and then "npm run dist" to commit the changes to a release version. 


![Screen Shot 2020-10-09 at 1 56 53 PM](https://user-images.githubusercontent.com/63688942/95617527-95f1d680-0a39-11eb-9361-4e47dbbb0f4f.png)
