### ISSUE TITLE
how to disable audio processing using #config.disableAP=true

### ISSUE THREAD

**Issue by atuctuc** [jitsi/jitsi-meet-electron#453]
i tried to add this to the "start a new meeting" name like:
myrehearsalroom#config.disableAP=true

unfortunately this does not work like in the chromium browser. does anyone have an idea how to disable audio processing for using it as a rehearsal room? 

would also be interesting, if we could disable this options in the config
disableAEC - Auto echo cancellation
disableAGC - auto gain control
disableAP - all audio processing
disableHPF - high pass filter
disableNS - noise supression

thanks, atuc

**Comment by saghul** [comment]
We don't support passing URL parameters in the room name at the moment.

**Comment by atuctuc** [comment]
ok, 
but as feature-request it would be nice, if a switch for disabling audio processing could be implemented, like the switches "Start with Audio muted". 
it's very interesting for music teachers and musicians.

**Comment by fremzy** [comment]
@atuctuc Not sure if this is an option for you, but if you have your own Jitsi installation, you can easily do this in your config.js file.

**Comment by csett86** [comment]
Passing config parameters via URL is supported since release v2.8. via #594, thus closing it here.
