### ISSUE TITLE
Screen Sharing not working in Electron 9.1.2

### ISSUE THREAD

**Issue by minhho3199** [jitsi/jitsi-meet-electron#455]
I'm trying to implement screen sharing on my electron app using jitsi meet and jitsi-meet-electron-utils. I did as the usage instructed on the jitsi-meet-electron-utils docs as well as the source code from jitsi-meet-electron but I couldn't get my app to run as expected.

When I press on the screen sharing button on the Jitsi Meet Iframe nothing happens and these errors show up:
`[features/base/tracks] Failed to create local tracks ["desktop"] s {name: "gum.screensharing_user_canceled", message: "User canceled screen sharing prompt", stack: "Error↵    at new s (https://jitsidystance.southeas…re.com/libs/lib-jitsi-meet.min.js?v=4428:1:183359"}`
`Logger.js:154 2020-10-08T07:01:53.921Z [conference.js] <Object.toggleScreenSharing>:  Failed to switch to screensharing s {name: "gum.screensharing_user_canceled", message: "User canceled screen sharing prompt", stack: "Error↵    at new s (https://jitsidystance.southeas…re.com/libs/lib-jitsi-meet.min.js?v=4428:1:183359"}`

**Comment by saghul** [comment]
Did you set it up like this app does?

**Comment by minhho3199** [comment]
I think I did, so please correct me if I'm wrong.

- Add `"jitsi-meet-electron-utils": "github:jitsi/jitsi-meet-electron-utils#v2.0.10"` to package.json and rebuild it with electron-rebuild (this step failed with robotjs module so I added it as a dev dependency, after that everything was ok)
- Import the library into main process and renderer process
- Setup setupScreenSharingMain and setupScreenSharingRender in correct places
- Append several switches like this app's `main.js`
- Using JitsiMeetExternalAPI from `external_api.js`
- I tested with `alwaysOnTop` and it works, so I think the native module is not a problem

I have reviewed the source code of this app several times but found no clue.

**Comment by saghul** [comment]
That sounds about right. Do you get any errors in the Electron console other than what you pasted? What options are you using when creating the BrowserWindow instance?

**Comment by minhho3199** [comment]
- I used the almost the same webPreferences as jitsi-meet-electron:
`webPreferences: {
      enableBlinkFeatures: 'RTCInsertableStreams',
      nodeIntegration: true, // I set it to false and it is still not working
      enableRemoteModule: true,
      plugins: true,
      autoplayPolicy: 'no-user-gesture-required',
      allowRunningInsecureContent: true,
      nativeWindowOpen: true,
      // webSecurity: false,
}`

- When webSecurity is set to true, sometimes I got `Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.`. Not sure about this one
- When checking the console of jitsi-meet-electron, right after I clicked Screen Sharing screen, a message `Using the new gUM flow` was followed by a warning about `@atlaskit/modal-dialog`
- When I checking the console of my app, a message `Using the new gUM flow` was followed by `2020-10-08T09:18:32.551Z [modules/RTC/ScreenObtainer.js] <Object.obtainScreenFromGetDisplayMedia>:  Using getDisplayMedia for screen sharing` and then come the errors
- I  also tried to modify this app by deleting Screen Capturing initialization but it still at least shows a choosing modal, unlike my setup

**Comment by saghul** [comment]
>  Using getDisplayMedia for screen sharing

This doesn't sound right. I'm not getting that on this app. Are you modifying the UA string?

**Comment by minhho3199** [comment]
Ah yes I did since there was a problem with Google Login that required me to modify the UA string. I removed that and the modal showed up correctly. Thanks a lot for that. But now it just keeps loading and I get this error `Logger.js:154 2020-10-08T12:57:31.334Z [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined`. Do you have any idea as to why?

**Comment by saghul** [comment]
Looks like something is not properly setup in the renderer.

**Comment by samtruelle** [comment]
Hello,
I am currently experiencing the same issue with the error 
020-11-24T09:22:20.380Z [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined 
as soon as i open the screen sharing window. 
@minhho3199 Have you managed to fix the renderer issues and do you have any clues on how i could do it?

I am currently using
 
- "github:jitsi/jitsi-meet-electron-utils#v2.0.7"

-  the last avaible Jitsi Meet API here : https://github.com/jitsi/jitsi-meet/blob/5a934c071a5cbe64de275a25d0ed62d8193cdd03/doc/api.md 

- "electron": "~8.1.1"

Thank you

**Comment by gimre** [comment]
I think @saghul is referring to this part of the jitsi-meet-electron-utils readme:
```
const {
    setupScreenSharingRender
} = require("jitsi-meet-electron-utils");

// api - The Jitsi Meet iframe api object.
setupScreenSharingRender(api);
```
