### ISSUE TITLE
JitsiMeetExternalAPI not working. 

### ISSUE THREAD

**Issue by behzadhaghgoo** [jitsi/jitsi-meet-electron#457]
I have been using JitsiMeetExternalAPI for creating calls in an electron app for the past month and since October 14th it has suddenly stopped working. I am getting the following error when JitsiMeetExternalAPI is called:
```
[1] [17937:1017/231347.020741:ERROR:render_process_host_impl.cc(5010)] Terminating render process for bad Mojo message: Received bad user message: Origins are not matching, or some cannot access service worker.
[1] [17937:1017/231347.021379:ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
```
Would love to know if you have any advice on what has changed recently. I am using 'meet.jit.si' for the domain.

**Comment by damencho** [comment]
Are you sourcing the external API fro meet.jit.si?

**Comment by behzadhaghgoo** [comment]
I'm using an external_api.js similar to https://github.com/jitsi/jitsi-meet-electron/blob/master/app/features/conference/external_api.js

**Comment by damencho** [comment]
Does it work if you use this one: http://meet.jit.si/external_api.js ? 
@saghul Is there a reason to embed the external API and not source it?

**Comment by behzadhaghgoo** [comment]
I get the same error when using http://meet.jit.si/external_api.js

**Comment by saghul** [comment]
This is an error in meet.jit.si which was fixed a bit ago and is pending a release, sorry about that 😢 

> Is there a reason to embed the external API and not source it?

Security. We don't want to `eval` that code.

**Comment by behzadhaghgoo** [comment]
Oh I see! Do you have an ETA for the release?

**Comment by saghul** [comment]
@behzadhaghgoo It has been released already. Cheers!
