### ISSUE TITLE
Screenshare glitches

### ISSUE THREAD

**Issue by chref** [jitsi/jitsi-meet-electron#458]
## Description
---
We are observing the same problem as described in https://github.com/jitsi/jitsi-meet/issues/7754 with JME versions 2.4.0 and 2.4.2. The problem does not occur with JME version 2.4.1.

## Current behavior
---
Screenshare content jitters between crisp and blurry, especially along hard contrast lines (e.g. black text on white background). The problem seems to be caused on the receiver side, i.e. in the same session, one receiver using JME 2.4.1 will see a stable picture, while another receiver using version 2.4.2 will see jitter. The version used by the sender does not seem to be relevant.

## Expected Behavior
---
Stable and crisp image.

## Possible Solution
---
Since the above mentioned issue 7754 reports that the problem also occurs on Chromium, is it possible that the problem lies in Electron 10?

## Steps to reproduce
---
Share a window via JME, e.g. a text editor or a terminal.

# Environment details
---
We use CentOS 8 as platform. Wayland or X11 session does not seem to make a difference. However, we were not able to reproduce the jitter problem with JME on Windows 10.
We tried both meet.jit.si as well as our private instance, the problem occurs on both.

**Comment by saghul** [comment]
> Since the above mentioned issue 7754 reports that the problem also occurs on Chromium, is it possible that the problem lies in Electron 10?

It would my guess yeah, that the Chromium version is the problem here.

**Comment by madmath03** [comment]
Different issue but probably related to Chromium version, but since 2.4.2 I got JME stuck in fullscreen.

Menu does not nothing, no error in developer console and JME even restarts in fullscreen 😕

**Comment by jeremiah-k** [comment]
I had the same problem.  Launching it with --disable-gpu fixed it for me.

**Comment by saghul** [comment]
Interesting. @jallamsetty1 FYI

**Comment by jallamsetty1** [comment]
Thanks @saghul, yep we have been asking users to disable hardware acceleration on windows to fix this issue.

**Comment by saghul** [comment]
Do you think it would make sense to set that command line argument by default (on Windows only) for now?

**Comment by jallamsetty1** [comment]
The issue was fixed here - https://github.com/jitsi/jitsi-meet-electron/commit/f3481522429fbfe18007e9082334fc56555323a9

**Comment by chref** [comment]
Umm, I'm sorry, but I reported this problem for CentOS 8, i.e. Linux, not Windows. So I don't think that this fixes it.

**Comment by jeremiah-k** [comment]
Did you try it?  I found that using that option fixed it for me running the flatpak in Linux Mint.

**Comment by jallamsetty1** [comment]
> Still, would you then perhaps consider adding the disable-gpu switch by default not only on win32, but also for Linux?

Will you be able to add  'disable-webrtc-hw-encoding' and 'disable-webrtc-hw-decoding' instead of 'disable-gpu' and see if that fixes the issue ? If it indeed fixes it, can you also please let us know what kind of an impact it has on the overall cpu load ? I don't have a Linux machine to test, greatly appreciate your help.

**Comment by chref** [comment]
> Will you be able to add 'disable-webrtc-hw-encoding' and 'disable-webrtc-hw-decoding' instead of 'disable-gpu' and see if that fixes the issue ? If it indeed fixes it, can you also please let us know what kind of an impact it has on the overall cpu load ? I don't have a Linux machine to test, greatly appreciate your help.

Yes, I just tried this: `./jitsi-meet-x86_64.AppImage --disable-webrtc-hw-encoding --disable-webrtc-hw-decoding`
Unfortunately, these options don't help, i.e. the screen jitter remains.

**Comment by jallamsetty1** [comment]
> > Will you be able to add 'disable-webrtc-hw-encoding' and 'disable-webrtc-hw-decoding' instead of 'disable-gpu' and see if that fixes the issue ? If it indeed fixes it, can you also please let us know what kind of an impact it has on the overall cpu load ? I don't have a Linux machine to test, greatly appreciate your help.
> 
> Yes, I just tried this: `./jitsi-meet-x86_64.AppImage --disable-webrtc-hw-encoding --disable-webrtc-hw-decoding`
> Unfortunately, these options don't help, i.e. the screen jitter remains.

Thanks for testing, will add the disable-gpu switch on all platforms.
