### ISSUE TITLE
Windows compiled app - changing default backround color

### ISSUE THREAD

**Issue by kokotko1337** [jitsi/jitsi-meet-electron#460]
I would like to ask, if it possible to change color of background in precompiled windows app.

I found JSON where is Server, Nick name etc, stored, but i can not find where is background color defined.

Thanks for the feedback.

thanks!

**Comment by saghul** [comment]
It's not currently changeable, sorry.

**Comment by kokotko1337** [comment]
ok, much thanks for answer
