### ISSUE TITLE
"npm install jitsi-meet-electron-utils --force" no longer valid?

### ISSUE THREAD

**Issue by fremzy** [jitsi/jitsi-meet-electron#461]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Trying to build with "npm install jitsi-meet-electron-utils --force" fails with error 

## Current behavior
"npm install jitsi-meet-electron-utils --force" fails with error 

## Expected Behavior
"npm install jitsi-meet-electron-utils --force" should build local copy of jitsi-meet-electron-utils

## Possible Solution
None

## Steps to reproduce
- Clone jitsi-meet-electron
- Clone jitsi-meet-electron-utils
- Change jitsi-meet-electron-utils default dependency path to local file path
- Run "npm install jitsi-meet-electron-utils --force"
---
# Environment details
Mac OS X - 10.13.6
Node version - 15.0.1
Npm Version - 7.0.3

These steps worked for me flawlessly in the past. Updated Node js as required in this latest release of jitsi-meet-electron, yet having problems. Was able to compile successfully in Windows.

**Comment by saghul** [comment]
I generally favor using `install-local`, which avoids having to modify package.json in order to test your changes: https://www.npmjs.com/package/install-local

**Comment by fremzy** [comment]
So, clone utils as usual and just run `install-local` instead of `npm install jitsi-meet-electron-utils --force`?

**Comment by saghul** [comment]
Close. While in the jitsi-meet-electron repo, `install-local ../your-custom-electron-utils`

**Comment by fremzy** [comment]
My man! 👊🏾

That worked! Thanks so much!

One quick question: is there a way to confirm it's actually using my custom utils?

**Comment by saghul** [comment]
Glad that worked! 

> One quick question: is there a way to confirm it's actually using my custom utils?

Not sure, check if your custom behavior works I guess?

**Comment by fremzy** [comment]
Okay, thanks again!

**Comment by fremzy** [comment]
Sorry to revive an old (and closed issue) @saghul, but this doesn't quite seem to work for me on Mac. Windows works fine (always has), but Mac builds somehow don't take my local electron-utils. I've tried running "npm install custom-electron-utils --force" as originally stated, no luck. I've tried install-local ../custom-electron-utils, no luck. In both instances, tried with the absolute path, tried with relative path, nothing worked. The app is built, but it appears to still maintain a primary link to the git repository. Any ideas what I may be missing?  😔

**Comment by csett86** [comment]
I understand your pain (and I had the same issues), as a workaround I usually apply the following: 

1. Fork jitsi-meet-electron-utils and bump version in its package.json (to avoid that electron-builder fetches and uses prebuilds of jitsi-meet-electron-utils)
2. Commit and push changes in jitsi-meet-electron-utils to a fork and a work branch
3. Set the dependency in the package.json to that repo and the commit sha1 (eg. github:csett86/jitsi-meet-electron-utils#8453ca283d595ed30ca3398d36815b796ade159d)
4. npm install

Yes, this is cumbersome, as every change in the utils needs to be committed, pushed and then the sha1 updated and npm-installed, but it at least works reliably.

**Comment by fremzy** [comment]
I just need it to stop calling back to the Jitsi git repo. Again, it works perfectly for Windows, but the Mac version has been a pain in the behind. I'm not really making any customizations to electron-utils, just don't need it prompting users to update whenever there's an update in the jitsi repo. 😕

**Comment by csett86** [comment]
@fremzy Ok, this sounds like two completely different issues here:

This issue here was (from my understanding) how to use a local (modified) copy of jitsi-meet-electron-utils when building jitsi-meet-electron. But if you dont want to modify the utils, then no need to do that.

What you now describe seems to me like #452, where users of your build get the upstream version installed every time an upstream release. Fortunately you can fix this easily by changing the `repository.url` parameter in your forks `package.json` before building: https://github.com/jitsi/jitsi-meet-electron/blob/master/package.json#L105

I did the same in my dev / testing version: https://github.com/csett86/jitsi-meet-electron/blob/main/package.json#L102

**Comment by fremzy** [comment]
@csett86 It's actually both. I'm working on a few deployments. On one, I'm making some slight modifications to electron-utils and that's what prompted this thread originally and the recent resurgence. I'm able to push my changes to the Windows electron app using my custom utils (and keep them), but haven't had much success doing the same for the Mac app.

But I also started seeing this prompt to upgrade (only on the Mac app) and that's what I mentioned in my last post. Your response helps a ton though - it's helped me to make a clear distinction between the driver behind each action (I wasn't thinking of them as distinct and separate). So, yeah for the lesser issue, changing the repository url is the solution - and this takes care of one of my deployments (no custom electron-utils). Thanks!

I'll keep looking for an 'easy' way to keep my custom utils linked to my electron build for the other deployments.

Thanks so much for your help!

**Comment by fremzy** [comment]
@csett86 or @saghul quick question: where can I find the system requirements for building the latest version? I'm able to debug, but when I try to build, I get some errors. I'm wondering if it's something to do with requirements for building the latest release.

**Comment by csett86** [comment]
@fremzy System requirements for building the latest version on windows and linux are unchanged for long and as documented in the readme.

For mac jitsi-meet-electron uses https://github.com/karaggeorge/mac-screen-capture-permissions which requires a macOS 11 SDK. Eg. Xcode 12.4 on macOS 10.15 or later fulfills this (and is what the CI is using to build: https://github.com/jitsi/jitsi-meet-electron/blob/master/.github/workflows/ci.yml#L43

**Comment by fremzy** [comment]
> For mac jitsi-meet-electron uses https://github.com/karaggeorge/mac-screen-capture-permissions which requires a macOS 11 SDK. Eg. Xcode 12.4 on macOS 10.15 or later

Thanks @csett86. That explains it all. I was getting errors around mac screen capture, trying to build on OSX 10.13.

**Comment by csett86** [comment]
@fremzy Glad that i could help. Also an fyi why this is not documented in the readme: The dependency to mac-screen-capture-permissions is on its way out anyway: https://github.com/jitsi/jitsi-meet-electron-utils/pull/119

If you don't need the (disabled) remotecontrol module from jitsi-meet-electron-utils, you can temporarily switch to https://github.com/csett86/jitsi-meet-electron-utils. That does not have any native code dependencies, so it should be buildable on OSX 10.13 as well.

**Comment by fremzy** [comment]
@csett86 Thanks for that. Will definitely look into it.
