### ISSUE TITLE
Portable (Windows) Version?

### ISSUE THREAD

**Issue by hoasis2** [jitsi/jitsi-meet-electron#462]
Is there a portable Windows version somewhere which is storing all the files and settings within the program folder?

Cheers

**Comment by saghul** [comment]
Nope, sorry. The settings are stored in the user profile folder.

**Comment by hoasis2** [comment]
I see, thanks for the answer.

If someone else is interested in a portable version, please [vote](https://github.com/portapps/portapps/issues/120) for it.
