### ISSUE TITLE
FeatureRequest: save username and password for organisator

### ISSUE THREAD

**Issue by mks-85** [jitsi/jitsi-meet-electron#464]
Hi there,

we host our own jitsi instance and I’m working with Jisti Meet Electron App.

In advanced settings I configured our Jisti URL.

As we only allow Meetings authorized by a organisator it would be very helfpul to configure and save the username and password of the organisator related to the configured Jitsi URL.

In a Browser like Crome or Edge Chromium it is possible to save but not in the Jitsi Meet Electron App.

**Comment by saghul** [comment]
We have no plans to implement this, sorry. You can configure session caching in Jicofo, so users will only need to re-login after that expires.
