### ISSUE TITLE
Feature Request: AppImage Update Information Embedding

### ISSUE THREAD

**Issue by Saijin-Naib** [jitsi/jitsi-meet-electron#468]
I'm trying to make more use of AppImages, and to that end, I've begun using AppImageUpdate to manage updating AppImages. However, it seems to error out with the Jitsi Meet AppImage, saying that Update Information is not embedded in the AppImage during build.

Is this possible to correct?

**Comment by saghul** [comment]
I have no idea what that is :-O We use electron-builder, if there is an easy way to achieve what you need with it, sure let's have it.

**Comment by Saijin-Naib** [comment]
https://docs.appimage.org/packaging-guide/optional/updates.html#using-electron-builder

Seems like doable, but a few extra steps/work-arounds due to how electron-builder does things.

**Comment by saghul** [comment]
I took a quick look, and that's now an avenue I'm interested in pursuing at this time, sorry. Jitsi Meet should already self-update with the builtin Electron updater, and we'll keep using that for the time being.
