### ISSUE TITLE
Stuck in full screen mode

### ISSUE THREAD

**Issue by akaihola** [jitsi/jitsi-meet-electron#471]
## Description
App goes full screen when started. Can't exit full screen mode.

## Current behavior
When starting `jitsi-meet-x86_64.AppImage`, the application goes straight into full screen mode. It's not possible to exit full screen mode in the main screen (the one with the "Enter a name for your conference or a Jitsi URL" field), nor in a call. I tried the following in both the main screen and in a call:
- the `S` key
- the `Esc` key
- the `F11` key
- right-clicking on screen
- `View full sreen` / `Exit full screen` (in the three-dots menu when in a call)

## Expected Behavior
The app should either always start in windowed mode, or exit full screen mode when the `S` shortcut or the `Exit full screen` menu option is selected.

## Steps to reproduce
I'm not sure how I ended up in this situation. Maybe I had a call in full screen mode and the app somehow got killed.

## Work-around
Manually edit `~/.config/Jitsi Meet/window-state.json` and change
```json
"isFullscreen":true
```
to
```json
"isFullScreen":false
```

# Environment details
- Fedora 30
- GNOME
- [jitsi-meet-x86_64.AppImage v2.4.2](https://github.com/jitsi/jitsi-meet-electron/releases/download/v2.4.2/jitsi-meet-x86_64.AppImage)

**Comment by raisercostin** [comment]
On my windows the windows-state was in `c:\Users\raiser\AppData\Roaming\Jitsi Meet\window-state.json`

**Comment by GitRon** [comment]
Same here. 😕 Thanks for the workaround.

**Comment by akaihola** [comment]
I created this launcher script in `~/.local/bin/jitsi` on my Linux box to automate the work-around:

```bash
#!/bin/bash

CONFIG_FILE="${HOME}/.config/Jitsi Meet/window-state.json"
TJQ=$(jq '.isFullScreen = false' < "${CONFIG_FILE}")
[[ $? == 0 ]] && echo "${TJQ}" > "${CONFIG_FILE}"
${HOME}/.local/bin/jitsi-meet-x86_64.AppImage
```
