### ISSUE TITLE
Screensharing not working on MacOS

### ISSUE THREAD

**Issue by dyros26** [jitsi/jitsi-meet-electron#472]
Screensharing not working on MacOS, its null.

![4275cef4e6e61e248af876c7e24d292182d0b9c8](https://user-images.githubusercontent.com/49423503/98824768-a3eaab00-246e-11eb-8479-0cfb932c74b1.png)

**Comment by saghul** [comment]
Are you running a release build or your own? Did you give Jitsi Meet permission to share the screen?

**Comment by dyros26** [comment]
i already found the issue on my build. JitsiMeetExternalAPI did not load correctly
