### ISSUE TITLE
Changing blue background color

### ISSUE THREAD

**Issue by timololipop** [jitsi/jitsi-meet-electron#474]
Hey,

I looked through all files to change the default blue background. I managed to change the logo, but now I'm failing with changing the background color from blue to any other color.

Also I dont find a possibility to hide the help button without deleting the related JS files. Can anyone help me out?

Thanks

//Edit: Managed to change the background color but not to remove the help icon.

**Comment by saghul** [comment]
You can remove the button from here: https://github.com/jitsi/jitsi-meet-electron/blob/ef0372eaad5f2326b5e6af580d0085dba1e3d22f/app/features/navbar/components/Navbar.js#L48
