### ISSUE TITLE
Redirecting to external site after closed call not working

### ISSUE THREAD

**Issue by frozenbanana** [jitsi/jitsi-meet-electron#475]
## Description
Redirect works using close3.html in selfhosted jitsi instance but not when using jitsi-meet-electron. Console error pointing to 
Content Security Policy directive frame-ancestors not being correctly set.

Not sure if this a bug or if I have missed something. Looking at the Jitsi forum I did not find anything of use.

Can anyone shed some light upon this issue?

## Current behavior
This works fine when using the browser. After closing a call we are directed to our form. But users using jitsi-meet-electron it is not working. We get a blank screen instead and an error message `Refused to frame 'https://our-external-site.com' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`

## Expected Behavior
To redirect to https://our-external-site.com/.../forms/123 after closing call on jitsi-meet-electron.

## Possible Solution
Adding a setting to specify frame-ancestors.

# Environment details
We have a selfhosted jitsi instance with a redirect going to an external form like so:
`/usr/share/jitsi-meet/static/close3.html` 
```html
<html>
	<head>
		    <meta http-equiv="refresh" content="0; url=https://our-external-site.com/.../forms/123" />
	</head>
</html>
```

**Comment by saghul** [comment]
Have you set any CSP policy in your server?

**Comment by csett86** [comment]
As CSP is coming from the server where your custom jisti is hosted, closing this here.
