### ISSUE TITLE
The "Give feedback" button within the Help menu does nothing

### ISSUE THREAD

**Issue by netsrotr** [jitsi/jitsi-meet-electron#477]
## Current behavior
The "Give feedback" button within the Help menu does nothing

## Expected Behavior
It should point me to the issues GitHub page, or any other Jitsi App forum site.

# Environment details
Jitsi Electron App v2.4.2

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/commit/01c2468666536496164bb4feb47161fe530a4bca
