### ISSUE TITLE
UI Menu Font issue: parts of the text is cutted out

### ISSUE THREAD

**Issue by netsrotr** [jitsi/jitsi-meet-electron#478]
## Description
If I open the (german) "Help" Menu, parts of the menu item text are cutted out (see littel red markers):

![image](https://user-images.githubusercontent.com/5443937/99228908-937b5d00-27ed-11eb-9cac-04d0ff08a949.png)

## Expected Behavior
The text should be visible completely.

## Possible Solution
Use another or smaller font for menu items

# Environment details
Jitsi Electron App v2.4.2

**Comment by csett86** [comment]
Looks fine now with v2022.6.1:

<img width="231" alt="Bildschirmfoto 2022-07-03 um 20 32 42" src="https://user-images.githubusercontent.com/1392875/177052772-e64205b3-87e8-40e8-99a7-bc6b37ba4614.png">
