### ISSUE TITLE
Screen Sharing forcing SD ?

### ISSUE THREAD

**Issue by kokotko1337** [jitsi/jitsi-meet-electron#479]
## Description
Screen sharing showing in SD but Cams in HD

Server Settings:

    resolution: 720,
     constraints: {
         video: {
             aspectRatio: 16 / 9,
            height: {
                ideal: 720,
                max: 720,
                min:720
            }
        }
     },

preferH264: true,

    testing: {
        enableFirefoxSimulcast: false,
        p2pTestMode: false

## Current behavior
All users have Cams in HD, but Screen share is SD only

## Expected Behavior
Screen Share should be HD - SD is not readable

## Possible Solution
i dont have one

## Steps to reproduce
1, Start Conference
2, all users are in HD
3, some of user try to share screen 
4, it is shown only as SD

# Environment details
OS: Ubuntu
Jitsi Server Lastest
Jitsi Electron Latest

**Comment by seppowalther** [comment]
Hmmm, I just tried to reproduce the error and it didn't occur on both of my Jitsi instances and the electron-app running on MacOS Big Sur. Neither had any issues like this on Ubuntu.
My settings on the server are looking the same.

Have you tried if the same problems occur on other Jitsi instances?
For example on meet.jit.si?

If not, the problem likely comes from your server.
