### ISSUE TITLE
Jitsi Meet is sharing your screen -> hide button not working - v2.4.2

### ISSUE THREAD

**Issue by TimmiORG** [jitsi/jitsi-meet-electron#480]
#  Description
Hello,
on my Fedora 33 with v2.4.2 the hide button on the small overlay has no effect.

## Current behavior
Hide button is not removing the overlay "Jitsi Meet is sharing your screen"

## Expected Behavior
Hide button is removing the overlay

## Steps to reproduce
1. Start a meet
2. start screenshare

# Environment details
Fedora 33
Jitsi Meet Electron 2.4.2 (latest)

Best regards
Timmi

**Comment by saghul** [comment]
Fixed in 2.5.1.
