### ISSUE TITLE
Issue with npm install

### ISSUE THREAD

**Issue by rattoo0** [jitsi/jitsi-meet-electron#486]
I'm trying to run "npm install" but node-gyp keeps crashing every time when i run npm install.
Global installed: npm@latest, windows-build-tools, node-gyp.

Below are the logs

`C:\Users\kacpe\Desktop\XXXXXX\jitsi-meet-electron>npm install

> robotjs@0.6.0 install C:\Users\kacpe\Desktop\XXXXXX\jitsi-meet-electron\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.15.1 runtime=node arch=x64 libc= platform=win32)

C:\Users\kacpe\Desktop\XXXXXX\jitsi-meet-electron\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2008, in GenerateOutput
    msvs_version)
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1843, in _CreateProjectObjects
    guid = _GetGuidOfProject(proj_path, spec)
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 910, in _GetGuidOfProject
    guid = guid or MSVSNew.MakeGuid(proj_path)
  File "C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 48, in MakeGuid
    d = hashlib.md5((str(seed) + str(name)).encode('utf-8')).hexdigest().upper()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 32: ordinal not in range(128)
gyp ERR! configure error
gyp ERR! stack Error: 'gyp' failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\kacpe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kacpe\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kacpe\Desktop\XXXXXX\jitsi-meet-electron\node_modules\robotjs
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.6.0 install: 'prebuild-install || node-gyp rebuild'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above`

**Comment by saghul** [comment]
We generally use Node 12 for building, can you try that?

**Comment by rattoo0** [comment]
Node v. 12 instead of Node v. 14? Ok, let me see.

**Comment by rattoo0** [comment]
It looks like it's working. Anyway, thanks. :)

**Comment by rattoo0** [comment]
Nah, npm install working, but npm run dist crashed.

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jitsi-meet-electron@2.4.2 dist: 'npm run build && electron-builder'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jitsi-meet-electron@2.4.2 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

When I run  'npm run build && electron-builder'; 

`'electron' is not recognized as an internal or external command,
operable program or batch file.`

I installed electron-packager globally and locally in project.

**Comment by rattoo0** [comment]
Solution: UTF-8 polish chars in folder name/path ;)
