### ISSUE TITLE
app does not start on linux (debian 10)

### ISSUE THREAD

**Issue by gabriel-tandil** [jitsi/jitsi-meet-electron#488]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
app does not start

## Current behavior
---
i got the followin error:
[15698:1201/141503.854292:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_jitsi-ptkA2Q/chrome-sandbox is owned by root and has mode 4755.

## Expected Behavior
---
The app init

## Possible Solution
---
./jitsi-meet-x86_64.AppImage --no-sandbox

## Steps to reproduce
---
./jitsi-meet-x86_64.AppImage

# Environment details
---
debian 10 xfce

**Comment by saghul** [comment]
This is a known issue and documented on the README. Different distros have different system settings and there doesn't seem to be a one size fits all.

**Comment by gabriel-tandil** [comment]
Sorry for the useless report, I missed that in the README

**Comment by saghul** [comment]
No worries!
