### ISSUE TITLE
Audio error, linux debian 10

### ISSUE THREAD

**Issue by gabriel-tandil** [jitsi/jitsi-meet-electron#489]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Audio does not working on meet

## Current behavior
---
On meet enter i got the following error
Audio Error: Could not start audio source

## Expected Behavior
---
Audio works fine

## Possible Solution
---
I have not idea

## Steps to reproduce
---
1. Enter app
2. enter to a meet

# Environment details
---
linux 64, debian 10 , xfce

**Comment by saghul** [comment]
Do you get the same behavior when using Chromium?

**Comment by gabriel-tandil** [comment]
I just tried it on chromium and it doesn't really work either. I was using it in chrome and it worked.

**Comment by saghul** [comment]
Sin electron is based on chromium, if it doesn't work on either, there is nothing we can really do.

**Comment by gabriel-tandil** [comment]
Well thank you 
:crying_cat_face: 
I will investigate on that side then.
Greetings
