### ISSUE TITLE
Can't Select Microphone on Linux

### ISSUE THREAD

**Issue by Arc676** [jitsi/jitsi-meet-electron#492]
## Description
Jitsi doesn't ask for permission to use the microphone or the webcam. However, the video feed works just fine, but I can't select the microphone. There was [this](https://community.jitsi.org/t/new-webcam-microphones-blocked-but-not-in-firefox-or-elsewhere/84001) post on the community forum, but my microphone works fine in the browser. I tried test.webrtc.org in Firefox and the microphone worked fine. I also tried joining a Jitsi meeting via Firefox and that also worked. I don't think it's an Electron issue because I also use Discord and my microphone works fine there.

This exact behavior is also described by @jrie in #333. I thought I'd open a new issue since there was no follow up in that thread, as this is not the original issue in that post. Just as described in that comment, I can't get Jitsi to use the headset microphone, but it *can* use the headset as an audio output.

## Current Behavior
If I join a meeting, under "Settings > Devices" the microphone dropdown is disabled and just says "Permission not granted." and attempts to unmute myself despite not having a microphone selected just yields an error message (see screenshots).

My headset is connected to the audio ports on the back of the motherboard. Interestingly, if I disconnect the headset and leave only the webcam connected via USB, the dropdown becomes usable and I can select the webcam's internal microphone.

## Expected Behavior
Can select microphone when headset is connected via headphone jack.

# Environment details

Electron app v2.4.2, installed via AUR package [`jitsi-meet-desktop-bin`](https://aur.archlinux.org/packages/jitsi-meet-desktop-bin/) on Arch Linux. Microphone is an external one on a Logitech G231 headset.

![error](https://user-images.githubusercontent.com/30745465/101179892-22d89b00-364b-11eb-8318-f30e6b43c47f.png)
![settings](https://user-images.githubusercontent.com/30745465/101179896-22d89b00-364b-11eb-87f6-55fcd5124a18.png)

**Comment by saghul** [comment]
Can you reproduce the problem when downloading the binary from the releases page here on GH instead of using AUR?

**Comment by Arc676** [comment]
Yes; I downloaded the `AppImage` from the latest release, added execution rights and reproduced the same behavior as shown in the two screenshots. For good measure, I also tried uninstalling the AUR version and launching the AppImage again, but with no effect.

**Comment by saghul** [comment]
You said you tested on Firefox, but did you test in Chromium?

**Comment by Arc676** [comment]
Good point, I didn't think to try that. I installed Chromium and got the same behavior as in the Electron app.

**Comment by saghul** [comment]
Cool! I'm going to close this as a "poltergeist" then :-)

**Comment by Arc676** [comment]
Sorry, that was unclear. I meant that it started working in Chromium, not in the Electron app. After selecting the microphone in Chromium settings, I could use the microphone in Jitsi in Chromium. I still can't access the microphone in the Electron app.

**Comment by saghul** [comment]
I can reopen, but there is not much I can do to help I'm afraid. It's something about your system.

**Comment by Arc676** [comment]
Thanks for the tip. I went to tinker around some more with my system audio settings and found a solution, even though I'm not sure what this does. For future visitors to this thread, here's what worked for me:

1. Open `pavucontrol`
2. Go to "Input Devices" and enable "Set as Fallback" for the desired microphone

After that, Jitsi was able to access the microphone.

Thanks for the help!
