### ISSUE TITLE
[Question] additional window optional?

### ISSUE THREAD

**Issue by AiyionPrime** [jitsi/jitsi-meet-electron#493]
Hey there,
As soon as the electron app loses focus, it opens a second window containing the current speaker, which is not what I want most of the time.
Is there any way to disable this well meant feature?

In html and react it's called the 'always on top toolbox'.

**Comment by saghul** [comment]
You can disable it in the advanced settings section.

<img width="1255" alt="Screenshot 2020-12-10 at 10 09 40" src="https://user-images.githubusercontent.com/317464/101750845-db7d5f00-3acf-11eb-968c-c2409fa8c2a1.png">

**Comment by AiyionPrime** [comment]
Awesome, thank you. Hadn't seen it, as i searched for it within a running conference.
