### ISSUE TITLE
Loud distorted noise after turning end-to-end on

### ISSUE THREAD

**Issue by majso** [jitsi/jitsi-meet-electron#495]
## Description

After enabling end-to-end encryption all participants are hearing loud distorted noise. (It can be dangerous for other participant's hearing, it is really loud)

## Expected Behavior

Other participant will be prompted to turn end-to-end on

## Possible Solution

 It would be great to mute sound for them until they will turn end-to-end on.

## Steps to reproduce

Turn on end-to-end encryption in a room with participant without end-to-end encryption turned on

# Environment details

jitsi electron 2.4.2

**Comment by saghul** [comment]
This is not electron specific, belongs in the main jitsi-meet repo, can you please reopen it there?
