### ISSUE TITLE
record screen permission MacOS?

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet-electron#496]
Hi guys,

Since updating to Catalina on MacOS I get a scary popup asking for permission for jitsi to record your screen (some wording along those lines).

Is this permission related to the remote control functionality or merely for sharing the desktop? Do we need this permission if we don't use the remote desktop feature? Any way we can remove this since it scares people from using the app?

On a slightly different topic, what's the best way to remove/disable the remote feature completey before compiling?

Thanks

**Comment by saghul** [comment]
That is only used for screen-sharing. Remote control is already disabled at compile time.

When are you seeing the pop up? Ideally you should see it when SS is used like for audio and video.

**Comment by pdarcos** [comment]
Thanks for the quick reply @saghul 

I believe the popup showed up right after installation but my memory could be playing tricks on me.

It makes sense to only ask for that permission the first time we try to share the screen so you're probably right.

I will reinstall again to confirm that is what's happening indeed.

**Comment by saghul** [comment]
This is now solved on 2.7.0 when running on Big Sur. If running on earlier versions the prompt will be shown because there is no way to check for the permission than to ask for it.
