### ISSUE TITLE
Add calendar integration

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#50]
Integrate with Google Calendar / Office 365 / system calendars on macOS (?). Design is TBD, but using a separate drawer for this is a possibility.

Alternatives if using web APIs directly is a no-go:

- https://www.cronofy.com/

**Comment by Echolon** [comment]
related: #4719 #5412

**Comment by saghul** [comment]
We either embed the welcome page or things shall remain as they currently are.
