### ISSUE TITLE
FeatureRequest: UI for switching rooms

### ISSUE THREAD

**Issue by kalvinwang** [jitsi/jitsi-meet-electron#501]
Since there aren't breakout rooms, we create separate Jitsi rooms for people to switch to, but anyone using the Electron app has to quit, restart, then join the new room. It would be great to have UI for switching to a different room/URL. Thanks for considering!

**Comment by saghul** [comment]
We have no plans to extend the app to support this, sorry.

Note that deep-linking should work and join the new meeting, or you can hangup and choose a different one from the recents list.
