### ISSUE TITLE
Jitsi Meet Electron Client Screenshare with Audio Causes Participants to hear echo

### ISSUE THREAD

**Issue by barisinanc** [jitsi/jitsi-meet-electron#502]
## Description
---
We are using the desktop sharing feature of the Jitsi Meet client on our demos. Some of our demos require to share audio of our application. When we share the desktop with audio on jitsi meet electron client participants start to hear their own voice. This problem occurs both on the public jitsi server (meet.jit.si) and on our private jitsi deployment.

## Current behavior
---
When screen share enabled with audio participant sounds echoing back to themselves.

## Expected Behavior
---
Only system sounds should be broadcasted to the conference.

## Possible Solution
---
Behaviour should be converted as same as chrome web client.

## Steps to reproduce
---
1- Login to a conference via Jitsi Meet Electron
2- Share screen with audio
3- Another participant starts to talk. (As a result, hears themself)

# Environment details
---
Windows 10
Jitsi Meet Electron 2.4.2
meet.jit.si public server

**Comment by saghul** [comment]
When sharing audio with the screen the entire system audio is sent over. This is a platform limitation in Chromium alas, and nothing we can act upon.

**Comment by barisinanc** [comment]
Electron based Discord or Microsoft Teams applications can capture desktop sound without participant sounds. Maybe we can investigate on this point.
