### ISSUE TITLE
Exec problem in Plasma KDE

### ISSUE THREAD

**Issue by LinuxCuba** [jitsi/jitsi-meet-electron#507]
## Description
---
./jitsi-meet-x86_64.AppImage --no-sandbox

## Current behavior
---
./jitsi-meet-x86_64.AppImage --no-sandbox
(electron) 'allowRendererProcessReuse' is deprecated and will be removed.
12:57:25.811 › Checking for update
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
12:57:27.842 › Update for version 2.4.2 is not available (latest version: 2.4.2, downgrade is disallowed).
12:57:27.842 › checkForUpdatesAndNotify called, downloadPromise is null
## Expected Behavior
---
./jitsi-meet-x86_64.AppImage
[388112:0120/115719.721297:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_jitsi-YiaJcp/chrome-sandbox is owned by root and has mode 4755.
`trap' para punto de parada/seguimiento (`core' generado)

# Environment details
---
KaOS (2021) Kernel: 5.10.6 KDE Plasma 5.20.5 KDE Framawork: 5.78.0 QT: 5.15.6

**Comment by saghul** [comment]
Not sure I understand what the problem is, can you elaborate?

**Comment by saghul** [comment]
See https://github.com/jitsi/jitsi-meet-electron/issues/231
