### ISSUE TITLE
Integrate with meet.jit.si via deep-linking

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#51]

**Comment by greveritt** [comment]
I'd also really like this. This feature would make it far more convenient to join meetings linked to in Google Calendar, which is one of the workflows that people would expect from a Zoom replacement.

As a user, I would like it if there were a way to prevent Firefox users from accidentally joining meetings through the browser and affecting call quality. That, or full Firefox support would be nice.

Regardless of whether or not you end up doing this, I appreciate that you have made this product, which so far seems to handle all the essential features of Zoom for my business purposes. Thanks again!

**Comment by saghul** [comment]
We now have a custom protocol scheme, which works for any domain.
