### ISSUE TITLE
Roomnames with Backslash not supported

### ISSUE THREAD

**Issue by sandos187** [jitsi/jitsi-meet-electron#512]
## Description
When we plan a conference, we organize the rooms in the following scheme:

https://meet.jit.si/conferencename
https://meet.jit.si/conferencename/slot1
https://meet.jit.si/conferencename/slot2
etc.

## Current behavior
In a Webbrowser this works just fine. In electron app we just get a black (dark grey) screen, with no chance to go back or anything. Only option is to restart the app

## Expected Behavior
The App should just behave like the Webbrowser Version

## Solution
Either electron app supports those links, just like a webbrowser, or at least there should be the possibility to change back to the main screen instead of restarting the app.

## Steps to reproduce
Try to open https://meet.jit.si/conferencename/slot1 (conferencename/slot1 as the room name)

# Environment details
macos 11.1
safari 14.0.2 (works)
chromium 88.0.4324.104 (works)
jitsi-meet 2.4.2 (produces the explained behaviour

**Comment by damencho** [comment]
Actually, the conference name is slot1 and you are using a tenant(is what we call it or subdomain) named conferencename.

**Comment by csett86** [comment]
tenants / subdomains are supported by v2022.6.1, thus closing as fixed.
