### ISSUE TITLE
Jitsi subdirectory installations are not supported

### ISSUE THREAD

**Issue by outis151** [jitsi/jitsi-meet-electron#514]
### Description:
When jitsi is installed at `http://example.com/meet/` the electron app hangs and fails to connect. 
The installations works flawlessly over the browser.

### Server information:

- Jitsi Meet version: docker-jitsi-meet stable-5390-3
- Operating System: Debian 10 / Linux

### Client information:

- App version: jitsi-meet-electron 2.4.2
- Operating System: Windows 10

**Comment by csett86** [comment]
Jitsi subdomain / subdirectory installations are supported with v2022.6.1, thus closing this as fixed.
