### ISSUE TITLE
Audio Error. Microphone not found.

### ISSUE THREAD

**Issue by HansGatu** [jitsi/jitsi-meet-electron#517]
I am using Manjaro Linux and I just installed **jitsi-meet-desktop-bin 2.4.2-1** powered by Electron from AUR.
The program starts and works, but an error message tells me that it cannot find the microphone.
I use a Logitech QuickCam Pro 9000, that works perfectly well with Zoom.
What is wrong. How can I solve this?

/ Hans Gatu

**Comment by saghul** [comment]
Does it work with Chrome / Chromium?

**Comment by HansGatu** [comment]
No, same problem in Chrome and Chromium.
Just now, minutes ago, I upgraded the application to **2.5.1-1**
and it got even worse, because now the camera doesn't start either.
So, both audio and video errors now.

/ Hans Gatu

**Comment by HansGatu** [comment]
So, what is wrong then?
Video works in Chrome and Chromium, but not audio.
Video worked in the 2.4.2-1 version of the application, but not audio.
Neither works now in 2.5.1-1.

/ Hans Gatu

**Comment by saghul** [comment]
I don't know. Audio not working is a Chrome engine problem, we cannot access a device we cannot see.

Regarding video, what Chrome version did you test? You cannot enable devtools in the electron app with the same shortcut as in Chrome and share check the console output.

**Comment by HansGatu** [comment]
Terminal:

$ jitsi-meet-electron
(electron) 'allowRendererProcessReuse' is deprecated and will be removed.
05:59:39.268 › APPIMAGE env is not defined, current application is not an AppImage
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.


/ Hans Gatu

**Comment by saghul** [comment]
Can you try the AppImage directly from the releases page here on GitHub instead of the AUR package?

**Comment by HansGatu** [comment]
When I run the AppImage, the video works.
But the audio error is still there.

/ Hans Gatu

**Comment by saghul** [comment]
Good to know. Since you have the audio problem with Chrome itself, there is nothing we can do here, sorry.
