### ISSUE TITLE
Fails to run on Big Sur - "unidentified developer"

### ISSUE THREAD

**Issue by pdarcos** [jitsi/jitsi-meet-electron#518]
Hi everyone,

Yesterday I compiled the app, signed and notarized it for Mac just as I had done in the past.

The app runs fine on Catalina, but when I try to run it in Big Sur I get the dreaded "unidentified developer" warning and the only way to run it is the old control-click-to-open trick.

The .app and the .dmg are signed and notarized but for some reason Big Sur thinks otherwise....

Anyone else experiencing this? Any thoughts on how to fix this in Big Sur?

Thanks

**Comment by saghul** [comment]
Maybe it's the binary used for checking the screen-sharing permissions. That package got refactored and I hope we can update to a version that doesn't depend on a binary that needs extra signing soon.

**Comment by pdarcos** [comment]
Thanks for the update @saghul 

I ended up using https://github.com/csett86/jitsi-meet-electron and I now have it working on Big Sur.

Cheers

**Comment by saghul** [comment]
2.7.0 is out and contains the updated screen-sharing permissions package.
