### ISSUE TITLE
[2.5.1] Fedora 33 App Icon not shown

### ISSUE THREAD

**Issue by TimmiORG** [jitsi/jitsi-meet-electron#519]
Hi,
please note that the App Icon is not shown on Fedora 33 and release 2.5.1
![grafik](https://user-images.githubusercontent.com/979342/108854264-f7c96c00-75e7-11eb-982d-3bfdd9b8fe36.png)

Best regards
Christoph

**Comment by TimmiORG** [comment]
Same in 2.6.0

**Comment by saghul** [comment]
Looks like a bug / limitation on electron-builder: https://github.com/electron-userland/electron-builder/issues/4617

Nothing we can do on our end though. We'll keep updating our dependencies and hope it eventually gets resolved.
