### ISSUE TITLE
Unable to copy meeting link to clipboard.

### ISSUE THREAD

**Issue by DillFrescott** [jitsi/jitsi-meet-electron#522]
## Description

When I click on the copy meeting link button, it turns green and says copied to clipboard, but never actually copies the link to the clipboard.
---

## Current behavior

When I click on the copy meeting link button, it turns green and says copied to clipboard, but never actually copies the link to the clipboard.
---

## Expected Behavior

It should copy the link to the clipboard.
---

## Possible Solution

Not sure, but when I test the button using a browser instance (Firefox) it copies just fine via the button.
---

## Steps to reproduce

1. Start meeting in the newest version of Jitsi Meet Electron client.
2. Click the "copy meeting link" button.
3. try to paste the link. It won't work.
---

# Environment details
Jitsi Meet Electron v 2.5.1 on Windows 10 x64

Jitsi Meet running on Ubuntu 20.04 unstable branch version 4734.

---

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues.

This is known and was a bug in jitsi-meet project which was fixed today upstream and on meet.jit.si. https://github.com/jitsi/jitsi-meet/pull/8677

**Comment by DillFrescott** [comment]
@damencho Sorry

**Comment by damencho** [comment]
NP.
