### ISSUE TITLE
If more than 2 user joins a session in V2.51 the screen gets black for all

### ISSUE THREAD

**Issue by Fiege** [jitsi/jitsi-meet-electron#524]
When more than two people are joining a room, the screen gets black for all

## Current behavior
It worked before 2.51

## Expected Behavior
Joining possible.

Hint: Downgrading to 2.4x works.

**Comment by saghul** [comment]
Are you using meet.jit.si or your own deployment?

What do you see in the JS console? You can open it with the same keyboard shortcut as in Chrome.

**Comment by Fiege** [comment]
Server running on site in docker.
Server is unchanged, except reboot.
All clients updated here, after that the issue occured.

Meanwhile we rolled back the clients to 2.4x and blocked the upgrade.

We did another test, three clients with older versions work. Everybody sees everybody.
One 2.51 client joined the meeting, result was: The 2.51 client got a black screen, didn't showe the video from any other user.
Cought the log from JS console, but can't post it here because it contains personal data. 
If you provide a pm, I will send it.

BR

**Comment by saghul** [comment]
GH username @ jitsi dot org.

**Comment by saghul** [comment]
FTR: I cannot reproduce this.

**Comment by Fiege** [comment]
Good moning.
The issue was gone after updating the server to the latest build.
I think you should close the ticket.
I will send you the log file anyway.

BR
Ulrich

**Comment by saghul** [comment]
Good to hear!
