### ISSUE TITLE
The bundled external API doesn't allow clipboard-write

### ISSUE THREAD

**Issue by ananace** [jitsi/jitsi-meet-electron#527]
## Description
The [bundled external api](https://github.com/jitsi/jitsi-meet-electron/blob/master/app/features/conference/external_api.js) doesn't allow writing to clipboard on the created iframe for hosting a conference.

## Current behavior
Excerpt from the bundled file;
`this._frame.allow="camera; microphone; display-capture"`

## Expected Behavior
Expect the allow list to include `clipboard-write`, like in the upstream external API;
https://github.com/jitsi/jitsi-meet/blob/master/modules/API/external/external_api.js#L323

## Possible Solution
Update the bundled external API

**Comment by saghul** [comment]
Thanks for the heads up. This is only a problem with the latest unstable right? The current Jitsi Meet stable release does not use the clipboard API.

**Comment by ananace** [comment]
Seems to have changed with https://github.com/jitsi/jitsi-meet/commit/87a110b9c30f9e74ae630ea66922e0bac3b2ce15 - which I don't think has been part of a stable release yet.
