### ISSUE TITLE
macOS Yosemite (10.10) no longer supported by Jitsi Meet.app? 

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#533]
Initially posted [on the community site](https://community.jitsi.org/t/macos-yosemite-10-10-no-longer-supported-by-jitsi-meet-app/95394)

Jitsi Meet 2.4.2 works.

Jitsi Meet 2.7.0 has a “forbidden” overlay on the icon.

Minimum required version of macOS should be clearly stated. (Maximum Jitsi Meet version supporting previous versions of macOS should be noted as well.)

What I’m looking for right now is a link to the latest Jitsi Meet that will work on my macOS Yosemite (10.10).

-----

For others who may find this -- having downloaded all the `.dmg` files for each release going back from [2.7.0](https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2.7.0) -- [2.5.1](https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2.5.1) is the latest that doesn't have the "forbidden" icon overlay.

**Comment by saghul** [comment]
We don't specify a minimum supported version so it must have been a dependency.

On our mobile apps we have an unwritten rule of supporting the last 3 major releases, so applying that here that would be 10.14 or higher.

If supporting lower versions can be accomplished with low effort sure let's have it, but it's not a goal of this project.

A PR restoring support for older versions would be acceptable if it's not too involved.
