### ISSUE TITLE
Jitsi alters room titles

### ISSUE THREAD

**Issue by dchmelik** [jitsi/jitsi-meet-electron#538]
## Description

Jitsi alters room titles.

## Current behavior

Jitsi alters room titles.  I created one called EFnet Spirituality.  It wrongly renamed it: E Fnet Spirituality.

## Expected Behavior

Don't alter titles.

## Possible Solution

Update the code

## Steps to reproduce

Create a room with an acronym with capital letter by another capital letter.

# Environment details

Slackware64-current

**Comment by saghul** [comment]
The room name is not changed. We just render it with some heuristics to try to make it more readable.

**Comment by dchmelik** [comment]
It's changed and wrong.  [EFnet](http://efnet.org) is one word

**Comment by saghul** [comment]
It's not changed. Room names are case insensitive, so it's just how we render it. We can't accommodate all possible capitalizations, we just try to render something useful. Alas it's not perfect, as this case, but that's a compromise we take.

**Comment by dchmelik** [comment]
It's changed for readers: confusing.

**Comment by altsalt** [comment]
This is also an issue for a conference I organize, SeaGL. It has long been an annoyance and I'm glad that someone linked me to this issue.
