### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by ItchyBugReporter** [jitsi/jitsi-meet-electron#539]
When launching versions 2.6.0, 2.6.1, 2.7.0 or 2.7.1, I get a blank white window with nothing displayed other than a title bar. This does *not* affect 2.5.1 or older, which correctly displays the blue screen asking me to join a meeting. I am using the AppImage to run Jitsi Meet on Debian 10.

**Comment by saghul** [comment]
Your own deployment or meet.jit.si? Check the browser console for errors, you can open it with Ctrl Alt i

**Comment by ItchyBugReporter** [comment]
To quote my first post:

> When launching versions 2.6.0, 2.6.1, 2.7.0 or 2.7.1, I get a blank white window with nothing displayed other than a title bar.

I don't get to choose a server due to the window being completely blank.

By "browser", I am assuming you mean the Jitsi Meet app. Pressing CTRL+ALT+I within the Jitsi Meet app does not cause it to display any errors or "console" -- the window remains blank. Pressing CTRL+ALT+I in 2.5.1 (the latest version to work) has no noticeable effect.

**Comment by saghul** [comment]
You could've made your own build and change the server, that's why I asked.

Sorry, it's Ctrl + Shift + I: https://github.com/sindresorhus/electron-debug#devtools a new window will show up with DevTools. Check the console tab for errors.

**Comment by ItchyBugReporter** [comment]
I don't have much involvement in software development beyond filing bug reports (hence the "bug reporter" in my handle), so I had assumed you were referring to a new thing that had been added to choose a server that I couldn't see because of this bug. If changing the server means building the app myself, I would be completely clueless on how to do that.

Anyways, the only output in the "console" tab is a single ">" symbol.

![jitsi meet debug](https://user-images.githubusercontent.com/20482407/112241956-50a91600-8c21-11eb-8430-51c57d774484.png)

**Comment by saghul** [comment]
How weird. Can you please try this? Open a new terminal window and launch the application from there: cd path-where-you-downloaded-the-appimage && ./jitsi-meet-x86_64.AppImage --no-sandbox

**Comment by ItchyBugReporter** [comment]
I still get a blank window, with only a '>' in the console tab. However, I do get the following output in my terminal (note: this is with 2.7.1):

`[kjg@ideapad3 Downloads]$ ./jitsi-meet-2.7.1.AppImage --no-sandbox
10:17:52.719 › Checking for update
pci id for fd 21: 8086:9b21, driver (null)
i965_dri.so does not support the 0x9b21 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
pci id for fd 21: 8086:9b21, driver (null)
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
i965_dri.so does not support the 0x9b21 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
pci id for fd 21: 8086:9b21, driver (null)
i965_dri.so does not support the 0x9b21 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: i965
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
10:17:54.616 › Update for version 2.7.1 is not available (latest version: 2.7.1, downgrade is disallowed).
10:17:54.617 › checkForUpdatesAndNotify called, downloadPromise is null`

With 2.5.1 (output below), there is no mention of the intel stuff; instead, it just downloads 2.7.1 without asking. Prior to download 2.7.1, the window displays correctly and asks me to join a meeting as expect, but then the screen refuses to redraw and becomes blank after updating then switching windows.
`[kjg@ideapad3 Downloads]$ ./jitsi-meet-2.5.1.AppImage
10:21:42.066 › Checking for update
(node:14165) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
10:21:43.778 › Found version 2.7.1 (url: jitsi-meet-x86_64.AppImage)
10:21:43.780 › Downloading update from jitsi-meet-x86_64.AppImage
10:21:43.783 › updater cache dir: /home/kjg/.cache/jitsi-meet-electron-updater
10:21:44.945 › Update has already been downloaded to /home/kjg/.cache/jitsi-meet-electron-updater/pending/jitsi-meet-x86_64.AppImage).`

The graphics chip is a fairly recent Intel HD Graphics. It seems well supported in Debian 10 without any issues -- glxgears runs fine, I've been playing 3D games and using one of the OpenGL screensavers, and glxinfo gives a long list of supported features. As far as I can can tell, I have mesa fully installed, and the needed requisite libgl packages installed.

**Comment by saghul** [comment]
Try starting the application with `--no-gpu` let's see if that helps.

**Comment by ItchyBugReporter** [comment]
I still get a blank screen. Same messages related to libgl and i965 in the terminal. Still just a ">" in the console tab. That's for both 2.7.1 and the newly release 2.8.3.

**Comment by saghul** [comment]
Ah, sorry, it's --disable-gpu not what I said earlier. Try that one.

**Comment by ItchyBugReporter** [comment]
That seems to get it working. The normal screen and can join meetings. However, because it's not using the GPU, video quality is absolutely abysmal and I need to turn down the quality in the meeting just to get a decent frame rate. That, as opposed to previous versions of Jitsi Meet where I could keep the video quality on HD and have the video quality and frame rate be just fine. In addition, I still get a few Intel-related failure messages in the terminal:

`[kjg@ideapad3 Downloads]$ ./jitsi-meet-2.8.3.AppImage --disable-gpu
09:49:00.946 › Checking for update
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
(electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
jitsi-meet: intel_memman.c:38: intel_memman_init: Assertion `intel->bufmgr' failed.
09:49:02.176 › Update for version 2.8.3 is not available (latest version: 2.8.3, downgrade is disallowed).
09:49:02.177 › checkForUpdatesAndNotify called, downloadPromise is null
2021-03-29T13:52:19.761Z [AOT] <logInfo>:  [MAIN] onAlwaysOnTopWindow
2021-03-29T13:52:20.830Z [AOT] <logInfo>:  [MAIN] onAlwaysOnTopWindow
2021-03-29T13:52:20.832Z [AOT] <logInfo>:  [MAIN] getPosition
2021-03-29T13:52:20.832Z [AOT] <logInfo>:  [MAIN] getSize
2021-03-29T13:52:20.852Z [AOT] <logInfo>:  [MAIN] setAspectRatioToResizeableWindow
2021-03-29T13:52:20.853Z [AOT] <logInfo>:  [MAIN] setAspectRatioToResizeableWindow end
2021-03-29T13:52:20.853Z [AOT] <logInfo>:  [MAIN] send jitsi-always-on-to new-window
2021-03-29T13:52:20.854Z [AOT] <logInfo>:  [MAIN] onAlwaysOnTopWindow end
2021-03-29T13:52:20.877Z [AOT] <logInfo>:  [MAIN] ready-to-show
2021-03-29T13:52:20.877Z [AOT] <logInfo>:  [MAIN] ready-to-show: shoInactive
2021-03-29T13:52:20.878Z [AOT] <logInfo>:  [MAIN] ready-to-show: showInactive end
2021-03-29T14:03:48.815Z [AOT] <logInfo>:  [MAIN] onAlwaysOnTopWindow`

**Comment by saghul** [comment]
I'm afraid that has to do with Chrome (Electron is basically Chrome in disguise) so there is nothing we can do on our end to fix it. It looks like a driver problem with your GPU.
