### ISSUE TITLE
Broken Apple Silicon DMG?

### ISSUE THREAD

**Issue by TechUser7** [jitsi/jitsi-meet-electron#541]
## Description
---
The macOS app in the DMG of version 2.7.0 and 2.7.1 refused to start on my Apple Silicon MacBook Air. macOS just tells me, that "Jitsi Meet" is broken and can't be opened. The Intel version via Rosetta 2 works but uses so much battery.

## Expected Behavior
---
Jitsi Meet should launch.

## Steps to reproduce
---
Dowload jitsi-meet-arm64.dmg, copy "Jitsi Meet" to "programs". Try to start it (double click, and right click/open tested)

# Environment details
---
MacBook Air M1 (Apple Silicon), macOS 11.2.3

**Comment by saghul** [comment]
Thanks for the feedback. I have no access to an M1 device so the release was done a bit blindly. We are going to switch on universal builds for the next release, hopefully that fixes it.

**Comment by callahad** [comment]
Forcing a new adhoc signature locally allowed me to launch on my M1 MacBook Pro:

    codesign --force --deep -s - "Jitsi Meet.app"

Which I gleaned from [this blog post](https://eclecticlight.co/2019/01/17/code-signing-for-the-concerned-3-signing-an-app/) about code signing on macOS.

**Comment by TechUser7** [comment]
Yes, this also worked for me, so it's a signing problem.

**Comment by saghul** [comment]
The app is unsigned. You may need to go to the Security options to allow it to run the first time.

**Comment by saghul** [comment]
Can you show a screenshot of the dialog you see when you try to open it?

**Comment by TechUser7** [comment]
<img width="289" alt="image-broken" src="https://user-images.githubusercontent.com/80621924/112210637-3a985700-8c1b-11eb-97e7-458c0d7ca8d4.png">
Sorry, I can only provide the german version of the dialog. But it's not the "do you realy want to run it" dialog. It's the "it is broken and I will not start it". But forcing a new adhoc signature worked. I had this problem only with the M1 version and not with the Intel one. I will retry the Universal-Image when it is released.

**Comment by callahad** [comment]
Here's the equivalent American English dialog:

!["Jitsi Meet" is damaged and can't be opened. You should move it to the Trash.](https://user-images.githubusercontent.com/24193/112214133-c1970080-8c16-11eb-840c-43164d72717f.png)

If it helps at all, here's the difference between `codesign -vv` on the image straight out of the DMG, and after forcibly re-signing with an ad hoc signature:

```
$ codesign -vv /Applications/Jitsi\ Meet.app
/Applications/Jitsi Meet.app: code has no resources but signature indicates they must be present

$ codesign --force --deep -s - /Applications/Jitsi\ Meet.app
/Applications/Jitsi Meet.app: replacing existing signature

$ codesign -vv /Applications/Jitsi\ Meet.app
/Applications/Jitsi Meet.app: valid on disk
/Applications/Jitsi Meet.app: satisfies its Designated Requirement
```

**Comment by callahad** [comment]
This is resolved with 2.8.3.

Codesign reports `Jitsi Meet.app: code object is not signed at all` and the usual Right Click → Open process works as expected.

**Comment by saghul** [comment]
Great, thanks for confirming!

**Comment by TechUser7** [comment]
Works for me too, thanks.
