### ISSUE TITLE
config.enableLocalVideoFlip=true not implemented?

### ISSUE THREAD

**Issue by hadmut** [jitsi/jitsi-meet-electron#544]
Hi,
jitsi and other video chat clients use to locally show your own image horizontally flipped to mimic the behavior of a mirror and to keep your right side right and left side left,  i.e. it feels more natural. 

But it is highly annoying and drives you crazy or even makes it impossible to give a talk, when there is some text, e.g. standing in front of a chalkboard, or showing slides through a video mixer, which you can't read when text is horizontally flipped. 

There's rumors that jitsi-meet implements an optional button that can be enabled by appending  #config.enableLocalVideoFlip=true to the meeting URL, but this doesn't seem to work with this application. 

Nevertheless, since it is highly annyoing and spoils giving a talk when text is flipped, there should be some button to turn flipping on and off.

**Comment by saghul** [comment]
This exists already. Right click on your local view and you get a context menu where you can flip / unflip your local view.
