### ISSUE TITLE
'Your Default Email' button not working

### ISSUE THREAD

**Issue by bsimml** [jitsi/jitsi-meet-electron#545]
## Description
I downloaded jitsi-meet-electron and opened a meeting on meet.lit.si. I tried inviting another user with the button 'Your Default Email' but nothing is happening. All the other mail buttons are working.

## Current behavior
Button 'Your Default Email' not working.

## Expected Behavior
Button 'Your Default Email' opens default mail application.

## Steps to reproduce
Just try using 'Your Default Email' button.

# Environment details
Win 10 Pro with and without admin rights.

Is there a real problem or am i doing something wrong?
Thanks in advance for any answers

**Comment by bsimml** [comment]
Hey Guys,
I spent quite some time debugging and I think I found the mistake. 
In app/features/utils/openExternalLink.js is a RegEx checking if the link starts with https and if it doesn`t it wont open the link
 ->  'mailto:xxxx' is ignored, explaning the behavior mentioned in my original issue. 
I changed the RegEx from '/^https?:/i' to '/^(https|mailto)?:/i' and it works now.
If You have some spare time please look at it and add the fix.

**Comment by saghul** [comment]
Sounds good, would you mind sending it as a PR?

**Comment by bsimml** [comment]
https://github.com/jitsi/jitsi-meet-electron/pull/546#issue-598943067

**Comment by saghul** [comment]
PR landed!
