### ISSUE TITLE
OBS Virtual Cam not reconized by Jitsi

### ISSUE THREAD

**Issue by tigexplorer** [jitsi/jitsi-meet-electron#553]
## Description
---
OBS provide the output via a virtual cam. 

If activated, Jitsi is not able to use or select one of the cameras. Not the virtual cam and nor the other available cams.

## Current behavior
---
Jitsi reports "Could not start video source".
## Expected Behavior
---
Like VLC or Chromium (83) Jitsi may show the list of available cams for picking one.
## Possible Solution
---

## Steps to reproduce
---
Start a virtual cam, start jitsi.
# Environment details
---
ubuntu 20.4
Jitsi Electron 2.8.3
OBS 26.1.1
/usr/bin/v4l2loopback-ctl 0.6

**Comment by saghul** [comment]
What resolution is the virtual cam outputting? If it's not 720p, can you please try that?

**Comment by csett86** [comment]
@tigexplorer, can you please check if this still applies with the current release v2022.6.1?

**Comment by saghul** [comment]
<img width="1241" alt="Screenshot 2022-07-04 at 10 14 14" src="https://user-images.githubusercontent.com/317464/177112175-9dcf4069-561f-4055-b31a-180703eaeb2f.png">

I cannot repro.
