### ISSUE TITLE
Event endpointTextMessageReceived is not triggered

### ISSUE THREAD

**Issue by davidus27** [jitsi/jitsi-meet-electron#554]
## Description
I want to send data between Jitsi Meet and Electron through the endpoint message and I want to define different behaviors on both sides to the messages received. The Jitsi Meet version of the event is triggered but the Electron version is not. 

## Steps to reproduce
In the Jitsi Meet conference.js in the event ENDPOINT_MESSAGE_RECEIVED add console.log:
```
room.on(
            JitsiConferenceEvents.ENDPOINT_MESSAGE_RECEIVED,
            (...args) => {
            // some code defining sender and eventData
            
            console.log('Web version:', sender.getDisplayName(), eventData); // our code
});
```

In the Jitsi Meet Electron Conference.js add the event:
```
this._api.on('endpointTextMessageReceived', (user, eventData) => {
            console.log('Electron version: ', user.getDisplayName(), eventData);
});
```

Connect both versions to the same meeting and send data from Web version to the Electron version by:
APP.conference.sendEndpointMessage('', data);

## Current behavior
After sending data the Web version of the code is executed, not the Electron version.

## Expected Behavior
I expect the Electron version of the endpointTextMessage event to be triggered, not the Web version.

# Environment details
Latest from Jitsi Meet master on development mode on https://alpha.jitsi.net/.

**Comment by csett86** [comment]
As jitsi-meet-electron is embedding the web in an iframe for the actual conference, I am not sure how the target functionality would be possible. Thus closing this as not feasible for the moment.

If you find a way, a PR is welcome.
