### ISSUE TITLE
Choose install location

### ISSUE THREAD

**Issue by LuNeder** [jitsi/jitsi-meet-electron#557]
On Windows, once you start the installer it installs jitsi automatically. It would be great to have an option to choose the install location instead.

**Comment by saghul** [comment]
We have no plans to change the current installer. A 1 click install makes things really simple specially for those not so tech savvy.

What would pick a different location for?

**Comment by LuNeder** [comment]
I have two disks in my computer, and the C: is a small SSD. I’d choose jitsi's install location to be E:\programs\jitsi or something like that, since I use my E: disk to install programs and store personal files while the C: is just for Windows itself.

Having an option to choose install path does not make the program harder to install at all, most programs have this option and they’re completely fine

**Comment by tippyentertainment** [comment]
Create an msix or appv package from it

**Comment by saghul** [comment]
> I have two disks in my computer, and the C: is a small SSD. I’d choose jitsi's install location to be E:\programs\jitsi or something like that, since I use my E: disk to install programs and store personal files while the C: is just for Windows itself.
> 
> 
> 
> Having an option to choose install path does not make the program harder to install at all, most programs have this option and they’re completely fine

I understand this is your case, but I still think our current approach helps the majority, sorry.
