### ISSUE TITLE
callstats call every 10 seconds hangs the app on MacOS

### ISSUE THREAD

**Issue by kaymyst** [jitsi/jitsi-meet-electron#585]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
with callstats.io enabled on our server, the webclient tries to send stats every 10 seconds.
Unfortunately as it does that it hangs the app every time which makes it unusable

## Current behavior
the error in the inspector console is as follows:
VM169 callstats-ws.min.js:33 [Violation] 'setTimeout' handler took 1961ms
I am using the release version on MacOS (2.8.6). The issue does not seem to occur while running dev or on any version in Windows.

## Expected Behavior
this didn't seem to happen in earlier version 2.4.2

## Possible Solution
After asking callstats.io for help, they mention a possible issue in the electron version and to put a bug on here.

## Steps to reproduce
turn on callstats on jitsi server and use the release version of Jitsi-meet-election 2.8.6 on Macos and start a meeting 
App and camera picture will freeze every 10 secs
you can even test with 8x8 's server:
https://8x8.vc/mymeeting3987349784 for example and see the issue there when using the electron app

# Environment details
MacOs 11.3.1 for client
latest release version of jitsi 2.0.5870 on ubuntu server

**Comment by csett86** [comment]
@kaymyst thank you for the but report. I could (easily) reproduce this, and the root cause seems to be the getWiFiStats that is offered in the electron app and used by callstats.io. Profiler run below:

![freeze-wifi-stats](https://user-images.githubusercontent.com/1392875/119221833-8ff4c580-baf1-11eb-8e1d-4ad71e2f5bc0.png)

I have temporarily removed the Wifi stats in #586
