### ISSUE TITLE
Auth with JWT

### ISSUE THREAD

**Issue by timowevel03** [jitsi/jitsi-meet-electron#587]
Hello,

my Server runs with JWT auth, so my question is how I can start meetings from the app then?

Thanks.

**Comment by csett86** [comment]
@timowevel03 you can enter the full URL incl. the ?jwt=XYZ query param in the main input field. eg. https://meet.jit.si/moderated/2999cdbf5fbd82a72af3de37d3d75b749bb139e33c3de525ec928e6a92ab68da?jwt=eyJraWQ... then the JWT token will passed to the conference and JWT auth should work as expected. I tried it with the https://moderated.jitsi.net/ service that is also using JWT auth. This was introduced with https://github.com/jitsi/jitsi-meet-electron/pull/286 in the electron app.
