### ISSUE TITLE
In the jitsi meet home page (before pre-checks and before entering the room), "Enter a name for your conference or a Jitsi URL" vs room shortcuts is confusing

### ISSUE THREAD

**Issue by nekohayo** [jitsi/jitsi-meet-electron#588]
This is related to the web version, and the Jitsi Meet electron desktop app.

Over the last six months I've been testing a lot with with non-technical users, and some of the most frequent calls I get where a participant ends up in the "wrong room" is because of this screen (which I have annotated for you a bit):

![first screen confusion around room names](https://user-images.githubusercontent.com/479401/119270316-1da3e400-bbca-11eb-967c-1b2fdc2c3b2c.png)

It is NOT obvious to computer-illiterate users what the bunch of recent/frequently used rooms below actually are, and that they can just click on them. You need to add a header that very clearly and explicitly says so, otherwise they don't even think of clicking those things, even if you tell them, they keep forgetting it.

Likewise, the "Enter a name for your conference or a Jitsi URL" string at the top is extremely confusing for them too, and so is the constantly changing random names (would probably be easier if the text placeholder was a static placeholder that said "**Example room name:** TheRandomGeneratedRoomName"). I have a participant who keeps entering their own firstname in there instead of entering the room name or clicking the recently used room name, and then they wonder why they're not seeing anyone else in the room...

**Comment by nekohayo** [comment]
Thanks for that @csett86 ; I would still recommend having the additional header for the lower part to explain to people that the stuff below are shortcuts to previously used rooms that people can click to re-join, otherwise it's not obvious to non-computer-savvy people...

**Comment by csett86** [comment]
@nekohayo I merged the additional header with #591 based on your suggestion this morning.

**Comment by nekohayo** [comment]
Oops, I hadn't realized this, I had somehow clicked only one of the two links. That's wonderful, thank you!
