### ISSUE TITLE
v.2.8.6 not compatible with Debian 11 bullseye anymore

### ISSUE THREAD

**Issue by Buntbart** [jitsi/jitsi-meet-electron#596]
Thank you for Jitsi-Meet-Electron!

The current version 2.8.6 depends on libappindicator3.1 which is no longer supported in the upcoming new Debian 11 Bullseye.

See [https://lists.debian.org/debian-devel/2018/03/msg00506.html](https://lists.debian.org/debian-devel/2018/03/msg00506.html)

**Comment by csett86** [comment]
Thank you for the headsup, this is probably an upstream electron issue. I will check if eg electron 13 solves this.

**Comment by Buntbart** [comment]
I tried current version 2.8.7 which relies on electron 12.0.12 but it still depends on libappindicator3-1. 
So Jitsi-Meet-Electron still cannot be used in Debian 11.
