### ISSUE TITLE
Mute/unmute and camera on/off button statuses and actions unclear

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#601]
It's not obvious whether the strike-through means the input device _is_ off, or _will be turned_ off.  The mouseover helptext offers both "enable / disable" which is no help.

The mouseover helptext should change with the status of the device.  It would also be helpful if the icons changed color such as green when on and/or red when off.  (Switching color on mouseover *might* also be helpful.)

Jitsi Meet.app **2.8.6** on macOS El Capitan.

Also, in trying to make this report, I discovered that there is again (still?) no in-app-UI to get the version of **Jitsi Meet.app** that's in use on macOS.  There *SHOULD* be an app-menu **`About Jitsi Meet`** selection which opens a simple dialog that minimally provides the app's version info.

**Comment by csett86** [comment]
@TallTed thank you for your feedback. Unfortunately all of the UI related suggestions are for the jitsi/jitsi-meet repository, as all of the UI during a conference is loaded on demand from the queried jitsi server.

Regarding the in-app UI to get the version: When you open the Jitsi Meet.app without joining a conference, you can open a help menu with the question mark in the lower left corner which also shows you the version:

<img width="245" alt="jitsi-meet-help" src="https://user-images.githubusercontent.com/1392875/123157147-75a06580-d46a-11eb-8a0a-63f778d513a5.png">

**Comment by TallTed** [comment]
*sighs* "When you open the Jitsi Meet.app without joining a conference" so, it's not available while in a session...  This is seriously flawed UI/UX that does not measure up to that expected of all apps on macOS.

**Comment by saghul** [comment]
Why would you need to check the app version while in a meeting?

**Comment by TallTed** [comment]
> Why would you need to check the app version while in a meeting?

Not a helpful response. Still ---

1. Because some issue arose with jitsi, and participants wanted to confirm all are on same or latest version.
2. Because some issue arose with jitsi, and I wanted to report it while it was fresh in my mind, and app version is usually important in such reports.
3. Because I want to!
4. There are others.

**Comment by saghul** [comment]
I’m just trying to understand your needs.

1. 99% of the time that check is pointless because the Electron app barely has any logic in it, it loads the web app on an iframe.

2. Same as above.

3. Sure. We could add it to some “about” native menu, like most macOS apps. PRs welcome.

4. 🤷‍♀️

**Comment by TallTed** [comment]
@saghul -- 

> 99% of the time that check is pointless because the Electron app barely has any logic in it, it loads the web app on an iframe.

OK, good, then the Electron app should indicate that fact alongside its own version info, and provide some guidance about what kinds of report/complaint/compliment/issue should come to https://github.com/jitsi/jitsi-meet-electron and what should instead go to https://github.com/jitsi/jitsi-meet or https://github.com/jitsi/jitsi or ....

> PRs welcome

I hate that cop-out answer in every FOSS project out there.

Not everyone is a coder, and those who are do not code in every language.

> 4. 🤷‍♀️

Note that emoji are remarkably platform specific.  I just see 2 boxes.  On the other hand, ASCII emoticons are fully portable and render fine everywhere.  :-)

**Comment by csett86** [comment]
As stated previously, thank you for your suggestions. As this is nothing that can be solved in the app, closing it here.
