### ISSUE TITLE
Mac version keeps asking microphone and camera permissions albeit they're already given consent

### ISSUE THREAD

**Issue by jk** [jitsi/jitsi-meet-electron#611]
## Description
The mac desktop client on an M1 mac / macOS Big Sur asks for microphone and camera permission, ableit both are already given consent and are visible under System Preferences → Security & Privacy → Camera / Microphone.

I already removed `"~/Library/Application Support/Jitsi Meet"`, but it didn't solve the issue.

## Current behavior
When joing a conference room  it first asks for microphone permissions even when I joining the room muted. It doesn't ask for camera permission when joining the room. Later when I activate the camera it also asks for camera permission. After turning the camera off and back on again, it asks for camera permissions again. It don't ask again for mircophone permission though.

Although it re-asks for microphone permission after leaving the room and re-enter the same (or any other) room again.

## Expected Behavior
Since I already gave consent for both mircophone and camera permissions and that's visible in System Preferences, I expected, I don't get asked for permissions again.

# Environment details
* MacBook Air M1
* macOS Big Sur (11.4 20F71)
* Jitsi Meet Desktop 2.8.8

**Comment by pixlwave** [comment]
I'm seeing the same on an M1 MacBook Pro. Have tried
```
tccutil reset Camera
tccutil reset Microphone
```
but with no change.

**Comment by csett86** [comment]
I am not seeing this behaviour with a signed and notarized version, eg https://github.com/csett86/jitsi-meet-electron, so I suggest that #581 should solve this issue.

**Comment by jk** [comment]
I can confirm that it works with the signed fork. So hopefully we see an official signed version soon.

**Comment by csett86** [comment]
Latest release 2021.11.1 is now signed and notarized, so this should be a thing of the past, thus closing.
