### ISSUE TITLE
Video not working on Fedora Wayland Gnome

### ISSUE THREAD

**Issue by ilippert** [jitsi/jitsi-meet-electron#612]
## Description
Running the app on Wayland Linux Fedora, Video does not work

## Current behavior
App reports it cannot access video

## Expected Behavior
app should ask for access to video in a way that is compatible to gnome running on Wayland.

# Environment details
running the app on fedora 5.12.15-300.fc34.x86_64

**Comment by vchernin** [comment]
Can you specify what you mean by video? Seeing each other's video and screen sharing should work out of the box as of the latest updates, it does for me on Fedora 34 wayland.

Also try [Flatpak](https://flathub.org/apps/details/org.jitsi.jitsi-meet) as that works well for me on Fedora. Maybe try reproducing this in Firefox as well.

**Comment by ilippert** [comment]
I apologise. Seems to work now. Cannot reproduce.
