### ISSUE TITLE
via WEB OK, meet-electron blocks Ports

### ISSUE THREAD

**Issue by FelipeEsBr** [jitsi/jitsi-meet-electron#615]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior
---

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
---

**Comment by FelipeEsBr** [comment]
Sorry first time
When we connect from outside via web (e.g. https://meet.company.org) it works but if we use the jitsi-meet-electron the firewall of the Windows PC blocks. (Port 5353 UDP)
Dont find anything about this specific port. 
Which outgoing Ports have to be allowed by the Windows Firewall?


THX

**Comment by saghul** [comment]
The port is dynamically allocated, with the target port being 10000 UDP in the default installation. Can't you whitelist the Jitsi Meet app as a whole?

**Comment by FelipeEsBr** [comment]
Ah I see. Randomly source Ports going to target port (default target ports: 10000 - 20000).
Nowadays it is preferred to open specific ports not whole Program. 

THX for clarification
