### ISSUE TITLE
Basic auth credentials in server URL not working

### ISSUE THREAD

**Issue by kleest** [jitsi/jitsi-meet-electron#618]
## Description
I have a jitsi meet instance which is protected by HTTP basic authentication on the web server layer (`auth_basic` of nginx, `.htaccess` of Apache). When configuring a URL with basic auth credentials, those are not used when connecting to a session resulting in `401 Authorization Required`. The application also does not show a dialog to enter basic auth credentials manually.

## Current behavior
I can enter a URL with basic auth credentials in advanced settings:
![grafik](https://user-images.githubusercontent.com/6516878/128608223-ee7b431a-3783-497f-a9c2-4d0c15a16808.png)

These credentials are also saved to `config.json`:
![grafik](https://user-images.githubusercontent.com/6516878/128608256-03497775-7223-42bb-b0f0-885d0da8fcfb.png)

When trying to connect to a session, I get a `401 Authorization Required` error. The developer console prints `Failed to load resource: the server responded with a status of 401 (Unauthorized)`. Server requests do not contain authorization-related headers.

## Expected Behavior
I expect the basic auth credentials being used when connecting to a session.

## Possible Solution
---

## Steps to reproduce
1. Configure basic auth on a server
2. Enter a URL with basic auth credentials in settings: `https://user:password@...`
3. Try to connect to a session

# Environment details
Version 2.8.9

**Comment by saghul** [comment]
The Electron app does not support basic auth. In general, we don't support that kind of auth, it won't work on mobile for instance, since our apps are not web browsers.

I recommend you use internal auth.

**Comment by kleest** [comment]
Internal auth still exposes jitsi to the internet. I do not want to expose the application to the internet to protect from potential security issues. Since the application is only used internally, basic auth seemed like a good solution.

Would you be open for a PR?

**Comment by saghul** [comment]
Internal auth does not need any internet access. It's internal to XMPP and as such it needs the same access as the frontend itself.

Sorry, but this is not something I'd like us to support.

**Comment by kleest** [comment]
That's not what I meant. Consider the following:

a) I use internal auth which is provided by jitsi meet (or dependencies), so this authentication is on the application layer of the jitsi application. Jitsi is exposed to the internet directly.
b) I use basic auth to guard HTTP access to the jitsi web frontend (https://meet.???.??). In this case, authentication is terminated at the web server and jitsi (or dependencies) do not handle authentication. Jitsi is only exposed to the internet if basic auth credentials are valid.

In case of security problems, with scenario a) anyone on the internet can attack jitsi. With scenario b) only authenticated users can attack jitsi. Since the jitsi instance is for private use only, I can control who has access to the software in case of scenario b) but not with scenario a).

b) is working perfectly fine when using a regular browser. But not with the electron app despite electron using chromium under the hood.

**Comment by l4rsV** [comment]
We use internal Ldap authentication system, but for security reasons our company has decided to introduce basic authentication system, to secure our ldap accounts.

Is there a possibility that the Linux/Windows desktop application will support Basic Auth in the future?

**Comment by saghul** [comment]
No, sorry, we won't support it.
