### ISSUE TITLE
conference: check if valid jitsi-meet server

### ISSUE THREAD

**Issue by AkshitKrNagpal** [jitsi/jitsi-meet-electron#62]
It would be nice if we can check if the given domain from settings or from the link is a valid domain and display an error if not. 

Currently, it goes back to the Welcome page.

If `https://${domain}/external_api.js` exists, the server is valid `jitsi-meet` server. Does this sound good?

**Comment by saghul** [comment]
> If https://${domain}/external_api.js exists, the server is valid jitsi-meet server. Does this sound good?

This sounds great indeed! I think we could do a `HEAD` request using `fetch()` to avoid downloading the file. OTOH, it's ok if we download the file because it will be cached and used later anyway.

**Comment by AkshitKrNagpal** [comment]
>  I think we could do a HEAD request using fetch() to avoid downloading the file.

Yeah. I wanted to use this as checking is the default domain is valid or not. It will only get updated if valid and restore it to the previous value or `meet.jit.si` if not.

> we download the file because it will be cached and used later anyway.

That's only valid if we check that in Conference component, which we will also have to do. But it can be handled by `onerror` function of the script tag. Error showing can be done with a loading screen.

**Comment by saghul** [comment]
> Yeah. I wanted to use this as checking is the default domain is valid or not. It will only get updated if valid and restore it to the previous value or meet.jit.si if not.

:+1: 



> That's only valid if we check that in Conference component, which we will also have to do. But it can be handled by onerror function of the script tag. Error showing can be done with a loading screen.

Sounds good!
