### ISSUE TITLE
While "npm start" error : JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by ConGorz** [jitsi/jitsi-meet-electron#625]
[](url)*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
While "npm start" error : JavaScript error occurred in the main process
<img src = 'https://s3.bmp.ovh/imgs/2021/08/90e1ecc68b1a19a4.jpeg' />
## Current behavior
---
npm start

## Expected Behavior
---
run 

## Possible Solution
---
no idea

## Steps to reproduce
---

# Environment details
---
Mac OS 11.5.2
Node.js 14.17.5

**Comment by ConGorz** [comment]
![](https://s3.bmp.ovh/imgs/2021/08/90e1ecc68b1a19a4.jpeg)

**Comment by ConGorz** [comment]
<img src = 'https://s3.bmp.ovh/imgs/2021/08/90e1ecc68b1a19a4.jpeg' />

**Comment by csett86** [comment]
This is fixed with #672 as now the dependencies are packages as universal binaries and launching with npm run start works again.
