### ISSUE TITLE
Debian Package Issue

### ISSUE THREAD

**Issue by oktay454** [jitsi/jitsi-meet-electron#628]
There is a bug in the Debian package.
The files are located in the `/opt/Jitsi Meet/` directory.
However, when creating `/usr/bin/jitsi-meet` file in postinst script, it follows `/opt/jitsi-meet/` directory.
My humble advice, replace `/opt/Jitsi Meet/` with `/opt/jitsi-meet/`.

**Comment by saghul** [comment]
This sounds like an electron-builder issue.

**Comment by csett86** [comment]
Yes, this is an electron-builder issue fixed with https://github.com/electron-userland/electron-builder/pull/5941, which is part of electron-builder v22.11.7+

So this issue would be fixed with #583

**Comment by csett86** [comment]
After further investigation: Its unfortunately not fixed with #583 alone, as the linux-sandbox-fix.js is not compatible with symlinks, and thus breaks the jitsi-meet command again :(
