### ISSUE TITLE
Upgrade to Electron 14

### ISSUE THREAD

**Issue by vchernin** [jitsi/jitsi-meet-electron#629]
Electron 14 includes a very notable addition: https://github.com/electron/electron/pull/19159

It means users on KDE or other desktop environments will get the native Qt file picker instead of the GTK one. Also, it means the Jitsi Flatpak can pick any file with the file picker without granting unilateral file system access.

I tried building it locally but failed likely due to inexperience.

**Comment by csett86** [comment]
Unfortunately electron 14 also removes the deprected remote module. That is used both in dependencies and in jitsi-meet-electron, so it has to be replaced everywhere before Electron 14 is feasible

**Comment by vchernin** [comment]
Ah, I think I might have run into that.

I guess since it's depended on there's no easy way of forcing it to build (and it being actually succesful).

**Comment by csett86** [comment]
In between I at least discovered all the issues that need to be fixed before the electron 14 update is possible:

- [ ] Replace remote module in jitsi-meet-electron-utils: https://github.com/jitsi/jitsi-meet-electron-utils/issues/126
- [ ] Replace / upgrade electron-store (to remove remote module usage in it): https://github.com/jitsi/jitsi-meet-electron/pull/635
- [ ] Make robotjs context-aware: https://github.com/octalmage/robotjs/issues/580
- [X] Make jitsi-meet-electron context-aware: https://github.com/jitsi/jitsi-meet-electron-utils/pull/120

**Comment by saghul** [comment]
Fantastic work!

**Comment by romain130492** [comment]
any news about `Make robotjs context-aware` ?

**Comment by ilippert** [comment]
Please note that on Fedora 35, this jitsi app does not run anymore - because on wayland it now only shows a black window. I think it is the same issue with other apps not using Electron 14. See e.g. https://github.com/vector-im/element-web/issues/18943#issuecomment-938748142

So, Electron 14 would be really great.

**Comment by saghul** [comment]
> any news about `Make robotjs context-aware` ?

This work has been completed already.



> Please note that on Fedora 35, this jitsi app does not run anymore - because on wayland it now only shows a black window. I think it is the same issue with other apps not using Electron 14. See e.g. [vector-im/element-web#18943 (comment)](https://github.com/vector-im/element-web/issues/18943#issuecomment-938748142)
> 
> So, Electron 14 would be really great.

We are already ready, thanks to the relentless work @csett86 has put into it. We are waiting a bit because the update may break backwards compatibility (lost settings) for some people, unless they are currently running the latest version, which has some migration code path in.

**Comment by ilippert** [comment]
> We are already ready, thanks to the relentless work @csett86 has put into it. We are waiting a bit because the update may break backwards compatibility (lost settings) for some people, unless they are currently running the latest version, which has some migration code path in.

thank you so much for the update, and for the work! A great app!

**Comment by csett86** [comment]
Released as v2021.12.1

**Comment by WhyNotHugo** [comment]
Thanks a lot for addressing this!
