### ISSUE TITLE
conference: https vs http

### ISSUE THREAD

**Issue by AkshitKrNagpal** [jitsi/jitsi-meet-electron#63]
I guess we should add support for HTTP servers too. 
How would we like to approach this? @saghul

**Comment by damencho** [comment]
Nope, webrtc does not support http.

**Comment by bgrozev** [comment]
> So there is no way of configuring http server of jitsi-meet?

You could, but your browser will not allow `getUserMedia`, so there not much use

**Comment by AkshitKrNagpal** [comment]
> You could, but your browser will not allow getUserMedia, so there not much use

Thanks for the info @bgrozev. This gave me some things to read. :smile:
