### ISSUE TITLE
Use ~/config/electron-flags.conf with appimage

### ISSUE THREAD

**Issue by aleixq** [jitsi/jitsi-meet-electron#641]
## Description
---
Running with a hidpi screen with wayland it gets all ui blurry, as electrons chromium engine runs through xwayland. As you know this behavior can be solved with `--enable-features=UseOzonePlatform --ozone-platform=wayland` .  With electron apps, To make this behavior permanent a file in `~/.config/electron[electron_version]-flags.conf` could contain these flags. 

But this is not working with the appimage. 

## Current behavior
---
Despite it works with built jitsi-mett-desktop it doesn't with appimage.

## Expected Behavior
---
Allow the use of `~/.config/electron[electron_version]-flags.conf` . 

# Environment details
---
Arch linux 5.14.6-arch1-1
Jitisi-meet-electron appimage 2.9.0 from the package https://aur.archlinux.org/packages/jitsi-meet-desktop-bin/

**Comment by saghul** [comment]
I don't think that's possible because the AppImage does not interact with the host filesystem.

**Comment by csett86** [comment]
In addition electron-flags.conf seems to be a arch specific thing: https://www.mail-archive.com/arch-commits@lists.archlinux.org/msg66855.html

With the following AUR package it should probably work out of the box, as that uses the electron launcher from arch: https://aur.archlinux.org/packages/jitsi-meet-desktop/

**Comment by aleixq** [comment]
Thank you all,  

@csett86 I though it was eanbled for all freedesktop s (but it was discarded in https://github.com/electron/electron/issues/28537 )... Anyway I was using it with electron-flags.conf but sadly https://aur.archlinux.org/packages/jitsi-meet-desktop/ is outdated and the package has issues leading to blank page at start. 

As a workaround I end up modifying the jitsi-meet-electron.desktop to provide the permanent flags. So I suppose it can be closed
