### ISSUE TITLE
JSON.parse for URL-Params missing

### ISSUE THREAD

**Issue by psi-4ward** [jitsi/jitsi-meet-electron#642]
In 
https://github.com/jitsi/jitsi-meet-electron/blob/master/app/features/conference/components/Conference.js#L216
we do not `JSON.parse()` the values of URL-Params (like config.channelLastN=0) which leads to errors cause it's all strings.

https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/util/parseURLParams.js#L57

**Comment by csett86** [comment]
As asked today in the community call, this also is an issue for parameters that are boolean, eg. disableChatSmileys=true, as also they are then all strings and not boolean.
