### ISSUE TITLE
Build FreeBSD version of jitsi-meet-electron

### ISSUE THREAD

**Issue by probonopd** [jitsi/jitsi-meet-electron#648]
* Electron taken from https://github.com/tagattie/FreeBSD-Electron/releases/tag/v11.4.7
* Downgraded harfbuzz to get it to run
* Jitsi app (`app-x64.asar.unpacked`, `app-x64.asar`, `app.asar`) taken from macOS version of Jitsi Meet
* Architecture-dependent parts built with

```
sudo pkg install node npm # node-16.10.0, npm-6.14.8
cd /tmp
sudo ln -s /usr/local/include/X11 /usr/include/
# /usr/local/bin/npm install --nodedir="/home/user/Desktop/Jitsi Meet.app/Resources/usr/local/share/electron12/node_headers" robotjs
sudo cp node_modules/robotjs/build/Release/robotjs.node "/home/user/Desktop/Jitsi Meet.app/Resources/app/app-x64.asar.unpacked/node_modules/robotjs/build/Release/robotjs.node"
/usr/local/bin/npm install --nodedir=/home/user/Desktop/Session.app/Resources/usr/local/share/electron12/node_headers https://github.com/DanielMcAssey/sourceid-2-coordinates
sudo cp node_modules/sourceid-2-coordinates/build/Release/sourceid-2-coordinates.node ~/Desktop/Jitsi\ Meet.app/Resources/app/app-x64.asar.unpacked/node_modules/jitsi-meet-electron-utils/build/Release/sourceId2Coordinates.node 
```

Getting

```
Electron could not be found. No hard resets for you!
```

In my case, Electron is at `/usr/home/user/Desktop/Jitsi Meet.app/Resources/usr/local/share/electron12/electron`. Is there an environment variable I can pass in so that it gets found?

**Comment by saghul** [comment]
> There are working Electron builds for FreeBSD, but indeed not from the Electron project itself yet. Can't a third-party provided Electron build work, until there is an official one?

Sorry no. Until official Electron supports it I don't want us to spend time on this.

**Comment by csett86** [comment]
Closing as both electron and electron-builder do not support FreeBSD and thus we dont have the capacity to work around that.
