### ISSUE TITLE
Running in dev mode is no longer possible.

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#650]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

## Current behavior

<img width="912" alt="Screenshot 2021-10-31 at 14 22 23" src="https://user-images.githubusercontent.com/317464/139585694-4dc53364-0fec-41d7-a04d-2c4069771e2e.png">

## Expected Behavior

The main window should show up.

## Possible Solution

No idea.

## Steps to reproduce

npm start

# Environment details

Node 14, npm7.

**Comment by saghul** [comment]
@csett86 Are you not running into this?

**Comment by csett86** [comment]
I am not using the dev mode much, but its working fine for me, see below: 

![npm dev mode](https://user-images.githubusercontent.com/1392875/139597472-9f8a8e6f-dd34-4b10-9639-e93badd61bb9.png)

**Comment by saghul** [comment]
Hum. What npm did you use to install the dependencies? I used 7 (we need to update past 6) I wonder if that's related...

**Comment by csett86** [comment]
I see, I use npm6 as bundled with node14 (as bundled in nodejs.org node 14 package) and npm start and npm run start both work fine.
