### ISSUE TITLE
RFC: switch versioning scheme to calver

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#652]
The current version scheme is quite meaningless since 90% of the functionality is inside the iframe.

On the mobile apps we have been using CalVer quite successfully for a while. Specifically we use "Year.Release.Opsie", but I think in this case something like what Ubuntu does is more appropriate: "Year.Month.Release".

This would help identify how old a release is at a glance for example.

Thoughts?

**Comment by csett86** [comment]
+1, as then the version numbers are also different to the old jitsi desktop app (non-electron). That is currently at 2.10, here we are at 2.9.1, so confusion is given.

I also like the ubuntu year.month.release as you proposed

**Comment by csett86** [comment]
One other alternative: We could also do „Chromium.Release“ to quickly know what chromium version is inside (as that is probably the main factor if things break, as you rightly said, 90%+ is within the loaded iframe, not bundled in the app). 

Current would be then 91.1, 91.2 etc.

**Comment by saghul** [comment]
Not a fan of the Chromium release numbers because they mean nothing. With CalVer at least one can know how old a release is, without looking at anything else.

**Comment by csett86** [comment]
Lets do calver then, with year.month.release, will follow with the next release, 2021.11.1 most likely. I was aiming at monthly security releases going forward anyway ;)

**Comment by saghul** [comment]
Excellent!
