### ISSUE TITLE
Alternate language shows up in Electron App 

### ISSUE THREAD

**Issue by cambo2010** [jitsi/jitsi-meet-electron#661]
## Description
When a 2nd language is loaded in Windows or MAC OS, the Electron App uses that language

## Current behavior

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/93780706/141133974-048ddfa3-29ba-4313-8758-d85aca7bf186.png)

## Expected Behavior
Language should default to primary language of OS

## Possible Solution
??

## Steps to reproduce
Load 2nd language keyboard in Win or MAC OS

# Environment details
Related to: https://github.com/jitsi/jitsi-meet-electron/issues/423

**Comment by csett86** [comment]
Not reproducible with v2022.6.1, thus closing
