### ISSUE TITLE
Handle URL parameters

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#67]
A user may enter the following URL: `https://meet.jit.si/fooo#config.p2p.enabled=false`

We need to convert all the hash parameters into config overrides which the iframe API takes (right @hristoterezov ?).

**Comment by AkshitKrNagpal** [comment]
I guess then we should have a function in `utils` that parses everything and returns an object with all the options.

Also, I guess we can have these settings for default server as well or do you think they should do this in their server config?

**Comment by saghul** [comment]
We currently have (or rather, will have) 2 settings: startWithAudioMuted and startWithVideoMuted. Those should take precedence over the stuff in the URL. So yeah, I think we should parse the URL and extract the hash parameters, and apply them together with those 2 when we join.

Let's discuss this is tomorrow's call! This goes after the start muted toggles anyway, so no problem.

**Comment by agraef** [comment]
I'd really like to give this a bump and a big thumbs up. For me, it is especially important to override audio-related options to get better audio quality when transmitting music (I'm teaching computer music courses via Jitsi Meet to my students at university). I currently have to resort to using Jitsi Meet in Chromium to make that work.

Can we please get this? Like really soon now? ;-)

I'd be willing to have a look at the sources myself if someone points me to the right place.

**Comment by chamerling** [comment]
Hello,

This has been addressed in https://github.com/jitsi/jitsi-meet-electron/pull/286 and available since v2.1.1

**Comment by saghul** [comment]
Indeed!

**Comment by agraef** [comment]
@chamerling Thanks for the heads-up! I actually saw your PR and already thought that this might fix it, so I got quite excited when the upgrade to version 2.3.0 landed on my system this morning. :)

However, giving it a quick whirl adding the parameters that I usually employ, `#config.p2p.enabled=false&config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true`, I still noticed some artifacts on the receiving end, so I wasn't sure whether that's actually supposed to work now. But I'll give it another try. Sometimes it's hard to hear (or rather not just imagine) the artifacts when you're looking for them...

**Comment by agraef** [comment]
Just gave it another whirl, and no, I didn't imagine those artifacts when playing music, they're still there. :( The language processing artifacts on music are immediately obvious when doing an A/B test running Jitsi Meet from the 2.3.0 version of the app versus Chrome/Chromium. If you don't believe me, I can record sound samples -- the differences are really obvious, even a non-musician will be able to notice them.

I tried adding the parameters both to the meeting URL in the "GO" field, and in the default server setting. It didn't make a difference.

Any ideas what I might be doing wrong?

**Comment by Bleuzen** [comment]
Same as @agraef , I try to enable stereo audio and it works in FireFox/Chromium but not in the electron app. Any news about this?

**Comment by csett86** [comment]
@agraef, @Bleuzen, I created a PR #594 to address at least all of the "top-level" config options like config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true
