### ISSUE TITLE
Turn off auto-update in UI?

### ISSUE THREAD

**Issue by asmaloney** [jitsi/jitsi-meet-electron#676]
Is there a way to turn off auto-update in the UI that I haven't found yet?

It's not a very good user experience.

1) There's no indication that it's downloading things in the background.
2) When you fire it up and try to enter a meeting, your bandwidth is being chewed up downloading >150M so then you run through the whole "connection problem scenario" with everyone in the meeting until it finishes.
3) It downloads the update, but fails to apply it (macOS 2021.11.1).

A much better user experience would be to:

1) alert the user that an update is available (maybe by adding a red "update" badge in the left sidebar?)
2) let them initiate the update from within the UI at a time that's convenient for them

**Comment by saghul** [comment]
There is no way to disable it, nor do we have plans to implement it. Electron being a web browser in disguise, it's critically important users get timely security updates. If you let them not update they might not.

> 3\. It downloads the update, but fails to apply it (macOS 2021.11.1).

Can you share the logs?

**Comment by csett86** [comment]
@asmaloney mac version 2021.11.1 unfortunately has a broken autoupdater that cannot be fixed retrospectively. Please instruct your mac users to update manually to 2021.12.1.

Please excuse the inconvenience!

**Comment by asmaloney** [comment]
OK. No other electron apps I use force updates like this, but in the interest of not getting bogged down I will avoid the debate about who decides what goes on my machine and when.

This does not preclude giving the user an indication about what's happening. If I fire up Meet and it tells me it's downloading an update, I then have the opportunity to wait for it to download & apply before I enter a meeting.

> Can you share the logs?

```
[2021-12-01 09:46:15.156] [info]  New version 2021.12.1 has been downloaded to /../Library/Application Support/Caches/jitsi-meet-electron-updater/pending/jitsi-meet.zip
[2021-12-01 09:46:15.159] [error] Error: TypeError: Cannot read property 'port' of null
    at p (/Applications/Jitsi Meet 2021.11.1.app/Contents/Resources/app-x64.asar/build/main.js:1:94888)
    at l.updateDownloaded (/Applications/Jitsi Meet 2021.11.1.app/Contents/Resources/app-x64.asar/build/main.js:1:95058)
    at Object.done (/Applications/Jitsi Meet 2021.11.1.app/Contents/Resources/app-x64.asar/build/main.js:1:94556)
    at f (/Applications/Jitsi Meet 2021.11.1.app/Contents/Resources/app-x64.asar/build/main.js:1:47403)
    at async l.executeDownload (/Applications/Jitsi Meet 2021.11.1.app/Contents/Resources/app-x64.asar/build/main.js:1:47895)
```

**Comment by asmaloney** [comment]
@csett86 Ah! Thanks.

**Comment by asmaloney** [comment]
Should I open a new issue for feedback to the user that an auto-update is in progress or is this a "never going to happen" thing as well?

**Comment by saghul** [comment]
I'll be honest: this project gets done in borrowed time, and lately thanks to @csett86's help. So unless you are ready to provide a patch opening an issue won't change anything.

**Comment by asmaloney** [comment]
OK, thanks @saghul - I always appreciate an honest answer!

I'm a C++ and golang guy, so I don't think you want me hacking around in javascript! 😄
