### ISSUE TITLE
No Titlebar on Gnome-Wayland run natively

### ISSUE THREAD

**Issue by 9Lukas5** [jitsi/jitsi-meet-electron#683]
## Description

Running Jitsi in Wayland native on Gnome doesn't have Window decorator, as Gnome-Wayland doesn't support this at the moment.
This is related to the electron upstream issue electron/electron#27522 , but no idea how long it would take the upstream issue get's closed and then taking effect for Jitsi.

---

## Current behavior

Running Jitsi in Wayland native under Gnome results in the window not having a titlebar.
Possible to fully use and move around with Super+Mouse Click&Drag.

---

## Expected Behavior

Having Window decorator on Gnome when running in Wayland native

---

## Possible Solution

Add custom decorator, or wait what electron does upstream

---

## Steps to reproduce

Run in a Gnome-Wayland session with 

```
<path to bin> --enable-features=UseOzonePlatform --ozone-platform=wayland
```

---

# Environment details

Ubuntu 20.04 Focal Fossa
Gnome 41 on Wayland
Jitsi 2021.11.2

---

**Comment by saghul** [comment]
This is not something we can solve, and having this issue open while Electron itself doesn't support won't help either.

When electron gets it we'll update.

**Comment by 9Lukas5** [comment]
Well, can not is maybe the wrong wording, as for example VSCode has an setting to enable client side decorations, as I found out [here](https://github.com/microsoft/vscode/issues/109176#issuecomment-833744341).

So the question would be more of is it worth the work, implementing something or waiting on what/when it changes in electron upstream^^

Jitsi doesn't have any menus, so it would basically only a simple bar, holding the buttons for minimize, maximize and close.

**Comment by csett86** [comment]
Upstream electron is nearly ready with client side decorations, so I suggest that we hold off here and wait for that: https://github.com/electron/electron/pull/29618

**Comment by snaggen** [comment]
The electron PR is merged, but I still do not see any borders when using native wayland....

**Comment by saghul** [comment]
Try passing this argument: `--enable-features=WaylandWindowDecorations`

**Comment by snaggen** [comment]
That worked! Thanks!

**Comment by saghul** [comment]
@csett86 Not sure how risky it would be to enable this by default...

**Comment by csett86** [comment]
Enabling by default at least under Ubuntu 22.04 (with wayland) causes issues, so I'd rather not do that by default:

![grafik](https://user-images.githubusercontent.com/1392875/177044802-51778ec9-651a-4602-ac0e-3a640dc1128d.png)
