### ISSUE TITLE
Need how this app uses autoupdate

### ISSUE THREAD

**Issue by comp-labs** [jitsi/jitsi-meet-electron#685]
Hello,
I modified this application's source code to my own logo, meeting URL, and some more settings. Then I run my app and I see that my app is not updating o the latest version in this repo which is 2021.12.2. I am stuck in 2021.12.1 and I do not know why. Can anyone help me with this? I also modified all the URLs to my own in `/app/features/config/index.js`. It may help.

**Comment by saghul** [comment]
Update the repo URL in your package.json file
