### ISSUE TITLE
forced auto update should NEVER be

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#686]
OH MY GHODS DO NOT FORCE AUTO UPDATE!

Among other things, OS incompatibilities come in with new app versions, and if you force-update, you will break anyone's use of the last-compatible app version on their older OS.

BEST PRACTICES include --
* **_prompting_** the user to see if they want to update, when a new version is available
* **_displaying_** the changes that the new version will bring -- optimally covering all versions between the user's existing install and the latest available; minimally including only the latest available vs the previous version
* **_preference_** for auto-update (which the user can disable) is viable but still concerning

Look to how, omg, Zoom does this, to get an idea of what is certainly possible.

(Past history of random incompatibilities I've experienced include multiple versions of Google Drive, which caused kernel panics that were mimicing a hardware problem for which I received multiple replacement motherboards.  This was expensive in multiple ways, including moving me from my treasured 17" MacBookPro to a much smaller 15" model, because the 17" had been discontinued.)

**Comment by saghul** [comment]
Please read past related issues before opening new ones.

**Comment by TallTed** [comment]
@saghul -- Linking to the past related issue I apparently overlooked would be friendly.

**Comment by TallTed** [comment]
@saghul -- It looks like you meant #676 which [basically says "go spin"](https://github.com/jitsi/jitsi-meet-electron/issues/676#issuecomment-983811959) to anyone who bothers to log an issue on the project, including this issue.

This is neither friendly nor productive.

Issues that are not fixed should indeed remain open, until someone comes and sees something to which they can contribute.

Closing everything that *you* won't fix makes it look like there's nothing needing fixing (which isn't accurate), and doesn't leave a path for other contributors to do so.

Maybe @csett86 didn't realize that the current auto-update pattern would be a problem when they assisted in implementing the pattern requested by myself and @asmaloney

(I am not a coder, so I cannot volunteer to leap into this, myself, much as I might like to.)

**Comment by TallTed** [comment]
@saghul -- As this is not your personal project, though you have been a substantial contributor, but is a @Jitsi Community project, I would appreciate you re-opening one of the issues logged on this forced-/auto-update "feature"/"bug" (depending on your perspective), or creating a new one that states things as you'd like but covering the same user concerns (including both what was reported in #676, which is more an issue with when the update is downloaded, than the fact that it is; and what was reported here, which is very much an issue with the fact that the update is forced, without any option for the user to skip it).

**Comment by csett86** [comment]
@TallTed unfortunately we disagree here. Jitsi Meet is basically a web browser that loads jitsi meet conferences from arbitrary remote servers. Like your Chrome or Firefox, standalone downloads of this app will have auto-update for security reasons that cannot be turned off.

The third-party builds from package managers like flathub (https://flathub.org/apps/details/org.jitsi.jitsi-meet) or brew  (https://formulae.brew.sh/cask/jitsi-meet) do not have built-in auto-updates, but are updated by the respective package manager and you can select the time of update there.

**Comment by TallTed** [comment]
@csett86 -- Both [Chrome](https://support.google.com/chrome/a/answer/7591084) and [Firefox](https://support.mozilla.org/en-US/kb/update-firefox-latest-release) offer ways to control, including disable, their auto-updates (which controls I make use of).  You might want to check that your cited examples support your position before you cite them.

**Comment by TallTed** [comment]
@csett86 /cc @saghul @jitsi

Since you are apparently taking your cue from Chrome and Firefox, and I've [linked to their own instruction pages](https://github.com/jitsi/jitsi-meet-electron/issues/686#issuecomment-989281876) for disabling or otherwise configuring their auto-update features, can I expect that you will reopen this issue and/or make a relevant PR?

/cc others who may be interested and/or able to contribute code (which is regrettably beyond me): @knobhead @cvandesande @arlt (#295) @Ribero (#410) @demlak (#243) @ebal @chamerling (#232) @UtkarshGupta-CS @akshitkrnagpal (#35)

**Comment by demlak** [comment]
@TallTed i am out.. i don't use jitsi anymore. we moved to BBB.

**Comment by saghul** [comment]
This will not be considered. Stop it already.
