### ISSUE TITLE
PreJoin Page does not update Username

### ISSUE THREAD

**Issue by JonnyTischbein** [jitsi/jitsi-meet-electron#687]
* Tested with version: `2021-12-02` (appImage version)
* Tested on multiple jitsi instances (with enabled prejoin page): e.g. https://meet.jit.si https://meet.ffmuc.net (and some more)
* Tested on ubuntu 21.10 `5.13.0-22-generic x86_64 x86_64 x86_64 GNU/Linux`

The name, which is set in the Jitsi App Settings always overwrites the value entered in the prejoin page. 

Example: 
* Setting Name is set to `User A`
* On the PreJoin Page I enter `User B`
* I join as `User A` and also see in the console ` action Symbol(SET_NAME) @ 10:09:38.701 - app.js:173`

If I clear the Name set in the settings and join via a prejoin page I join without a username (even if I enter a name on the prejoin page).

I guess it is because of this line, where the app setting user name is set.

https://github.com/jitsi/jitsi-meet-electron/blob/22b34066132f7dd39920e7f3a2f3d3eb26695374/app/features/conference/components/Conference.js#L362-L379

When I join a conference and go to the "conference settings" -> profile and update there my username it is also updating the app setting username.

I guess because of this code:
https://github.com/jitsi/jitsi-meet-electron/blob/22b34066132f7dd39920e7f3a2f3d3eb26695374/app/features/conference/components/Conference.js#L157-L172

It seems to me that we miss an update of the username when it changes on the prejoin page

**Comment by saghul** [comment]
Good analysis.

I have actually been thinking about something related this week: I think this app should remove those settings altogether and force the prejoin screen to be visible.

This way one could customize mucho more before actual joining, such as the devices, background, etc.

We have had prejoin for long enough that there would be no risk assuming it's supported, and we can easily override it from the iframe API.

A nice bonus is we'd delete a bunch of code from this project :-)

Thoughts @csett86 ?

**Comment by csett86** [comment]
I agree that the prejoin page would be better than the current settings, as its very confusing to have both and they sometimes are in sync, sometimes not (as seen here).

So yes, forcing the prejoin via the iframe api sounds good!

**Comment by saghul** [comment]
Excellent I'll try to take a crack at it.
