### ISSUE TITLE
[Feature] Support "Mic Mode" on macOS Monterey

### ISSUE THREAD

**Issue by svoop** [jitsi/jitsi-meet-electron#691]
On macOS Monterey, it's possible to use different microphone modes. A very useful mode for audio/video calls is "voice isolation" which tries to reduce background noise:

![Screenshot 2021-12-22 at 17 07 48](https://user-images.githubusercontent.com/7255/147122077-7b88febb-fa1f-469c-b6f2-2501e810b2af.jpg)

Jitsi does not yet enable this feature, I'm not even sure whether that's possible for an Electron app yet. But it would be a very useful feature!

https://developer.apple.com/videos/play/wwdc2021/10047/?time=1384

**Comment by saghul** [comment]
Looks like this would need to be implemented by Chronium first, then Electron would get it and then we'd be able to leverage it.

**Comment by svoop** [comment]
@saghul Good point, I've [submitted a feature suggestion on Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1282442). (Not sure whether their bugtracker is the right place, but we'll see I guess.)

**Comment by saghul** [comment]
I'm going to close this since there is nothing actionable here for us, at the app level.
