### ISSUE TITLE
cannot  cancel joining a meeting that's not active

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#698]
### Description:

Use a saved jitsi URL within Jitsi Meet.app to join a session where the host will never join.  (Actual case involved accidentally clicking the URL for a different weekly session.)

### Steps to reproduce:

1. Launch Jitsi Meet.app
2. Click on any saved meeting URL where the host will not join during your test.
3. Have to quit Jitsi Meet.app to get out of the waiting room, in order to click the URL for another session.

### Expected behavior:

Have a CANCEL button alongside the "I am the host" button.

### Actual behavior:

Be trapped waiting for host forever. 

Try to claim the host role, but without credentials, no dice. 

Cancel taking host role, and you're back to the waiting room.

### Server information:

Unknown. Probably irrelevant.

How would I discover this as a client?

### Client information:

- Jitsi Meet.app 2.8.6
- macOS El Capitan 10.11.6 (15G22010)

### Additional information:

nada

**Comment by saghul** [comment]
We have a cancel button now.
