### ISSUE TITLE
Deeplinking to Mobile App?

### ISSUE THREAD

**Issue by gelsas** [jitsi/jitsi-meet-electron#701]
Hello everyone, 

I have read that deeplinking is available and it is working great for me on desktop but I wanted to ask if it is possible to deeplink to the mobile app aswell and if yes how can this be done ?

Best,
gelsas

**Comment by saghul** [comment]
Here you go https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#opening-meetings-in-the-jitsi-meet-app

**Comment by gelsas** [comment]
Thank you very much!
