### ISSUE TITLE
[CRITICAL] CI Workflow Error

### ISSUE THREAD

**Issue by complabs28** [jitsi/jitsi-meet-electron#702]
Hello,
I have made a modified version of `jitsi-meet-electron`. The name is `comp-labs-meet`. I have made a GitHub Repository of it - `https://github.com/comp-labs/comp-labs-meet` where the code is hosted. I have also created a ci.yml like yours in my repo. An issue came up like code errors. As I am a student, I do not understand much of code. It is giving errors. Please can anyone help me fix it? **Another Helping Information- The issue comes up only in the macOS Platform. Linux and Windows go fine. I have attached the logs of the CI GitHub Actions Logs.** Any help is highly appreciated.

[GitHub Actions - CI - Logs.zip](https://github.com/jitsi/jitsi-meet-electron/files/7956721/logs.zip)

**Comment by saghul** [comment]
Flow seems to be complaining, did you make any changes to the code?

**Comment by complabs28** [comment]
I made changes only to the UI/UX. Anyway, You can see the code on https://github.com/comp-labs/comp-labs-meet. There you can see the code and the ci workflow error on the Actions Tab.

**Comment by complabs28** [comment]
And can you tell me please how to enable the remote control feature in the app code

**Comment by saghul** [comment]
You can disable linting in your CI: https://github.com/Comp-Labs/comp-labs-meet/blob/main/.github/workflows/ci.yml#L59

Since I don't know how you intend to use your app and don't want to put any users in potential risk I'll leave finding how to enable remote control as an exercise to you.
