### ISSUE TITLE
Popup when using i3 window manager

### ISSUE THREAD

**Issue by hemker** [jitsi/jitsi-meet-electron#703]
Hey,
I am using i3 as a window manager on Linux. Every time I switch to another virtual desktop, a new window opens showing the last active speaker icon. I guess that this window shows up as a small popup on the lower right corner on other window managers.
My question: Can I disable the popup completely?

Best
Dennis

**Comment by saghul** [comment]
Yes, you can turn the "always on top window" off in the settings.

<img width="1345" alt="Screenshot 2022-02-02 at 11 53 26" src="https://user-images.githubusercontent.com/317464/152140452-68412482-38e4-4e63-a43f-f355fdb3010f.png">
