### ISSUE TITLE
Jitsi Meet Audio and Video error : Permission denied

### ISSUE THREAD

**Issue by abuech2s** [jitsi/jitsi-meet-electron#704]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

## Description
I just receive a banner with "Audio and Video error: Permission denied", while entering a channel.

I know, that there are many of these kind of problems, but mostly there a just approaches to find a solution at Chrome or any other browser. I use jitsi-meet.exe (Version 2022.1.1)

I have activated cam and mic at Windows-settings.

## Current behavior
After entering a channel name, I receive the error "Audio and Video error: Permission denied".
After entering the room (this is possible), I try to select any camera/microphone/audio output, but there are no options for me.

The following two screenshots are showing the options. 

![grafik](https://user-images.githubusercontent.com/44176089/152770575-bb6c3374-a0fc-4c4d-9757-37cbd07ed6d2.png)
![grafik](https://user-images.githubusercontent.com/44176089/152770790-490644b8-f2b6-4ece-845c-000f7631ac96.png)

If I use jitsi via any kind of browser (Chrome, Edge, Firefox), camera and mic are working, but there are several other problems. I have installed and/or started jitsi with and without admin rights. 

## Expected Behavior
Microphone and Camera should work (or can be selected) and have permissions.

## Possible Solution
Dont know.

## Steps to reproduce
Use Version 2022.1.1
Install jitsi-meet.exe (latest version)
Open it, enter a channel room name, enter the channel
Even an older version does not work - an update will start automatically.

I have stored our internal jitsi server adress, which is a https link

# Environment details
Windows 10 Enterprise x64, 20H2, built 19042.1466

**Comment by saghul** [comment]
Can you reproduce this with a different server, such as meet.jit.si?

**Comment by abuech2s** [comment]
Oh indeed, based on your url will be mapped automatically to https://meetjit.si, but it seems to work.

**Comment by saghul** [comment]
Do you know what versions of the software your installation is running?

**Comment by abuech2s** [comment]
I took the latest jitsi-meet.exe
2022.1.1

https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2022.1.1

**Comment by saghul** [comment]
Sorry, I meant on the server side.
