### ISSUE TITLE
Ad video volume painfully loud

### ISSUE THREAD

**Issue by e-t-l** [jitsi/jitsi-meet-electron#719]
## Description
The ad video that displays after a call ends (using the default server) is way too loud, especially if the user is wearing earbuds from their Jitsi call. 

## Current behavior
Ad starts playing at a painfully high volume

## Expected Behavior
Ad does not cause users physical trauma

## Possible Solution
1. Start the ad muted
2. Start the ad paused
3. Start the ad at lower volume, e.g. 30%
4. Match the max gain of the ad to the max gain of the previous Jitsi call (most difficult to implement, but most effective outcome)

## Steps to reproduce
1. Start a Jitsi call on the default server
2. End the call
3. Make appointment with audiologist

# Environment details
1. Wearing earbuds/headphones
2. Device global volume was set to ~40% fyi
2. Jitsi v2022.2.1, Windows 11

**Comment by csett86** [comment]
Ads are part of the meet.jit.si deployment, not this app, thus closing here. Using your own or an alternate server is possible where no ads are played out.
