### ISSUE TITLE
Keep losing microphone when running via jack alsa plugin on Debian

### ISSUE THREAD

**Issue by musger** [jitsi/jitsi-meet-electron#720]
Hi, 
for the last two years I was able to run jitsi-meet using the jack audio server by installing the "jack" alsa plugin, and telling jitsi-meet to use it as default via my ~/.asoundrc holding the following:
```
pcm.!default{
        type plug
        slave { pcm "jack" }
        hint {description" jack with software conversions added by me" }
}
```
Since the last two or three upgrades (which are hard to trace because they happen forcibly and in the background without user notification) jitsi-meet will lose its microphone input a few seconds after the mic is unmuted, tracable by a vanishing audio connection in jack's gui qjackctl. When this happens I see jackd posting 
```
subgraph starting at alsa-jack.jackC.468772.0 timed out (subgraph_wait_fd=17, status = 0, state = Triggered, pollret = 0 revents = 0x0)
09:27:13.048 JACK connection graph change.
**** alsa_pcm: xrun of at least 393698.976 msecs
09:27:13.052 XRUN callback (8).
09:27:13.232 JACK connection change
```
How can I go about debugging this further? Did something regarding audio change in the last three or so versions? Thank you a lot!

**Comment by saghul** [comment]
Do you observe the same behavior in Chromium? We don't do any special audio management here, just use what Electron / Chromium provide.

**Comment by musger** [comment]
Thank you! Chromium is also unable to use the alsa jack plugin. I get
```
ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM jack
[6152:6152:0223/095557.999564:ERROR:alsa_util.cc(204)] PcmOpen: default,No such file or directory
```

If I insert apulse on top of jack, which is a pulseaudio emulation,
chromium fails to access the mic as well.

In Firefox things work fine with apulse talking to exactly that alsa jack plugin.

**Comment by saghul** [comment]
Then I'm afraid there is nothing we can do. Maybe you can try using pipe wire?
