### ISSUE TITLE
Question - What CI tool is used to automatically build the binaries

### ISSUE THREAD

**Issue by dante0026** [jitsi/jitsi-meet-electron#730]
Hello,

first of all, thanks for this great project.

I was searching for how to automatically build the executable files but just found an older revision containing the appveyor approach. This is currently not in use anymore, right?

Can somebody shortly tell, how to automatically build for the various plattforms? I guess it has something to do with the "ci.yml" located in "../.github)/workflows/".

P. S.: Flag a question with a flag (e. g. question) can just be done by some kind of moderator, right?

**Comment by csett86** [comment]
Yes, we are using Github Actions: https://github.com/features/actions
