### ISSUE TITLE
Dev Dependencies outdated

### ISSUE THREAD

**Issue by kb-0311** [jitsi/jitsi-meet-electron#731]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Most of the dev dependencies are pretty outdated so there is a need to update it for security issues, performance improvements, easier to transition to a newer version of the project release, etc. I don't think that would require a change in config

---

## Expected Behavior
---

## Possible Solution
---
However, we should not update everything at once, to not break the production.

The updates can be made in different part updating specific dependencies 

## Steps to reproduce
---

# Environment details
---

**Comment by csett86** [comment]
Closed by #732
