### ISSUE TITLE
hanging up call forces quit & relaunch of app before joining another call

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#737]
## Description

When you click the "hangup" button in **Jitsi Meet.app**, you now get prompted to "embed this meeting" with no way out of that full-app "alert" except to quit the app and relaunch to get back to the original assortment of past meeting links.  Either that "embed this meeting" should be made a partial window, or it should have an "exit" path that takes me back to the pseudo-menu of previous calls.

---

## Current behavior

No way forward but to quit and restart **Jitsi Meet.app**.

---

## Expected Behavior

Some way to fully end one call and join a new call without quitting and relaunching **Jitsi Meet.app**

---

## Possible Solution

Revert to previous behavior, which was to simply go back to the "initial launch" window upon meeting hangup.

---

## Steps to reproduce

As described above.

---

# Environment details

**Jitsi Meet.app** 2022.3.1 on macOS 10.12.6. 

This wasn't an issue with **Jitsi Meet.app** 2022.2.1 on macOS 10.12.6. 

---

**Comment by saghul** [comment]
There is an X on the top right of the screen, isn't there?

<img width="1345" alt="Screenshot 2022-03-24 at 16 36 42" src="https://user-images.githubusercontent.com/317464/159953707-9bbee460-a107-47a6-981f-86868506b66b.png">

**Comment by TallTed** [comment]
Hm.  Possible.  I did have a few app notifications onscreen, which may have hidden that X, as Jitsi Meet.app window was all-but-full-screen (opt-green, to expand to fill the screen modulo the menu bar).

I think this is still a bug.  

For something like this modal dialog, macOS standard is to have a "close" or "escape" that does the same as such X, i.e., to accept ESC (and sometimes ctrl-W a/k/a "close window") as synonym for clicking the X.  A [cancel] button alongside the [Learn more] would also be more typical than just the [Learn more].

It's very atypical for such a modal dialog to take over a full window, and even more abnormal for such to only be exited by clicking such an X as is now here.

**Comment by saghul** [comment]
Jitsi Meet is a web application. This is just a wrapper around it. While we try to make it feel as natural as possible it's an alien, and always will be.

The close screen you see is only visible on meet.jit.si because that is out close screen. You won't see it on custom deployments. It's not an electron screen.

> It's very atypical for such a modal dialog to take over a full window, and even more abnormal for such to only be exited by clicking such an X as is now here.

It's very typical for web applications.

Sorry, not a bug.
