### ISSUE TITLE
Add Travis and Appveyor intergration

### ISSUE THREAD

**Issue by akshitkrnagpal** [jitsi/jitsi-meet-electron#75]
CI should do the following
- [ ] Lint Testing
- [ ] Generate Binaries

**Comment by saghul** [comment]
I wonder how the binary generation will work on macOS since it requires signing. Do you know?

**Comment by saghul** [comment]
:+1:

**Comment by akshitkrnagpal** [comment]
> But native modules might create a problem.

Huh. Since we have native dependencies we won't be able to use Travis to build for Windows. 
@saghul 
Can we use appveyor?
https://www.electron.build/multi-platform-build

**Comment by saghul** [comment]
Sure we can. In the past I built windows binaries on Linux and Mac with Wine though. Maybe that’s an option?

**Comment by akshitkrnagpal** [comment]
>  In the past I built windows binaries on Linux and Mac with Wine though. Maybe that’s an option?

Yeah. Actually, I was counting on that. And `.exe` is being generated with no errors and have icons and all. But after opening the executable it installs and shows error. 🙃 
That is, most probably, because of "native dependencies". ( `robotjs` as we are using a fork with our own improvements and don't have prebuild binaries for them )
I'll investigate more.

**Comment by saghul** [comment]
Got it, makes sense. In that case it would be ok to use AppVeyor.
