### ISSUE TITLE
Multiple window jitsi electron app

### ISSUE THREAD

**Issue by PrasantKumarBiswal** [jitsi/jitsi-meet-electron#756]
How to create multiple window for jitsi electron app

**Comment by saghul** [comment]
Just open the meeting in a new BrowserWindow. Do you have a problem with that?

**Comment by PrasantKumarBiswal** [comment]
> Just open the meeting in a new BrowserWindow. Do you have a problem with that?

we want to open single jitsi electron app with multiple window and join multiple meeting at a time.

**Comment by saghul** [comment]
Then open multiple BrowserWindow instances to launch those meetings.

What exact problems are you running into?

**Comment by PrasantKumarBiswal** [comment]
can you please share me the example links for opening multiple BrowserWindows in jitsi electron.

**Comment by csett86** [comment]
This is not a support forum, please use https://community.jitsi.org for any community help
