### ISSUE TITLE
Missing button to close ad after ending call to return to home page

### ISSUE THREAD

**Issue by mariohm1311** [jitsi/jitsi-meet-electron#757]
Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Self explanatory. The X button that was available on previous versions to close the ad and get back to the home page isn't available.

## Current behavior
Already explained.

## Expected Behavior
Some way to close the ad and return to the home page without having to close the program.

## Possible Solution
Some way to close the ad and return to the home page without having to close the program.

## Steps to reproduce
End a call.

# Environment details
Windows 10 64 bit, Jitsi Desktop 2022.4.1

PS: Could you reevaluate your ad policy? Nobody cares about embedding.

**Comment by saghul** [comment]
Thanks for the report.

**Comment by csett86** [comment]
The button is back on meet.jit.si (upper left corner), thus closing this:

<img width="1174" alt="Bildschirmfoto 2022-07-03 um 20 15 19" src="https://user-images.githubusercontent.com/1392875/177052286-54492a04-a36d-44cf-a38c-999662458e93.png">
