### ISSUE TITLE
2022.4.1 says restart to auto-update, but it fails to do so; have to manually download and install 2022.6.1

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#762]
## Description

**Jitsi Meet.app** 2022.4.1 says restart to auto-update, but it fails to do so. Have to manually download and install 2022.6.1

## Current behavior

**Jitsi Meet.app** 2022.4.1 launches.

## Expected Behavior

**Jitsi Meet.app** 2022.6.1 launches.

## Possible Solution

Fix the auto-update.

## Steps to reproduce

Launch **Jitsi Meet.app** 2022.4.1 on macOS (High Sierra, 10.13.6, in case it matters).  Note that it says an update has been downloaded and will be auto-applied upon quit.  Quit and launch **Jitsi Meet.app** again.  Note that its version remains 2022.4.1.

# Environment details

macOS High Sierra 10.13.6 on MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by saghul** [comment]
Run it with the full path like so: `/Applications/Jitsi\ Meet.app/Content/MacOS/Jitsi\ Meet` you should see the output in the terminal now.

**Comment by saghul** [comment]
I could update without issues, on macOS Monterrey.

**Comment by TallTed** [comment]
With corrected full path (`Contents` subdirectory, not `Content`) --
```
$ /Applications/Jitsi\ Meet.app/Contents/MacOS/Jitsi\ Meet
09:30:57.515 › Checking for update
09:30:58.940 › Found version 2022.6.1 (url: jitsi-meet.zip, jitsi-meet.dmg)
09:30:58.941 › Downloading update from jitsi-meet.zip, jitsi-meet.dmg
09:30:58.942 › Checking for macOS Rosetta environment
sysctl: unknown oid 'sysctl.proc_translated'
09:30:58.951 › sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'

09:30:58.952 › Checking for arm64 in uname
09:30:58.958 › Checked 'uname -a': arm64=false
09:30:58.959 › updater cache dir: /Users/macted/Library/Application Support/Caches/jitsi-meet-electron-updater
09:30:59.532 › Update has already been downloaded to /Users/macted/Library/Application Support/Caches/jitsi-meet-electron-updater/pending/jitsi-meet.zip).
09:30:59.533 › Creating proxy server for native Squirrel.Mac (fileToProxy=https://github.com/jitsi/jitsi-meet-electron/releases/download/v2022.6.1/jitsi-meet.zip)
09:30:59.534 › Proxy server for native Squirrel.Mac is created (fileToProxy=https://github.com/jitsi/jitsi-meet-electron/releases/download/v2022.6.1/jitsi-meet.zip)
09:30:59.534 › Proxy server for native Squirrel.Mac is starting to listen (fileToProxy=https://github.com/jitsi/jitsi-meet-electron/releases/download/v2022.6.1/jitsi-meet.zip)
09:30:59.541 › Proxy server for native Squirrel.Mac is listening (address=http://127.0.0.1:64936, fileToProxy=https://github.com/jitsi/jitsi-meet-electron/releases/download/v2022.6.1/jitsi-meet.zip)
09:30:59.576 › / requested
09:30:59.582 › /181aa82104e-ac.zip requested
09:30:59.583 › /181aa82104e-ac.zip requested by Squirrel.Mac, pipe /Users/macted/Library/Application Support/Caches/jitsi-meet-electron-updater/pending/jitsi-meet.zip
2022-06-28 09:31:00.492 Jitsi Meet[72279:1156302] Download completed to: file:///Users/macted/Library/Caches/org.jitsi.jitsi-meet.ShipIt/update.zER48R9/181aa82104e-ac.zip
09:31:05.092 › Proxy server for native Squirrel.Mac is closed (fileToProxy=https://github.com/jitsi/jitsi-meet-electron/releases/download/v2022.6.1/jitsi-meet.zip)
$
```

Immediately upon quitting, Jitsi Meet.app remains 2022.4.1 ... but a few minutes later, it has changed to 2022.6.1.

So the issue appears to be one of timing -- someone who launches 2022.4.1, sees the message about a new version, quits, and immediately relaunches, may not be updated (and this failure appears to stick until the binary is manually updated), while someone who launches 2022.4.1, sees the message about a new version, quits, waits a few minutes, and then relaunches, _will_ be updated.

**Comment by saghul** [comment]
Hum, looks like an Electron problem, not sure there is anything we can do about this.

**Comment by saghul** [comment]
Not sure we post that or it's automatic, TBH.

**Comment by csett86** [comment]
The notification is automatic from electron-update, thus closing this here.
