### ISSUE TITLE
dist-error

### ISSUE THREAD

**Issue by filwu8** [jitsi/jitsi-meet-electron#782]
when i run :  npm run dist

my env :
window 11
node -v v16.16.0
node-gyp -v v9.0.0
vs 2022

~~~~~~~~~~~~~~~~~~~~~


Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.
webpack 5.70.0 compiled with 67 warnings in 8802 ms
  • electron-builder  version=23.1.0 os=10.0.22000
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@jitsi/electron-sdk@3.0.15, @jitsi/robotjs@0.6.9 platform=win32 arch=ia32
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path E:\jitsi-meet-electron-master\node_modules\@jitsi\robotjs
    npm ERR! command failed
    npm ERR! command C:\windows\system32\cmd.exe /d /s /c C:\Users\filwu\AppData\Local\Temp\install-b8506362.cmd
    npm ERR! �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
    npm ERR!   robotjs.cc
    npm ERR! E:\jitsi-meet-electron-master\node_modules\node-addon-api\napi.h(4,10): fatal error C1083: �޷��򿪰��� �ļ�: ��node_api.h��: No such file or directory [E:\jitsi-meet-electron-master\node_modules\@jitsi\robotjs\build\robotjs.vcxproj]
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.16.0 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Users\filwu\AppData\Local\Programs\Python\Python310\python.exe"
    npm ERR! gyp info find VS using VS2019 (16.11.32630.194) found at:
    npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\Users\filwu\AppData\Local\Programs\Python\Python310\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\Users\\filwu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'E:\\jitsi-meet-electron-master\\node_modules\\@jitsi\\robotjs\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\filwu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\filwu\\.electron-gyp\\19.0.8\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\filwu\\.electron-gyp\\19.0.8',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\filwu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\filwu\\\\.electron-gyp\\\\19.0.8\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=E:\\jitsi-meet-electron-master\\node_modules\\@jitsi\\robotjs',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'E:\\jitsi-meet-electron-master\\node_modules\\@jitsi\\robotjs\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'build/binding.sln',
    npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
    npm ERR! gyp info spawn args   '/nologo',
    npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp ERR! build error
    npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\filwu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.22000
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\filwu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd E:\jitsi-meet-electron-master\node_modules\@jitsi\robotjs
    npm ERR! gyp ERR! node -v v16.16.0
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\filwu\AppData\Local\npm-cache\_logs\2022-08-08T10_07_53_976Z-debug-0.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\filwu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js' rebuild @jitsi/electron-sdk@3.0.15 @jitsi/robotjs@0.6.9
                    workingDir=

**Comment by saghul** [comment]
Can you try again from latest master? This should have been fixed just a few minutes ago.

**Comment by filwu8** [comment]
> Can you try again from latest master? This should have been fixed just a few minutes ago.

yes，I am  just downloaded the latest version  1 hours ago 


https://github.com/jitsi/jitsi-meet-electron/archive/refs/heads/master.zip

**Comment by filwu8** [comment]
thank you！

but I'm running fine on macbook，
how to   dist   x64 x32 exe for mac？

**Comment by filwu8** [comment]
when i use npm start ，it's works fine，mic camera  the device working well。

I  dist it successfull  on macos   12.5

but   app ，i'cant used my camera，



<img width="1040" alt="截屏2022-08-08 22 29 41" src="https://user-images.githubusercontent.com/54697960/183442125-dbd6bb16-cd89-4b70-80a7-47d045e64eb9.png">

**Comment by filwu8** [comment]
Logger.js:154 2022-08-09T12:53:15.217Z [modules/RTC/RTCUtils.js] Failed to get access to local media. NotReadableError: Could not start video source {"video":{"height":{"ideal":720,"max":720,"min":180},"width":{"ideal":1280,"max":1280,"min":320},"facingMode":"user"},"audio":false}

**Comment by filwu8** [comment]
[modules/xmpp/strophe.jingle.js] getting turn credentials with extdisco:2 failed, trying extdisco:1
r @ Logger.js:154
(anonymous) @ strophe.jingle.js:381
(anonymous) @ strophe.umd.js:2716
run @ strophe.umd.js:1875
(anonymous) @ strophe.umd.js:3157
forEachChild @ strophe.umd.js:830
_dataRecv @ strophe.umd.js:3146
_onMessage @ strophe.umd.js:5836

**Comment by filwu8** [comment]
Logger.js:154 2022-08-09T12:56:07.960Z [modules/xmpp/strophe.jingle.js] getting turn credentials failed


2022-08-09T12:56:07.960Z [modules/xmpp/strophe.jingle.js] is mod_turncredentials or similar installed and configured?

2022-08-09T12:56:08.053Z [modules/RTC/RTCUtils.js] Failed to get access to local media. NotReadableError: Could not start video source {"video":{"height":{"ideal":720},"width":{"ideal":1280},"deviceId":"801e5e5a1a1fbb67e0f298fb5945f58c1580b04d0d7ccf8f4f6f63935c898cde"},"audio":{"autoGainControl":false,"deviceId":"default","echoCancellation":true,"noiseSuppression":true}}

2022-08-09T12:56:08.055Z [features/base/tracks] Failed to create local tracks (2) ['audio', 'video'] bt {gum: {…}, name: 'gum.general', message: 'Could not start video source', stack: 'Error\n    at new bt (https://A.a.com/l…ft.com/libs/lib-jitsi-meet.min.js?v=6260:2:510146'}

**Comment by filwu8** [comment]
**Is this the reason?**


• skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, it could cause some undefined behaviour, e.g. macOS localized description not visible, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found

**Comment by saghul** [comment]
Sorry this is not a Jitsi Meet specific issue but an Electron one. Please ask in our forum.

**Comment by cheermao** [comment]
@filwu8 I found the same issues.I build on windows,It's very ok, but on mac camera is not working. Do U find some ideas?

**Comment by filwu8** [comment]
> @filwu8 I found the same issues.I build on windows,It's very ok, but on mac camera is not working. Do U find some ideas?
I'm just Solved

./package.json  add :

"extendInfo": {
        "NSMicrophoneUsageDescription": "Please give us access to your microphone",
        "NSCameraUsageDescription": "Please give us access to your camera",
        "com.apple.security.device.audio-input": true,
        "com.apple.security.device.camera": true
      },


./main.js add:

const { systemPreferences } = require('electron')
const microphone = systemPreferences.askForMediaAccess('microphone');
const camera = systemPreferences.askForMediaAccess('camera');

**Comment by cheermao** [comment]
@filwu8 Excellent, Thx bro, It works.
