### ISSUE TITLE
App auto-updated in the middle of a call

### ISSUE THREAD

**Issue by opusforlife2** [jitsi/jitsi-meet-electron#784]
## Description

This happened a while ago. I was in the middle of a video call when Jitsi Meet started to stutter and hang, practically hanging the entire OS, for 15-20 minutes or so. After troubleshooting quite a lot, I stumbled upon the fact that the app had updated itself to a new version.

## Current behavior

The app seems to auto-update even in the middle of a call.

## Expected Behavior

The app should either detect user activity and delay auto updates, or prompt the user.

## Steps to reproduce

Start a call and then auto update Jitsi Meet. I assume devs have the ability to trigger a dummy update.

## Environment details

Windows 7, 4 GB RAM

**Comment by csett86** [comment]
Unlikely that this is the cause of a 20 hanging system. The autoupdate is done right at the start of the app, before any call activity.

**Comment by opusforlife2** [comment]
Okay. To be clear, if the update check at the start doesn't find an update, but an update is available later in the same session, that doesn't matter? The app only ever checks again on the next start?

**Comment by csett86** [comment]
Yes, it only checks once at the start: https://github.com/jitsi/jitsi-meet-electron/blob/master/main.js#L174

**Comment by opusforlife2** [comment]
I see. Once the update check occurs and an update is found, is there any UI that shows this, or does the entire download take place in the background? I'm thinking of the possibility that the download starts, but I don't see it so I start a call. Then the download and call take place in parallel.

If there _is_ an update notification, is it still possible that because of some reason (slow Internet, etc.) the user could quickly start a call before the update check returns true and notifies the user?
