### ISSUE TITLE
Wayland XDG share permission popup endless loop back

### ISSUE THREAD

**Issue by 9Lukas5** [jitsi/jitsi-meet-electron#785]
## Description
Endless XDG Portal Popup is back. (see #677)

## Current behavior
- Click share
- Jitsi own dialogue comes up
- XDG Popups are started to be generated
- It stops as soon as the Jitsi own share dialogue is closed

If the Jitsi own share dialogue is closed by clicking share, it is indeed possible to get a working screenshare, if the desired Window to share is chosen on the xdg popup Jitsi seems to still have a hands on. After the share got started successfully through that, all remaining ones can just be closed.

## Expected Behavior
Only one XDG Popup is generated

## Possible Solution
Either only start a single xdg popup after clicking share on the Jitsi own dialogue, or directly go to the xdp popup skipping the Jitsi own dialogue entirely as proposed in electron/electron/issues/30652

## Steps to reproduce
Have Jitsi 2022.6.1 or newer installed (switch to Electron 19.x) and run it with the parameters  
```
--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer,WaylandWindowDecorations --ozone-platform=wayland
```

# Environment details
|||
|-|-|
| Ubuntu | 22.04 |
| Gnome | 42 |
| Jitsi | 2022.6.1<br>2022.7.1<br>2022.8.1<br> _basically since Electron 19.x_ |
| xdg-desktop-portal | 1.14.4-1ubuntu2~22.04.1 |
| xdg-desktop-portal-gnome | 42.1-0ubuntu1 |
| xdg-desktop-portal-gtk | 1.14.0-1build1 |

On a Sidenote: The previously working Jitsi 2022.4.1 with Electron 17.x brings one popup, but after starting the screenshare I see an OpenGL error line in the terminal (see below) instead of a picture. No idea when this changed, as I rarely use it atm, but that's why using the older Version is no possibility atm.  
```
[610022:0821/114222.939224:ERROR:egl_dmabuf.cc(429)] Failed to process buffer: Cannot import passed GBM fd - Das Argument ist ungültig
```

**Comment by maymage** [comment]
This can be closed then, as non reproducible on latest versions + current GNOME.

**Comment by csett86** [comment]
No (longer) reproducible

**Comment by 9Lukas5** [comment]
Yes can confirm it's working again for me as well 👍🏼
