### ISSUE TITLE
Add ability to use url redirects for a Jitsi conference

### ISSUE THREAD

**Issue by tigexplorer** [jitsi/jitsi-meet-electron#796]
URL redirects may be a way to provide participants of a Jitsi always the same start url to join the conference.

By using a web browser for Jitsi, that works fine.
With the electron-app, it ends up in a blank screen.

Is it possible to implement handling of redirects in the desktop app?

**Comment by csett86** [comment]
Unfortunately this is not possible, and as Jitsi conferences also have stable URLs (eg meet.jit.si/thisismylongandstableurl) I dont see a benefit here
