### ISSUE TITLE
Noise cancellation

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#799]
How do I enable noise cancellation, new feature in jitisi?

It exists already. If you're hosting your own server, you can configure it
in your config.js (disableNS: true). If not, you can pass it as a URL     
param e.g. [44]https://meet.jit.si/meetingname#config.disableNS=true      

See here:
 https://github.com/jitsi/jitsi-meet/issues/11224

**Comment by saghul** [comment]
They are on by default.

If you are referring to the new enhanced noise suppression then it's available on the in-meeting menu (the 3 dots).

**Comment by OrionRandD** [comment]
> They are on by default.
> 
> If you are referring to the new enhanced noise suppression then it's available on the in-meeting menu (the 3 dots).

I've just see it!
But, if I click on it, a perpendicular line tick appear.
If I unclick it, not perpendicular line tick appear, but just the icon.
Which one is noise-supression on?

**Comment by saghul** [comment]
The button expresses the action. When it's not crossed out, you'll activate it on lock, when it's crossed out you'll deactivate it on click.

**Comment by csett86** [comment]
Noise cancellation is an in-meeting feature and no further action required in the electron app, its supported already (if the jitsi server version supports it). Thus closing here
