### ISSUE TITLE
Update Wayland Instructions

### ISSUE THREAD

**Issue by maymage** [jitsi/jitsi-meet-electron#808]
For a correct wayland experience I need the 

`--enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto`

flags.. Perhaps the Readme.md should be updated accordingly. 

Best and thanks for the electron app!

**Comment by saghul** [comment]
Any chance you could send a PR?

**Comment by maymage** [comment]
Closing, as the Readme.md is correct, as is.
