### ISSUE TITLE
Wacom Pen Tablet Input Not Recognized

### ISSUE THREAD

**Issue by maymage** [jitsi/jitsi-meet-electron#811]
Hi all, 

probably this issue is a more generallly an Electron/Chromium issue, but I cannot in good faith report to those instances due to lack of testing. 

Anyway: using the jitsi-meet-electron-flatpak app from flathub and  a wacom graphic tablet pen input on a wayland session, 
I cannot use the whiteboard - or any other part of the app UI for what it's worth. 
The same happens on other electron apps, but for those I don't use a pen input anyway. 

This is on all the latest software: debian sid, jitsi as of this week etc. 

I would be happy, if someone could reproduce and push this issue to the right (upsteam) place.

**Comment by saghul** [comment]
Does it work when you use the browser directly?

**Comment by maymage** [comment]
I just tested the non-wayland situation

* running in an xorg session`flatpak  run org.chromium.Chromium` and `flatpak  run org.jitsi.jitsi-meet`
* running a wayland session and starting chromum with `flatpak  run org.chromium.Chromium --ozone-platform=x11` and `flatpak  run org.jitsi.jitsi-meet  --ozone-platform=x11`, that is Chromium or Jitsi on xwayland.

In both cases the whiteboards run smoothly. More generally the pen input is recognized by the jitsi or chromium windows. 
This is not the case under wayland. That is the pen-cursor vanishes completely, as soon as the cursor-icon enters the windows. 

So this has nothing to do with the whiteboard, but is an issue with chromium. 

My input device is a wacom graphical tablet btw.

**Comment by saghul** [comment]
Then I'm afraid you'll need to report this to Chromium. We cannot really do anything here.

Usually the simplest the repro case the better, so if you can report it in the excalidraw site directly with Chromium, that's great, because it's clearly a Chromium on Wayland bug, not something that could be suspected of Electron.

**Comment by maymage** [comment]
For the record

https://bugs.chromium.org/p/chromium/issues/detail?id=1393299
