### ISSUE TITLE
Module not found: Error: Can't resolve 'jsonfile/utils' in '/node_modules/fs-extra/lib/json'

### ISSUE THREAD

**Issue by raphael10-collab** [jitsi/jitsi-meet-electron#812]
raphy@pc:~$ git clone --branch debian-package https://github.com/jitsi/jitsi-meet-electron.git
    Cloning into 'jitsi-meet-electron'...
    remote: Enumerating objects: 2855, done.
    remote: Counting objects: 100% (149/149), done.
    remote: Compressing objects: 100% (91/91), done.
    remote: Total 2855 (delta 91), reused 96 (delta 56), pack-reused 2706
    Receiving objects: 100% (2855/2855), 5.17 MiB | 11.17 MiB/s, done.
    Resolving deltas: 100% (1722/1722), done.
    raphy@pc:~$ cd jitsi-meet-electron/
    raphy@pc:~/jitsi-meet-electron$ yarn
    yarn install v1.22.19
    info No lockfile found.
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
    [1/5] Validating package.json...
    [2/5] Resolving packages...
    warning @atlaskit/button > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
    warning @atlaskit/button > @atlaskit/analytics-next-types@3.2.0: Typescript type definition files are now hosted directly from @atlaskit/analytics-next
    warning @atlaskit/css-reset > fbjs > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
    warning @atlaskit/droplist > @atlaskit/item > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    warning @atlaskit/droplist > @atlaskit/layer > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
    warning @atlaskit/droplist > @atlaskit/icon > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    warning @atlaskit/droplist > @atlaskit/tooltip > @atlaskit/popper > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
    warning @atlaskit/droplist > @atlaskit/tooltip > @atlaskit/popper > react-popper > create-react-context > fbjs > core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
    warning @atlaskit/icon > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    warning @atlaskit/navigation > @atlaskit/dropdown-menu > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    warning @atlaskit/toggle > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    warning @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
    warning babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
    warning electron-builder > app-builder-lib > @electron/universal > asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
    warning electron-builder > app-builder-lib > electron-osx-sign@0.5.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
    warning electron-notarize@1.1.1: Please use @electron/notarize moving forward.  There is no API change, just a package name change
    warning patch-package > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
    warning patch-package > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    warning patch-package > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
    warning patch-package > find-yarn-workspace-root > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    warning react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
    [3/5] Fetching packages...
    [4/5] Linking dependencies...
    [5/5] Building fresh packages...
    success Saved lockfile.
    $ patch-package && electron-builder install-app-deps
    patch-package 6.2.2
    Applying patches...
    No patch files found
      • electron-builder  version=22.11.11
      • loaded configuration  file=package.json ("build" field)
      • rebuilding native dependencies  dependencies=@jitsi/electron-sdk@3.3.6, @jitsi/robotjs@0.6.11 platform=linux arch=x64
      • rebuilding native dependency  name=@jitsi/robotjs version=0.6.11
      • rebuilding native dependency  name=@jitsi/electron-sdk version=3.3.6
    Done in 92.78s.
    raphy@pc:~/jitsi-meet-electron$ yarn start
    yarn run v1.22.19
    $ webpack --config ./webpack.main.js --mode development && concurrently "npm:watch" "electron ./build/main.js"
    asset main.js 950 KiB [emitted] (name: main)
    asset preload.js 7.29 KiB [emitted] (name: preload)
    runtime modules 1.43 KiB 7 modules
    modules by path ./node_modules/ 787 KiB 153 modules
    modules by path ./app/ 3.37 KiB
      ./app/preload/preload.js 1.83 KiB [built] [code generated]
      ./app/features/config/index.js 1.05 KiB [built] [code generated]
      ./app/features/utils/openExternalLink.js 497 bytes [built] [code generated]
    + 24 modules
    
    ERROR in ./node_modules/fs-extra/lib/json/output-json-sync.js 3:22-47
    Module not found: Error: Can't resolve 'jsonfile/utils' in '/home/raphy/jitsi-meet-electron/node_modules/fs-extra/lib/json'
    resolve 'jsonfile/utils' in '/home/raphy/jitsi-meet-electron/node_modules/fs-extra/lib/json'
      Parsed request is a module
      using description file: /home/raphy/jitsi-meet-electron/node_modules/fs-extra/package.json (relative path: ./lib/json)
        resolve as module
          looking for modules in /home/raphy/jitsi-meet-electron/node_modules
            existing directory /home/raphy/jitsi-meet-electron/node_modules/jsonfile
              using description file: /home/raphy/jitsi-meet-electron/node_modules/jsonfile/package.json (relative path: .)
                using description file: /home/raphy/jitsi-meet-electron/node_modules/jsonfile/package.json (relative path: ./utils)
                  no extension
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils doesn't exist
                  .js
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils.js doesn't exist
                  .json
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils.json doesn't exist
                  .wasm
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils.wasm doesn't exist
                  as directory
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils doesn't exist
     @ ./node_modules/fs-extra/lib/json/index.js 7:26-55
     @ ./node_modules/fs-extra/lib/index.js 10:5-22
     @ ./node_modules/electron-updater/out/AppImageUpdater.js 6:19-38
     @ ./node_modules/electron-updater/out/main.js 11:24-52 28:28-72
     @ ./main.js 12:24-51
    
    ERROR in ./node_modules/fs-extra/lib/json/output-json.js 3:22-47
    Module not found: Error: Can't resolve 'jsonfile/utils' in '/home/raphy/jitsi-meet-electron/node_modules/fs-extra/lib/json'
    resolve 'jsonfile/utils' in '/home/raphy/jitsi-meet-electron/node_modules/fs-extra/lib/json'
      Parsed request is a module
      using description file: /home/raphy/jitsi-meet-electron/node_modules/fs-extra/package.json (relative path: ./lib/json)
        resolve as module
          looking for modules in /home/raphy/jitsi-meet-electron/node_modules
            existing directory /home/raphy/jitsi-meet-electron/node_modules/jsonfile
              using description file: /home/raphy/jitsi-meet-electron/node_modules/jsonfile/package.json (relative path: .)
                using description file: /home/raphy/jitsi-meet-electron/node_modules/jsonfile/package.json (relative path: ./utils)
                  no extension
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils doesn't exist
                  .js
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils.js doesn't exist
                  .json
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils.json doesn't exist
                  .wasm
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils.wasm doesn't exist
                  as directory
                    /home/raphy/jitsi-meet-electron/node_modules/jsonfile/utils doesn't exist
     @ ./node_modules/fs-extra/lib/json/index.js 6:24-48
     @ ./node_modules/fs-extra/lib/index.js 10:5-22
     @ ./node_modules/electron-updater/out/AppImageUpdater.js 6:19-38
     @ ./node_modules/electron-updater/out/main.js 11:24-52 28:28-72
     @ ./main.js 12:24-51
    
    webpack 5.75.0 compiled with 2 errors in 716 ms
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Other Info:

    O.S. : Ubuntu 22.04 Desktop
    node:  v16.15.1

**Comment by saghul** [comment]
Can you please try npm? We don't use or support yarn.

**Comment by raphael10-collab** [comment]
Yes. With `npm` it works fine

It's a pity you don't use and support `yarn`
