### ISSUE TITLE
lobby function popup

### ISSUE THREAD

**Issue by pyon3375** [jitsi/jitsi-meet-electron#820]
Jitsi Moderated Meetings
Always-On-Top window
no notification

sorry for not writing well

**Comment by saghul** [comment]
I have no idea what you are asking, sorry.

**Comment by pyon3375** [comment]
> I have no idea what you are asking, sorry.

thank you for your reply.

Sorry for the translation function.
When the meeting organizer turns on the lobby function and a member joins, when the top screen is always displayed, the popup is not visible and the request is not noticed.

If this doesn't tell you, I'll close the commit.

Thank you for listening to me.

**Comment by saghul** [comment]
Do you mean that when someone joins the lobby, but you don't have main screen on focus, just the always-on-top, you don't see the notifications when someone joins the lobby?

**Comment by pyon3375** [comment]
Yes, you are right.

Thank you.

**Comment by parteekcoder** [comment]
@saghul could you please assign this issue to me , I would to like to part of your GSOC projects this year

**Comment by saghul** [comment]
We are not participating in GSoC this year, sorry.
