### ISSUE TITLE
Broken polls 'allow-forms' permission is not set

### ISSUE THREAD

**Issue by q-b** [jitsi/jitsi-meet-electron#837]
## Description

Polls can no longer be send in the last few electron app releases (works from firefox)

## Current behavior

Clicking on the "send" button trigger the following error in the debug console: 
```
Blocked form submission to <jitsi url redacted> '' because the form's frame is sandboxed and the 'allow-forms' permission is not set.
```

## Expected Behavior

No error, poll submitted

## Possible Solution

Fix permission

## Steps to reproduce

Create a poll from the electron application

# Environment details

2023.1.2 (at least the previous release was also broken)

**Comment by csett86** [comment]
@saghul Can you please take a look?

**Comment by zerg11** [comment]
Hello, everyone!

We've faced with the same problem, but with external auth integration page(with keycloak):

`Blocked form submission to '<https://url-keycloak>' because the form's frame is sandboxed and the 'allow-forms' permission is not set.`

Version: 2023.1.1, 2023.1.2

**Comment by saghul** [comment]
Opsie number 2. Will fix.

**Comment by csett86** [comment]
Fixed in https://github.com/jitsi/jitsi-meet-electron/pull/838, will release a new version with the fix hopefully this week

**Comment by csett86** [comment]
Now released, closeing as fixed: https://github.com/jitsi/jitsi-meet-electron/releases/tag/v2023.2.0
