### ISSUE TITLE
please remove the auto update function

### ISSUE THREAD

**Issue by AndySchroder** [jitsi/jitsi-meet-electron#846]
Please remove the mandatory auto update function.

I don't understand why you would have such an invasive function built into the program. What's the point of End to End Encryption (https://jitsi.org/blog/e2ee/) and self hosting (https://jitsi.github.io/handbook/docs/devops-guide/) if there is a back door built right into the client? It just seems totally bizarre.

**Comment by saghul** [comment]
How about you prove your claims?

The meeting content is still downloaded from your server.

If you don't like how this app works, fork it and disable auto-updates.

It's interesting how you mention e2ee and then disregard security updates as "invasive".

**Comment by AndySchroder** [comment]
How do we know an update is a "security" update? We have no way to audit your update distribution system, we have no way to know if you've been compromised, etc.. The concept of a "security" update is relative to who is issuing the update and who is receiving it.

**Comment by saghul** [comment]
The full process is open source, if cared to check. It's the standard Electron auto-updater which gets the builds from GH releases which are built with GH Actions in an automated way.

It doesn't get more transparent than that.

Or you can build it yourself, because it's fully open source.

**Comment by AndySchroder** [comment]
Just because everything is automated doesn't mean it can't be compromised. You just cited a number of computer systems that are are not public auditable. It seems very unclear whether ALL of the binaries are signed, and if they are signed locally on a local development machine or on these remote github machines.

Even if all binaries are signed locally on a local development machine, how do we trust that a human has not made a mistake, been manipulated, or their computer compromised? If the process is fully automated there is no way to stop a change. This seems reckless and intrusive. An opt in update is a perfectly useful feature to have, but the involuntary approach is what is disturbing.

**Comment by saghul** [comment]
Stop the FUD already.

With how vast the attack surface on a browser is, security updates are very important, and unless they are automated, they are pointless.

For the last time. You don't have to trust me. Build your own binaries.
