### ISSUE TITLE
How do I save my jitsi chat sessions

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#848]
How do I save my jitsi chat sessions?
I mean not video recorded sessions, but just written chat sessions.
I have seen this implementation in here:
https://community.jitsi.org/t/how-to-how-to-save-chats-and-speaker-stats/80904
But, I do not know how to do it on jitsi-electron

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This is done server-side. So it needs to be implemented on the server. jitsi-electron is the client, a wrapper around the browser to show the meeting.
