### ISSUE TITLE
not a bug, just a question

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#854]
1. How do I get the current version of jitsi-meet-electron in this repository?
2. How do I get the current installed version in my system through command-line?
3. Reason: to compare the two and decide if there is a need to upgrade...
:)

**Comment by saghul** [comment]
1. You can get it here: https://github.com/jitsi/jitsi-meet-electron/releases
2. I don't know TBH
3. The app already checks for that on startup and every 24h (IIRC) so you don't need to do it manually

**Comment by OrionRandD** [comment]
> 1. You can get it here: https://github.com/jitsi/jitsi-meet-electron/releases
> 
>     2. I don't know TBH
> 

Thx

>     3. The app already checks for that on startup and every 24h (IIRC) so you don't need to do it manually

Thx
