### ISSUE TITLE
not sure if it is a bug

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#856]
Three days ago everything was working OK.
But, although most things are all right, option to share applications is not working.
I can only share the entire window...
Is this problem related to the chrome-sandbox?
I have installed it with the deb package.
I purged jitsi-electron and reinstalled everything again but it still does not work.
The Share button is greyed for the share application option and I cannot see the open application in the small window option...

/opt/Jitsi Meet $ ls
locales/                chrome_crashpad_handler*  libEGL.so*             libvulkan.so.1*         snapshot_blob.bin
resources/              chrome-sandbox*           libffmpeg.so*          LICENSE.electron.txt    v8_context_snapshot.bin
chrome_100_percent.pak  icudtl.dat                libGLESv2.so*          LICENSES.chromium.html  vk_swiftshader_icd.json
chrome_200_percent.pak  jitsi-meet*               libvk_swiftshader.so*  resources.pak

**Comment by csett86** [comment]
Now I understood the issue you described, lets track this in #857 where already more details are in
