### ISSUE TITLE
High CPU usage if camera on. Low if camera off

### ISSUE THREAD

**Issue by mankoff** [jitsi/jitsi-meet-electron#875]
This bug has been addressed several times, most recently on #77.

However, that bug seems to be focused on OS X and importantly says,

    if I turn my camera off altogether, the CPU usage does not go down

I'm opening a new bug because I'm on Linux and CPU drops as soon as I turn off my camera.

I've turned `performance` to one-above-lowest (where lowest turns off the camera) and am using a URL with:  `MyMeetingRoom#config.disableAudioLevels=true&config.channelLastN=3&config.startSilent=false` and in the GUI set `Disable automatic gain control`.

I much prefer Jitsi to other tools and would be happy to help debug this if you can provide any suggestions.

## Description

After about 1-5 minutes of running Jitsi (Firefox or Electron app installed via Flathub), all 8 cores on my laptop peg to 100 % and the system becomes unusable. Audio and video drop. Mouse becomes laggy. If I turn off my camera (in Jitsi) CPUs immediately drop. This is therefore due to outbound video, not inbound.

## Possible Solution

Audio only.

# Environment details

```bash
$ flatpak list|grep jitsi
Jitsi Meet      org.jitsi.jitsi-meet    2023.5.3        stable  user
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

```
$ uname -a
Linux t480 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by saghul** [comment]
What hardware are you running this on?

Is you r meeting happening on meet.jit.si or a different server?

Can you please run the AppImage? The flatpak is a third party build, and I rather have least amount of uncertainty here.

**Comment by mankoff** [comment]
> What hardware are you running this on?

T480 Thinkpad laptop 

     *-cpu
          product: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          version: 6.142.10
          size: 1733MHz
          capacity: 4200MHz
          width: 64 bits
 
32 GB RAM
 
> Is you r meeting happening on meet.jit.si or a different server?

`meet.jit.si`

> Can you please run the AppImage? The flatpak is a third party build, and I rather have least amount of uncertainty here.

I will use AppImage for my meeting today. Would you rather I use `deb` or `AppImage`?

**Comment by mankoff** [comment]
And more hardware details from `lsusb`

```
Bus 001 Device 003: ID 13d3:56a6 IMC Networks Integrated Camera
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.01
  bDeviceClass          239 Miscellaneous Device
  bDeviceSubClass         2 
  bDeviceProtocol         1 Interface Association
  bMaxPacketSize0        64
  idVendor           0x13d3 IMC Networks
  idProduct          0x56a6 
  bcdDevice           17.11
  iManufacturer           3 Azurewave
  iProduct                1 Integrated Camera
  iSerial                 2 0001
  bNumConfigurations      1
```

**Comment by mankoff** [comment]
No CPU spike with AppImage!

I'll try the `deb` version tomorrow.

**Comment by saghul** [comment]
AppImage or deb should yield the same result. I guess the flatpak sandboxing might prevent GPU acceleration maybe...

**Comment by saghul** [comment]
It's normal to have higher CPU usage when the camera is on. Even when it's off, depending on the video you're receiving.

There is not much we can act on here really.

**Comment by mankoff** [comment]
I expect high CPU usage. But this entirely shuts down an 8-core machine. Seems excessive. I would be happy to try to debug this if you can offer any advice on what I should look for, although it's hard to type or even move the mouse when this happens. 

It's also strange (to me) that it takes 5 minutes to occur. If I toggle off the camera for just 1 second everything calms down for ~5 minutes. Either it's an intensive process or it isn't, I'm not sure why it builds up like this.

**Comment by saghul** [comment]
What kind of hardware is that?

**Comment by saghul** [comment]
Sorry missed it before.

Do you observe the same behavior if you use Chromium directly instead of the Electron app?

**Comment by mankoff** [comment]
I've  turned off 'show self view' and will report back if that makes a difference...

**Comment by saghul** [comment]
If the results are the same in Chrome this needs to be handled in the Jitsi-meet repo, not in the Electron wrapper.

**Comment by mankoff** [comment]
Ok. Well wherever it happens, I think the meeting went for a while without taking all CPUs when I turned off self view. It'll be later next week when I can test this further, but I will report back (using the `deb` version).

**Comment by maymage** [comment]
@saghul

Can you use your moderator superpowers to move this issue to the Jitsi-meet repo
or is @mankoff supposed to open a new issue there and provide which informations again?
