### ISSUE TITLE
Approving Remote Control Request Hangs Application

### ISSUE THREAD

**Issue by benkaiser** [jitsi/jitsi-meet-electron#877]
## Description

Accepting the dialog to allow remote control permissions hangs the entire application. Below is a screenshot of the application in it's stuck state.

<img width="803" alt="image" src="https://github.com/jitsi/jitsi-meet-electron/assets/608054/6dd06b79-54eb-473e-bcf5-9629a1bf0fdb">

## Current behavior

App freezes.

## Expected Behavior

App should continue to work, enabling remote control for requested user.

## Possible Solution

I tried executing the electron instance with devtools opened, but trying to record a performance trace was stuck on the first initializing step, it was *really* stuck whatever it is that is causing it. The only thing to do is quit the application and re-open.

## Steps to reproduce

1. Run the electron client locally [changing this line](https://github.com/jitsi/jitsi-meet-electron/blob/276b3e175e9e8b5bb829a213bb1da6e0d1b3c6f4/app/features/conference/components/Conference.js#L19) to true to enable remote control
2. Run either with `npm start` or `npm run dist` (and then copy to Applications folder)

# Environment details

MacOS Ventura 13.0.1

**Comment by benkaiser** [comment]
I understand this is a disable feature / likely not officially supported. But would be great to get to the bottom of what broke this functionality.

**Comment by milaq** [comment]
Same behavior on Windows with `ENABLE_REMOTE_CONTROL = true;`

**Comment by saghul** [comment]
We haven't found the time to look into this yet, sorry!

**Comment by ed76** [comment]
is there any news on this? does it work again with the current version?

**Comment by bilogic** [comment]
this is happening on https://github.com/jitsi/jitsi-meet-electron/commit/e64c8acda459d26d5277b53d5ce85bee08449c8f too for Windows 10/11

**Comment by bilogic** [comment]
I propose renaming the title of this issue to `Approving Remote Control Request Hangs Application`

**Comment by bilogic** [comment]
Any interest in funding someone to fix this?

**Comment by saghul** [comment]
@hristoterezov @horymury can either of you PTAL?

**Comment by bilogic** [comment]
anything?

**Comment by bilogic** [comment]
No, that is unrelated. Remote control was disabled by default.
This issue is about remote control being broken when enabled.

**Comment by saghul** [comment]
@hristoterezov @horymury Guys, can either of you PTAL?

**Comment by horymury** [comment]
I'm not able to reproduce remote control freezing the application with the latest jitsi-meet-electron ran in terminal, tested both on Windows and macOS.

Does this still reproduce for you @bilogic ?

CC: @saghul @hristoterezov

**Comment by bilogic** [comment]
@horymury 

thanks for getting back. 

1. I think the important thing is: does https://github.com/jitsi/jitsi-meet-electron/commit/e64c8acda459d26d5277b53d5ce85bee08449c8f freeze for you?
2. where can i get a copy of this latest jitsi-meet-electron you refer to? which hash which release?

**Comment by horymury** [comment]
@bilogic 

1. I see that commit is one commit behind on master - and the changes are not related to remote control
2. I cloned the master branch , enabled remote control by setting the flag to true on the two places in code, and ran locally with `npm start`

**Comment by horymury** [comment]
ha! the keywords  from the previous post are 'the two places' :) I was able to repro the issue by setting it in a single place(Conference.js).

Please also put the flag to true on the main.js file and it should fix it 👍

**Comment by horymury** [comment]
Set `ENABLE_REMOTE_CONTROL` to true here as well:
<img width="700" alt="image" src="https://github.com/user-attachments/assets/a1b43a24-1faa-4d3a-8632-3f552017aad4">

**Comment by bilogic** [comment]
ok let me test, is there a way to centralized this `ENABLE_REMOTE_CONTROL`?

**Comment by saghul** [comment]
Yes! @horymury can you pl point out exactly where the changes need to be made? 🙏

**Comment by horymury** [comment]
@bilogic  did changing the flag on main.js fix the issue for you? We added instructions on enabling remote control as comments on the 2 files:

https://github.com/jitsi/jitsi-meet-electron/commit/31204c723f97b189d95b846d33f764dc34d5827c

If all good I'll be closing this issue.

Thank you


CC: @saghul
