### ISSUE TITLE
Screen sharing problem on macOS

### ISSUE THREAD

**Issue by supczinskib** [jitsi/jitsi-meet-electron#881]
When I download the binary (2023.7.0), everything works fine. When I build the app myself (npm install; npm run dist), when I try to share the screen, macOS (13.4.1) asks permission to record the screen, which I grant, it is listed, but after restarting the app disappears from the list and asks for permission again. 

https://github.com/jitsi/jitsi-meet-electron/assets/40168732/a81063e7-32b2-452f-a048-352bce77bf52

**Comment by saghul** [comment]
Do you notarize the app?

**Comment by csett86** [comment]
And do you sign the app with an Apple Distribution certificate?

**Comment by supczinskib** [comment]
Thank you for the tip. I did not expect such an effect when the app is not signed with a certificate.

**Comment by supczinskib** [comment]
Signing the app with a certificate solved the problem. Thanks again for your help.

**Comment by csett86** [comment]
No, notarizing worked without issues for me, so no idea where that error is coming from

**Comment by supczinskib** [comment]
Problem has been solved. The "Developer ID Certification Authority" certificate was missing from the system. The topic can be closed.

<img width="1036" alt="cert" src="https://github.com/jitsi/jitsi-meet-electron/assets/40168732/915cbc25-a23e-4c5e-a35a-1477d41e306f">
