### ISSUE TITLE
No translations for Hindi [hi]

### ISSUE THREAD

**Issue by shellheim** [jitsi/jitsi-meet-electron#883]
No translation available for the Hindi language. [IETF Code - hi]
I could make a pull request for that if no one's working on it currently, thanks.

**Comment by saghul** [comment]
Feel free to do so! Thank you!

**Comment by shellheim** [comment]
Hey! Thanks for allowing me contribute.  I just made the PR in #886, closed the previous #885 accidentally, sorry.

**Comment by shellheim** [comment]
Closed by PR #888
