### ISSUE TITLE
Linux: Adding aarch64 (ARM) Support

### ISSUE THREAD

**Issue by sallyahaj** [jitsi/jitsi-meet-electron#887]
Hello there,
Thanks for all the developers of the project.
I want to ask if there is a plan to add a support for ARM64 aarch64 on Linux, as the ARM devices becoming to some distance  widely used.
I have asked the Flathub [team](https://github.com/flathub/org.jitsi.jitsi-meet/issues/73), they said they are depending on your available supports.

Regards.

**Comment by saghul** [comment]
Does electron release binaries for aarch64?

**Comment by sallyahaj** [comment]
Yes, it does. @saghul

**Comment by saghul** [comment]
Cool! Then I guess it might be as simple as some CI tweaking to build for it.

**Comment by csett86** [comment]
I also thought so, until I hit issues with our native extensions for robotjs... I already tried prebuildify-cross, but that fails due to missing X11 headers in the default cross environment. And github does not offer an easy linux arm64 native runner, as far as I know. So open for suggestions and PRs

**Comment by saghul** [comment]
Ah, bummer!

**Comment by csett86** [comment]
I think I got it now ready for linux-arm64 with https://github.com/jitsi/robotjs/pull/16

Can you please take a look @saghul ?

**Comment by saghul** [comment]
Looking great!

**Comment by sallyahaj** [comment]
Thank you @csett86 for starting the built.
Is that issue related to as the same here
https://github.com/signalapp/Signal-Desktop/issues/4530#issuecomment-1493145575

**Comment by csett86** [comment]
I hit other issues with electron-builder trying to rebuild the native addons where it should not, as they come with prebuild binaries. Solved that via an electron-builder update that has an option to disable the rebuilds manually. Now its looking good, as soon as the PR is merged I would cut another release, then you can use it @sallyahaj 

The PR results I already tested successfully with a Raspberry Pi 4 with Raspbian Bullseye.

**Comment by sallyahaj** [comment]
I have successfully tested Applmage and DEB on a vanilla debian testing/trixie release on RPi4, both of them are working as expected.
Note: Using the AppImage requires two additional packages: libfuse2, zlib1g-dev.
Thank you so much.
