### ISSUE TITLE
Pop-out window whenever the mouse leaves the window

### ISSUE THREAD

**Issue by mpldr** [jitsi/jitsi-meet-electron#893]
## Description

Whenever the mousecursor leaves the Jitsi window, a pop-out window is shown. Unfortunately it does not have a separate app-id and my window manager is set to tiling by default.
 
[jitsi.webm](https://github.com/jitsi/jitsi-meet-electron/assets/33086936/2bad6e21-c1ee-4f0f-84d6-50fca8b061c5)

---
## Current behavior

Currently, the meeting experience is rather bad, since every time the cursor moves, a random window pops up. It's become so bad, that I opted to use the web-version instead.

---
## Possible Solution

A simple solution would be to add a setting (maybe under general) to disable the pop-out window.

Alternatively, it would be possible to set a distinct title or an app id so we window manager plebs can configure it away ^^

---
## Steps to reproduce

- install sway
- install Jitsi Meet Desktop
- join a meeting
- move the cursor out of the window

---
# Environment details

WM: sway

**Comment by saghul** [comment]
You can disable it in the settings. It's called the "always on top" window.

**Comment by mpldr** [comment]
I cannot find that setting, I'm afraid. Neither in General, nor in any of the other categories.

**Comment by saghul** [comment]
It's before you join the meeting. In the Electron app's left side bar.

**Comment by mpldr** [comment]
Much appreciated.

**Comment by saghul** [comment]
Cheers!
