### ISSUE TITLE
disabling auto-gain not working properly

### ISSUE THREAD

**Issue by socphoenix** [jitsi/jitsi-meet-electron#894]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- On linux jitsi-meet-dekstop app (running manjaro) there is an option to disable automatic gain control. I'm trying to use Jitsi to host a virtual lesson, but the automatic gain only partially works. Periodically throughout the meeting the audio will fade out and crackle regardless of settings like it is still trying to control gain.

## Current behavior
--- auto-gain not fully suppressing audio tampering

## Expected Behavior
--- ability to play music over meeting for virtual lessons without odd audio issues

## Possible Solution
--- 

## Steps to reproduce
--- start meeting with auto-gain disabled, play music.

# Environment details
--- Linux x86_64 manjaro linux, locally installed app through aur.

I have audio recordings of the instrument (virtual pipe organ) itself, and through zoom and jitsi [here:](https://drive.google.com/drive/folders/19p5zAKCgew9YYvU1YB_zorOmIV2AIdFV?usp=sharing) labeled as Bach Master, zoom, and jitsi. On Jitsi, first instance is about 13 seconds in, 19 for the second and it gets more frequent from there.

The issue in the waveform can be seen [here](https://drive.google.com/file/d/1KpSlnmBdJz30jAzHzZl9LMkjkE1vd810/view?usp=sharing)

**Comment by saghul** [comment]
If you want music to be passed unfiltered you need to disable AEC and NS as well.

You probably also want to enable stereo.

This will require headphones since echo will be a problem otherwise.

You can disable those using URL parameters, but we currently have no UI for them.

**Comment by socphoenix** [comment]
> If you want music to be passed unfiltered you need to disable AEC and NS as well.
> 
> You probably also want to enable stereo.
> 
> This will require headphones since echo will be a problem otherwise.
> 
> You can disable those using URL parameters, but we currently have no UI for them.

Would I need to use the web interface or do those work for the app as well? Is there a guide for the url parameters? I checked the [user documentation](https://jitsi.github.io/handbook/docs/user-guide/user-guide-advanced) and didn't see anything referencing those parameters.

**Comment by socphoenix** [comment]
Found the web commands on google, for reference: 
#config.disableAP=true&config.disableAEC=true&config.disableNS=true&config.disableAGC=true&config.disableHPF=true&config.stereo=true&config.disable.AGC=true

seems to have done the trick!
