### ISSUE TITLE
meet.jit.si: Joining as moderator fails since auth enabled on 24 August on meet.jit.si

### ISSUE THREAD

**Issue by asmaloney** [jitsi/jitsi-meet-electron#900]
## Description

Something has changed with Jitsi which now seems to require a "moderator" to log in. Trying to do this from Jitsi Meet Electron fails.

## Current Behaviour

Trying to join a room and it tells me to sign in to become a moderator. It takes me to a site on the web browser and when I login with GitHub, it asks me about going back to "Jitsi Meet.app".  Clicking the allow button leaves me on the blank page and does nothing, so I can't join the room.

## Expected Behaviour

1. I shouldn't need to sign in for anything.
2. If I do sign in, it should redirect me back to the app properly (or better yet, just do it all in the app).

## Possible Solution

If I start with & login using the web version, I can then login using the Jitsi Meet Electron application (as can other participants).

## Steps To Reproduce

1. Run Jitsi Meet Electron
2. Choose an old room
3. It blocks "Waiting for a moderator"
4. Click the log-in button
5. Takes you to a web page to choose a login method (I chose GitHub)
6. It then pops up a "Open in Jitsi Meet.app" dialog
7. Clicking "Open Jitsi Meet.app" does nothing
8. I have to quit Jitsi Meet Electron because there's no way to cancel "Asking to join meeting..."

# Environment Details

- macOS 12.6.8
- Version 2023.7.2

# Other Info

https://community.jitsi.org/t/waiting-for-host-but-there-is-no-host/125976/13

This is an unfortunate development because it takes away the "no login" capability that was so useful.

**Comment by asmaloney** [comment]
Thanks @damencho !

This was a really unfortunate change. I just had a meeting, and this whole thing took me by surprise. 20 minutes of the 1-hour meeting was taken up by me scrambling around trying to figure out what was going on and how to fix it.  Not a great feature rollout 😆

**Comment by damencho** [comment]
You can always try out the browser. And this was announced more than a month ago in the community call, and recently there was a post in the forum and on the website about the date it will be active.

**Comment by asmaloney** [comment]
> You can always try out the browser.

I mention that in the issue.

What I didn't mention is that when we tried that, the video and audio quality was horrendous. Switching to the electron version fixed it.

> And this was announced more than a month ago in the community call, and recently there was a post in the forum and on the website about the date it will be active.

With respect, that's not useful for general users. For example I use Jitsi to speak with my parents. They are not going to follow any of those things. They are just using an app they expect to work. But if there was a notification in the app it would have been clear what was coming up and what the problem was.

This really should be an optional feature.

**Comment by damencho** [comment]
This is already fix, we need a new release for that. 

As said in the announcement we are not happy with the change, but we need to do it and it will be a bumpy ride. And here it is one of those bumps. Sorry for that.

**Comment by csett86** [comment]
I'll prep a release in the coming days, the new electron version with more wayland fixes for screensharing is also out so that was on my todo list anyway

**Comment by damencho** [comment]
Yeah, if its easy as pushing the button, can we do one now, so we fix people's conferences when using meet.jit.si and later do the rest if it will take time. Sorry for insisting. Thank you.

**Comment by csett86** [comment]
I see its a blocking issue for meet.jit.si. Then please follow the steps here, @damencho 

https://github.com/jitsi/jitsi-meet-electron#publishing

**Comment by damencho** [comment]
Hum ... there is no such link.

**Comment by csett86** [comment]
In the README, Development -> Show building instructions -> Publishing

**Comment by damencho** [comment]
🤦 Thank you

**Comment by damencho** [comment]
@saghul I prepared the draft release but testing it still does not work for me. Can you take a look please, when you can.

**Comment by saghul** [comment]
Hum that's odd! Does the system browser open?

Please check the Electron logs when you go "back" to the app.

**Comment by damencho** [comment]
Yeah I see action @@router/LOCATION_CHANGE but it still shows the lobby screen.

**Comment by damencho** [comment]
@hristoterezov reported it works on linux (the auto login part is not working, but this expected I think, it was missing and on mobile we were adding it after releasing the mobile versions with initial support). And I don't have windows to test :)

**Comment by saghul** [comment]
I just tested it works on macOS. Don't have a Windows handy to test right now alas. I'd go ahead with the release, it's not more broken than the previous one.

**Comment by damencho** [comment]
Done. Thank you.

**Comment by asmaloney** [comment]
Thanks guys!

That _sort of_ fixes it - at least it gets something working. It seems to login properly and doesn't leave me in an unusable state waiting for login . However it still launches an external browser for the "moderator log in".

And there are problems with the saved rooms which I'll file another issue for a bit later.

**Comment by damencho** [comment]
The log in is a requirement of meet.jit.si if you want to avoid that you can self-host your own deployment and use that.

**Comment by asmaloney** [comment]
I understand that, but Electron is a browser. Can't all the login stuff be done within the app instead of launching an external browser? I mean, we don't want to use the browser which is why we're using this 😄.

And it would make for much better UX.

**Comment by saghul** [comment]
I could ask the same in reverse, why use the Electron app if you can use a browser? :-) 

The point of using the system browser is to reuse credentials since you are likely already authenticated there, and also simplify our navigation logic since there many redirects that happen before joining.

We have a few rough edges still, but I don't see this changing in the short term.

**Comment by asmaloney** [comment]
> I could ask the same in reverse, why use the Electron app if you can use a browser? :-)

It works better than the browser. Whenever I have been in meetings where everyone is using the browser, the video quality suffers and the audio always has problems. Using an app is a known quantity and doesn't have any potential interference from plugins, 100s of tabs open, browser incompatibility, and so on.

(It can also help participants focus since they don't have the 100s of tabs in front of them 😄 )

> is to reuse credentials

I don't understand this argument. Typing in a password once isn't really too onerous is it? Am I misunderstanding?

> simplify our navigation logic

I hear you, however hiding a little complexity in the software for the sake of better UX is usually a good tradeoff. This workflow just feels really janky for a professional environment.

Anyway - thanks for getting it up and running again!

**Comment by saghul** [comment]
It's not just a password. It's the user, password and depending on the type of account and options also MFA might kick in. If you have already done that in the system browser, it's good to reuse all that state.
