### ISSUE TITLE
meet.jit.si: Room name lowercased for moderators through auth flow

### ISSUE THREAD

**Issue by asmaloney** [jitsi/jitsi-meet-electron#902]
## Description

The room selection at the landing page has problems with the latest update 2023.08.01. It also changes the room names.

## Current Behaviour

With the new login workflow, the room names get changed and the landing page with all the old room is... less useful (see below).

## Expected Behaviour

Room names should be what I set them to and the links on the landing page should be what they used to be.

## Steps To Reproduce

1. Click on an old room (e.g. "New Secret Room For Us")

<img width="612" alt="Screen Shot 2023-08-26 at 19 22 26 PM" src="https://github.com/jitsi/jitsi-meet-electron/assets/391371/54978ff6-8027-4758-b9f6-bb68bff91f10">

2. It comes up with the new "Waiting for a moderator" blocking dialog
3. Clicking "Log-In" takes me to an external browser simply to click the "Open Jitsi Meet.app" button
4. It takes me back to the electron app, but the name of the room when I'm in has changed to "Newsecretroomforus"
5. It didn't take me to the "holding page" like it used to before joining the room
6. The landing page now has the following room (don't know if that's sensitive, so I blacked some out):

<img width="608" alt="Screen Shot 2023-08-26 at 19 53 57 PM" src="https://github.com/jitsi/jitsi-meet-electron/assets/391371/04552048-76c8-4b89-9d64-5c8db168add1">

7. Clicking it puts me right into the room without the "holding area" that we used to have before actually joining the room (presumably because it's added that `prejoinConfig` thing on the URL).

# Environment details

- macOS 12.6.8
- Jitsi Meet.app 2023.08.01

**Comment by saghul** [comment]
Hum, it's weird the redirect didn't take you straight into the meeting.

What system browser was opened for you to login?

**Comment by asmaloney** [comment]
> Hum, it's weird the redirect didn't take you straight into the meeting.

It did in step 4/5 (with a different room name). I would have expected it to leave me on the "holding page" so I could check the camera, etc. and click to actually join the meeting. I went looking for any prefs for that and didn't find any.

Step 6 (about the landing page) is after I've left the room or restarted the software.

**Comment by damencho** [comment]
> It did in step 4/5 (with a different room name). I would have expected it to leave me on the "holding page" so I could check the camera, etc. and click to actually join the meeting. I went looking for any prefs for that and didn't find any

But you have already been on that page and you have already clicked join. The idea is not to request from users to do the same operation twice.

Changing the link capital vs small case letters is not a problem. Welcome page has been already working like that, it removes spaces from the names you enter.

**Comment by asmaloney** [comment]
> But you have already been on that page and you have already clicked join.

Not really. When I clicked on the room in the landing page, it took me to the "holding page" but blocked me with a dialog to log in. When I do that, it drops me straight into the room. So I don't get to check the camera or mic, or adjust anything like I used to.

> Changing the link capital vs small case letters is not a problem. Welcome page has been already working like that, it removes spaces from the names you enter.

Not a problem for who? I'm a user who has a problem with it 😄 The name of the room should match the name on the landing page or the one I type in to create a room. Before this, the name that shows up for the room has always been what I type in (or click from the landing page). Changing the room name is new to me.

Please keep in mind that not all people using this are tech-savvy, so this can be confusing for people. One of the first questions I (as organizer) got after this login change: why is the name goobledygook - that's not what I typed in. Am I in the right place?

Is there an issue with capitals and spaces? A URL encoding issue or something?

**Comment by csett86** [comment]
Without auth, when you enter a room named ThisIsATest it is displayed in the conference as "This Is A Test", if I recall it correctly...

It seems that the new auth flow on meet.jit.si lowercases all characters in the room name, and with that the spaces in the display of the room name are lost.

**Comment by asmaloney** [comment]
Is there a technical reason anything needs to modify the room name at all?

**Comment by asmaloney** [comment]
(I know writing can sound harsh, so I just want to let you know where I'm coming from.)

FWIW the reason I'm pushing so much on UX is that 95% of the people I recommend Jitsi to are non-tech people (some who struggle with logging into their computer) & it is the simplest vid-chat to get them up-and-running. (And it's open source of course!)

So keeping it as simple & easy to use is very important to me.

I'm mainly a C++/go dev who really, really does not enjoy web dev, so I'm afraid I'm not in a position to contribute code - I can only offer opinions/suggestions based on lots of experience, and I can raise issues I find.

I really appreciate all your work on this project!

**Comment by saghul** [comment]
> Is there a technical reason anything needs to modify the room name at all?

No, it's likely a small bug in the rendering, since internally room names are all lowercase and without spaces.

**Comment by mankoff** [comment]
> Step 6 (about the landing page) is after I've left the room or restarted the software.

I found that a `CTRL+r` (refresh) works too. After logging in using the browser I'm returned to the Jitsi App, but it still just shows 'Waiting for moderator' until I refresh (then instantly join). Easier than leaving + re-entering.

**Comment by saghul** [comment]
Yep this is currently a known issue I plan on addressing shortly. Any PR is welcome though.
