### ISSUE TITLE
jwt login token part of 'recent rooms', but expires on meet.jit.si within an hour

### ISSUE THREAD

**Issue by mankoff** [jitsi/jitsi-meet-electron#903]
## Description

Related to the new login system and perhaps #902 

My `recent` list contains the `jwt` token. When I tried to join the same meeting room (new meeting) a few hours later, it complained that I could not log in. I now had to manually type the room name into the text box and re-login.

**Comment by saghul** [comment]
Yep this is currently a known issue we plan on fixing shortly.
