### ISSUE TITLE
v2023.9.0 no mic and cam access in windows

### ISSUE THREAD

**Issue by t0xa2000** [jitsi/jitsi-meet-electron#909]
## Description
app in windows report no access to camera and microphone. No permission requested.

## Current behavior
cannot use camera and microphone in conferences

## Expected Behavior
shoud be able to use cam & mic :)

## Possible Solution
use web version :(

## Steps to reproduce
launch 2023.9.0 on windows (10 or 11). Same behavior when use jitsi on-prem or meet.jit.si

# Environment details
<span role="heading">Вам необходимо включить доступ к микрофону и камере</span>

**Comment by t0xa2000** [comment]
Its related somehow to Kaspersky Antivirus. With protection turned off - everything works fine.

**Comment by saghul** [comment]
In that case I guess there is nothing for us to do, is there?

**Comment by t0xa2000** [comment]
Problem started from 2023.9.0. Before that version we had no issues with camera and microphone.

**Comment by saghul** [comment]
Can you test 2023.9.1? We had to downgrade Electron.

**Comment by t0xa2000** [comment]
same behavior with 2023.9.1 :(

**Comment by saghul** [comment]
There must be something about the antivirus. Our build is virtually the same as the previous one.
