### ISSUE TITLE
Called JitsiMeetElectron.obtainDesktopStreams but it is not defined

### ISSUE THREAD

**Issue by JMSevilla** [jitsi/jitsi-meet-electron#914]
Hello I'm opening this issue so maybe someone can help me with this.

I'm using @jitsi/react-sdk and I use <JaasMeeting /> 

Whenever I try to share my screen it is just loading and based on console it gives me that error.

**Comment by saghul** [comment]
Please avoid opening duplicate issues.

**Comment by JMSevilla** [comment]
can you give me the closed issue for this problem ? @saghul

**Comment by saghul** [comment]
You need to use the Electron SDK: https://github.com/jitsi/jitsi-meet-electron-sdk

**Comment by JMSevilla** [comment]
Do you know how can I use this on react typescript ? because my electron has react typescript 

const {
    setupScreenSharingRender
} = require("@jitsi/electron-sdk");

// api - The Jitsi Meet iframe api object.
setupScreenSharingRender(api);

**Comment by saghul** [comment]
You need to use the `onApiReady` method to get it and do the Electron SDK setup: https://github.com/jitsi/jitsi-meet-react-sdk#onapiready

**Comment by JMSevilla** [comment]
Hi @saghul yup i'm currently getting the iframe like this 

`onApiReady={ (externalApi: any) => {
 const iframe = externalApi.getIFrame()
 // how can I pass this iframe to setupScreenSharingRender
}}`

Because my current directory is this. my main.js was outside of my CRA project. 
![image](https://github.com/jitsi/jitsi-meet-electron/assets/44269169/b04a6e54-0abb-4617-9b91-8c76d600b376)

my sti_monitoring_system contains my CRA project. So I've tried to reach the setupScreenSharingRender by importing it on .tsx but it is not working. I also come up with an idea to use window.require('@jitsi/electron-sdk') but it is not also working.

**Comment by JMSevilla** [comment]
@saghul I also try to use ipc from electron and still no luck.

**Comment by JMSevilla** [comment]
@saghul  Can you tell me how I can do it ?

**Comment by saghul** [comment]
You need to expose `setupScreenSharingRender` with a preload script. Again, check how our electron app does it, even if it doesn't use the React SDK.
