### ISSUE TITLE
Where do I change the instance addresses?

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#920]
I want to change instances addresses in my jitsi-electron.
I know how to change it using the gear icons, but I want to change accessing its configuration file through a terminal (cli) editor, say, vim.
Where is the configuration file for changing "https://$newInstance.org" - this is just a fictional example - located? Mine is in

/opt/Jitsi Meet $ ls
locales/                chrome_crashpad_handler*  libEGL.so*             libvulkan.so.1*         snapshot_blob.bin
resources/              chrome-sandbox*           libffmpeg.so*          LICENSE.electron.txt    v8_context_snapshot.bin
chrome_100_percent.pak  icudtl.dat                libGLESv2.so*          LICENSES.chromium.html  vk_swiftshader_icd.json
chrome_200_percent.pak  jitsi-meet*               libvk_swiftshader.so*  resources.pak

But, have no idea which one is that feature located

I have used 'rg' command to find it, but after scanning the whole directory recursively, I did not find where the file is.

**Comment by saghul** [comment]
There is no config file in the software itself. You'd need to go to the user data directory, which on Linux it should be in `~/.config/Jitsi Meet`

**Comment by OrionRandD** [comment]
> There is no config file in the software itself. You'd need to go to the user data directory, which on Linux it should be in `~/.config/Jitsi Meet`

LOL. There are only long database infos about used instances which the program turns into directories. But, not actual place to change the instances through a config file, like so:
~/.config/Jitsi Meet/IndexedDB $ ls
https_meet.jit.si_0.indexeddb.leveldb/

**Comment by saghul** [comment]
I don't know if it's changeable at all. That's where the app stores its state, but it was never intended to be modified by outside code.

**Comment by csett86** [comment]
You can give https://github.com/cions/leveldb-cli a try, @OrionRandD, as its Chromiums localStorage where the app stores its state. We had a more readable version, but that broke with electron 14, unfortunately. For all the details, see #638 and related PRs

**Comment by OrionRandD** [comment]
> You can give https://github.com/cions/leveldb-cli a try, @OrionRandD, as its Chromiums localStorage where the app stores its state. We had a more readable version, but that broke with electron 14, unfortunately. For all the details, see #638 and related PRs

Thx

**Comment by OrionRandD** [comment]
> You can give https://github.com/cions/leveldb-cli a try, @OrionRandD, as its Chromiums localStorage where the app stores its state. We had a more readable version, but that broke with electron 14, unfortunately. For all the details, see #638 and related PRs

That a pity!
