### ISSUE TITLE
Forced updates mean I must re-downgrade after every launch

### ISSUE THREAD

**Issue by TallTed** [jitsi/jitsi-meet-electron#924]
## Description

Version 2023.11.0 reports "You have macOS 10.14.6. The application requires macOS 10.15 or later."

Manually downgrading to 2023.10.0 works fine for the duration of that launch. But upon quit, it forces update to 2023.11.0, which will report "You have macOS 10.14.6. The application requires macOS 10.15 or later." at next launch.

Related to this, "What's Changed" should include "no longer compatible with macOS 10.14.x or earlier."

## Current behavior

Manual downgrade to 2023.10.0 is required after quit, which forces update to 2023.11.0.

## Expected Behavior

Announce that 2023.11.0 is available, and prompt me to install if I want to, and optimally warn that the new version won't run on my version of macOS, so I shouldn't update Jisti Meet.app unless I also update macOS.

## Possible Solution

Revert from forced app update to manual updates.

## Steps to reproduce

Should be obvious

## Environment details

macOS Mojave 10.14.6 (18G9323)

## Other notes

I am sure I am not the only person impacted by this. Unfortunately, there's no good way of learning how many others are impacted aside from posting here, and even then, it's not at all guaranteed that others will notice and/or chime in. Equally unfortunately, I participate in working groups which ditched Zoom and WebEx and others because they are not open source, in favor of Jitsi *primarily* because of its open source nature, so I have no choice but to use it. This is in many ways a replay of #686 and #676, but I remain hopeful that there will be a change in response.

**Comment by csett86** [comment]
First of all thank you for highlighting this, this slipped through on my end. I have now added it as a note to the release

**Comment by TallTed** [comment]
To head off one possible suggestion of possible workaround...  

Previous suggestions of [Flathub](https://flathub.org/apps/details/org.jitsi.jitsi-meet) and [HomeBrew](https://formulae.brew.sh/cask/jitsi-meet) don't work because Flathub is for Linux, and both of these have already bumped to `2023.11.0`, anyway.

I have long used [MacPorts](https://ports.macports.org/port/jitsi-meet-electron/), so I tried to install the [`jitsi-meet-electron` port](https://ports.macports.org/port/jitsi-meet-electron/) which still shows as being `2023.10.0`, but it fails to build, without useful error. (I've also [logged a bug on the port](https://trac.macports.org/ticket/68699).)

**Comment by saghul** [comment]
Please stop posting the same issue over and over again.

You are using an operating system that has been without any support from Apple for over 2 years now, that includes security updates.

We cannot support your use case.

**Comment by TallTed** [comment]
@saghul — I am currently trapped on macOS 10.14 due to mission critical abandonware, which breaks with the update to macOS 10.15. I would *LOVE* to upgrade, I assure you, but I cannot.

I have found and hereby offer a workaround for the worst Jitsi pain, for others who may run into this issue: install **Little Snitch**, and when it alerts that **Jitsi Meet.app** wants to connect to `githubusercontent.com`, _DENY_ it. This will silently prevent the new version from being discovered and downloaded on this and subsequent Jitsi sessions. So far (one meeting), it doesn't seem to have caused any problem with active use.

**Comment by saghul** [comment]
That can work. Now that we reached the point of no return you could just make a custom frozen in time build for yourself too.

**Comment by TallTed** [comment]
> you could just make a custom frozen in time build for yourself

I'd love to know how to do that. At first blush, it seems I would need to disable the phone-home code somehow, in addition to running whatever compiler, etc., (all of which I have installed, just minimally used)...

At this point, I'm little more than a script kiddie. My primary coding language is English, though I have ever debugged a little Pascal and a little C and even written some AppleScript and `shell`.

**Comment by saghul** [comment]
You can follow these steps: https://github.com/jitsi/jitsi-meet-electron#building-the-production-distribution

**Comment by TallTed** [comment]
Note that that anchor is hidden by default. Readers must expand the [Show building instructions](https://github.com/jitsi/jitsi-meet-electron#development) section.

Then, the "first step" is not documented beyond "Install Node.js 16 first", which I think would benefit by at least a link to relevant instructions from that crew. I did [Google that f'ing thing](https://www.google.com/search?q=install+node.js+16+macos), and that got me to nodejs.org where I found that Node.js 16 is on its [last last last legs](https://nodejs.org/en/about/previous-releases#release-schedule). Still, I downloaded and installed the [relevant `node-v16.20.2.pkg`](https://nodejs.org/download/release/v16.20.2/node-v16.20.2.pkg). Guidance beyond that was found on [a third-party site](https://radixweb.com/blog/installing-npm-and-nodejs-on-windows-and-mac), but of course, it's focused on getting the latest-and-greatest version, not this multi-year-old v16, so I'm not sure I *should* `sudo npm install npm --global // Update the npm CLI client`. I'm also pretty certain that `export PATH=/usr/local/git/bin:/usr/local/bin:$PATH` doesn't have the desired effect on macOS, and that some extra hoops need to be jumped through to adjust $PATH and other environment variables.

All that said, if I had reached the point of building the production distribution — so far as I can see, I would have exactly the same issue of auto-updates as I have with the prebuilt download.

I think I am best off living with blocking **Jisti Meet.app**'s access to `githubusercontent.com`, until and unless there are real step-by-step guides for near-absolute beginners.

**Comment by saghul** [comment]
Oh right I forgot the most important part 🤦 

Edit package.json and drop the project URL. That is what is used for checking for updates.

**Comment by TallTed** [comment]
I wonder whether `config.json` might be put to use for Jitsi Meet, as [it can be](https://github.com/vector-im/element-desktop/issues/1315) to prevent updates of [Element.app](https://github.com/vector-im/element-desktop)?

**Comment by saghul** [comment]
We don't use that file ourselves AFAIK. The update URL gets bundled with the app and it's taken from package.json.

Since you will essentially be keeping a fork, edit the file, remove the URL and the build won't self-update.

**Comment by bilogic** [comment]
Sorry, I also maintain a fork which allows remote desktop.

Where is this update URL currently? I can't find it in package.json https://github.com/jitsi/jitsi-meet-electron/blob/master/package.json

**Comment by bilogic** [comment]
> Edit package.json and drop the project URL. That is what is used for checking for updates.

@saghul do you mean `repository.url`?
