### ISSUE TITLE
whiteboard image cannot be downloaded

### ISSUE THREAD

**Issue by andreicon** [jitsi/jitsi-meet-electron#925]
## Description
---
After drawing in the whiteboard, if the user tries to download a copy of the canvas to the local filesystem by clicking on the download button, the file download won't be triggered. The same issue may occur when the user tries to download files that were shared via chat (not sure if this is a feature).
## Current behavior
---
File download is not triggered.
## Expected Behavior
---
The file should be downloaded (i.e. save dialog opens, allowing the user to save a copy of the file to disk)
## Possible Solution
---
Allowing downloads via the sandbox attribute of the iframe.
## Steps to reproduce
---
- Join a call
- Open the whiteboard
- Draw something
- click "download image"
# Environment details
---

The sandbox feature for the iframe was introduced in this PR: https://github.com/jitsi/jitsi-meet-electron/pull/861
Unless there's a reason for the omission, the list of permissions should also include `allow-downloads`

Opened a PR with a fix: https://github.com/jitsi/jitsi-meet-electron/pull/926

**Comment by saghul** [comment]
Have you tested that is enough? In Electron one needs to provide the UI and stuff for downloads.

**Comment by andreicon** [comment]
Fixed by #926. closing.
