### ISSUE TITLE
Can’t get into any room after configuring jitsi-keycloak-adapter

### ISSUE THREAD

**Issue by CreepyJ** [jitsi/jitsi-meet-electron#933]
## Description
---
I use jitsi-keycloak-adapter to connect keycloak and jitsi.The web version works fine, but jitsi deskopt can’t get into any room.
The strange thing is that after commenting out the code “app.commandLine.appendSwitch(‘disable-site-isolation-trials’),” I can enter the room successfully, but other issues arise.

**Comment by CreepyJ** [comment]
After commenting out the code,the aspect ratio cannot be adjusted on its own, and screen sharing doesn’t work
![image](https://github.com/jitsi/jitsi-meet-electron/assets/39795353/81ef3565-0624-48dd-847b-e1c03cd746f5)
![image](https://github.com/jitsi/jitsi-meet-electron/assets/39795353/0a85047d-e8a0-4559-be40-646567698238)

**Comment by CreepyJ** [comment]
I found that after entering several spaces in the input box on the main interface of Jitsi Electron, the page will jump to the main interface of the web version. I can successfully join the meeting through this interface. However, directly joining the meeting from the main interface of Jitsi Electron, the request to Keycloak is canceled.
![37680A69-A097-47d9-BADC-0C3D4DC90DB1](https://github.com/jitsi/jitsi-meet-electron/assets/39795353/6fb23b62-21cb-4f14-9d06-b1d121646e35)

**Comment by saghul** [comment]
Have you asked the maintainers of the keycloak adapter?

**Comment by CreepyJ** [comment]
No, it seems they haven't adapted it for the Jitsi Electron version. The web version works fine, the Jitsi Electron app also allows access to meetings via the web homepage. But it is not possible to enter the meeting properly through the built-in homepage of Jitsi Electron.I think the issue with the inability to navigate pages properly is related to Electron's security policies, but I haven't found a solution yet.

**Comment by saghul** [comment]
What version of the Jitsi Meet server components are you using? We added support for opening the token auth URL on a new window a couple of months ago.

**Comment by saghul** [comment]
I am not familiar with jitsi-keycloak-adapter, but you should be able to ask the authors.

**Comment by SignFinder** [comment]
The same issue. Application redirects to browser for authorization but ... how to return to jitsi-electron after successful authorization in browser?

**Comment by saghul** [comment]
The page that is opened after a succesful login would need to redirect to `jitsi-meet://domain.tld/meeting` that is not something we can fix in the app.
