### ISSUE TITLE
Enable new macOS screen capture when we have Chromium >= 120

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron#934]
https://github.com/chromium/chromium/commit/843de713e921eac9ed07418a876ee3480833443e

**Comment by csett86** [comment]
Electron 28 (due 5 dec) should already contain Chromium 120 :)

**Comment by csett86** [comment]
I think just Chromium 120 is probably not enough, as I have not seen any traces in electron for this.

See eg https://github.com/electron/electron/issues/38722

**Comment by saghul** [comment]
That is different. The Chomium side is about using ScreenCaptureKit for capture, which is supposed to be more efficient and bring back content hiding, which was lost somewhere along the way IIRC: https://developer.apple.com/documentation/screencapturekit?language=objc

**Comment by saghul** [comment]
I think not!
