### ISSUE TITLE
Jitsi electron shared Entire Screen instead of only selected Chrome browser

### ISSUE THREAD

**Issue by seregasoft** [jitsi/jitsi-meet-electron#935]
## Description
Jitsi electron shared Entire Screen instead of Chrome browser window.
The problem is not reproduced if you use Jitsi in browser.
The problem is not reproduced if you use Jitsi electron and choose any Window except Chrome browser.

## Current behavior
While in a conference using the Jitsi electron, choose share a Window > Chrome browser instance
The result is as if I chose to share the Entire Screen.
Starts share the Entire Screen.

## Expected Behavior
Starts share only selected Chrome browser windows

## Possible Solution
---

## Steps to reproduce
In Jitsi electron choose share a Window > Chrome browser instance

# Environment details
Jitsi electron: v2023.11.3

OS: Windows 10

Server:
jitsi-meet-prosody/stable,now 1.0.7658-1
jitsi-meet-turnserver/stable,now 1.0.7658-1
jitsi-meet-web-config/stable,now 1.0.7658-1
jitsi-meet-web/stable,now 1.0.7658-1
jitsi-meet/stable,now 2.0.9111-1
jitsi-videobridge2/stable,now 2.3-61-g814bffd6-1

**Comment by saghul** [comment]
Sorry I don't understand. When you select a Chrome window to share just that, what happens? CAn you share a screenshot?

**Comment by seregasoft** [comment]
> Sorry I don't understand. When you select a Chrome window to share just that, what happens? CAn you share a screenshot?

Yes, select a Chrome window to share. But started sharing entire screen with taskbar
![image](https://github.com/jitsi/jitsi-meet-electron/assets/2384838/20f7c760-5e5a-48e8-a377-4b0f036f946b)

**Comment by saghul** [comment]
CAn you reproduce this when connecting to meet.jit.si? I know we did some fixes to this lately due to a regression.

**Comment by seregasoft** [comment]
> CAn you reproduce this when connecting to meet.jit.si? I know we did some fixes to this lately due to a regression.
It is also reproduced on meet.jit.si

**Comment by saghul** [comment]
@gabiborlea can you PTAL?

**Comment by gabiborlea** [comment]
What version of jitsi meet are you using?
