### ISSUE TITLE
best way to support this project ?

### ISSUE THREAD

**Issue by gsaslis** [jitsi/jitsi-meet-electron#939]
Hi there, 

the app is great and it works great with my self-hosted jitsi server, allowing me to finally move away from gmeet / zoom / etc. etc. 

Do you have a patreon / github sponsors account (or even some less mainstream way) so that I could support this project?

In any case, thank you for all your work here. It is greatly appreciated! 🙏🏼 
Yorgos

**Comment by saghul** [comment]
Thanks for the kind words! Currently this project is mostly maintained by @csett86 with the ocasional fix by me or someone else on the Jitsi team at 8x8.

In what concerns the 8x8 Jitsi team, we are happy to work on Jitsi full- time and it's messages like these that encourage us to go above and beyond.

❤️

**Comment by csett86** [comment]
Thanks a lot @gsaslis from me as well, and regarding support: Thank you for your kind words, and if you want to, also tell others that you like Jitsi ❤️
