### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [jitsi/jitsi-meet-electron#94]
```
me@host:~$ Downloads/jitsi-meet-x86_64.AppImage 
28082
[28750:0721/121145.898703:FATAL:nss_util.cc(632)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required. Please upgrade to the latest NSS, and if you still get this error, contact your distribution maintainer.
Aborted
me@host:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
```

This can be worked around by patching `jitsi-meet`: 

```
sed -i -e 's|3.26|3.00|g' jitsi-meet
``` 

It then launches. Also seems to work without issues.

**Comment by akshitkrnagpal** [comment]
@probonopd 
Please try this.
`sudo apt-get install libnss3`

**Comment by probonopd** [comment]
I can confirm that this works. Thank you very much :+1: 

By the way, I have been waiting for an app like this for Linux for a _very_ long time since every time I wanted to start a quick web conference, I had to fiddle around with browser versions, plugins, stuff not working. This: Download, set executable, launch, works. Awesome! :1st_place_medal:

**Comment by probonopd** [comment]
Also added it to the AppImageHub central directory of available AppImages. https://appimage.github.io/jitsi-meet/

**Comment by akshitkrnagpal** [comment]
Glad to help. :smile:

**Comment by saghul** [comment]
@probonopd Thank you for doing that!

**Comment by probonopd** [comment]
Same on Ubuntu 16.04. It's really annoying to have to run an `apt-get` command on a freshly booted Live ISO just to run an AppImage. Workaround works:

```
./jitsi-meet-x86_64.AppImage --appimage-extract
sed -i -e 's|3.26|3.00|g' squashfs-root/jitsi-meet
./appimagetool-x86_64.AppImage squashfs-root/
```

**Comment by akshitkrnagpal** [comment]
@probonopd 
Thanks for reporting this and solution too.

But I don't think we should bypass this check. This error is thrown by chrome and the error says `Please upgrade to the latest NSS`.
IMHO, the user should install the latest NSS.

**Comment by saghul** [comment]
Agreed with @akshitkrnagpal. While a bit annoying, I think we should fix it with documentation. I'm working on a new README and I'll incorporate this.

**Comment by saghul** [comment]
The README mentions this now, so I'm going to close this.

**Comment by probonopd** [comment]
The idea behind AppImage is that you just need to get one file and can run the application without needing to change anything in the underlying operating system. Since the workaround above seems to work, why not apply it?
