### ISSUE TITLE
windows 7系统的上面，Jitsi Mee客户端不支持，无法使用

### ISSUE THREAD

**Issue by 2016ZHANGHONGZHENG** [jitsi/jitsi-meet-electron#944]
Jitsi Meet 电脑版客户端可不可以兼容windows 7系统，安装后无法使用，可不可以解决这个问题？谢谢

**Comment by csett86** [comment]
As Windows 7 is long out of support, electron and chromium no longer support it as well, that's why we cant support it either

**Comment by 2016ZHANGHONGZHENG** [comment]
您好，jitsi meet只能使用Gmail邮箱，Facebook，GitHub来注册账号来开会议。我的问题是：可不可以使用中国的邮箱，比如QQ邮箱或163邮箱，因为Gmail邮箱，Facebook，GitHub在中国大陆都不能直接使用，必须另外付费购买VPN才能使用这些账号来开会议，非常的不方便。盼望这个问题得到解决，感激不尽！

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Christoph Settgast ***@***.***&gt;
发送时间: 2024年2月3日 23:15
收件人: jitsi/jitsi-meet-electron ***@***.***&gt;
抄送: 2016ZHANGHONGZHENG ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jitsi/jitsi-meet-electron] windows 7系统的上面，Jitsi Mee客户端不支持，无法使用 (Issue #944)





 
As Windows 7 is long out of support, electron and chromium no longer support it as well, that's why we cant support it either

**Comment by csett86** [comment]
If the authentication on meet.jit.si does not suit you, I suggest that you look for a different jitsi instance, eg in mainland china or host your own. Its open source :)
