### ISSUE TITLE
Add recording functionality

### ISSUE THREAD

**Issue by probonopd** [jitsi/jitsi-meet-electron#96]
It would be great if streams could be recorded locally so that they could be edited (e.g., cut using Kdenlive) afterwards, in addition to being able to do live streams on YouTube.

**Comment by akshitkrnagpal** [comment]
This would be nice. But as you can see, we already have a ToDo list. 😄
So we may not get time to start working on this anytime soon or at all.

Let's keep this open anyway.

**Comment by Ark74** [comment]
Doesnt Jibri take care of it?

**Comment by saghul** [comment]
Yes, but the feature request is about doing a **local** recording. We might add this, we might not, but it's different from jibri recording.

**Comment by saghul** [comment]
Based on the time that has passed, I'd say it won't happen anytime soon. Closing.

**Comment by probonopd** [comment]
> Based on the time that has passed, I'd say it won't happen anytime soon. Closing.

That's very unfortunate to hear. Is adding _local_ recording really that different/more complicated than recording to an online location?
