### ISSUE TITLE
Share screen not working  - Called JitsiMeetElectron.obtainDesktopStreams but it is not defined

### ISSUE THREAD

**Issue by thidieu41** [jitsi/jitsi-meet-electron#969]
Hi guys... I'm trying to share screen on my video call.. but I  received this error : 
**_Called JitsiMeetElectron.obtainDesktopStreams but it is not defined_**
and this is my screen  : 
<img width="367" alt="Screenshot 2024-06-21 at 10 52 10" src="https://github.com/jitsi/jitsi-meet-electron/assets/131291852/d0ef197a-8ad0-4efe-ad7e-4da6aab3d361">
 I don't know what I'm missing when setup jitsi in my desktop app. 
 Can anyone here help me explain this problem? 
 Thanks.

**Comment by saghul** [comment]
That UI is very old. What versions of the software is your server running?

**Comment by thidieu41** [comment]
<img width="669" alt="Screenshot 2024-06-21 at 13 06 38" src="https://github.com/jitsi/jitsi-meet-electron/assets/131291852/8fd407b5-3ffd-4ffd-b24c-4cbab65c815e">

I'm using :
@jitsi/electron-sdk": "^6.0.40" 
"electron": "^30.0.6"

**Comment by saghul** [comment]
I mean on the server.

**Comment by thidieu41** [comment]
> I mean on the server.

I'm sorry but what server do you mean?
That would be great if you can tell me how can I check that. Thanks

**Comment by saghul** [comment]
You are connecting to some server other than the default meet.jit.si, right?

Are you in control of that server? Can you share the URL?

**Comment by thidieu41** [comment]
That's the private of the company.. Do we have other way to check this problems ?

**Comment by saghul** [comment]
You can open the JS console in the Electron app using the smake shortcut as in a browser. Then search for "version" in the logs.

**Comment by csett86** [comment]
Seems no more open questions here
