### ISSUE TITLE
Not a bug, but a question about login accounts

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#971]
;; Not a bug but a question:

;; How can I use this server with
;; jitsi-electron?
;; https://authent.framatalk.org/login
;; Previously I could use it in jitsi-electron
;; but now they demand us to have an account
;; in their server...
;; and inside jitsi-electron I cannot login in my framatalk.org account...
;; So that, jitsi-electron sends me to a firefox tab to open the room in the browser and not inside jitsi-electron  

:(

**Comment by saghul** [comment]
I don't know how their accounts work, but it's possible to implement auth like on meet.jit.si for custom accounts too.

You should ask them, since they will know.

**Comment by OrionRandD** [comment]
> I don't know how their accounts work, but it's possible to implement auth like on meet.jit.si for custom accounts too.
> 
> You should ask them, since they will know.

OK.
Do you have a list of free jitsi servers to use with jitsi-electron?
If so, Perhaps it would be good to add this suggestion to your Readme.md.
What do you think?

**Comment by saghul** [comment]
Sorry, we cannot provide such a list. meet.jit.si is free. The account is only needed for the 1st participant to join the room.

We used to have such a list, but it was used to abuse the service, unfortunately.

**Comment by OrionRandD** [comment]
> meet.jit.si

Where is this server? And what does this mean?
