### ISSUE TITLE
option to login with github as well

### ISSUE THREAD

**Issue by OrionRandD** [jitsi/jitsi-meet-electron#974]
When I place 
https://meet.jit.si
on settings and try to login it only gives me 
gmail login option.
But, if I try to login with the same address on a webbroser
it gives me
gmail
github
facebook

as options to login.
Could you add these options to jitsi-meet-electron as well?
I want to login with github an not with gmail.
Thx

**Comment by saghul** [comment]
The in-meeting option is for the calendar integration, which is of no use here since the electron app doesn't render the welcome page.
