### ISSUE TITLE
Cannot connect to custom jitsi meet

### ISSUE THREAD

**Issue by yasithph** [jitsi/jitsi-meet-electron#98]
The app works perfectly for meet.jit.si but not for my domain. It doesn't connect.
Do I need to enable anything in jitsi meet config? Or what could I be doing wrong?
Also how can see the error log for this?

**Comment by yasithph** [comment]
Thanks this worked.

**Comment by manang** [comment]
Hi, could you tell me how to solve the issue?
I'm new in jitsi and I want to know if the error is the same.
Thanks
Angelo

**Comment by yasithph** [comment]
Are you serving the frontend from a different folder than the debian package? If not then just simply rename the file external_api.min.js to external_api.js (make a copy) which is in libs folder
